apple/servicetalk

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/netty/NettyPipelinedConnectionBenchmark.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedStreamingHttpConnection.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
Motivation:
NettyPipelinedConnection provides pipelined request/response
support on the client. It uses 2 queues: 1 for writes and 1
for reads. The initial queue sizes are not set and therefore
the default value of 1024 is selected. This number should be
correlated to the max number of pipelined requests expected
(which is often 1). This initial queue size is wasteful and
consumes extra memory per connection.
Modifications:
- Correlate queue size to max pipelined requests in
NettyPipelinedConnection.
Result:
Less memory usage for h1 connections.
> Reduce initial queue size for h1 pipelined connection

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
Motivation:
WriteStreamSubscriber initial queue size is 8 however
most messages have ~3 items in the stream
{headers, payload, trailers}, and h2 may have 2 items.
We can save memory in most cases by reducing the initial
size from 8 to 4.
> Reduce initial size of WriteStreamSubscriber queue

- servicetalk-examples/http/http2/build.gradle
- servicetalk-examples/http/mutual-tls/build.gradle
- servicetalk-examples/http/redirects/build.gradle
- servicetalk-grpc-netty/build.gradle
- servicetalk-http-netty/build.gradle
- servicetalk-tcp-netty-internal/build.gradle
- servicetalk-transport-netty-internal/build.gradle
Motivation:
netty-tcnative-boringssl-static accelerates TLS and is enabled
if included on the classpath. ServiceTalk include's Netty's bom
which now also includes the compatible tcnative version, so we
can include this dependency to simplify version alignment.
Modifications:
- Add netty-tcnative-boringssl-static runtimeOnly dependency for
macOS/linux x86-64/aarch-64
Result:
Accelerated TLS without coordinating versions manually.
> Add netty-tcnative-boringssl-static runtime dependency

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatWhenSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetrySingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryWhenSingle.java
Motivation:
RepeatWhenSingle was recently introduced and avoids allocating
new Subscribers for each repeat operation. This helps save
object allocation when the operator is used in a loop. We
should use a consistent strategy for existing Publisher/Single
repeat/retry related operators.
Modifications:
- Redo[When]Publisher and Retry[When]Single no longer allocates
a new Subscriber on each iteration.
- All the repeat/retry operators now have consistent behavior
for AsyncContext map which is to re-use it. Previously a copy
was made before resubscribing, however the old map is no longer
used after a terminal event anyways so this shouldn't have any
benefit. Either we copy the map up front before subscribe, or
we just re-use the same map and let the async source at the top
of the chain reset …
> Reduce Publisher/Single retry/repeat allocations

- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq.yml
- .github/workflows/gradle-wrapper-validation.yml
Motivation:
Our GitHub action names have some duplicate info when displayed
in PRB builds (e.g. `PR Builder / Build JDK 8 ubuntu-latest`)
and also not consistent between PRB and PRQ.
> Minor improvement in Github action names

- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingClient.java
- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingServer.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/package-info.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
- servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
Motivation:
The current debugging examples include a minimal explanation of the
`logUserData` feature of `enableWireLogging` and `enableFrameLogging`
which could be expanded to clarify the use.
Modifications:
Additional explanation of `logUserData` by provided by defining a
`LOG_USER_DATA` constant with JavaDoc
Result:
Improved examples.
> Explain wire/frame logging `logUserData`

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingStreamingHttpClient.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToHttpClient.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategiesTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategyTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/StrategyInfluencerChainBuilderTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutFromRequest.java
Motivation:
The `HttpExecutionStrategies.defaultStrategy()` strategy currently
provides a special `merge()` implementation that, rather than merge,
simply returns the other strategy. This behavior is often surprising
and requires specific handling elsewhere to ensure that the strategy
has consistent merging when referenced reflexively.
Modifications:
Replace use of `HttpExecutionStrategies.defaultStrategy().merge()` with
explicit substitution of `defaultStrategy()` with the appropriate
strategy.
Result:
Reduced special behavior in the `HttpExecutionStrategy` implementation
which clarifies the actual interaction and behavior of strategies.
> Remove special `defaultStrategy()` merge method

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpAuthorityFormUri.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Uri3986.java
Motivation:
Provide more information in URI exceptions to help users understand the
issue.
Modifications:
- Enhance messages with more context;
Result:
Messages provide more context without leaking the full URI because it
may contain sensitive info in query or path params.
Example:
- before: duplicate/invalid host
- after: Invalid URI format: duplicate or invalid host. Already parsed host: localhost, but found ':' character at index 23. Total URI length: 45
> Enhance URI parsing exceptions

- servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
- servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
- servicetalk-examples/http/serialization/protobuf/build.gradle
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/SerializerUtils.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/ProtobufClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/ProtobufServer.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/ProtobufUrlClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/package-info.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/streaming/ProtobufStreamingClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/streaming/ProtobufStreamingServer.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/streaming/ProtobufStreamingUrlClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/async/streaming/package-info.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/BlockingProtobufClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/BlockingProtobufServer.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/BlockingProtobufUrlClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/package-info.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/streaming/BlockingProtobufStreamingClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/streaming/BlockingProtobufStreamingServer.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/streaming/BlockingProtobufStreamingUrlClient.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/blocking/streaming/package-info.java
- servicetalk-examples/http/serialization/protobuf/src/main/java/io/servicetalk/examples/http/serialization/protobuf/package-info.java
- servicetalk-examples/http/serialization/protobuf/src/main/proto/message.proto
- servicetalk-examples/http/serialization/protobuf/src/main/resources/log4j2.xml
- settings.gradle
Motivation:
HTTP users who work with protobuf payloads need an example of how to use
`ProtobufSerializerFactory`.
Modifications:
- Add `servicetalk-examples-http-serialization-protobuf` module to
demonstrate use of `ProtobufSerializerFactory` with HTTP;
- Update docs to reference a new example;
Result:
Users can see how to use `ProtobufSerializerFactory` with HTTP.
Depends on #2106 to avoid merge conflicts, review the 2nd commit.
> Add an HTTP example for protobuf serialization

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/MultiClientTest.java
This reverts commit 74ac3902a0ba09c72fde79923906ad1c3ac394ee.
> Revert "Removed GrpcClientBuilder#MultiClientBuilder (#1809)"

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/ClosedPartitionException.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/DuplicateAttributeException.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionAttributes.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionAttributesBuilder.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionMap.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionMapFactory.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionedServiceDiscovererEvent.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/UnknownPartitionException.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Motivation:
`PartitionedHttpClientBuilder` is hard to use because it requires
implementation of a special `ServiceDiscoverer` that we do not provide
OOTB. We are unaware of anyone using this feature, but if there are any
users they should consider `ClientGroup` as an alternative or reach out
to us to provide more context why the `PartitionedHttpClientBuilder` is
required.
Modifications:
- Deprecate `PartitionedHttpClientBuilder` and
`HttpClients.forPartitionedAddress`;
- Deprecate everything in `io.servicetalk.client.api.partition` package
Result:
`PartitionedHttpClientBuilder` is deprecated and can be removed in
future releases.
> Deprecated `PartitionedHttpClientBuilder` and partition client APIs

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Motivation:
Users can use
`MultiAddressHttpClientBuilder#initializer(SingleAddressInitializer)`
to override `ServiceDiscoverer` using
`SingleAddressHttpClientBuilder#serviceDiscoverer(ServiceDiscoverer)`.
Existing static factory is not necessary.
Modifications:
- Deprecate `HttpClients.forMultiAddressUrl(ServiceDiscoverer)`;
Result:
Less public API surface.
> Deprecate `HttpClients.forMultiAddressUrl(ServiceDiscoverer)`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionHttpClientBuilderConfigurator.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
Motivation:
A client instance is also used to create a request object because it
implements a request-response factory. Users of multi-address and
partitioned clients always use `DefaultHttpHeadersFactory.INSTANCE`.
There is no easy way to override headers factory. Use-cases: change
header name/value validation, preset some headers, etc.
Modifications:
- Add `MultiAddressHttpClientBuilder#headersFactory(HttpHeadersFactory)`
- Add `PartitionedHttpClientBuilder#headersFactory(HttpHeadersFactory)`
- Implement new methods;
- Test new feature for `MultiAddressHttpClientBuilder`;
Result:
Users of multi-address and partitioned clients can override the default
`HttpHeadersFactory`.
> Allow override of the `HttpHeadersFactory` for multi-address and partitioned clients

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/GlobalDnsServiceDiscoverer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilderTest.java
Motivation:
`DefaultMultiAddressHttpClientBuilder` and
`DefaultPartitionedHttpClientBuilder` use
`DefaultSingleAddressHttpClientBuilder` as a template for underlying
single-address clients. It was helpful before we introduced a
`SingleAddressInitializer` in #1387. Before that, all builders had the
same set of methods and it was nice to reuse the single-address builder
instead of maintaining a similar state at higher level builders. Now,
`SingleAddressInitializer` helps to avoid duplication between builders.
We don't have to use `DefaultSingleAddressHttpClientBuilder` as a
template and can simplify its state by using a factory for
`SingleAddressHttpClientBuilder`.
Modifications:
- `DefaultMultiAddressUrlHttpClientBuilder` and
`DefaultPartitionedHttpClientBuilder` use a factory for …
> Decouple multi-address and partitioned client builders from `HttpClientBuildContext`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
Quote from the spec
(https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2):
> This means that an intermediary transforming an HTTP/1.x message to
HTTP/2 will need to remove any header fields nominated by the
Connection header field, along with the Connection header field
itself.  Such intermediaries SHOULD also remove other connection-
specific header fields, such as Keep-Alive, Proxy-Connection,
Transfer-Encoding, and Upgrade, even if they are not nominated by the
Connection header field.
`H2ToStH1Utils.h1HeadersToH2Headers()` removes all described headers
except `proxy-connection`.
Modifications:
- Remove `proxy-connection` header from the outgoing HTTP/2 messages;
- Test that HTTP/2 client and server remove prohibited headers;
Result:
Outgoing HTTP/2 messages never …
> Remove `proxy-connection` header from outgoing HTTP/2 messages

- servicetalk-grpc-protoc/build.gradle
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
Motivation:
Generated gRPC classes have javadoc with illegal HTML characters
`<` and `>` and misses some `@param`. It causes build failures when
project compiles with `-Xwerror` flag.
Modifications:
- Replace parametrized types with non-parametrized for javadoc `@link`;
- Add missing `@param`;
- Include generated classes into `testJavadoc` task for
`servicetalk-grpc-protoc`;
Result:
Project generates javadoc successfully when run with `-Xwerror` flag.
> Javadoc for generated gRPC classes has warnings and errors

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
Motivation:
The generated code to build a service has two methods
with the same name:
* `addService(X)`
* `addService(BlockingX)`
The method overloading approach requires that folks cast their
services if they are implemented as lambdas. We can avoid
this ambiguity by qualifying the method name to:
* `addBlockingService(BlockingX)`
> grpc-protoc addService -> addBlockingService

- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
Motivation:
`addService(BlockingX)` was deprecated and javadocs were
added to indicate this. However we need to add javadocs for
all params/return value or else javadoc lint warnings will
be generated.
> grpc-protoc fix missing javadoc

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
Motivation:
The `RetryingHttpRequesterFilter` uses the context executor timer for
scheduling retry attempt. If offloading is disabled it should use the
context ioExecutor timer instead.
Modifications:
Use the appropriate timer based upon context execution strategy.
Result:
Retry timer will not use the context executor for scheduled retries if
offloading is disabled.
> Conditionally use ioExecutor timer for retry

- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
Motivation:
The current `DefaultHttpExecutionStrategyTest` does not cover all cases
and has a race condition involving subscribe and cancel.
Modifications:
Refactor test to cover all strategies and add more cases for each
strategy.
Result:
Improved and more reliable test.
> Extend `DefaultHttpExecutionStrategyTest`

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsClients.java
Motivation:
A `ServiceDiscoverer` returned from `DefaultDnsServiceDiscovererBuilder`
is an anonymous class without a proper name. To let users log what type
of `ServiceDiscoverer` they have a reference to, implement `toString()`.
Modifications:
- Implement `toString()` for `DnsClients`;
Result:
Users can log what `ServiceDiscoverer` they have reference to.
> Implement `ServiceDiscoverer#toString()` for DefaultDnsServiceDiscoverer

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapConcatUtils.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapConcatSingleTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ConcurrentUtils.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapConcatSingleDelayErrorTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapConcatSingleTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeSingleDelayErrorTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeSingleTckTest.java
Motivation:
Publisher.flatMapConcatSingle provides similar semantics to
Publisher.flatMapMergeSingle except the results are returned
in the same order as the original Publisher.
> Add Publisher.flatMapConcatSingle

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractPublisherProcessorSignalsHolder.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultBlockingProcessorSignalsHolder.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ProcessorBufferUtils.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherProcessorTest.java
Motivation:
Processors.newPublisherProcessor checks in the thread generating
data if a terminal has already been observed, and discards duplicates.
However the consumer thread also has the same logic which is required
because we cannot deliver signals to the Subscriber after a terminal
signal is delivered.
Modifications:
- Keep the required check in the queue consumer thread which filters
out duplicate terminal events, remove the check in the producer
thread. If there is a strict limit applied to the queue size
this may impact how many items the queue needs to hold.
Result:
Less atomic operations, 1 less class in the hierarchy, and less
memory consumed by Processors.newPublisherProcessor.
> Processors.newPublisherProcessor simplify duplicate terminal check

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/netty/NettyPipelinedConnectionBenchmark.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
- servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/TestHttpServiceContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/Tls13Test.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpClientConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpConnectorTest.java
- servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
- servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionInfo.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingConnectionContext.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherRefCountTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
Motivation:
`SSLSession` represents the result of SSL negotiation. However, it's
useful to know what `SslConfig` was used to establish the session for
observability or runtime checks.
Modifications:
- Add `ConnectionInfo#sslConfig()` method;
- Propagate `SslConfig` to all `ConnectionInfo` implementations;
- Adjust tests;
Result:
Users have access to `SslConfig` from service or connection
factory/filter.
> Expose `SslConfig` through `ConnectionInfo`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
Motivation:
The Publisher.multicast operator may throw IndexOutOfBounds
exception if a Subscription is cancelled multiple times and
there are other active Subscriptions.
> Publisher.multicast duplicate cancel IndexOutOfBounds exception

- servicetalk-concurrent-api/gradle/spotbugs/main-exclusions.xml
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CacheSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CacheSingleTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletableCacheTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleCacheTckTest.java
Motivation:
Some scenarios require that a `Single` or `Completable`
can be subscribed to multiple times. Using `Processors`
requires additional state management outside of the
subscriber/operators chain which must be done with care
to preserve backpressure, cancellation, and lazy semantics.
`Publisher.multicast` isn't directly applicable either
because the terminal value isn't cached and retained for
late subscribers as is often required.
Modifications:
- Add `Single.cache` and `Completable.cache` operators.
> Add [Single | Completable].cache operators

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthStrategyInfluencerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java
Motivation:
Currently the filter strategy is not considered in the computation of
the effective strategy for async streaming servers. This was done
because with a default builder strategy the result could be less
offloading which would be unexpected for that builder strategy.
Modifications:
Consider filter strategy in computing effective strategy for
async streaming servers.
Result:
More predictable offloading behavior.
> Use filter strategy for streaming async server

- CONTRIBUTING.adoc
Motivation:
The contributing instructions include no statement of requirements or
suggested practices for contributing documentation to the project.
Modifications:
Add minimal (and hopefully non-controversial) requirements and
suggestions for contributing to ServiceTalk documentation.
Result:
Improved clarity for contributors.
> CONTRIBUTING - Documentation Requirements section

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
Motivation:
Classes that extend `AbstractH2DuplexHandler` validate incoming HTTP/2
messages and if there are any protocol-specific errors (missing or
invalid headers) throws `IllegalArgumentException`. This later
translates into `RST_STREAM(CANCEL)`. Instead, HTTP/2 spec says that
in case of malformed message `RST_STREAM(PROTOCOL_ERROR)` must be sent.
We should also use `Http2Exception` type to propagate streamId and
error code to the users.
Modifications:
- In `AbstractH2DuplexHandler`s, replace all `IllegalArgumentException`
with `Http2Exception`;
- Write `RST_STREAM(PROTOCOL_ERROR)` before throwing an exception;
Result:
HTTP/2 behavior aligned with the spec, users see more detailed exception
type.
> HTTP/2 handlers should throw `Http2Exception` and send RST_STREAM frame

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverRequesterFilter.java
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverServiceFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLifecycleObserverHttpFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverServiceFilter.java
Motivation:
gRPC users can not use `HttpLifecycleObserverServiceFilter` to install
`GrpcLifecycleObserver` because `onGrpcStatus` won't be invoked.
Sometimes, it's necessary to see the state of other filters from inside
the observer.
Modifications:
- Make `HttpLifecycleObserverServiceFilter` extensible as a class, but
keep all its methods `final`;
- Add `GrpcLifecycleObserverServiceFilter`;
Result:
Users can install `GrpcLifecycleObserver` anywhere in a filter chain.
> Let users move `GrpcLifecycleObserver` in the filter chain

- servicetalk-dns-discovery-netty/build.gradle
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
Motivation:
Current DNS implementation of the `ServiceDiscoverer` sends new queries
after each TTL expires. This may lead to spikes in load on DNS servers
if many clients align their requests based on the returned TTL value.
Modifications:
- Add jitter for the subsequent DNS queries;
- Allow users to customize jitter value;
Result:
Subsequent DNS queries are spread out in time using jitter.
> Add jitter for the subsequent DNS queries

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
Motivation:
Cold start or traffic spikes can result in opening excess connections to
handle unexpected load. Current selection algorithm in
`RoundRobinLoadBalancer` attempts to pick a random connection. This
approach does not let to decrease number of open connections when
traffic stabilizes.
Modifications:
Introduce `linearSearchSpace` configuration option for
`RoundRobinLoadBalancerFactory` to start a linear search before falling
back to a random selection.
Result:
Allows configuring more predictable selection of the connection. When
configured with `IDLE_TIMEOUT` socket option, helps to reduce the number
of connections that can serve multiplexed or pipelined requests.
Default value of 16 has no performance impact on non-pipelined HTTP/1.1
connections, but significantly reduces …
> `RoundRobinLoadBalancer`: better identify excess connections

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionContextSocketOptionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpConnectorTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServiceTalkSocketOptions.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IdleTimeoutInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SocketOptionUtils.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherRefCountTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
Motivation:
It's a good practice to close excess connections if they become idle.
Modifications:
- Set default `IDLE_TIMEOUT` to 5 min;
- Clarify in javadoc that 0 value disabled idle timeout;
- Remove `@Nullable` annotation for `idleTimeoutMs` in internal classes;
Result:
Users always have `ServiceTalkSocketOptions#IDLE_TIMEOUT` set by
default.
Improves default behavior in conjunctions with #2173.
> Always set default `ServiceTalkSocketOptions#IDLE_TIMEOUT`

- servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/TextMapFormatter.java
Motivation:
When incoming context has no sampled key, the original code defaults sampled value to false, which causes all the downstream to not sample their spans.
The correct behavior is to default to `null` if sampled bit is not present.  If sampled bit is present, then set the `true`/`false` value.
This was previously fixed in `B3KeyValueFormatter`.
Modifications:
* `TextMapFormatter.extract` to default `sampled` to `null` unless set
> Default sampled to null rather than false when extracting trace context

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
Currently, health-checking events are logged at `DEBUG` level and the
failure cause is not propagated. Users have to change the logging level
and reproduce in order to understand the root cause.
Modifications:
- Log each failed attempt to create a connection at `INFO` level for
visibility;
- Log at `WARN` level when the health-checking is triggered;
- Retain the last cause that triggered health-checking inside
`HealthCheck` state to use it for `toString()`;
Result:
Users see when a connectivity issue occurs, cause is logged and
propagated for subsequent selection attempts if there are no other
`ACTIVE` hosts.
> `RoundRobinLoadBalancer`: increase visibility into health-checking

- servicetalk-examples/grpc/observer/src/main/java/io/servicetalk/examples/grpc/observer/LifecycleObserverServer.java
Motivation:
Demonstrate two different ways how to configure `GrpcLifecycleObserver`.
Modifications:
- Add more comments and option 2 in `LifecycleObserverServer`;
Result:
Users can see how to configure `GrpcLifecycleObserver` in 2 different
ways.
Follow-up for #2171, forgot to enhance the example.
> Enhance `servicetalk-examples-grpc-observer`

- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/DefaultContextMap.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractHttpMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpContextKeys.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
Motivation:
The connection initialization sequence is different for secure HTTP proxy
tunnels.  It's necessary for the `ConnectionFactory` and
`TransportObserver` to know if the `newConnection(...)` is being invoked for
a regular connection or a proxy tunnel in order to correctly count timing
of events.
Modifications:
- Introduce new `HttpContextKeys#HTTP_TARGET_ADDRESS_BEHIND_PROXY` key;
- Enhance `ProxyConnectConnectionFactoryFilter` and
`AbsoluteAddressHttpRequesterFilter` to fill in the value for
`HTTP_TARGET_ADDRESS_BEHIND_PROXY`;
- Enhance proxy tests to verify that the key value always present;
Result:
Users can distinguish attempts to open direct connections and
connections through a proxy.
Depends on #2168, review starting from the 2nd commit.
> Let `ConnectionFactory` see difference between proxied and direct connections

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultClientGroup.java
Motivation:
The current use of `ConcurrentMap` methods, especially for `remove()`
could be more specific about what it expects to remove or replace and
the operation should fail if the expectation is not met.
Modifications:
Use `ConcurrentMap::remove(key, value)` and
`ConcurrentMap::replace(key, oldValue, newValue)` methods
Result:
Greater assurance of correct behavior as the removed and replaced
values are checked.
> Use more specific `ConcurrentMap` methods

- servicetalk-grpc-protoc/build.gradle
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/FileDescriptor.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Main.java
- servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/InsertionPointTest.java
Adds plugin insertion point (comment) into servicetalk generated service classes.
When we want to enrich ServiceTalk generated service classes with additional functionality, this insertion point enables to add such code.
When we want to enrich ServiceTalk generated service classes with additional functionality, this insertion point enables to add such code.
- List the changes
Since JavaPoet has no way to add a comment within a class, Added an empty type as place holder and replaced it with the comment before adding the content to CodeGeneratorResponse
What is the result of this change?
Every ServiceTalk generated service class will have following comment towards the end of the class.
```
// @@protoc_insertion_point(service_scope:<fully qualified name of service>)
```
> Make ServiceTalk protoc plugin extensible

- scripts/publish-docs.sh
Motivation:
JDK11 was used for javadoc generation because of new features (search, ..).
JDK17 is now the latest LTS and we can take advantage of latest javadoc
features.
> Update JVM version for javadoc generation

- docs/generation/.gitignore
- scripts/release.sh
Motivation:
japicmp.sh is a standalone script that must be
manually run which is easy to forget.
Modifications:
- add branch name support to release.sh
- build locally
- call japicmp.sh by default
> Call japicmp.sh from release.sh

- scripts/release.sh
Motivation:
release.sh has a bug that doesn't allow specifying the branch,
also generating docs from non-main branch may overwrite antora
docs bundle which includes main branch content, so disable
publishing in this case.
> release.sh fixes to build on non-main branch

- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCompletable.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestPublisher.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSingle.java
- servicetalk-grpc-health/build.gradle
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/FileDescriptor.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/GenerationContext.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/ServiceClassBuilder.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
Motivation:
The release.sh script runs `javadocAll` task on JDK17 which
found a few errors.
Motivation:
- JDK8 javadoc generation has an erroneous
`warning - @link can't find` from generated code.
Workaround the issue by using canonical type name in the link.
- Remove `h3` usage in Test sources
- Remove exclude of generated code that is linked in javadocs
from non-generated code.
> Resolve javadocAll errors

- servicetalk-data-jackson-jersey/build.gradle
- servicetalk-data-jackson/build.gradle
Motivation:
The `servicetalk-data-jackson-jersey` module exposes types that are
located in the `servicetalk-data-jackson` module. Similarly, the
`servicetalk-data-jackson` module exposes types that are in the
`servicetalk-serializer-api` and `servicetalk-serialization-api` modules.
Dependencies that contain types exposed in a module's API should be imported using `api` scope but currently these dependencies are imported using only `implementation` scope. Attempting to use the types results in a `ClassNotFoundException`.
Modifications:
- Change `servicetalk-data-jackson` to an `api` dependency of `servicetalk-data-jackson-jersey`
- Change `servicetalk-serializer-api` and `servicetalk-serialization-api` to `api` dependencies of `servicetalk-data-jackson`
Result:
Consumers of the …
> fix: servicetalk-data-jackson dependency scopes

- servicetalk-concurrent-api/docs/modules/ROOT/pages/async-context.adoc
Modifications:
async-context.adoc provides some examples to describe
control flow and potential concurrent modification scenarios.
The example with the operator flow doesn't provide enough
explanation to understand the expected control flow.
Modifications:
- Add more comments to the example and code which
shows expected values on key modified "later" in the
operator chain.
> Clarify AsyncContext concurrency docs

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromBlockingIterablePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromIterablePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpClientTest.java
Motivation:
The blocking streaming APIs allow for specifying a Iterator
as input which is consumed by ServiceTalk. ServiceTalk assumes
it can consume in batches from the same thread in order to make
progress. However if the Iterator `next()` method is dependent
on external input we may deadlock:
- `PublisherAsBlockingIterable.onSubscribe(..)` does a `request(16)`
- `FromIterablePublisher.request(..)` loops calling `hasNext()` and
`next()` until demand is exhausted. Each loop iteration calls
`subscriber.onNext(next())`.
- The same thread looping in `FromIterablePublisher.request(..)` is
also responsible for draining the queue in `PublisherAsBlockingIterable`.
This means that no data will be sent downstream until
`FromIterablePublisher` exits the loop. This maybe perceived as
“dead lock” …
> Avoid deadlock consuming from blocking Iterator

- servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
- servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
- servicetalk-examples/grpc/keepalive/README.adoc
- servicetalk-examples/grpc/keepalive/build.gradle
- servicetalk-examples/grpc/keepalive/pom.xml
- servicetalk-examples/grpc/keepalive/src/main/java/io/servicetalk/examples/grpc/keepalive/KeepAliveClient.java
- servicetalk-examples/grpc/keepalive/src/main/java/io/servicetalk/examples/grpc/keepalive/KeepAliveServer.java
- servicetalk-examples/grpc/keepalive/src/main/java/io/servicetalk/examples/grpc/keepalive/package-info.java
- servicetalk-examples/grpc/keepalive/src/main/proto/helloworld.proto
- servicetalk-examples/grpc/keepalive/src/main/resources/log4j2.xml
- settings.gradle
Motivation:
Add an example demonstrating how the HTTP/2 transport keep alive feature can be used for gRPC clients and servers.
> Add example for h2 keep alive

- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkRootPlugin.groovy
Motivation:
Some modules generate JavaDoc to check that source code they generate
includes conforming JavaDoc. This test JavaDoc should not be included
in the consolidated project JavaDocs.
Modifications:
Filter JavaDoc tasks using task name to include only the default
JavaDoc task.
Result:
Mysterious test code JavaDoc excluded from project JavaDocs.
> Generate JavaDoc only for API JavaDoc tasks

- servicetalk-grpc-protoc/build.gradle
Motivation:
Currently the `servicetalk-grpc-protoc` module exposes javapoet and
protobuf-java as dependencies though they are used only in the protoc
plugin and are not accurately dependencies of the module.
Modifications:
Use `compileOnly` for protoc plugin dependencies and change shadowJar
to build using `compileClasspath` configuration. The dependencies are
also needed for `testImplementation`.
Result:
Fewer exposed dependencies, especially dependency which is not
actually used by module outside of protoc plugin.
> Tighter dependency for protoc plugin

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
RoundRobinLoadBalancer logs at the warn level if it takes
a host out of rotation due to exceeding the consecutive
failure threshold. The failure maybe retried and/or captured
in metrics/logs by the application and may not necessarily
justify a warn level log from the framework.
Modifications:
- Adjust log level to debug when below the failure threshold,
and info when crossing the threshold. Note the log level is
also info when the host is connected to again and taken out
of the penalty box.
> Reduce log level in RoundRobinLoadBalancer

- build.gradle
Motivation:
After some environmental changes (possibly #2184), some PRs fail to
resolve dependencies if `mavenCentral()` is not defined in
`build.gradle`.
Modifications:
- Add `mavenCentral()` if no repositories are configured;
Result:
Successful respolution of dependencies, see #2208.
> Add `mavenCentral()` repository if no repositories are configured

- servicetalk-examples/grpc/helloworld/pom.xml
Motivation:
`build.gradle` for grpc example uses `servicetalk-grpc-protoc-all`
artifact, but `pom.xml` uses `servicetalk-grpc-protoc`. After #2209,
maven example does not work anymore:
```
servicetalk-grpc-protoc_out: ServiceTalk code generation failed:
java.lang.NoClassDefFoundError: com/squareup/javapoet/ClassName
```
Modifications:
- Use `<classifier>all</classifier>` to let maven use an uber jar;
Result:
Maven build works for grpc example.
Related:
https://github.com/servicetalk/examples/pull/1
> Use `servicetalk-grpc-protoc-all` for pom.xml

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcOverH1.java
Motivation:
ServiceTalk can do gRPC over HTTP/1.x, and it can negotiate
protocols with TLS via ALPN. This isn't expected to be commonly
used in practice but is possible given the layering of transports
below protocol.
> Add unit test for gRPC over h1, negotiated by TLS+ALPN

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
Health checking is an indefinite process (for as long as the host is present), and relying on async-context can lead to misbehavior with code storing stuff in it.
Modification:
Upon subscribing for the health-check process, we clear async-context.
Result:
No state maintained in async-context for the lifetime of health-checking.
> Clear async-context inside RRLB health checking

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CallableCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
Motivation
New `Completable` adapter from a `Callable` implementation.
Modification
New API to support this adaptor along with modification on the pre-existing `fromRunnable` to re-use this new `Callable` approach and minimize duplication.
Result
Richer API
> Support Completable from a Callable

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatusCode.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/HttpResponseUponGrpcRequestTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
Motivation:
ServiceTalk currently assumes the response status is 200
when decoding into gRPC. This means we will fail during
checking the content-type or during deserialization if
an error is return from a middle proxy with a different
encoding type. We can provide more informative gRPC
error codes if we validate the h2 response status.
> gRPC improve error status for non-200 h2 response status

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java
Motivation:
The cause is logged only when users explicitly set
`-Dio.servicetalk.transport.netty.requireNativeLibs=true`. Logging cause
in all cases simplifies debugging of the issue. Looks like we accidentally 
removed the cause in #2006.
Modifications:
- Include the cause in `NativeTransportUtils` log message;
Result:
Users see the root cause why native libs are not loaded.
> Log the cause why native transport libs are not loaded

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerDefaultExecutionStrategyTest.java
Motivation:
When a `StreamingHttpService` is converted to another API flavor the
expected offloading points change.
Modifications:
Add a test that verifies that converted HTTP services have the expected
offloading.
Result:
Additional test coverage.
> Additional test of expected server offloading

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
Users should see when the resulting execution strategy is different from
what they configured at the builder and should be able to debug the
root cause.
Modifications:
- Log at `info` level when computed strategy adds more offloading to the
custom strategy specified at the builder;
- Add debug level logging for each computation step when changes are
detected;
Result:
Users see when strategy changes after analyzing filters and are able to
debug the cause.
> Enhance logging for execution strategy computation

- servicetalk-concurrent-api/gradle/spotbugs/main-exclusions.xml
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultExecutor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromIterablePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java
- servicetalk-concurrent-internal/gradle/spotbugs/main-exclusions.xml
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/AbstractCloseableIterable.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/AutoClosableUtils.java
- servicetalk-http-api/gradle/spotbugs/main-exclusions.xml
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedSerializer.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RequestResponseFactories.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
- servicetalk-opentracing-zipkin-publisher/gradle/spotbugs/main-exclusions.xml
- servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
- servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java
- servicetalk-serialization-api/src/test/java/io/servicetalk/serialization/api/DefaultSerializerDeserializationTest.java
Motivation:
In some instances we use APIs that throw checked
exceptions from methods without checked throws
exception in the method signature. In some of these
instances we wrap in a RuntimeException, however
this doesn't provide any insight into the exception
being thrown. Recent spotbugs warnings highlights
these cases.
Modifications:
- DefaultExecutor to rethrow checked exception which
is used internally to terminate async control flow
- RequestResponseFactories factory methods to rethrow
checked exceptions.
- Zipkin UdpReporter report method to throw
ClosedChannelException if already closed.
> Avoid direct usage of RuntimeException

- .gitignore
- docs/modules/ROOT/pages/performance.adoc
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/RouteSummaryBuilder.java
- servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/BlockingUdsClient.java
- servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/BlockingUdsServer.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestEncoder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-opentracing-internal/src/main/java/io/servicetalk/opentracing/internal/ZipkinHeaderNames.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DomainSocketAddress.java
This PR updates various `http` links found in the project documentation.
Yeah, I know, very low priority but an excuse for me to look around the codebase 😅.
Some clarifications:
- it does **not** affect the project code or tests suite.
- the licensing links were left untouched.
- the links updates have been split in separate commits so changes are easier to inspect.
Closes #2152
> Update `http` documentation links to `https`

- servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilder.java
Motivation:
Some of the types used by `HttpPredicateRouterBuilder` have changed
resulting in dead code.
Modifications:
Reduce complexity by removing code paths that are now impossible.
Result:
Cleaner, more obvious implementation.
> Cleanup `HttpPredicateRouterBuilder`

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcToHttpLifecycleObserverBridge.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverTest.java
- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/BiGrpcLifecycleObserver.java
- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLifecycleObserver.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLifecycleObserverHttpFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NoopHttpLifecycleObserver.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BiHttpLifecycleObserver.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
Motivation:
Track how subscriber requests payload body items.
Modifications:
- Add `HttpRequestObserver#onRequestDataRequested(long)`;
- Add `HttpResponseObserver#onResponseDataRequested(long)`;
- Enhance `HttpLifecycleObserverTest` and `GrpcLifecycleObserverTest`;
Result:
Users can track how many items subscriber requests from payload body,
and time difference between requested-delivered items.
> `HttpLifecycleObserver`: notify when payload body is requested

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
Motivation:
Callback helps users to see when channel's writability state changes.
Modifications:
- Add `ConnectionObserver#connectionWritabilityChanged(boolean)`;
Result:
Users can detect inefficient network configuration (too small outbound
socket buffer) or when the remote peer reads slower than expected.
> Add `ConnectionObserver#connectionWritabilityChanged(boolean)`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLifecycleObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportObserver.java
Motivation:
`TransportObserver` does not clarify if users can block or not inside
their implementations.
Modifications:
- Copy offloading requirements from `HttpLifecycleObserver` to
`TransportObserver`;
Result:
`TransportObserver` javadoc clarifies expectations for non-blocking
implementations and suggests to do manual offloading if necessary.
> Clarify expectations for `TransportObserver` implementations

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
Motivation:
Several methods in `HttpApiConversions` are due to be removed in the
next major release.
Modifications:
Mark methods deprecated for removal with comments to ensure they are
removed.
Result:
Better preparation for future removal.
> Mark methods to be removed in 0.43

- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-http-api/gradle/spotbugs/main-exclusions.xml
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpServerResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpServerResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequestMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpResponseMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerChainBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java
Motivation:
Without providing a `default` implementation for methods that are
deprecated, users can not avoid using those in the codebase.
Modifications:
- Enhance gRPC code generator to add `default` impl for deprecated
client methods;
- Add all missed `default` implementations for deprecated methods of
`HttpMetaData` and its subclasses;
Result:
Users can avoid depending on deprecated methods in their codebase and
prepare for the next version.
> Add default implementations for deprecated methods

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
- servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java
- servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/InOrderRouter.java
Motivation:
The `InOrderRouter` (aka predicate router), GRPC and Jersey routers
inherit default `requiredOffloads()` of `offloadAll()` from
`HttpStreamingService`. This behavior should be explicit.
Modifications:
Add implementations of `requiredOffloads()` returning `offloadAll()` with
documentation explaining the behavior and suggestions for handling
non-offloading requirements.
Result:
Explicit rather than implicit behavior.
> Make routers explicit about offloading behavior

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
Motivation:
The changes in #2108 introduced a regression in the handling of
computation of the effective strategy of a client when a
strategy `offloadNone()` (or the deprecated `offloadNever()`) was used
with the  `HttpClientBuilder`. Rather than preventing all offloading,
the computed offloading was used.
Modifications:
If the strategy specified on the `HttpClientBuilder` does not specify
any offloads then no offloading will be used.
Result:
The offloading behavior matches the requested behavior specified on
the  `HttpClientBuilder`.
> Fix regression of client `offloadNone()` strategy

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractBlockingStreamingHttpRequesterTest.java
- servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpRequesterFilterTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/FilterableClientToClient.java
Motivation:
`FilterableClientToClient` uses a provided `HttpExecutionStrategy` with
the underlying client but the `executionContext()` method returns an
`ExecutionContext` of the underlying client rather than the context and
strategy it is using.
Modifications:
Accept an `ExecutionContext` rather than an `ExecutionStrategy` and
return the context for `executionContext()`.
Result:
Accurate `executionContext()` result.
> Return `ExecutionContext` with correct strategy

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLifecycleObserver.java
Motivation:
When we added two new callbacks in #2230, we forgot to add a default
impl for one of them.
Modifications:
- Add default noop impl for
`HttpResponseObserver#onResponseDataRequested(long)`;
Result:
`HttpResponseObserver` is backward compatible for existing users.
> `HttpResponseObserver`: add default impl for `onResponseDataRequested`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
Motivation:
While RFC7230, section 3.1.2
(https://datatracker.ietf.org/doc/html/rfc7230#section-3.1.2) requires a
`SP` before a `reason-phrase`, even if it's an empty phrase, many
implementations don't include that `SP` character. Many clients parse a
response without trailing `SP` character with no error. Those
implementations are:
- Apache HTTP Client
- JDK HttpClient
- Netty
- Tomcat (https://bz.apache.org/bugzilla/show_bug.cgi?id=60362)
- Go HttpClient (https://github.com/golang/go/commit/d71d08af5ab15c7b166d92a31219c4c218438841#diff-0e6945dfde3e4dcaba7cfd394a85328b8137c42e152b4486dbfb6756ad69a779R145-R146)
- Rust HttpClient (https://github.com/hyperium/http/issues/345)
- httpd with Passenger (https://bugzilla.redhat.com/show_bug.cgi?id=1032733)
Moreover, neither HTTP/2 nor HTTP/3 …
> Allow no SP after status-code for HTTP/1.x responses

- servicetalk-examples/README.adoc
Motivation:
The `servicetalk/examples` repository contains examples of standalone
Gradle and Maven projects that import ServiceTalk without using the
related module "project" notation but use the more typical artifact
coordinate notation. We should provide a link to those examples.
Modifications:
Add reference to `[servicetalk-examples](https://github.com/servicetalk/examples)`
repository.
Result:
More linking between examples.
> Link to `servicetalk/examples` repo

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingle.java
Motivation:
The processing chain can add suppressed exceptions. If we return a
static instance of a `Throwable`, it can lead to a memory leak.
Modifications:
- Make `H2ClientParentConnectionContext.StacklessCancellationException`
pkg-private;
- Create a new `StacklessCancellationException` instead of always
returning the same static instance;
Result:
No possibility for a memory leak in a static `Throwable` instance.
> `SpliceFlatStreamToMetaSingle`: avoid returning a static `Throwable`

- servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/BufferDecoderGroup.java
- servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/BufferDecoderGroupBuilder.java
- servicetalk-examples/grpc/compression/src/main/java/io/servicetalk/examples/grpc/compression/CompressionExampleClient.java
- servicetalk-examples/grpc/compression/src/main/java/io/servicetalk/examples/grpc/compression/CompressionExampleServer.java
- servicetalk-examples/http/compression/src/main/java/io/servicetalk/examples/http/compression/CompressionFilterExampleClient.java
- servicetalk-examples/http/compression/src/main/java/io/servicetalk/examples/http/compression/CompressionFilterExampleServer.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BaseContentEncodingTest.java
Motivation:
BufferDecoderGroupBuilder#add has an `advertised` parameter
which often is true and the impacts of it being false may not
be clear.
Modifications:
- Add BufferDecoderGroupBuilder#add with no `advertised` param
- Clarify javadoc on BufferDecoderGroupBuilder#add method for
`advertised == false` implications.
> BufferDecoderGroupBuilder#add method w/out advertised

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverRequesterFilter.java
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverServiceFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverRequesterFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverServiceFilter.java
Motivation:
Make javadoc of all 4 filters consistent and clarify more use-cases for
consideration when users make a decision how to append an observability
filter.
Modifications:
- Improve javadoc for `HttpLifecycleObserverServiceFilter`,
`HttpLifecycleObserverRequesterFilter`,
`GrpcLifecycleObserverServiceFilter`, and
`GrpcLifecycleObserverRequesterFilter`;
Result:
More use-cases considered in javadoc of observability filters.
> Clarify preferred ordering for `[Http|Grpc]LifecycleObserver` filters

- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeClosableTest.java
Motivation:
CompositeClosableTest.alternatingOperationSOE on macOS M1 machine
doesn't stack overflow, and therefore the test fails.
Modifications:
- Add more objects to increase likelihood of SOE.
> Increase object count in CompositeClosableTest

- gradle.properties
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent.java
Motivation:
JCTools 3.3.1-ea provides unpadded queue variants which remove
padding intended to avoid false sharing scenarios. The padding
adds significant overhead when queue sizes are small which is
common for ServiceTalk's queue usage (operators that only queue
when back pressure occurs, pipelining requests which isn't
frequently used, ..)
Modifications:
- Unpadded queue variants currently only exist for the UNSAFE
variants. Switch PlatformDepedent UNSAFE queues to use them.
> Update JCTools 3.3.0 -> 3.3.1-ea, use unpadded queues

- servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilter.java
- servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpServiceFilter.java
- servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/ExecutionStrategyTest.java
Motivation:
Currently, `TracingHttpServiceFilter` inherits default implementation of
`requiredOffloads()` which enabled offloading. However, this filter is
non-blocking.
Modifications:
- Implement `TracingHttpServiceFilter#requiredOffloads()` that returns
`offloadNone()` strategy;
Result:
`TracingHttpServiceFilter` correctly identifies itself as a non-blocking
filter.
> `TracingHttpServiceFilter` should implement `requiredOffloads()`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
Motivation:
Currently, `appendNonOffloadingServiceFilter` does not include a name of
the filter/predicate that triggers this exception. It makes it harder to
understand the root cause.
Modifications:
- Reword the `IllegalArgumentException` message to include the class
name of the filter/predicate, and suggestion for resolution;
Result:
Easier for users to understand the root cause and how to fix it.
> Enhance exception message thrown from `appendNonOffloadingServiceFilter`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableDefer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FilterPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherDefer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherGroupBy.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherGroupToMany.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatWhenSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryWhenSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleDefer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleFlatMapCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleFlatMapPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleFlatMapSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutSingle.java
Motivation:
Some operators require a Functional interface that provide a
non-null result (e.g. flatMap). When this scenario occurs
as NPE is propagated however the control flow is async so
it is challenging to determine where the code is that caused
the NPE.
Modifications:
- Enhance the NPE to include a reference to the Functional
interface which provides more context as to where the NPE
originated from.
> Enhance NPE in operators that invoke functions

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
Motivation:
Server can cancel response before it starts requesting payload body.
Modifications:
- Change Mockito verification from `atLeastOnce()` to `atMostOnce()`;
Result:
Resolves #1847.
> Fix `HttpLifecycleObserverTest#testClientCancelsRequestBeforeResponse()`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpConnection.java
Motivation:
The `connectStrategy` propagated to `AbstractLBHttpConnectionFactory`
should be used only for `newConnection` operation, but not for the
conversions inside `LoadBalancedStreamingHttpConnection`. That strategy
has to be taken from the `ExecutionContext` that takes into account
all filters that are applied to a reserved connection.
Modifications:
- `LoadBalancedStreamingHttpConnection` uses a strategy from execution
context instead of a `connectStrategy`;
- Validate `protocolBinding` in `AbstractLBHttpConnectionFactory` before
allocating `filterableConnectionFactory`;
- Skip the merge of `connectionFactoryStrategy` with
`ProxyConnectConnectionFactoryFilter` bcz we know the internal filters
never block or modify the strategy;
Result:
`LoadBalancedStreamingHttpConnection` uses the …
> `LoadBalancedStreamingHttpConnection` doesn't need connect strategy

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java
Motivation:
If a response is cancelled at the connection level (skipping explicit
closure of the connection in `LoadBalancedStreamingHttpClient`), it will
hang in half-closed state (inbound closed) if the server doesn't proceed
with sending more bytes on that connection (outbound will never be
closed). Also, cancellation marks the connection as
`CHANNEL_CLOSED_INBOUND`, which is misleading because the closure is
initiated by the client.
Modifications:
- Enhance `ResponseCancelTest` to verify the described scenario;
- Adjust `NettyChannelPublisher` to close both outbound (first, to
correctly mark the connection close reason) and inbound;
Result:
Cancelled HTTP/1.x connection is always closed correctly.
> Cancellation can leave an HTTP/1.x connection in half-closed state

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultKeepAlivePolicy.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1ProtocolConfigBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1SpecExceptions.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
Motivation:
For easier debugging and visibility of the internal state of the
`HttpProtocolConfig` implementations and its subcomponents.
Modifications:
- Implement `toString()` for `DefaultH1ProtocolConfig`,
`DefaultH2ProtocolConfig`, `DefaultHttpHeadersFactory`,
`H2HeadersFactory`, `DefaultKeepAlivePolicy`, `H1SpecExceptions`;
Result:
Users can log intercepted configurations to see what is inside.
> Implement `toString()` for `HttpProtocolConfig` and its components

- scripts/release.sh
Motivation:
The `release.sh` script when pushing version update commit updates the
upstream branch.
Modifications:
Push but do not update the upstream branch.
Result:
No unexpected change of upstream.
> Do not update user's upstream branch

- servicetalk-bom/build.gradle
Motivation:
servicetalk-bom currently has `-internal` dependencies as `runtime`. This means
that projects which do depend upon these artifacts for implementation purposes
don't inherit the version from the bom. This can be problematic if the version
of ServiceTalk isn't directly specified by the project but instead inherited
through another bom (multi-level bom). In this case without `api` depdencies
the application must again manually track versions which the bom is intended
to avoid.
> servicetalk-bom to include internal depdencies as API

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ClientInvoker.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
Motivation:
After simplifying offloading in #1695, `ClientInvoker` interface does
not provide any value and can be removed.
Modifications:
- Remove the remaining pkg-private use of `ClientInvoker`;
- Deprecate `ClientInvoker` interface;
Result:
`ClientInvoker` interface is deprecated and can be removed in the future
releases.
> Deprecate unused `ClientInvoker` interface

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactory.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
Motivation:
#2168 and #2235 added default implementations that throw an exception.
However, those method signatures return an async source.
Modifications:
- Return a `failed` source with an exception instead of throwing;
Result:
Default methods follow async contract.
> Default methods that return async sources should not throw

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IdleTimeoutInitializer.java
Motivation:
Stick to the consistent format of starting all netty-level logs with
the channel info.
> Adjust logging in `IdleTimeoutInitializer`

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancedAddress.java
Motivation:
#2168 add `ContextMap` for `LoadBalancer` and `ConnectionFactory`, but
does not let the context go through `LoadBalancedAddress`.
Modifications:
- Add `LoadBalancedAddress#newConnection(ContextMap)` method;
- Deprecate `LoadBalancedAddress#newConnection()`;
Result:
Caller context can be propagated through `LoadBalancedAddress`.
> Propagate `ContextMap` through `LoadBalancedAddress`

- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/ConnectablePayloadWriterTest.java
Motivation:
The default timeout is 10 seconds. When build servers or local machines are
busy this test may timeout.
> ConnectablePayloadWriterTest.multiThreadedProducerConsumer increase timeout

- servicetalk-dependencies/build.gradle
- servicetalk-http-netty/build.gradle
- servicetalk-http-netty/gradle/checkstyle/suppressions.xml
- servicetalk-transport-netty-internal/build.gradle
- servicetalk-transport-netty-internal/gradle/checkstyle/suppressions.xml
Motivation:
netty-incubator-transport-native-io_uring is referenced in multiple projects
and not yet included in Netty's bom. We should include it in the dependency
bom to align versions until Netty provides this.
> Add netty-incubator-transport-native-io_uring to servicetalk-dependencies

- servicetalk-grpc-protoc/build.gradle
Motivation:
The grpc-protoc plugin generates javadoc but uses
inconsistent options to validate relative to the
main project options. We should make the options
consistent.
> grpc-protoc javadoc testing updates

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFactory.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFilterFactory.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
Motivation:
#1893 removed support of gRPC Filters and stopped using some of the
public/protected API that were targeted for filters. Some of these APIs
were not marked as `@Deprecated` and were not removed before 0.42
release.
Modifications:
- Mark `GrpcRoutes#registerRoutes` and `GrpcRoutes#newServiceFromRoutes`
methods as deprecated;
- Mark `GrpcRoutes.AllGrpcRoutes` interface as deprecated;
- Add reminding `FIXME` comments to make sure we remove all deprecations
in 0.43;
Result:
Unused code is marked as deprecated and can be removed in the next
release.
> Deprecate public gRPC API that is not used anymore by ST

- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeClosableTest.java
Motivation:
This test fails for me on local builds when the build system is heavily
saturated.
Modifications:
Increasing the timeout allows the tests to succeed.
Result:
Fewer intermittent test failures
> Increase `CompositeClosableTest` timeouts

- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/AbstractRequestConcurrencyController.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/AbstractReservableRequestConcurrencyController.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/IgnoreConsumedEvent.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/RequestConcurrencyController.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/RequestConcurrencyControllerMulti.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/RequestConcurrencyControllerOnlySingle.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/RequestConcurrencyControllers.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyController.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllerMulti.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllerOnlySingle.java
- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllers.java
- servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/AbstractRequestConcurrencyControllerOnlySingleTest.java
- servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/RequestConcurrencyControllerMultiTest.java
- servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/RequestConcurrencyControllerOnlySingleTest.java
- servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllerMultiTest.java
- servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllerOnlySingleTest.java
- servicetalk-dns-discovery-netty/build.gradle
- servicetalk-http-api/build.gradle
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllersTest.java
- servicetalk-loadbalancer/build.gradle
Motivation:
#2278 moved `RequestConcurrencyController` and
`ReservableRequestConcurrencyController` from `client-api-internal` to
`client-api` module. This is an API incompatible change for 0.42.x.
Also, it removed
`DefaultHttpLoadBalancerFactory#toLoadBalancedConnection` impl, this
is a binary incompatible change.
Modifications:
- Restore `io.servicetalk.client.api.internal.RequestConcurrencyController`
and `io.servicetalk.client.api.internal.ReservableRequestConcurrencyController`
interfaces and all references to them in `client-api-internal` module;
- Create a pkg-private copy of `ReservableRequestConcurrencyControllers`
inside `http-netty` module that targets public
`io.servicetalk.client.api.ReservableRequestConcurrencyController`;
- Copy tests for …
> Revert backward incompatible changes (api & binary) introduced in #2278

- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/DefaultPartitionedClientGroup.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
Motivation:
#2131 and #2267 deprecate partitioned HTTP client and classes required
for its impl, but `DefaultPartitionedClientGroup` is still not
deprecated.
Modifications:
- Deprecate
`io.servicetalk.client.api.internal.DefaultPartitionedClientGroup`;
Result:
All (hopefully) classes related to "partitioned" client are deprecated
now.
> Deprecate `io.servicetalk.client.api.internal.DefaultPartitionedClientGroup`

- servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeNoZeroingDirectByteBuf.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent0.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ThrowableUtils.java
- servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/PlatformDependentTest.java
- servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/ThrowableUtilsTest.java
Motivation:
Attempting to build using a Java 9+ `javac` with the `--release`
option fails because the ServicetTalk source contains references to
the `sun.misc.Unsafe` class. This class is not required by ServiceTalk
for correct execution but the appearance of the class in the source
currently requires that source be compiled with Java 8 or without
the `--release` option.
Modifications:
Use reflection and method handles rather than direct class use for
`sun.misc.Unsafe` to avoid [JDK-8214165](https://bugs.openjdk.org/browse/JDK-8214165).
Result:
ServiceTalk may be compiled using the `javac --release` option.
> Hide use of `sun.misc.Unsafe` from `javac`

- build.gradle
- docs/generation/gradle.properties
- gradle.properties
- servicetalk-buffer-api/build.gradle
- servicetalk-concurrent-jdkflow/build.gradle
- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
Motivation:
Using `sourceCompatibility` and `targetCompatibility` for specifying
Java version does not always produce correct module metadata because
the setting is quite sensitive to order of operations.
Modifications:
Use `options.release` whenever build JDK is >= Java 9. To support `javac`
compilation using the `--release` option it is necessary to hide direct use
of the `sun.misc.Unsafe` class as this class is not provided in the symbols
used for compiling.
Result:
Correct Java variant versions exported in module files
> Use `compileJava` `options.release`

- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
Motivation:
gRPC filters were previously removed due to infrequent usage, large amount
of generated code, and users ability to manually wrap to provide the same
capabilities. However on the client side wrapping requires converting
from async to blocking which pushes common boilerplate code onto users.
Modifications:
- Use the existing AsyncToBlocking client generated code (which isn't
used) as the default conversion from the async API.
Result:
Users can create an async wrapper for the client, and don't need
to worry about the blocking API conversion.
> gRPC add default method for asBlockingClient to simplify filter creation

- servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java
Motivation:
DefaultJerseyStreamingHttpRouter relies upon the `ContainerResponseWriter` to
terminate the request, and therefore the reactive stream subscriber. However
it wasn't known if there were control flows that may result in duplicate
termination so defensive code was added to guard against this case.
During shutdown it is possible for the `ApplicationHandler#handle(..)` method
to throw and in this case duplicate termination maybe expected. We currently
log an error because this wasn't expected but this raises false alarms and
should be removed.
```
java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,0,891192830) has been shut down
at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2370)
at …
```
> Remove logging for duplicate termination in Jersey router

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
Motivation:
If server returns a `Trailers-Only` response for a streaming request, we
never drain the response message-body, because `concat` never subscribes
to the next source if the first source fails. As the result, concurrency
controller won't mark the request as finished. If the request publisher
never completes we will start leaking h2 connections because streams
won’t be closed.
Modifications:
- Enhance `TrailersOnlyErrorTest` to cover blocking client and make sure
the HTTP response terminates;
- In case of an error in `Trailers-Only` response, subscribe and cancel
the response message body to abort the request;
- Always check that `Trailers-Only` response doesn't have any further
frames on the wire;
Result:
gRPC response correctly terminates even if client receives a …
> gRPC Trailers-Only response doesn't mark a streaming request as finished

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
Motivation:
Different load-balancer implementations can support connection scores or not.
Due to common interfaces it would be easy for a user to mix scoring protocol agnostic load-balancer with a non scoring
protocol specific wrapper, without knowing that the configuration was wrong, either in built or run times.
Modifications:
Let default implementations of `score()` throw an error instead, thus making visible the misuse during runtime.
Result:
Better misconfiguration visibility
> Throw error when score is invoked on a connection that doesn't support it.

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
Motivation:
`DefaultGrpcServerBuilder` invokes a provided Supplier without checking
the result for null. A `NullPointerException` will occur, but will not
include context about what was null.
Modifications:
Add `Objects.requireNonNull` check when invoking `Supplier`
Result:
Better diagnostic for failed Supplier.
> Null check result of `HttpServerBuilder` supplier

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/netty/NettyPipelinedConnectionBenchmark.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ParentConnectionContextTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpConnectionContext.java
- servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/TestHttpServiceContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultNettyHttpConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ParentConnectionContextTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionContext.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingConnectionContext.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
Server-side users have access only to HTTP/2 stream `ConnectionContext`
from the `HttpServiceContext`. In some cases, it's important to access
a `ConnectionContext` of the underlying TCP connection.
Modifications:
- Add `@Nullable ConnectionContext#parent()` method;
- Implement support for a new method;
- Add tests;
Result:
Users can access the underlying TCP `ConnectionContext` from the HTTP/2
service endpoint.
> Give access to the underlying TCP ConnectionContext from HTTP/2 service

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapConcatUtils.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SourceToFuture.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ThrowableWrapper.java
Motivation:
Publisher#flatMapConcatSingle maintains a queue of elements
on top of Publisher#flatMapSingle to maintain ordering. Elements
within this queue have non-volatile state due to outer concurrency
protections, however there are two independent variables indicating
"terminal type" and "terminal value". This may result in reading
the "terminal type" the "terminal value" may not be visible yet
and return `null`.
Modifications:
- Collapse the 2 variables into a single variable, so when reading
if it is non-null we have the "type" and "value" visible.
Result:
Fixes https://github.com/apple/servicetalk/issues/2321
> Publisher#flatMapConcatSingle null value concurrency fix

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
RoundRobinLoadBalancer will put hosts/remote-addresses that
we fail to establish a connection to 5 consecutive times
into a "penalty box" making them ineligible for selection
and in the background retry connection attempts. The retry strategy
uses FullJitter and default of 1 second. This has been observed to
issue many retry attempts (16+) per second which is more frequent
than typically required.
Modifications:
- Switch to using DeltaJitter and increase the default retry duration
to 5 seconds.
> RoundRobinLoadBalancer bad host retry use DeltaJitter

- servicetalk-dependencies/build.gradle
Motivation:
Gradle intentionally skips dependencies constraints with a classifier
when it generates Maven BOM file.
See https://github.com/gradle/gradle/issues/8561.
It negatively affects maven users bcz maven marks
`servicetalk-transport-netty-internal` POM file as invalid:
```
[WARNING] The POM for io.servicetalk:servicetalk-transport-netty-internal:jar:0.42.14 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for io.servicetalk:servicetalk-transport-netty-internal:0.42.14
[ERROR] 'dependencies.dependency.version' for io.netty.incubator:netty-incubator-transport-native-io_uring:jar:linux-x86_64 is missing. @
[ERROR] 'dependencies.dependency.version' for …
```
> Add io_uring dependencies with classifiers in `servicetalk-dependencies`

- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingClient.java
- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingServer.java
- servicetalk-examples/http/debugging/build.gradle
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
- servicetalk-examples/http/debugging/src/main/resources/log4j2.xml
- servicetalk-examples/http/http2/build.gradle
- servicetalk-examples/http/mutual-tls/build.gradle
- servicetalk-examples/http/redirects/build.gradle
Motivation:
Users unintentionally copy HTTP/2 configuration when they should debug
only HTTP/1.1 and still ask questions why trace logs are not visible.
Modifications:
- Clarify 2nd and 3rd argument of `enableWireLogging` and
`enableFrameLogging`;
- Clarify that `HttpProtocolConfigs.h2()` is required only for HTTP/2;
- Clarify how to `enableFrameLogging` in case of ALPN;
Result:
More comments for debugging examples.
> Clarify debugging examples with more comments

- gradle.properties
This reverts commit a0c8d6150e1b9eb257728f94777fe85b3e1f977c.
We anticipate another release before updating Netty versions,
and there is a Netty issue that may impact ServiceTalk users:
https://github.com/netty/netty/pull/12743.
> Revert "Update Netty 4.1.79 -> 4.1.80 (#2332)"

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CloseUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionInfoTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerGracefulConnectionClosureHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TimeoutHttpRequesterFilterTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java
Motivation:
#2266 (released in 0.42.13) introduces a race between cancel marking a
connection as "closing" (requires a hop to the event-loop), followed by
propagation of `onError` (on the cancel thread) that marks the request
as "finished", and the next request selecting the same connection. This
only affects rare users who cancel at the connection level, users who
use `TimeoutHttpRequesterFilter` as `appendClientFilter` are not
affected.
Modifications:
- Move `onClosing` to `NettyChannelListenableAsyncCloseable`;
- Notify `onClosing` asap for `channelInactive` event;
- Log a warning if `AbstractLBHttpConnectionFactory` can not access
`onClosing` (users incorrectly wrapped a connection);
- Log a warning if `LoadBalancedStreamingHttpClient` takes ownership of
the `OnStreamClosedRunnable` …
> Avoid race when HTTP/1.x request is cancelled at connection level filter

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpKeepAlive.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
Motivation:
ServiceTalk can negotiate http/1.x or http/2 through ALPN when TLS
is enabled. ServiceTalk doesn't know which request factory to use
until the protocol negotiation completes. It is possible that the
http/1.x request factory is used when speaking http/2.x which may
result in premature connection closure due to keep alive logic bug.
Modifications:
- http/2+ should be treated as always using keep alive and doesn't
use connection specific keep alive headers [1].
[1] https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.2
> HTTP/2 avoid premature connection closure when negotiating via ALPN

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/RequestRejectedException.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/IdleTimeoutConnectionFilter.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/IdleTimeoutConnectionFilterTest.java
Motivation:
When `IDLE_TIMEOUT` is used as a mechanism to close unused (excess)
connections, it introduces a risk to impact long-polling requests. Users
always have to coordinate request timeout value with `IDLE_TIMEOUT`
value.
Modifications:
- Add `IdleTimeoutConnectionFilter` and tests;
Result:
Users can still close excess connection without interference with
long-polling requests.
> Introduce `IdleTimeoutConnectionFilter` as alternative to `IDLE_TIMEOUT`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
Motivation:
#2278 added a new connection wrapper
`DefaultFilterableStreamingHttpLoadBalancedConnection` that does not
implement `toString()`. It hides the channel id in RRLB logs.
Modifications:
- Implement `toString()` for
`DefaultFilterableStreamingHttpLoadBalancedConnection` in
`HttpLoadBalancerFactory` and `DefaultHttpLoadBalancerFactory`;
- Make `AbstractStreamingHttpConnection#toString()` final;
Result:
RRLB logs include channel id.
> Override `toString()` for delegating connections

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/IoUringTest.java
Motivation:
Users may run tests on linux kernel that does not support io_uring. To avoid failure of `IoUringTest.ioUringIsAvailableOnLinux()` we need to run it only when io_uring is available.
Modifications:
- Use `assumeTrue` instead of `assertTrue`;
- Test with & without offloading;
Result:
Users can run tests on any linux kernel without failure due to io_uring unavailability.
> Make io_uring tests on linux more lenient

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Http2SettingsBuilder.java
Motivation:
If `DefaultHttp2Settings` has a non-standard setting id that falls into control characters space, those won't be visible in logs.
Modifications:
- Print HEX value of an unknown setting identifier;
- Increase initial `StringBuilder` length to account for the max length of standard settings;
Result:
Custom settings identifiers are visible in logs.
> Improve `DefaultHttp2Settings#toString()`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpConfig.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpServerConfig.java
Motivation:
#2341 changed default HTTP/2 settings that client sends to notify the server it does not support Server Push.
Modification:
- Set `ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0` in settings frame that client sends to a server;
- Validate custom initial settings that users pass to `H2ProtocolConfig` and throw if users try to override ENABLE_PUSH/MAX_CONCURRENT_STREAMS on the client or set ENABLE_PUSH other than 0 for the server;
- Include content message in GO_AWAY frame if client receives a Push Stream frame;
Result:
Default client behavior doesn't change, custom settings validated to prevent programming mistakes.
> Revert default HTTP/2 settings sent by the client

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/IdleTimeoutConnectionFilter.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/IdleTimeoutConnectionFilterTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
Motivation:
`ServiceTalkSocketOptions.IDLE_TIMEOUT` currently has the default value of 5 min. This default value makes it harder for users to coordinate between per-request timeout and per-client `IDLE_TIMEOUT`. Example: long-polling requests that use much higher timeout might be interrupted by lower `IDLE_TIMEOUT` value.
Modifications:
- Change the default value for `IDLE_TIMEOUT` to 0;
- If users didn't append `IdleTimeoutConnectionFilter`, configure one by default with 5 min timeout;
- Allow configuring `IdleTimeoutConnectionFilter` with `Duration.ZERO`;
- Add `toString()` impl for `IdleTimeoutConnectionFilter`;
Result:
Long-polling requests are not affected by default `IDLE_TIMEOUT` value, while ST users still have a filter that closes connections that were not used to serve any …
> Use `IdleTimeoutConnectionFilter` instead of SocketOption by default

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java
Motivation:
The parsing of Set-Cookie headers is deviating from the standard in a couple of ways.
- Cookie values are allowed to contain the equals sign character.
- Percentage-prefixed hexadecimal literals are not a thing.
- Only cookie-values need to adhere to the cookie-octet rule.
- Defined but empty values should decode to the empty string rather than null, so we can distinguish between their empty and absent cases.
- When parsing Set-Cookie values, every ; must be followed by a space.
See the `set-cookie-string` rule in https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1
The parser should check for this, since it can lead to mis-parsing later data and produce confusing error messages, or the produce a cookie object with wrong data.
Modification:
When the parser decodes the '=' …
> Improve parsing of Set-Cookie headers

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingInputStreamTest.java
Motivation:
Users of the blocking HTTP clients, like Apache HTTP Client, know that it's possible to access entity's `InputStream` multiple times and continue to read the payload body.
Modifications:
- Cache a reference to `InputStream` and return the same instance for subsequent calls in `DefaultBlockingStreamingHttpRequest` and `DefaultBlockingStreamingHttpResponse`;
- Add a test to verify this behavior;
Result:
Users can take `payloadBodyInputStream()` multiple times without seeing `DuplicateSubscribeException`.
> Allow users access `payloadBodyInputStream()` multiple times

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
Motivation:
`CharSequences.asciiStringIndexOf` is not used outside of the `CharSequences` class. Users should use `CharSequences#indexOf` instead.
Modifications:
- Deprecate `CharSequences.asciiStringIndexOf`;
Result:
`CharSequences.asciiStringIndexOf` is deprecated and can be made private in future releases.
> Deprecate `CharSequences.asciiStringIndexOf`

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/AsciiBuffer.java
- servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/CharSequencesTest.java
Motivation:
`AsciiBuffer.indexOf` casts `char` to `byte` by dropping the higher 8 bits. As the result, it may return an index of an ascii character that has the same lower 8 bits.
Modifications:
- Check character length and return `-1` if it's 2-bytes character;
Result:
Correct result when users try to find an index of a 2-bytes character in `AsciiBuffer`. Consistency with other `CharSequence` implementations, like `String` and `StringBuilder`.
> `AsciiBuffer.indexOf` returns incorrect result for 2-bytes characters

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CacheSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompositeExceptionUtils.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java
Motivation:
Publisher#flatMapMerge has internal state that tracks demand. This state is used to drive the internal state machine and prevents invalid demand to avoid internal state being corrupted. However this code didn't always allow for the subsequent terminal (e.g. likely onError) to be propagated downstream which may result in a hang.
Modifications:
- FlatMapPublisherSubscriber demand tracking shouldn't prevent terminal if there is too many items delivered.
- Remove conditionals that are unnecessary for needsDemand because the call sites know if demand is required.
> Publisher#flatMapMerge allow terminal propagation after invalid demand

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfig.java
Motivation:
#2341 added 3 new methods on `H2ProtocolConfig` interface but didn't provide default implementations.
Modifications:
- Add default impls for `initialSettings()`, `flowControlQuantum()`, and `flowControlWindowIncrement()`;
Result:
`H2ProtocolConfig` is backward compatible with 0.42.16 release.
> Make `H2ProtocolConfig` interface backward compatible

- servicetalk-http-api/build.gradle
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpRequesterFilter.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilterTest.java
- servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpRequesterFilterTest.java
Motivation:
ContentEncodingHttpRequesterFilter will apply compression or decompression. This may change the overall payload length and if the content-length header is present it will likely be incorrect after.
Modifications:
- Remove the content-length header if encoding/decoding is applied in ContentEncodingHttpRequesterFilter. Headers are already manipulated to add/remove content-encoding.
> ContentEncodingHttpRequesterFilter to remove content-length

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilter.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/ContentEncodingHttpRequesterFilterTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilterTest.java
- servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpServiceFilterTest.java
Motivation:
ContentEncodingHttpServiceFilter will apply compression or decompression. This may change the overall payload length and if the content-length header is present it will likely be incorrect after.
Modifications:
- Remove the content-length header if encoding/decoding is applied in ContentEncodingHttpServiceFilter. Headers are already manipulated to add/remove content-encoding.
> ContentEncodingHttpServiceFilter to remove content-length

- servicetalk-http-api/build.gradle
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesRfc6265Test.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java
Motivation:
- #2329 made parsing of `set-cookie` header strict according to RFC6265. In practice, there are still many implementations that encode cookies according to the obsolete RFC2965 and/or RFC2109.
- Semicolon and space are not validated after a wrapped value.
- Without a cookie name in the exception message it's harder to find a problematic cookie.
Modifications:
- Allow no space after semicolon by default;
- Add a system property `io.servicetalk.http.api.headers.cookieParsingStrictRfc6265` to enforce strict parsing;
- Instead of blindly skipping `SEMI` and `SP` after `DQUOTE`, validate skipped characters;
- Include the cookie name (if already parsed) in all exception messages;
- Enhance test coverage for `DefaultHttpSetCookie#parseSetCookie`;
Result:
1. No space is required after …
> Improvements for `Set-Cookie` parsing, allow lax parsing of older specs

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
The test assumes that graceful closure should be initiated within 300ms. However, on close CI this can take longer.
Modifications:
- Await indefinitely for initialization of the server-side graceful closure;
Result:
`H2PriorKnowledgeFeatureParityTest.serverGracefulClose()` does not fail due to too short await time.
> Fix flaky `H2PriorKnowledgeFeatureParityTest.serverGracefulClose()`

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
Motivation:
It's possible that requesting more data from the payload publisher can race with completion. Subsequent `request(N)` are possible even after both observers terminate.
Modifications:
- Await for client & server shutdown before starting verification of invoked observer callbacks.
Result:
No more events are possible after server shutdown. Verification step sees all observed events.
Resolves #2343.
Resolves #2298.
> Fix flaky `[Http|Grpc]LifecycleObserverTest`

- servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
- servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
- servicetalk-examples/http/serialization/bytes/build.gradle
- servicetalk-examples/http/serialization/bytes/src/main/java/io/servicetalk/examples/http/serialization/bytes/SerializerUtils.java
- servicetalk-examples/http/serialization/bytes/src/main/java/io/servicetalk/examples/http/serialization/bytes/blocking/BlockingBytesClient.java
- servicetalk-examples/http/serialization/bytes/src/main/java/io/servicetalk/examples/http/serialization/bytes/blocking/BlockingPojoServer.java
- servicetalk-examples/http/serialization/bytes/src/main/java/io/servicetalk/examples/http/serialization/bytes/blocking/package-info.java
- servicetalk-examples/http/serialization/bytes/src/main/java/io/servicetalk/examples/http/serialization/bytes/package-info.java
- servicetalk-examples/http/serialization/bytes/src/main/resources/log4j2.xml
- settings.gradle
Motivation:
Some times folks want to get the payload body as a `byte[]` and `ByteArraySerializer` can be used for this.
> Add http byte[] aggregated example

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java
Motivation:
#2297 indicates that `ResponseCancelTest` sometimes fails. It happens
because we incorrectly request signals from `delayedClientTermination`
queue. After cancel we may or may not see a terminal event. In rare
cases, `StacklessClosedChannelException` is propagated to the subscriber
after cancel. The next request does not assume that there is a pending
`ClientTerminationSignal` in the queue and considers this exception as
failure for a new request.
Modifications:
- Introduce a `requestId` to associate `ClientTerminationSignal` with
a proper request;
- Discard signals for prior requests inside `resume` logic;
- Wrap `signal.err` with `AssertionError` to preserve a caller stack
trace;
Result:
Fixes #2297.
> Fix flaky `ResponseCancelTest`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
Motivation:
DefaultBlockingStreamingHttp* objects have control flow where they use map and cast to an Object, this can use the `cast` operator. There are also defer operators used that don't need to copy AsyncContext so `shareContextOnSubscribe` can be used to avoid copying.
> DefaultBlockingHttp objects to use cast and shareContextOnSubscribe

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcClients.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingSingleAddressHttpClientBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Motivation:
The types in the client builders are too restrictive and prevent us from using
them with custom ServiceDiscoverers with custom ServiceDiscovererEvent
implementations.
Changes:
Open up the types so we can use these APIs with a larger selection of custom
ServiceDiscoverers. This change is not breaking.
> Expand allowed types to accommodate custom service discoverer events

- servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyCompressionSerializer.java
- servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyCompressionStreamingSerializer.java
- servicetalk-encoding-netty/src/test/java/io/servicetalk/encoding/netty/NettyCompressionStreamingSerializerTest.java
Motivation:
NettyCompression's gzip streaming decompression fails to decompress
payloads when split over multiple buffers and may result in:
```
DecompressionException: Input is not in the GZIP format
```
Modifications:
- NettyCompressionStreamingSerializer skips bytes unconditionally after
they are feed to the Netty decoders. However in some scenarios not all
bytes maybe consumed, and if we skip the bytes the aggregation maintained
by Netty's ByteToMessageDecoder will be discarded. Instead of skipping
unconditionally we should only advance the reader index if the ByteBuf
and Buffer don't already match.
> NettyCompression gzip streaming decompression over multiple buffers fix

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientsCompileTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientsCompileTest.java
Motivation:
We recently expanded the allowed types for the Netty client factories and in
order to prevent a regression we should make sure they are used in a test and
fail the build if the types are narrowed.
Changes:
Create two simple tests that will fail to compile of a regression occurs in the
scope of the allowed types.
> Add regression tests for netty client factories

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleConcatWithPublisherDeferSubscribePropagateCancelTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleConcatWithPublisherPropagateCancelTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleConcatWithPublisherTckTest.java
Motivation:
In some scenarios concat is used where the right hand side has assocated state that is desirable to always trigger (concat payload body to meta data for http response processing). Regular concat will not subscribe if the Single terminates with onError or is cancelled which will prevent terminal event visibility.
> Single#concatPropagateCancel(Publisher) to force cancel propagation

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
Motivation:
LinkedBlockingQueue goes through LockSupport park and unpark methods which can incur relatively expensive context switching if the EventLoop thread has to unpark an application thread. This has been shown to be a bottleneck as throughput increases.
Modifications:
- Use LinkedTransferQueue which does a `Thread.yield()` before parking on the consumer thread. This may use more CPU on the consumer thread but the assumption is there will be many more application threads than EventLoop threads and we want to minimize producer costs.
Results:
LinkedTransferQueue
```
Running 30s test @ http://localhost:8080/medium, using 'ServiceTalkGrpcBlockingClientStrAgg' client
1024 threads and 1024 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency       -          -       - …
```
> PublisherAsBlockingIterable LinkedBlockingQueue -> LinkedTransferQueue

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
Motivation:
Application of user supplied filters before those added by default can cause
situations where the client will deadlock when it is unable to resolve a service
address.
Results:
Delay the application of user supplied filters to after default filters in the
gRPC client builder.
> Apply user supplied gRPC filters after default filters

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
`RetryingHttpRequesterFilter` has `responseMapper` feature that helps users to translate some responses into `HttpResponseException`. However, it doesn't drain the response payload body, which will cause connection leaks.
Modifications:
- Drain response payload body before returning `HttpResponseException`;
- Improve tests to verify connections do not leak;
- Use `assertThrows` instead of `fail` in tests;
Result:
Connections do not leak when `responseMapper` feature is used.
> `RetryingHttpRequesterFilter`: drain response before mapping to exception

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java
- servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/NettyBuffer.java
- servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/NettyBufferTest.java
Motivation:
Javadoc for `Buffer.writeBytes` and `Buffer.setBytes` says it reads "length bytes have been read, the end of stream is reached, or an exception is thrown". However, its internal implementation in Netty does only a single `InputStream.read(byte[], int, int)` invocation. `InputStream` contract does not guarantee to read the whole requested `length`, is says "reads up to len bytes of data from the input stream". There are implementations that may return less than `len` bytes on a single read attempt.
Modifications:
- `NettyBuffer` keeps reading from the `InputStream` until length bytes have been read;
- Add tests to demonstrate a problem;
- Also add tests for `writeBytesUntilEndStream` bcz it's a custom method that does not exist in Netty;
Result:
`Buffer.writeBytes` and …
> `Buffer.[set|write]Bytes` doesn't respect length when reading from `InputStream`

- .github/workflows/ci-netty-snapshot.yml
- servicetalk-dns-discovery-netty/build.gradle
- servicetalk-tcp-netty-internal/build.gradle
- servicetalk-transport-netty-internal/build.gradle
Motivation:
To catch any issues with newer Netty releases, run a scheduled job to test ServiceTalk with the latest netty 4.1.X-SNAPSHOT.
Modifications:
- Adjust `build.gradle` files to exclude macos-specific artifacts when we build with a netty snapshot;
- Add CI job to run with Netty 4.1.+;
Result:
Regular tests with the latest Netty snapshot.
> Run scheduled tests with Netty 4.1.X-SNAPSHOT

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractWriteTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertClientHandlingTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java
Motivation:
1. Protocol can signal when the effective write of the message is complete and no more items are expected. In this case, `WriteStreamSubscriber` will do `request(MAX_VALUE)` to drain the remaining (likely empty) items from the publisher and terminate subscriber. However, premature termination of the completable subscriber breaks Reactive Streams control flow. Users of
`connection.write(publisher)` can compose more operators on the returned `Completable` and they expect that the `Completable` terminates only after the passed `publisher` terminates too. The `publisher` can have more business logic after it emits all items. For example, service can read request payload body after it returns the full response.
2. If it waits for continuation but protocol signals it's not …
> `WriteStreamSubscriber`: respect termination of the publisher

- gradle.properties
- servicetalk-dependencies/build.gradle
Motivation:
It's a good practice to use boms when possible to let users manage dependencies easier. Even if we depend only on a single dependency from jackson scope, it has other transitive jackson dependencies in it.
> Use `jackson-bom` instead of `jackson-databind`

- servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/NettyBuffer.java
- servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/NettyBufferTest.java
Motivation:
#2389 introduced a bug for `Buffer.[set|write]Bytes` methods that returns `0` instead of `-1` after EOF.
Modifications:
- Make sure we preserve `-1` signal if nothing else was read from the `InputStream`;
Result:
`Buffer.[set|write]Bytes` correctly return `-1` after EOF.
> `Buffer.[set|write]Bytes` doesn't return `-1` after EOF

- gradle.properties
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13
> Update Jackson 2.13.4.20221012 -> 2.13.4.20221013

- servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java
Motivation:
We have assertions that expect no terminal signals. When they fail, hamcrest prints a lambda name that is hard to understand.
Modifications:
- Implement `toString()` for the returned `Supplier` from `TestPublisherSubscriber#pollTerminal(...)`;
Result:
Easier to understand what was the terminal signal when assertion fails.
> Implement `toString()` for `TestPublisherSubscriber#pollTerminal(...)`

- .github/workflows/ci-prb-reports.yml
- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq-reports.yml
- .github/workflows/ci-prq.yml
- .github/workflows/ci-release.yml
- .github/workflows/ci-snapshot.yml
- README.adoc
Motivation:
JDK 1.11-0.17.8 javadoc fails due to package-info.java not linking
annotation from class path.
> Pin CI builds to use JDK 11.0.16+8

- servicetalk-buffer-api/build.gradle
- servicetalk-buffer-api/src/testFixtures/java/io/servicetalk/buffer/api/Matchers.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
HTTP/2 has special rules that TE header is only allowed to have a value of `trailers`. The sanitizing of the TE headers may have infinite looped in some scenarios.
> H2 TE header parsing bug fix

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
Motivation:
H2 doesn't support the connection header, and must remove all headers that are referenced in the value of the conneciton header. In the event the connection header contains a CSV we should support OWS.
> H2 conversion support OWS for connection header csv

- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
- servicetalk-http-api/build.gradle
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpCookiePair.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesRfc6265Test.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/LegacyCookieParsingTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
https://github.com/netty/netty/pull/12833 adds additional 3 commits to fix problems with missing space after semicolon and adds more tests.
Modifications:
- Port changes made in the last 3 commits of Netty PR;
- Remove unused internal methods;
- Consistently throw `cookie is not allowed to end with ;` from anywhere we parse cookies;
- Include `DefaultHttpSetCookiesTest` and `LegacyCookieParsingTest` for `testProps`;
- Apply all settings we have to `test` task to `testProps` too: timeout, logging, args, etc;
Result:
Correct parsing of cookies without SP after a semicolon.
> `HeaderUtils`: fix problems with missing space after semicolon

- gradle.properties
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeadersFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentChannelInitializer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthAndTrailersTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExpectContinueTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
Netty 4.1.84 includes https://github.com/netty/netty/pull/12760 which moves validation of connection-related headers for HTTP/2 from `HpackDecoder` to `DefaultHttp2Headers`. This breaks our existing control flow because in case there is no `content-length` header, we always unconditionally add `transfer-encoding: chunked` header that will be removed later in HTTP/2 pipeline if the HTTP/2 is the actual negotiated protocol.
Modification:
- Improve our control flow to take protocol into account when it adds `transfer-encoding: chunked` header;
- Adjust existing tests that target `transfer-encoding: chunked` handling to always use `DefaultHttpHeadersFactory`, even  when testing HTTP/2, it helps to avoid validation in netty's `DefaultHttp2Headers`;
Result:
All tests pass with both …
> Prepare for upgrade to Netty 4.1.84

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/IdleTimeoutConnectionFilterTest.java
Motivation:
`BeforeFinallyHttpOperator` has a single `state` inside `ResponseCompletionSubscriber` that is shared between `Single` and `Publisher` of the message body. If users re-subscribe to the message body, the state is already in `TERMINATED` position and does not propagate signals.
Modifications:
- Move message body processing logic into a new `MessageBodySubscriber` class;
- Each subscribe operation creates a new `MessageBodySubscriber` and their states are managed independently;
- Improve `IdleTimeoutConnectionFilterTest` to always create a new response object (otherwise, the response payload body can be transformed multiple times);
Result:
Users of `BeforeFinallyOperator` always see all terminal events, even for re-subscribe. Terminal signal will always be delivered to the second …
> `BeforeFinallyHttpOperator`: support re-subscribe to the message body

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeadersFactory.java
Motivation:
Forgot to add javadoc when this method was added in #2392.
> Add missing javadoc for `HttpHeadersFactory#validateNames()`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleConcatWithPublisherTckTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
Motivation:
Boolean arguments for operators are harder to read, especially when number of possible boolean args is growing.
Modifications:
- Introduce `Single.concatDeferSubscribe(Publisher)` that behaves like `Single.concat(Publisher, true)`;
- Deprecate `Single.concat(Publisher, boolean)`;
Result:
Clear behavior based on operator name, consistency with `concatPropagateCancel`.
> `Single.concatDeferSubscribe(Publisher)` instead of `Single.concat(Publisher, boolean)`

- servicetalk-opentelemetry-asynccontext/src/main/java/io/servicetalk/opentelemetry/asynccontext/ServiceTalkContextStoreProvider.java
Motivation:
`ServiceTalkContextStorage`, similar to the original `ThreadLocalContextStorage` logs when the `Scope` was not closed correctly. However, it allocates a new exception to capture the stacktrace on every log level.
Modifications:
- Allocate exception only when `debug` logging level is enabled;
Result:
Less overhead when logging is disabled.
> OpenTelemetry scope: log stacktrace only when debug mode is enabled

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExpectContinueTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SplittingFlushStrategy.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
This reverts commit a0e6540ffe77eac504e3a73181c5f428e98c2c63.
We will reapply this change after release.
> Revert "Make HTTP/1.x server-side control flow consistent with the client-side (#2367)"

- servicetalk-concurrent-api-internal/src/main/java/io/servicetalk/concurrent/api/internal/BlockingUtils.java
- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/BlockingUtilsTest.java
Motivation:
Users of blocking API do not expect `ExecutionException`, like users of `Future.get()`. However, `ExecutionException` plays an important role to capture the caller's stacktrace, which helps to understand which path made a blocking call. Currently, we unwrap `ExecutionException` and lose this information.
Modifications:
- Instead of dropping the `ExecutionException` wrapper, move it as a suppressed exception for the original one;
- Test new behavior;
Result:
Users can understand what path requested blocking invocation when an async operation fails with an exception.
> Preserve the caller's stacktrace for blocking API

- servicetalk-grpc-api/build.gradle
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DelegatingGrpcClientBuilder.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DelegatingGrpcServerBuilder.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExceptionMapperServiceFilter.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcFilters.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatusException.java
- servicetalk-grpc-netty/build.gradle
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverRequesterFilter.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcTimeoutOrderTest.java
Motivation:
The default insertion order for gRPC deadline filter is after user filters. If a user's filter deadlocks the timeout will never be applied.
Some use cases may necessitate applying the deadline timeout filter in a custom order (e.g. relative to retries). There is currently no way to customize the append ordering.
Modifications:
- Move the gRPC server deadline filter to the beginning of the filter chain so timeouts are applied regardless if user filter code hangs.
- Add appendTimeoutFilter method to gRPC client and server builder to give users control over filter append ordering.
- Introduce GrpcFilters utility class to create the filters that apply deadline propagation.
> Move gRPC server deadline filter, allow custom insertion order

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
DefaultDnsClient takes the List from the Netty's DNS client and sorts it. This may result in a ConcurrentModificationException if the underlying cache modifies this list.
Modifications:
- Make a copy of the List we get back from Netty before we sort the collection and retain a reference.
> DefaultDnsClient ConcurrentModificationException

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultExecutor.java
Motivation:
By default the JDK's ScheduledExecutorService does not remove timer objects from its queues upon cancel. Cancellation is expected to be common when requests have timeouts applied, and therefore the object retention lifetime will be longer than required and may negatively impact GC performance.
> ScheduledExecutorService to remove timeout objects on cancel

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExpectContinueTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SplittingFlushStrategy.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
Motivation:
#2367 changed server-side control flow. After that, `connection.write` doesn't start before we received a request meta-data. As the result, all errors that happen during parsing of the meta-data do not reach `WriteStreamSubscriber` and can leave a connection in undefined state, when we logged an error but didn't clean up the channel state.
Modifications:
- Close the channel if an error occurs on the `Single` of request meta-data;
- Add tests to verify the expected behavior;
Result:
Channel is closed when an early request error happens, client doesn't hang forever.
> Server control flow should close connection on `DecoderException`

- servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
- servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
- servicetalk-examples/grpc/request-response-context/README.adoc
- servicetalk-examples/grpc/request-response-context/build.gradle
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/HttpContextFilters.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/async/RequestResponseContextClient.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/async/RequestResponseContextServer.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/async/package-info.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/blocking/BlockingRequestResponseContextClient.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/blocking/BlockingRequestResponseContextServer.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/blocking/package-info.java
- servicetalk-examples/grpc/request-response-context/src/main/java/io/servicetalk/examples/grpc/context/package-info.java
- servicetalk-examples/grpc/request-response-context/src/main/proto/greeter.proto
- servicetalk-examples/grpc/request-response-context/src/main/resources/log4j2.xml
- settings.gradle
Motivation:
Demonstrate how users can use gRPC request/response context to access HTTP headers.
Modifications:
- Add `servicetalk-examples-grpc-request-response-context` module;
Result:
Users can see how to use gRPC request/response context.
> Add gRPC Request Response Context Example

- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/FlowControlUtils.java
- servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/FlowControlUtilsTests.java
Motivation:
FlowControlUtils.addWithUnderOverflowProtection exists for long types but not int types.
> Add FlowControlUtils.addWithUnderOverflowProtection for int

- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ProjectUtils.groovy
- servicetalk-grpc-health/build.gradle
- servicetalk-grpc-netty/build.gradle
- servicetalk-grpc-protoc/build.gradle
Motivation:
The protobuf gradle plugin will generate tasks dynamically, which have implicit relationships on our dynamically generated quality tasks (pmd, spotbugs, checkstyle). Gradle build generates warnings and deoptimizes some flows.
```
Execution optimizations have been disabled for task ':servicetalk-grpc-health:pmdMain' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/Users/scottmitchell/git/servicetalk/servicetalk-grpc-health/src/generated'. Reason: Task ':servicetalk-grpc-health:pmdMain' uses this output of task ':servicetalk-grpc-health:generateTestProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer …
```
> Avoid implicit task dependencies for grpc generated tasks

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionTest.java
Motivation:
H2PriorKnowledgeFeatureParityTest.serverGracefulClose installs a ConnectionAcceptor which intercepts messages through the netty pipeline. However the filter is offloaded by default and may miss events.
Modifications:
- Override `requiredOffloads` when creating the `ConnectionAcceptorFactory` to disable offloading.
Fixes:
https://github.com/apple/servicetalk/issues/2378
> H2PriorKnowledgeFeatureParityTest.serverGracefulClose ConnectionAcceptor disable offloading

- .github/workflows/codeql-analysis.yml
Motivation:
CodeQL job started to fail with javadoc bug:
https://github.com/apple/servicetalk/actions/runs/3567715145/jobs/5995737033
Looks like they updated JDK11 version.
Modifications:
- Force CodeQL task to use a specific JDK11 version;
Result:
CodeQL task continues to work.
> Pin specific JDK11 version to avoid javadoc bug

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java
Motivation:
Intermediate allocations from PublishAndSubscribeOn* are in the top 10 on jfr reports from perf bencmarks.
Modifications:
- Remove intermediate allocations for safe invocation of handleSubscribe. The parent method is internal and which calls a final method which handles exceptions.
> Reduce allocation in PublishAndSubscribeOn*

- servicetalk-concurrent-api/docs/modules/ROOT/pages/blocking-safe-by-default.adoc
The publishOn, subscribeOn and the detailed example were all duplicated, only with small differences. This changeset cleans it up but preserves the information.
> Remove duplicate doc sections from "Blocking: Safe by default"

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
RetryingHttpRequesterFilter retries on two scenarios:
1. load balancer not ready (due to no available addresses to connect to from ServiceDiscoverer)
2. request was issued but failed
The overall retry strategy applies the same count for both the above scenarios to the retry strategy that only deals with (2). This means less than desired amount of actual requests will be sent if one of the failures is due to (1).
Modifications:
- Add OuterRetryStrategy to RetryingHttpRequesterFilter that tracks how many load balancer not ready events cause a retry, and subtract this amount before applying to the request retry strategy from (2).
Result:
Fixes https://github.com/apple/servicetalk/issues/2405
> RetryingHttpRequesterFilter subtract LB not ready from request retry strategy

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLifecycleObserverHttpFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/LoggingCloseHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NonPipelinedCloseHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
Motivation:
HttpLifecycleObserverTest#testClientCancelsRequestAfterResponse tests half close
behavior but is subject to the OS's TCP implementation sending a RST before
the test writes, and therefore the write returning an error. However some
scenarios the client would just send a FIN and the server write would succeed.
Modifications:
- Server should wait to write until it has recieved the RST
- CloseHandler should force a RST before full close is done. This can
be achieved by setting SO_LINGER to 0.
Result:
Fixes `HttpLifecycleObserverTest#testClientCancelsRequestAfterResponse(HttpProtocol) [1] protocol=HTTP_1`
prevents hangs when read is complete and write is still open.
> CloseHandler force RST on close if still reading to avoid half close hang

- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
- servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/alpn/HttpClientWithAlpn.java
- servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/alpn/HttpServerWithAlpn.java
- servicetalk-examples/http/mutual-tls/src/main/java/io/servicetalk/examples/http/mutualtls/HttpClientMutualTLS.java
- servicetalk-examples/http/mutual-tls/src/main/java/io/servicetalk/examples/http/mutualtls/HttpServerMutualTLS.java
- servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/RedirectingServer.java
Motivation:
`DefaultTestCerts` contains self-signed certificates that we use only to demonstrate SSL configuration API.
Modifications:
- Add a note in all examples to notify users they should not copy paste this certificates in their projects;
Result:
Users have a warning about DefaultTestCerts.
> Add warning in example that DefaultTestCerts should not be used

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/loadbalancer/RoundRobinLoadBalancerSDEventsBenchmark.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingFilterableStreamingHttpConnection.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingFilterableStreamingHttpLoadBalancedConnection.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CacheConnectionHttpLoadBalanceFactoryTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/CacheConnectionFactory.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/CacheConnectionHttpLoadBalanceFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
When traffic spikes occur ServiceTalk will create as many
new connections as concurrent requests cannot be satisfied
with existing connections. This is common at startup and
results in more connections than necessary for protocols that
support multiple requests in parallel on the same connection
(http/1.x pipelining, h2 multiplexing).
Modifications:
- Add CacheConnectionHttpLoadBalanceFactory which wraps a
HttpLoadBalancerFactory and will cache connection creation attempts
according to max concurrent requests supported by the connection.
- LoadBalancerFactory#newLoadBalancer is deprecated in favor of a
variant that doesn't have generic override on the method. This makes
it possible for the LoadBalancer implementation to more easily wrap
the connection and augment behavior if …
> Add CacheConnectionHttpLoadBalanceFactory

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferHolder.java
- servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
- servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BufferHandler.java
Motivation:
Both the BufferHandler and the BufferHolder did see very limited use and are scheduled for removal in the next minor release.
Modifications:
To preserve backwards compatibility and to notify potential users, both APIs are marked as deprecated now in preparation for removal.
> Deprecate BufferHandler and BufferHolder

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferInputStream.java
- servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/BufferInputStreamTest.java
Motivation:
BufferInputStream can support the mark/reset functionality, as noted in #1562, like ByteArrayInputStream and ByteBufInputStream (from netty).
Modifications:
- Implemented the mark, reset and markSupported methods of BufferInputStream
- Added test cases
Result:
Resolves #1562.
> Add mark/reset functionality to `BufferInputStream`

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CacheConnectionHttpLoadBalanceFactoryTest.java
Motivation:
CacheConnectionHttpLoadBalanceFactoryTest may fail by creating one more connection than the test currently allows.
Modifications:
- allow 1 more connection than currently is allowed.
> CacheConnectionHttpLoadBalanceFactoryTest allow more tolerance

- servicetalk-loadbalancer/build.gradle
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
RoundRobinLoadBalancer clears state of all hosts and each host clears all connections when closing. However a common pattern is to initiate gracefulClosure with a timeout, and then force a full close after a timeout interval. In this scenario RRLB has discarded the reference to connections and will not full close the connections.
Modifications:
- asyncCloseable needs to keep state about what hosts are being closed and each host can't dereference connections until they are fully closed.
- switch back to using onClose to cleanup the connection list as otherwise we may leak connections that have started graceful closure and never finished.
> RoundRobinLoadBalancer fix connection leak during graceful closure

- servicetalk-benchmarks/build.gradle
- servicetalk-benchmarks/src/jmh/java/io/servicetalk/data/jackson/JacksonStreamingSerializerBenchmark.java
- servicetalk-data-jackson/build.gradle
- servicetalk-data-jackson/src/main/java/io/servicetalk/data/jackson/JacksonStreamingSerializer.java
- servicetalk-data-jackson/src/test/java/io/servicetalk/data/jackson/JacksonSerializerFactoryTest.java
Motivation:
In 2.14.0, Jackson added support for feeding ByteBuffers directly
into the streaming parser engine (where previously only byte arrays
would be supported). This changeset adds a benchmark and provides
rationale why the decision has been made to stick with the current
code.
Modifications:
The benchmark numbers show that there is no substantial benefit
in either completely switching over to the ByteBufferFeeder or
decide which one to use when the first buffer arrives. In some
scenarios it is even slower.
As a drive-by fix, the feeder is now properly closed when the
operator terminates successfully or because of an error.
> Clarify semantics around Jackson's ByteBufferFeeder

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcInputValidationTest.java
- servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
Motivation:
At the moment the generated GRPC code does not perform input validation in all necessary methods and might pass invalid/null inputs down into the GRPC layer where it is harder to track down what went wrong in the first place.
Modifications:
This changeset adds explicit requireNonNull to all generated methods which accept user input and adds a test case to verify that the requireNonNull is performed at the earliest point in time and not deeper in the call stack.
Result:
Early argument null checks to improve debugability in case of invalid argument values.
> Add null checks to generated GRPC API

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionLimitReachedException.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LimitingConnectionFactoryFilter.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
`ConnectionLimitReachedException` should implement a `RetryableException` contract and should not mark the remote host unhealthy bcz it's a local limit that does not affect the host's actual healthiness. Hosts are not marked as "unhealthy" if there are open connections to them, but there is currently a risk to changes host's state to "unhealthy" from the cold start, if we wait for allowed connections to open.
Modifications:
- Enhance `markUnhealthy` logic inside `RoundRobinLoadBalancer` to ignore `ConnectionLimitReachedException` for counting towards the threshold;
- Test that `ConnectionLimitReachedException` doesn't move a host to "unhealthy" state;
- Add `RetryableException` marker for `ConnectionLimitReachedException`;
- Clarify `LimitingConnectionFactoryFilter`'s javadoc …
> `ConnectionLimitReachedException` should not trigger RRLB health-checking

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConsumableEvent.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/LatestValueSubscriber.java
- servicetalk-context-api/build.gradle
- servicetalk-context-api/src/main/java/io/servicetalk/context/api/ContextMap.java
- servicetalk-context-api/src/test/java/io/servicetalk/context/api/ContextMapTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpEventKey.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpEventKeyTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentChannelInitializer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttp2ExceptionUtils.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpConnectionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllersTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
Motivation:
A remote server can change `MAX_CONCURRENT_STREAMS` setting as part of establishing an HTTP/2 connection or at any time later. When this happens, there is a possibility that a request will fail with an exception caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint: 100
This happens in both cases: when the value increases or decreases bcz we need to coordinate between a state inside `ReservableRequestConcurrencyControllers` and inside Netty's http2-codec. Update of these states races with incoming requests when offloading is enabled.
Modifications:
- Enhance `H2ConcurrencyControllerTest` with reproducers for described scenarios;
- Refactor `ReservableRequestConcurrencyControllers` to handle events differently …
> Possible race when `MAX_CONCURRENT_STREAMS` setting changes in HTTP/2

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
#2458 changed `disableAutoRetries()` to still wait for the LB for the first time. As the result, the test can select a connection up to 2 times.
Modifications:
- Change the matcher to `lessThanOrEqualTo(2)`;
Result:
`RetryingHttpRequesterFilterTest.disableAutoRetry()` is not flaky.
> Fix `RetryingHttpRequesterFilterTest.disableAutoRetry()`

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyConnectionContext.java
Motivation:
#2430 moved `onClosing()` method from internal `NettyConnectionContext` to public `ListenableAsyncCloseable` interface. While moving a method upward in the class hierarchy should be a binary compatible change, let's preserve it for 0.42.x for extra cautious.
> Revert `NettyConnectionContext.onClosing()` back

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingHttpService.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpService.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpService.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServiceBase.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Service.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpService.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServiceTest.java
**Motivation**
Right now four different Service API variants are provided, all
with their async and sync listen* overloads. If the service
type is known at compile time those overloads suffice, but in
situations where the type is only determined at runtime (for
example when DI is used) the user needs to write verbose code
that can be provided by ServiceTalk and improve the developer
experience.
**Modifications**
This changeset introduces a new "Service" interface in the
http package and it now acts as a parent for the four different
service implementations. The HttpServerBuilder gets two more
overloads (blocking and non-blocking) to accept the Service
type and then internally performs the runtime type checking
and delegates to the appropriate methods.
> Provide common HTTP Service interface for all API variants.

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
Motivation:
At the moment building a GRPC route is performed right when the application registers a new one at the high level API.
Since every route needs an execution strategy when being built, the execution strategy needs to be provided at construction time of the ServiceFactory/Builder. In order to improve the user experience and to make the execution strategy an optional builder method the building of the routes needs to be moved to a later point in the build stage.
Modifications:
This changeset, in preparation to making the execution strategy optional in a later commit, makes the route building lazy by moving it inside a closure which is executed at "bind" time instead of being evaluated immediately.
To preserve the current semantics (especially that an error is thrown if two routes …
> Perform GRPC route building lazily on bind

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractServiceAdapterHolder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingToStreamingServiceTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionContextToStringTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RequestResponseContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SupportedBufferAllocatorsTest.java
- servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilder.java
Motivation:
The ServiceAdapterHolder is not needed anymore conceptually since the Service now carries its offloading properties (HttpExecutionStrategy) as part of the class itself.
Modifications:
This changeset is the first step to remove the ServiceAdapterHolder by removing it from the DefaultHttpServerBuilder. The HttpExecutionStrategy is still computed but instead of going through the ServiceAdapterHolder indirection the codepath now consistently uses the StreamingHttpService codepath.
Result:
Simplified DefaultHttpServerBuilder as well as removing most of the current ServiceAdapterHolder usage (there is still some left which can be cleaned up in follow-up changesets).
> Remove ServiceAdapterHolder from DefaultHttpServerBuilder

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
Motivation:
`SpecialHttpExecutionStrategy` impls miss override for `isRequestResponseOffloaded()` flag. While it still computes the same result, it's better to be explicit for these implementations.
> `SpecialHttpExecutionStrategy` should implement all interface methods

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
This reverts commit 1c463da9974575711b032d57988c62724facb395 (https://github.com/apple/servicetalk/pull/2386).
We didn't observe visible improvements for `ServiceTalkGrpcBlockingClientStrAgg`, but saw negative impact on HTTP/1.1 blocking-streaming cases:
1. On the client-side for `GET` : -10k RPS, +5-10ms p99
2. On the server-side for `POST` : -10k RPS, +5ms p99
> Revert "PublisherAsBlockingIterable LinkedBlockingQueue -> LinkedTransferQueue (#2386)"

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ExecutionContextUtils.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherRefCountTest.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
Motivation:
#2430 adds `ListenableAsyncCloseable.onClosing()` method. Its implementations require allocation of a `CompletableProcessor`.
Because we wrap channel's `EventLoop` with `IoExecutor` on every new connection and every new HTTP/2 stream, it caused significant increase of allocations and pressure for GC. As the result, latency increased for all HTTP/2 and gRPC use-cases.
Modifications:
- Add `ExecutionContextUtils` that adapt `EventLoop` to `IoExecutor` API for `ExecutionContext` and cache its value in `FastThreadLocal` to reduce allocations;
- Make sure that HTTP/1.x and parent HTTP/2 connections use `ExecutionContextUtils`;
- For each new HTTP/2 stream (child channel) take execution context from the parent channel because child channel uses the same `EventLoop` as its parent …
> Fix increased latency for gRPC after adding `ListenableAsyncCloseable.onClosing()`

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/ClientTransportGrpcCallFactory.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/CustomTransportTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/InMemoryServerTransport.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/AbstractNettyIoExecutor.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/EventLoopGroupIoExecutor.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/EventLoopIoExecutor.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/GlobalExecutionContextTest.java
Motivation:
`io.servicetalk.transport.netty.internal.NettyIoExecutors` has a few public methods that are not necessary and can be removed in the future releases. All these methods already have alternative ways to achieve the same.
Modifications:
- Deprecate `NettyIoExecutors.toNettyIoExecutor(IoExecutor)`;
- Deprecate `NettyIoExecutors.fromNettyEventLoop(EventLoop)`;
- Deprecate `NettyIoExecutors.fromNettyEventLoopGroup(EventLoopGroup)`;
- Adjust tests to avoid using deprecated API;
Result:
Less publicly exposed internal methods.
> Deprecate unnecessary internal methods of `NettyIoExecutors`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
It's not obvious for users that `BackOffPolicy.ofImmediate()` retries only 3 times.
Modifications:
- Deprecated `BackOffPolicy.ofImmediate()`;
- Introduce `BackOffPolicy.ofImmediateBounded()` that behaves the same way;
- Cache the returning value for `BackOffPolicy.ofImmediateBounded()`;
Result:
Easier for users to understand that immediate `BackOffPolicy` has a limit for number of retries.
> `RetryingHttpRequesterFilter`: rename `ofImmediate` to `ofImmediateBounded`

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategy.java
Motivation:
To ensure partiy with HttpExecutionStrategies it makes sense to introduce "offloadNone" as a static utility method instead of only making it accessible through a builder.
Modifications:
This changeset adds the static "offloadNone" utility method in GrpcExecutionStrategies and clarifies the javadoc of "offloadNever" (which is deprecated) on alternative usage.
Result:
Feature parity between GRPC and HTTP on the "offloadNone" execution strategy creation.
> Introduce GrpcExecutionStrategies#offloadNone

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilterTest.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpServiceFilterTest.java
Motivation:
Currently, timeout and retrying filter uses an `HttpExecutionStrategy` from the `ExecutionContext`. However, on the requester side users can either use a different API that optimizes the pre-computed strategy or they can put a custom strategy per request.
Modifications:
- For `RetryingHttpRequesterFilter`, compute `alternativeTimerExecutor` based on `HTTP_EXECUTION_STRATEGY_KEY`;
- For `TimeoutHttpRequesterFilter`, compute `useForTimeout` based on `HTTP_EXECUTION_STRATEGY_KEY`;
- Adjust tests for new behavior;
Result:
1. On the client-side, the actual `HttpExecutionStrategy` associated with the request is considered.
2. Less use of offloading executor when there is no need to offload.
> Consider request strategy when we schedule timeouts or retries

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingHttpClient.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpClient.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClient.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpContextKeys.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClient.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReserveConnectionTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
When a connection is being reserved on one of the HttpClient variants, at the moment the user has no control over the decision if an existing connection should be reused or a new one will be opened.
Use cases have been reported where being able to explicitly reserve a new connection instead of reusing one would be benefitial.
Modifications:
This changeset adds support for this feature by introducing two new APIs at different levels:
- At the HttpClient level a HTTP_FORCE_NEW_CONNECTION context key has been added which signals the intention at the reserveConnection level by the user.
- The LoadBalancer now features a newConnection method which by default throws an UnsupportedOperationException for backwards compatibility.
The RoundRobinLoadBalancer implements the newConnection …
> Allow to open a new connection when reserving (HTTP).

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
#2473 added a new overload for `initChannel`, but forgot to deprecate the previous one and update javadoc to point to the latest overload we use.
> Deprecate unused `DefaultNettyConnection#initChannel(...)` overload

- gradle.properties
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent.java
Modifications:
- `io.servicetalk.internal.queues.useUnpadded` value defaults to "false" to use unpadded queues by default. This property will be removed in future releases, but exists in case there are any regressions detected.
> Update jctools 3.3.1-ea -> 4.0.1

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/EarlyAndLateConnectionAcceptorTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java
Motivation:
AUTO_READ should be disabled by default to prevent reading any data before the decision to accept the connection is made and to allow managing back-pressure after that. Protocols that require AUTO_READ have to enable it at their handler (i.e. H2).
Modifications:
This changeset removes the autoRead option from the bind method of the TcpServerBinder and always sets it to false.
The code also re-enables the previously failing test in EarlyAndLateConnectionAcceptorTest.
> Always disable AUTO_READ for TcpServerBinder

- .github/workflows/ci-release.yml
Motivation:
To allow us releasing versions like a.b.c and a.b.c.d, we need to improve the regex to account for the optional 4th section.
Modifications:
- Update ci-release.yml
Result:
Release job will be triggered for both a.b.c and a.b.c.d versions.
> Update release tag regex to allow optional 4th version section

- .github/workflows/ci-release.yml
- .github/workflows/ci-snapshot.yml
Motivation:
GitHub Actions pattern matching does not support full regex features: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Modifications:
- Split one regex into 2 different patterns;
- Do the same for ci-snapshot.yml to ignore these releases;
Result:
Release pipeline should be triggered for a.b.c and a.b.c.d releases.
> Split release tag regex into 2 separate patterns

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Problem/Solution/Result
The DNS client can attempt to complete its result promise even after the Promise
itself has been cancelled upstream, ie the subscriber is no longer interested in
the DNS query results; this will result in an unhandled exception in what should
be a normal use case. We should instead replace calls to setSuccess with
trySuccess on the DNS Promise to guard against this situation.
> Guard against trying to complete a cancelled Future

- .github/workflows/ci-prq.yml
- scripts/check-source-root.sh
- scripts/check_source_root.sh
- servicetalk-examples/grpc/observer/README.adoc
- servicetalk-examples/grpc/protoc-options/README.adoc
- servicetalk-grpc-protoc/README.adoc
Motivation:
Some of the documentations .adoc files are missing a definition for
source-root but use them in hyperlinks. This results in broken links.
This happens easily because each file that references source-root
needs the definition.
Modifications:
Add a script to check all the .adoc files for missing source-root
definitions. We also run the script with the -r flag to fix up the broken
files. To avoid regressions, the script is run as part of the Github
PR Quality workflow.
Result:
Files are fixed and it's easier to check this in the future.
> Fix some broken {source-root} references in documentation

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ConnectionContextToStringTest.java
Motivation:
`GrpcServiceContext` gives users access to a connection/stream. `DefaultGrpcServiceContext` doesn't implement `toString()`. As the result, users can not see the connection id from netty.
Modifications:
- Implement `DefaultGrpcServiceContext.toString()`;
- Add `ConnectionContextToStringTest` to make sure we never regress;
Result:
Users can see netty channel id via `GrpcServiceContext`, similar to `HttpServiceContext`.
> `GrpcServiceContext` should provide access to netty channel id

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslCertificateCompressionTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CertificateCompressionAlgorithm.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CertificateCompressionAlgorithms.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CertificateCompressionException.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SslConfig.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ZlibOpenSslCertificateCompressionAlgorithm.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/ZlibOpenSslCertificateCompressionAlgorithmTest.java
Motivation:
RFC 8879 defines a TLS extension called "TLS Certificate Compression" which allows to compress certificates and possibly reduce the amount of data exchanged during a TLS handshake.
Since netty already added support for it when used together with BoringSSL (netty-tcnative), ServiceTalk can benefit from a higher-level integration.
Modifications:
This changeset implements ServiceTalk API for Certificate Compression and hooks it up with the Netty APIs internally.
The main entry point for the user is through the SslConfigBuilder where they can set the supported algorithms (for now only ZLIB) for both client and server use cases. We also support both the compression and decompression depending on the use case.
At the moment it is not possible to define custom algorithms, although …
> Implement TLS Certificate Compression Support

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcFilters.java
Motivation:
`GrpcDeadlineServerFilter` defines a function that fallbacks to `defaultTimeout`. Because we use lambda, the `defaultTimeout` is not visible during heap dump investigation.
Modifications:
- Use a static inner class `GrpcDetermineTimeoutForRequestFunction` to capture the state;
Result:
`defaultTimeout` value can be found in heap dump.
> GrpcDeadlineServerFilter: use inner class to capture external state

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsTestUtils.java
- servicetalk-test-resources/build.gradle
Motivation:
#2500 showed that `DefaultDnsClientTest` can be flaky. Because these tests rely on real time, they intentionally use larger TTL to make sure all updates are set before the next resolution. However, CI can be too slow and even 1 second delay may not be enough. Some tests deadlock. Also, there are too many unnecessary parametrized tests and all tests take more than 3 minutes.
Modifications:
- Create `NettyIoExecutorWithTestTimer` that delegates to `EventLoopAwareNettyIoExecutor` but uses `TestExecutor` as a time source and to schedule follow-up resolutions;
- Manually advance time and clear the cache before each follow-up query;
- Use cursor to select `nextIp6` instead of random selection. If random selects the same IPv6 address, tests fail their expectations;
- Remove …
> Simplify `DefaultDnsClientTest`, avoid depending on real time

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
Motivation:
At the moment it is possible to configure a minTTL for DNS resolution, but maxTTL is not configured (the cache uses Integer.MAX_INT) and the actual maxTTL for resolution is applied to whatever the DNS entry returns from the server.
To provide more customizations as well as being able to explicitly "cap" a TTL at a maximum value, it makes sense to allow setting an explicit maximum TTL.
Modifications:
This changeset introduces a configurable maxTTL option on the DefaultDnsServiceDiscovererBuilder with a sensible default setting. This value then:
- Propagates to netty's DefaultDnsCache as the maximum value
as well as
- Caps the returned TTL from the server to this value and logs a INFO level message if it has been capped (since reaching the MAX is really not expected in a well …
> Implement explicit, customizable DNS maxTTL

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DelegatingDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilderProvider.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscoverers.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilderProviderTest.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserverTest.java
- servicetalk-dns-discovery-netty/src/test/resources/META-INF/services/io.servicetalk.dns.discovery.netty.DnsServiceDiscovererBuilderProvider
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/GlobalDnsServiceDiscoverer.java
Motivation:
Similar to the related functionality in GRPC and HTTP servers, it can be useful to configure the DNS service discoverer also through a ServiceProvider.
Modifications:
This changeset introduces ServiceProvider functionality on top of the DefaultDnsServiceDiscovererBuilder. To do this, a new interface is introduced (to also provide a Delegate implementation) as well as a DnsServiceDiscoverers factory class to construct a builder with an ID.
Note that uniqueness on this ID is not enforced by ServiceTalk, but is something to recommend to the application developer when using this mechanism. The default construct is marked as deprecated and will use a UUID as the ID.
Result:
It is now possible to configure the DNS service discoverer through the ServiceProvider mechanism.
> Implement DnsServiceDiscovererBuilderProvider

- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SequentialCancellable.java
- servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/SequentialCancellableTest.java
Motivation:
After `SequentialCancellable` is cancelled, all subsequent invocations of `nextCancellable` must cancel the `next`.
> `SequentialCancellable`: all `nextCancellable` must be cancelled too

- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/TestCompletableTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/TestPublisherTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/TestSingleTest.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ConcurrentCompletableSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ConcurrentPublisherSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ConcurrentSingleSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/SequentialCompletableSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/SequentialPublisherSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/SequentialSingleSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCompletable.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestPublisher.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSingle.java
Motivation:
When `Sequential*SubscriberFunction` (this is a default mode for all test sources) is used, `cancel()` doesn't reset the current `Subscriber`. Therefore, following re-subscribes fail with "Duplicate subscriber" exception. This happens because `AutoOnSubscribe*SubscriberFunction` is applied before `subscriberCardinalityFunction`. As the result, `onSubscribe` is invoked before `Sequential*SubscriberFunction` wraps the `Subscriber`.
Modifications:
- Always apply `autoOnSubscribeSubscriberFunction` last, after `subscriberCardinalityFunction`;
- Add tests to verify the described scenario;
- Always reset the current `Subscriber` when `Sequential*SubscriberFunction` resets;
- Clarify that `Concurrent*SubscriberFunction` always requires manyual `onSubscribe` management;
- Disable auto …
> Sequential `Subscriber` is not reset after cancel for all test sources

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslCertificateCompressionTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
Motivation:
Netty recently added a getter to SslProvider which allows us to check if certain options are supported or not.
Modifications:
This changeset changes the SslContextFactory to use this new getter and explicitly check for
OpenSslContextOption.CERTIFICATE_COMPRESSION_ALGORITHMS before enabling certificate compression.
Result:
More reliable check if certificate compression is supported or not.
> Use SslProvider.isOptionSupported to determine certificate compression support

- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SequentialCancellable.java
- servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/SequentialCancellableTest.java
Motivation:
In scenarios when `SequentialCancellable` is used to manage global cancellation, there might be cases when we have to re-subscribe. Cancelling the current `Cancellable` will allow us to do this.
Modifications:
- Add `SequentialCancellable#cancelCurrent()` method;
- Test the new feature;
Result:
It's possible to cancel only the current `Cancellable` inside `SequentialCancellable` and then re-subscribe.
> `SequentialCancellable`: add `cancelCurrent()` method

- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilderProviderTest.java
Motivation:
Gradle can run test classes in different order. In case it runs `DnsServiceDiscovererBuilderProviderTest` after any other test, the numbers are off because existing `TestDnsServiceDiscovererBuilderProvider` is applied to any builder.
Modifications:
- Apply `TestDnsServiceDiscovererBuilderProvider` logic only for `DnsServiceDiscovererBuilderProviderTest`;
Result:
Tests pass regardless of the execution order.
> Apply `TestDnsServiceDiscovererBuilderProvider` only for a specific id

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
If a static `SrvAddressRemovedException` is propagated, there is a risk for a memory leak because the processing code can add suppressed exceptions to this static instance.
Modifications:
- Always create a new stackless `SrvAddressRemovedException` instance;
Result:
Memory leak is not possible if some codepath adds a suppressed exception to `SrvAddressRemovedException`.
> Avoid potential memory leak when `SrvAddressRemovedException` is thrown

- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/SequentialPublisherSubscriberFunction.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
- servicetalk-loadbalancer/build.gradle
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NormalizedTimeSourceExecutor.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/NormalizedTimeSourceExecutorTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/DurationUtils.java
- servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/DurationUtilsTest.java
Motivation:
It’s possible for the RRLB to turn into a state when all available
hosts become unhealthy. Possible scenarios:
- DNS returned incorrect results;
- All hosts were restarted and got different addresses.
RRL will be in a dead state until TTL expires, which may take some time.
Modifications:
- When RRLB detects that all hosts are unhealthy, it re-subscribes to the
SD events publisher to trigger a new resolution;
- Add `RoundRobinLoadBalancerFactory.Builder#healthCheckResubscribeInterval`
option to configure the new feature;
- Wrap `backgroundExecutor` with `NormalizedTimeSourceExecutor` to make
sure `currentTime` is always positive;
- Test behavior when the new feature is enabled/disabled;
- Add `DurationUtils.ensureNonNegative(...)` utility for validation;
- Make …
> `RoundRobinLoadBalancer`: re-subscribe when all hosts become unhealthy

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserver.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserverTest.java
Motivation:
To enhance the utility of the DnsServiceDiscovererObserver a couple additional APIs can be provided:
- The newly introduced ServiceDiscoverer ID is brought in scope
- Further lifecycle callbacks are added to the DnsDiscoveryObserver
Modifications:
This changeset adds the two enhancements mentioned in the motivation in a backwards-compatible way. In the next minor released the interface can be cleaned up.
Tests have been enhanced to test the newly added functionality.
Result:
More functionality around the DnsServiceDiscovererObserver.
> Extend DnsServiceDiscovererObserver functionality

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ForResolvedAddressTest.java
Motivation:
`HttpClients.forResolvedAddress(...)` uses a special `ServiceDiscoverer`
that users should not override. Otherwise, behavior will be
unpredictable.
Modifications:
- Use `withUnmodifiableServiceDiscoverer` to protect from overriding the
`ServiceDiscoverer`;
- Add `ForResolvedAddressTest` to validate this behavior;
Result:
Users can not change `ServiceDiscoverer` used by `HttpClients
.forResolvedAddress(...)`. In case they need a custom SD for this use
case, they can use `HttpClients.forSingleAddress(ServiceDiscoverer, U)`.
---
Depends on #2520, review only the latest commit: https://github.com/apple/servicetalk/pull/2524/commits/3713d8dc64cecdda0fb56e6f07d85db71eb41ebc
> Don't allow to override ServiceDiscoverer for resolved address client

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/loadbalancer/RoundRobinLoadBalancerSDEventsBenchmark.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CacheConnectionHttpLoadBalanceFactoryTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DelegatingRoundRobinLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderProvider.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancers.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderProviderTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/resources/META-INF/services/io.servicetalk.loadbalancer.RoundRobinLoadBalancerBuilderProvider
Motivation:
It can be useful to configure the RoundRobinLoadBalancer through a ServiceProvider, similar to other components already present in ServiceTalk.
Modifications:
This changeset introduces ServiceProvider functionality on top of the RoundRobinLoadBalancerBuilder. To do this, the builder has been refactored into an interface and a delegate implementation is also introduced.
Result:
It is now possible to configure the RoundRobinLoadBalancer through the ServiceProvider mechanism.
> Implement RoundRobinLoadBalancerBuilderProvider

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsResolverAddressTypes.java
Motivation:
Since we recently added control for min/max TTL for `DnsCache`, we have to apply the same boundaries to the other 2 caches that netty' `DnsNameResolver` uses internally.
Modifications:
- Configure `DnsCnameCache` and `AuthoritativeDnsServerCache` using the same `minCacheTTL/maxCacheTTL` boundaries;
Result:
All caches inside `DnsNameResolver` have consistent limits.
> `DefaultDnsClient`: make configuration for all caches consistent

- servicetalk-dependencies/build.gradle
- servicetalk-opentelemetry-asynccontext/build.gradle
- servicetalk-opentelemetry-http/build.gradle
Motivation:
Depending on the BOM instead of just the minimal -api package causes downstream issues in terms of how these dependency versions are managed.
Modifications:
In order to more tighly control what we are depending on, this changeset only depends on the-api package.
> Only depend on OpenTelemetry api and not the overall BOM

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MutualSslTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
Motivation:
It may be necessary for users to read SNI used for the SSL handshake to apply different policies. Let's make sure the SNI is always present in `SSLSession`.
Modifications:
- Enhance `SniTest` to validate that `getRequestedServerNames()` contains value regardless of the used `SslProvider` and that `SNIHostName` matches the expected value;
Result:
Better test coverage for SNI use-case.
> Enhance `SniTest` to verify that SNI is present in `SSLSession`

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/RequestTagExtractor.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilterTest.java
- http.url will not have localhost as it's not available all the time
- added http.target, http.route, http.flavor, http.user_agent, http.scheme, net.host.name, net.host.port
- allow http client filter to use host as default value, making component name optional
> Update tags for OpenTelemetry

- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent.java
Modifications:
- `io.servicetalk.internal.queues.useUnpadded` value defaults to "true" to use unpadded queues by default. This property will be removed in future releases, but exists in case there are any regressions detected.
> Use unpadded jctools queues by default

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FilterPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/SkipWhileTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherSkipWhileTckTest.java
- servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
Motivation:
It's useful to be able to skip elements of a stream until a predicate fails but that isn't yet supported in Servicetalk.
Modifications:
Add the SkipWhile operator to the Servicetalk Publisher class.
Result:
SkipWhile is now supported.
> Add the SkipWhile operator to Publisher

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/EmptyHttpHeaders.java
Motivation:
`EmptyHttpHeaders` inherits some default methods from `HttpHeaders`. Even though they work as expected, not all of them are optimal for an empty impl, like `spliterator()`. Override all methods to make it explicit.
Modifications:
- Implement all default methods in `EmptyHttpHeaders`.
Result:
All methods have explicit impl in `EmptyHttpHeaders`.
> Implement all default method in `EmptyHttpHeaders`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java
Motivation:
When proxy returns 2xx status code with `Connection: closed` header, users see an awkward error saying:
Failed to find a handler of type DeferSslHandler in channel pipeline. It confuses users. We can handle this case with a better exception message.
Modifications:
- Check if the channel is still active before generating `IllegalStateException`;
Result:
More clear exception message when proxy closes the connection.
> `ProxyConnectConnectionFactoryFilter`: report when the channel is closed

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
Motivation:
`java.net.URI` considers `http://localhost?param=value` a correct absolute address. However, `MultiAddressUrlClient` sends `/` instead of `/?param=value` to the server after transforming absolute to relative request target.
Modifications:
- Enhance `DefaultMultiAddressUrlHttpClientBuilder.absoluteToRelativeFormRequestTarget` to account for this use-case;
- Sync `RedirectSingle.absoluteToRelativeFormRequestTarget`;
Result:
`MultiAddressUrlClient` and redirect logic correctly transform `http://localhost?param=value` to a relative `/?param=value` request target.
> MultiAddressUrlClient: incorrect transformation of target without path

- gradle.properties
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcSslAndNonSslConnectionsTest.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
https://github.com/netty/netty/pull/13314 changes the exception type that netty throws when one of the sides is plaintext and another one is SSL. Instead of `SSLHandshakeException` it throws `NotSslRecordException`.
We need to adjust our tests to align with the new behavior.
Since this is a rare case that happens only due to programming mistake, the change has low risk.
> Update Netty 4.1.89 -> 4.1.91

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
Motivation:
`null` is the default value for DefaultMultiAddressUrlHttpClientBuilder. redirectConfig. If the builder method does not allow null argument, users don't have a way to reset the builder back to defaults when they need.
Modifications:
- Make an argument for `MultiAddressHttpClientBuilder.followRedirects` nullable;
Result:
Users can set a `RedirectConfig`, build a client, reset it back to `null`, build another client.
> `MultiAddressHttpClientBuilder.followRedirects` take a nullable config

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfig.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilter.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
Motivation:
Existing implementation of `RedirectSingle` strictly follows only redirect responses defined by RFC7231 and extract the target resource from `Location` header. This is too restrictive behavior that does not allow users to redirect custom status codes with custom location headers.
Modifications:
- Add `RedirectConfig.allowedStatuses()` to customize which status codes can follow redirect;
- Add `RedirectConfig.locationMapper()` to customize the target resource identification;
- Enhance `RedirectConfigBuilder` and `RedirectSingle` to support new config options;
- Enhance tests;
Result:
Users can configure redirects for custom status codes and location mapper.
> Extend `RedirectConfig`: custom allowed statuses and location mapper

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/JavaNetSoTimeoutHttpConnectionFilterTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/JavaNetSoTimeoutHttpConnectionFilter.java
Motivation:
For backward compatibility with blocking Java libraries, it's helpful to have a filter that mimics behavior of `SO_TIMEOUT` socket option.
> New filter: `JavaNetSoTimeoutHttpConnectionFilter`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedHttpSerializer.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/UriUtils.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractHttpRequestMetaDataTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/FormUrlEncodedHttpDeserializerTest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/FormUrlEncodedHttpSerializerTest.java
Motivation:
At the moment the behavior around null (and to an extent empty) values is a little bit unflexible. ServiceTalk makes the decision to ignore null values on encoding and converting them to the same value as an empty string on decoding.
Since there is no spec which says that null values are disallowed, it is better if ServiceTalk is flexible and lets the user decide if they want to ignore values (which they can do by checking and then just not encoding them in the first place).
Modifications:
This changeset modifies behavior as follows.
On the encoding side:
- null values are now allowed and encoded as "just" the key, instead of not being encoded at all. (Distinguished without an "=" compared to an empty string)
On the decoding side:
- Null values are now not turned into an empty …
> Allow null values with FormUrlEncodedHttp[De]Serializer

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/TimeoutCompletableTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/TimeoutSingleTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ConcurrentTerminalSubscriber.java
Motivation:
Publisher#timeout operator is inconsistent with Single and Completable timeout operators in that when a timeout triggers it will not ensure the timeout exception is propagated. It is possible for upstream to propagate a different exception even though the source of the error is a timeout exception.
Modifications:
- Enhance ConcurrentTerminalSubscriber to allow for external termination and take advantage of that in Publisher#timeout.
- Add tests for Completable and Single timeout operators to ensure existing expected behavior doesn't regress.
> Publisher#timeout always propagate TimeoutException

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
DefaultDnsClient logs at info level if the TTL from DNS is larger than the maximum configured TTL value. This level of logging can be noisy in production and not necessarily be within the client's control.
> DefaultDnsClient reduce log level for TTL > max

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultPayloadInfo.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
Motivation:
- No need to always use `concat` when we carry message body from original to redirect request;
- We can access `DefaultPayloadInfo` to copy original request flags;
Modifications:
- Discard an empty publisher instead of using concatenation;
- Give pkg-private access to `DefaultPayloadInfo`;
- Copy original flags when available instead of using pessimistic approach that always sets "mayHaveTrailers";
Result:
More optimal copying of the message body, preserving original PayloadInfo flags.
> Improve how we copy payload body in case of redirect

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TakeUntilPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/TakeUntilPublisherTest.java
Motivation:
For `takeUntil` operator, when either `Publisher` or `Completable` terminates, downstream `Subscriber` should see the original terminal signal, even if the other source terminates concurrently.
Modifications:
- Use recently added "deferred" methods of `ConcurrentTerminalSubscriber`;
- Add test to reproduce the original issue;
- Refactor existing tests to use `ParameterizedTest`;
Result:
`takeUntil` operators propagates the initial terminal signal.
> `Publisher.takeUntil(Completable)`: preserve original terminal signal

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
Motivation:
`RetryingHttpRequesterFilter` uses an async `flatMap` operator to drain response payload body, but it doesn't share the context. It will result in `AsyncContext` propagation if some other user filters manipulate with context during payload body read.
> `RetryingHttpRequesterFilter`: share context when drain response payload

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Http2SettingsBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
Motivation:
RFC says: Values above the maximum flow-control window size of 2^31-1 MUST be treated as a connection error of type `FLOW_CONTROL_ERROR`. To prevent users from accidentally setting incorrect values, we should accept only `int`. Also, `Http2Settings.initialWindowSize()` return type is `Integer`. Builder should be consistent.
Modifications:
- Deprecate `Http2SettingsBuilder.initialWindowSize(long)`;
- Add `Http2SettingsBuilder.initialWindowSize(int)`;
- Change `validate32Unsigned` and `validate31Unsigned` to throw an exception only when the passed value is greater than the max value;
- Remove unnecessary type cast for `maxHeaderListSize` in `H2ProtocolConfigBuilder`;
Result:
1. Users can not accidentally configure too large `initialWindowSize` value.
2. `Integer.MAX_VALUE` and …
> `Http2SettingsBuilder.initialWindowSize` should accept `int`, not `long`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/CacheConnectionHttpLoadBalanceFactory.java
Motivation:
RFC defines that settings values are represented as unsigned 32-bit numbers: https://datatracker.ietf.org/doc/html/rfc9113#section-6.5.1 Since it doesn't explicitly describe any additional restrictions for `SETTINGS_MAX_CONCURRENT_STREAMS` value, it can be as high as 4,294,967,295. When this happens, our concurrency controller receives `-1` and it forces the LB to create a new connection for every HTTP/2 request.
Modifications:
- `H2ClientParentConnectionContext` should adjust high `maxConcurrentStreams` values to `Integer.MAX_VALUE`. This is an equivalent of unbounded concurrency. Netty's
`DefaultHttp2ConnectionDecoder` and `DefaultHttp2ConnectionEncoder` do the same.
- Add a reproducer;
Result:
Large `SETTINGS_MAX_CONCURRENT_STREAMS` values are adjusted to …
> Avoid int overflow when receive large `MAX_CONCURRENT_STREAMS` value

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
When health-checking opens a new connection,
`host.addConnection(newCnx)` only adds a connection to the list, but keeps the state as `UNHEALTHY`. The following `markHealthy` will flip the state. This makes it possible for a racy state transitions in between. We can enhance `addConnection` to also change the state to keep everything atomic.
Modifications:
- `addConnection` transitions `ACTIVE` and `UNHEALTHY` states to `STATE_ACTIVE_NO_FAILURES`;
- Update comment to clarify why `markHealthy` can `cancelIfHealthCheck`;
Result:
Unhealthy host transitions to `ACTIVE` state at the same time when it adds a new connection to the list.
> RRLB: reduce number of state transitions when health-check passed

- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ProjectUtils.groovy
- servicetalk-grpc-protoc/build.gradle
Motivation:
Gradle 8 deprecated the classifier member in its API which was replaced with archiveClassifier. However when upgrading the archiveExtension member was used by mistake.
> gradlew 8 extension -> classifier

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
Motivation:
HttpObjectDecoder parses chunk size as a long but in practice we truncate the value to an integer internally. We should parse the value as a int and raise an error early rather than discarding data.
> HttpObjectDecoder chunk size long -> int

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutDemandPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
- servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
Motivation:
Publisher#timeoutDemand had a race condition that was fixed between startTimer and stopTimer. However there is still a race condition where the timer may fire and propagate a timeout even though there is demand.
Modifications:
- timerFires should atomically check/set the demand to verify there is no demand before propagating a timeout.
- Move the race detection to the Subscriber thread which avoids busy-wait-loop between Subscription and Subscriber threads. This should reduce busy-wait due to thread visibility and may reduce the spurious timeout condition (where timer fires before it is cancelled) since the cancellation is done on the same thread that sets the timer.
- Fix TestExecutor NPE when removing a scheduled queue.
> Publisher#timeoutDemand avoid suprious timer error

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
Motivation:
Users are not sure if they have to close the `InputStream` or not after converting it into a `Publisher` or after passing into a request object.
Modifications:
- Clarify `InputStream` ownership for `Publisher.fromInputStream`;
- Enhance `FromInputStreamPublisherTest`;
Result:
Users have better understanding if they should close `InputStream` or not.
> `Publisher.fromInputStream`: clarify `InputStream` ownership in javadoc

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherBuffer.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferTest.java
Motivation:
If the BufferStrategy terminates and the operator is applied to a Publisher that only supports sequential subscription model any retry operations will fail with duplicate Subscriber exception.
Modifications:
- Cancel before propagating error, so any retry operator will have state reset on the publisher.
> Publisher#buffer retry with sequential subscription

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExceptionMapperServiceFilter.java
- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpServiceFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExceptionMapperServiceFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/CacheConnectionFactory.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
Motivation:
LoggingGrpcLifecycleObserver and LoggingGrpcLifecycleObserver log the connection context, but the connection context string has spaces and special characters that may impact log indexers.
Modifications:
- quote places that log connection strings
> Logging LifeCycleObservers quote connection

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToOffloadedStreamingHttpService.java
- servicetalk-http-netty/gradle/spotbugs/testFixtures-exclusions.xml
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
- servicetalk-http-netty/src/testFixtures/java/io/servicetalk/http/netty/AsyncContextHttpFilterVerifier.java
- servicetalk-http-router-jersey/build.gradle
- servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/EndpointEnhancingRequestFilter.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AsyncContextTest.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AsynchronousResourceTest.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/BaseJerseyRouterTestSuite.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyTest.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/resources/AsyncContextResources.java
Motivation:
When users use `AsyncContext` inside endpoints that operate with async primitives, the context is not propagated as expected on the response path.
Modifications:
- `EndpointEnhancingRequestFilter`: add `shareContextOnSubscribe()` when we subscribe to `Single<Response>` and when we use `flatMap` to `handleContainerResponse`;
- Add `AsyncContextTest` and `AsyncContextResources` to verify expected behavior for different endpoints;
- Make more `AsyncContextHttpFilterVerifier` utilities public to share code for `AsyncContext` verification;
- Avoid using deprecated `Matchers.isEmptyString()`;
- Remove outdated exclusion from `testFixtures-exclusions.xml`;
Result:
Jersey endpoints correctly propagate `AsyncContext`.
> Jersey router: async endpoints don't propagate AsyncContext

- servicetalk-concurrent-api/docs/modules/ROOT/assets/images/blocking-scenarios.svg
Motivation:
The Subscriber and Subscription labels are reversed in the blocking flow diagram.
> docs: Clarify blocking scenarios Subscriber/Subscription

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/LongBinaryConsumer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ValidateDemandPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ValidateDemandPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherValidateDemandTckTest.java
Motivation:
Some use cases use custom operators and sources that may invalidate demand
which can invalidate state in other operators and leave the system in
an undefined state. There is no easy way to validate this and get visibility.
Modifications:
- Add Publisher#validateOutstandingDemand operator
> Publisher#validateOutstandingDemand operator

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
Motivation:
If a connection attempt fails before it was established, the observer invokes `connectionClosed()` callback instead of
`connectionClosed(Throwable)`. As the result, observer doesn't see an error.
Modifications:
- `TcpConnector` intercepts the failed `ChannelFuture` and assigns the exception before Netty invokes `CLOSE_ON_FAILURE` listener that `Bootstrap` attached by default;
- Enhance `TcpTransportObserverErrorsTest` to validate this use-case;
Result:
Users see exception via observer if connect attempt fails.
> `TransportObserver` doesn't propagate early connect failures

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAliveManager.java
Motivation:
`KeepAliveManager` has very limited logging that doesn't describe what is going on during graceful closure process. Also, it's internal state is not user-friendly when analyzing heap dumps.
Modifications:
- Add more logging, include the parent `channel` in every log statement with extra information from internal fields when necessary;
- Use enum for internal state instead of `Object` constants;
- Rename `activeChildChannels` -> `activeStreams` to align name with public API;
Result:
More debug-level visibility, easy to read internal state for heap dump analysis.
> `KeepAliveManager`: improve debuggability

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultExecutor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executors.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/DefaultExecutorTest.java
Motivation:
It's very difficult to properly use an Executor that has a fixed size thread pool because the current queue is a SynchronousQueue which will result in rejecting work if there isn't a free thread to service it. This also runs contrary to the patterns used in the JDK for fixed size thread pools which default to the unbounded LinkedBlockingQueue.
Modifications:
Use the unbounded LinkedBlockingQueue for Executors with fixed size.
Result:
Less surprising behavior of the fixed size Executors.
> Use an unbounded queue for fixed size Executors

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/CustomTransportTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAliveManager.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveManagerTest.java
Motivation:
`KeepAliveManagerTest` covers only non-duplex `Channel` use-case. However, `KeepAliveManager` state machine is a lot more complex for `DuplexChannel`. We need to enhance test coverage for the most used case.
Modifications:
- Parametrize `KeepAliveManagerTest` to test with duplex and non-duplex `Channel`, add more assertions;
- Modify `H2ParentConnectionContext` and `KeepAliveManager` to accept `Http2StreamChannel` instead of `Channel`;
- `KeepAliveTest`: fix `clientBuilder.initializeHttp` override issue (`CLIENT_CTX` is not set), do some other minor refactoring;
Result:
Enhanced test coverage for `KeepAliveManager`.
> Test HTTP/2 `KeepAliveManager` with `DuplexChannel`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAliveManager.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveManagerTest.java
Motivation:
1. If we failed to write a `PING` or `GO_AWAY` frame, the channel is already corrupted and we should not expect a gentle FIN exchange, simply close the channel.
2. If we shutdown output, wait for input shutdown only for a reasonable time frame to prevent a resource leak because network can lose a FIN back.
Modifications:
- Close the channel immediately if `close0` is invoked with an exception;
- Do `SslHandler.closeOutbound()` only for a duplex channel;
- Schedule a timer for `pingAckTimeoutNanos` to wait for input shutdown and force close if it's not received;
Result:
HTTP/2 connections don't hang indefinitely if the remote peer does not reply with a FIN back or if FIN was lost.
> `KeepAliveManager`: force close the channel in case of any issues

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveManagerTest.java
Motivation:
#2611 fixed behavior, but didn't add new tests to assert fixed scenarios.
Modifications:
- Test that the input will be shutdown after timeout;
- Test that channel is closes if any write operation inside `KeepAliveManager` fails;
- Reduce `KeepAliveTest` timeouts to speed up local tests;
Result:
Behavior fixed in #2611 is tested now.
> `KeepAliveManager`: add tests for #2611

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAliveManager.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveManagerTest.java
Motivation:
1. `GO_AWAY` allows including a content for debugging purposes. It helps to debug closure based on frame-logging data.
2. `PING` frames always include data, using even/odd numbers help to understand originator of the frame.
Modifications:
- Include content when sending `GO_AWAY` frames;
- Use even numbers for keep-alive `PING`s and odd numbers for graceful close `PING`s;
- Test new behavior;
Result:
Possible to understand the cause for GO_AWAY and PING frame when frame logging is enabled.
> `KeepAliveManager`: include human-readable debug data in h2 frames

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequestMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractHttpRequestMetaDataTest.java
Motivation:
Without fragment support users are not able to build a full request target using only builder methods
Modifications:
- Adds setter and getter for fragment in HttpRequestMetaData implementations
- Adds tests to AbstractHttpRequestMetaDataTest
Result:
Users are now able to set a fragment for request targets
> Add fragment methods to HttpRequestMetaData

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
Currently, clients fallback to `retryWithConstantBackoffDeltaJitter` retry strategy for `ServiceDiscovery` if users didn't provide one. Retrying with a constant backoff could add more pressure on DNS servers if they start failing consistently. Exponential backoff will help us to slow down for permanent errors.
Modifications:
- `retryWithConstantBackoffDeltaJitter(10, 5)` -> `retryWithExponentialBackoffFullJitter(8, 256)` - changes retries from every 5-15 seconds to exponentially increasing delay from 0-8 to 0-256 seconds;
Result:
Less pressure on DNS servers for permanent failures.
> Change default SD retry strategy to exponential backoff with full jitter

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ThrowableUtils.java
Motivation:
If `ServiceDiscoverer` fails for the first discovery call of a new client, the exception is propagated to the request caller. If it fails after the first collection of resolved addresses is returned, users never see errors from `ServiceDiscoverer` unless they opt-in for a `ServiceDiscoverer`-specific observer. This hides errors for users by default.
Modification:
- `DefaultSingleAddressHttpClientBuilder$StatusAwareServiceDiscoverer` logs all observed errors at `debug` level;
Result:
Users can see errors from `ServiceDiscoverer` and react when error rate increases.
> Client should log observed errors from `ServiceDiscoverer`

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DelegatingDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserverTest.java
Motivation:
Currently, Netty's DNS resolver is configured to bind automatically after we write a packet. As the result, logs show only channel id but not local address:port pair. As the result, it's hard to correlate the packets we send with server-side DNS logs.
Modifications:
- Introduce `DnsServiceDiscovererBuilder` API for users to specify a local `SocketAddress`;
- Use `new InetSocketAddress(0)` by default for binding;
- Temporarily add a system property that allows users to quickly revert pre-existing default behavior:
`-Dio.servicetalk.dns.discovery.netty.skipBinding=boolean`;
- Log pre-initialized default values of `DefaultDnsServiceDiscovererBuilder` at debug level;
Result:
Users can see `[id: 0x1d761bfc, L:/0.0.0.0:63085]` instead of just `[id: 0x1d761bfc]` in Netty logs when …
> Bind DNS channels to a local wildcard address

- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServerBuilder.java
Motivation:
`DefaultGrpcServerBuilder` was created before
`DelegatingHttpServerBuilder` was available and had to implement its own delegation logic.
Modifications:
- Use `DelegatingHttpServerBuilder` for `DefaultGrpcServerBuilder` instead of repeating delegation for all method;
- Add 2 missing delegation overloads for `DelegatingHttpServerBuilder`: `listenService` and `listenServiceAndAwait`;
Result:
Less code.
> Use `DelegatingHttpServerBuilder` for `DefaultGrpcServerBuilder`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SourceToFuture.java
Motivation:
Visibility for how long we were waiting for the `Future` to complete before it timed out.
> Include timeout value when `toFuture().get(long, TimeUnit)` times out

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslHandshakeTimeoutTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SslConfig.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SniServerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslClientChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslServerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslUtils.java
- servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/AddressUtils.java
Motivation:
Users need control the timeout for SSL handshake.
Modifications:
- Add `SslConfig.handshakeTimeout()` and `AbstractSslConfigBuilder.handshakeTimeout(Duration)`;
- Refactor `SslContextFactory` to store timeout value in `SslContext` attributes and reuse code between `forClient` and `forServer` factories;
- Refactor `SslUtils` to apply handshake timeout when a new `SslHandler` is created;
- Add `SslHandshakeTimeoutTest`;
- Add javadoc references from `SslConfig` builders to `SslConfig`;
Result:
Users can control SSL handshake timeouts via `SslConfig` API.
> Add `SslConfig.handshakeTimeout()`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MutualSslTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
- servicetalk-tcp-netty-internal/build.gradle
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SniServerChannelInitializer.java
Motivation:
Netty 4.1.94 exposed a new option to configure maximum length of a
`ClientHello` message. `SniHandler` also allows configuring a timeout
for parsing SNI info before starting the handshake.
See https://github.com/netty/netty/commit/535da17e45201ae4278c0479e6162bb4127d4c32
Modifications:
- Add `HttpServerBuilder.sslConfig(ServerSslConfig, Map, int, long)`
overload to give users a way for `SniHandler` configuration;
- Propagate new options via `TcpServerConfig`;
- Enhance `SniServerChannelInitializer` to apply new options when the
min required Netty version is detected;
- Set reasonable default values;
- Add `SniTest.sniTimeout(...)`;
Result:
Users can control the maximum `ClientHello` length and timeout for parsing
SNI information.
> Add `ClientHello` configuration options for SNI

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
Motivation:
Even though `HttpRequestMetaData#fragment()` has default implementation, because all request types override it with different return type, we must provide default implementations for these overrides too. Otherwise, the code is not backward compatible.
Modifications:
- Add `default` implementation for `fragment(String)` in `HttpRequest`, `StreamingHttpRequest`, `BlockingStreamingHttpRequest`;
Result:
Request interfaces are backward compatible.
> Provide default `fragment(String)` override for all request types

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
Motivation:
Having no cache works well for happy path and for poisoned cache use-case described in #2518. Unfortunately, users may leak new client instances and add excess load on DNS. Having a short-lived cache, similar to OpenJDK default, will help to reduce number of outgoing DNS queries.
Modifications:
- Increase `DEFAULT_MAX_TTL_CACHE_SECONDS` from 0 to 30 seconds;
- Use `Math.min(pollTtl, cacheTtl)` inside `ttl(int, int)` overload to avoid `minCacheSeconds > minSeconds` and `maxCacheSeconds > maxSeconds`;
- Log `DEFAULT_TTL_POLL_JITTER_SECONDS` at debug level;
- Stop using `DEFAULT_MIN_TTL_POLL_SECONDS` for `srvHostNameRepeatInitialDelay` because they are not related;
- Adjust tests to disable default cache because we manage time manually;
Result:
`DnsServiceDiscoverer` caches …
> Adjust DNS default max TTL cache boundary to 30 seconds

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToOffloadedStreamingHttpService.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
Motivation:
When `offloadAll()` strategy is used, offloading is applied for all paths. Invocation of the `delegate.handle(...)` becomes a single of the response. Because the response single also uses `subscribeOn(...)`, we are already offloaded. But the `shouldOffload` predicate for `handle(...)` is validated upfront, when we were on `IoThread`. This results in double offloading.
Modifications:
- If both `isMetadataReceiveOffloaded()` and `isSendOffloaded()` are true, wrap the `offloadHandle` with `defer` to validate the `shouldOffload` predicate at the time we already subscribed to the response single;
Result:
Less thread hops.
> Avoid double offloading a service when `offloadAll()` is used

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DelegatingDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsNameResolverBuilderUtils.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilder.java
Motivation:
Starting from Netty 4.1.88, it added a new features to consolidate all concurrent lookups for the same hostname instead of sending independent requests.
Modifications:
- Add new `DnsServiceDiscovererBuilder.consolidateCacheSize(int)` API;
- Consolidate 1024 concurrent DNS hostnames by default, log default value;
Result:
By default, up to 1024 different hostnames will consolidate concurrent lookups. Users have API to change this value, if necessary.
> Add `DnsServiceDiscovererBuilder.consolidateCacheSize(int)`

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/IoUringTest.java
Motivation:
Currently, the ioUringIsAvailableOnLinux test assumes that if when run under CI, the kernel version is always up to par with what netty needs to get IoUring enabled. This assumption might not always hold true, so allow to skip the test gracefully when CI has an older kernel version instead of failing the test suite.
> Do not fail IoUring test on older CI systems

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DelegatingDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilder.java
Motivation:
Both JDK and Netty resolvers allow configuring "negative TTL" for
caching unsuccessful DNS resolutions. By default, it's configured to
0, but there is a Java system property to change it for
`java.net.InetAddress`.
Modifications:
- Add `DnsServiceDiscovererBuilder#ttl(int, int, int, int, int)`
overload that allows configuring negative TTL;
- Recognize `networkaddress.cache.negative.ttl` system property to
adjust the default value for Netty resolver;
- Log the default value at debug level;
Result:
Users can configure DNS caching for unsuccessful results.
> Allow configuring "negative" DNS TTL for failed resolutions

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SourceToFuture.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ThrowableWrapper.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AbstractToFutureTest.java
Motivation:
[Single|Completable].toFuture() may hang if there is a thread blocked on get(), a different thread invokes cancel, and the Cancellable for the Subscriber chain throws.
Modifications:
- Unblock the CountDownLatch in a finally block
- Preserve stack trace from the thread that invokes cancel
> [Single|Completable].toFuture() cancellable handle exception

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
- servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java
Motivation:
Netty's `MultithreadEventLoopGroup` already has a logic to identify the default number of EventLoop threads and exposes system properties to influence these numbers. Users of Netty based frameworks expect these properties to be taken into account:
- `io.netty.eventLoopThreads`
- `io.netty.availableProcessors`
Modifications:
- Allow users to pass `0` (zero) to `NettyIoExecutors.createIoExecutor`, which is recognized by Netty as a special value that considers system properties;
Result:
Users can use Netty's system properties to influence default Netty behavior for number of EvenLoop threads.
> `NettyIoExecutors`: allow passing 0 for N of IoThreads to infer default

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslCertificateMaxSizeTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SslConfig.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
Motivation:
Some use cases have certificate chains larger than the BoringSSL default limit. This may result in handshake failures and there is no way to configure the maximum value.
Modifications:
- Add SslConfig#maxCertificateListBytes() and corresponding builder methods to allow configuring the limit (if supported by SSLEngine).
> Add SslConfig#maxCertificateListBytes()

- servicetalk-concurrent-internal/build.gradle
- servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/DelayedSubscriptionTest.java
Motivation:
setDelayedFromAnotherThreadIsVisible can be enhanced to force concurrency and that multiple invocations of DelayedSubscription are hanlded correctly.
> Enhance DelayedSubscriptionTest

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RepeatTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RepeatWhenTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RetryTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RetryWhenTest.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
Publisher `retry*` and `repeat*` operators need to persist outstanding demand between "re-do" operations. Otherwise the downstream Subscriber will have requested signals, but they won't be requested from the new async source after switching. If a downstream operator (or Subscriber) throws from onNext the retry/repeat operator has to decrement demand to avoid violating the Reactive Streams specification (no more than request(n) amount of onNext(..)), but downstream Subscribers that didn't see the onNext (because an earlier operator threw) will be hung waiting for request(n) that will never be delivered.
Modifications:
- Publisher[retry|repeat] introduce a flag to determine if downstream onNext throwing should be terminal. This mode should be used unless it is known the onNext …
> Publisher[retry|repeat] operators demand management if onNext throws

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/JavaNetSoTimeoutHttpConnectionFilterTest.java
Motivation:
When running on slow CI, 100ms might be too low timeout value that may cause races and result in flaky test behavior.
Modifications:
- Use 10x timeout value when running on CI;
Result:
`JavaNetSoTimeoutHttpConnectionFilterTest` is not flaky.
Fixes #2641.
> Increase timeout value for `JavaNetSoTimeoutHttpConnectionFilterTest`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RepeatTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RepeatWhenTest.java
Motivation:
The current default mode of Publisher retry/repeat operators allows exceptions to propagate from onNext. However this may result in incorrect demand management and lead to "hangs" due to off-by-one demand (downstream subscriber requested X, but may only see X-1 if an earlier downstream subscriber threw). ReactiveStreams spec specifies that Subscriber methods are generally not expected to throw [1]. For these reasons the current default maybe unsafe and isn't commonly expected. The alternative mode makes exception handling explicit and won't result in hangs.
[1] https://github.com/reactive-streams/reactive-streams-jvm#2.13
Modifications:
- Change default mode of operation to not allow downstream exceptions to propagate upstream.
> Publisher[retry|repeat] change default exception handling mode

- servicetalk-concurrent-api/gradle/checkstyle/suppressions.xml
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanLifetimeMapper.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanMapper.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithLifetimePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithMapper.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ScanWithPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherScanWithLifetimeTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherScanWithMapperTckTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
Motivation:
Publisher scanWith operators only allow a limited set of
mapped terminal transformations. Use cases like mapping
state and preserving the onError Throwable aren't possible.
Modifications:
- Introduce ScanMapper and ScanLifetimeMapper which
support MappedTerminal that allows all the terminal combinations
to be mapped.
- Deprecate ScanWithMapper and ScanWithLifetimeMapper in favor of
these new APIs.
- Deprecate Publisher.scanWith and Publisher.scanWithLiftime in
favor of the new extension operators.
> Publisher scanWith enhancements

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllersTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
Motivation:
Provide more visibility for `ReservableRequestConcurrencyControllers` and how it changes internal state when new events received.
Modifications:
- Pass a connection to `ReservableRequestConcurrencyControllers` to always include connectionId when logging;
- Log when retrying MaxConcurrentStreamsViolatedStacklessHttp2Exception;
- Remove logging transport events from `AbstractLBHttpConnectionFactory` because we log it in `ReservableRequestConcurrencyControllers` now;
Results:
All `ReservableRequestConcurrencyControllers` logs contain connectionId.
> Enhance debug logging for `ReservableRequestConcurrencyControllers`

- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLifecycleObserver.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
Motivation:
If request is retried multiple times, multiple callbacks can be invoked
multiple times (for every retry attempt) when logging observers are
applied at the client level.
Modifications:
- Remove some assertions from
`LoggingGrpcLifecycleObserver` and `LoggingHttpLifecycleObserver`;
- Clarify some expectations in `HttpLifecycleObserver` javadoc;
Result:
No `AssertionError` in tests that can retry.
> Remove incorrect assertions from logging lifecycle observers

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
If DNS resolution fails with an exception, currently we log only the fact of cancelling the subscription, but we don't log what was the root cause.
Modifications:
- Log `cause` inside `cancelAndTerminate0`;
Result:
Debug logs show DNS errors.
> `DefaultDnsClient` log when resolution fails with an exception

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/NoActiveHostException.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerUnhealthyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
Today, `NoAvailableHostException` can be thrown when either LB is not ready yet or when it's already ready, but all hosts turned into unhealthy state. In this case, there is no need to wait for "ready" event, because the onHostsAvailable completable is already completed. There is a risk to never exit from the retry loop if `RetryingHttpRequesterFilter` is configured with
`maxTotalRetries(Integer.MAX_VALUE)`.
Modifications:
- Introduce `NoActiveHostException` to avoid interacting with `LoadBalancerReadySubscriber` when LB turns into unhealthy state;
- Add tests to verify expected behavior;
Result:
`RetryingHttpRequesterFilter` doesn't involve
`LoadBalancerReadySubscriber` when LB is unhealthy.
> `RetryingHttpRequesterFilter`: don't wait for LB if it's unhealthy

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RetryTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RetryWhenTest.java
- servicetalk-concurrent-internal/gradle/spotbugs/main-exclusions.xml
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java
Motivation:
Publisher.retry default mode of operation changed to not propagate exceptions from onNext due to demand hangs. This means the retry operator may not honor the retry strategy due to invalid usage.
Modifications:
- wrap exceptions from onNext to clarify the rational for not honoring the retry strategy
> Publisher.retry wrap exceptions thrown from onNext

- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
Motivation:
`OPENSSL` provider uses 16Kb for `maxCertificateListBytes` by default.
Modifications:
- Increase default value to 32Kb;
Result:
Users can handle larger cert chains by default.
> Increase default `SslConfig.maxCertificateListBytes()` to 32Kb

- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
`https://tools.ietf.org/search/` prefix is broken. All other Javadoc links has `https://tools.ietf.org/html/` prefix and works just fine.
> Javadoc: fix broken RFC link.

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
Motivation:
The Publisher.timeoutDemand(Duration) method calls timeout operator overload instead of the timeoutDemand overload and is therefor applying the wrong timeout.
> Publisher.timeoutDemand(Duration) not timing out demand

- gradle.properties
- servicetalk-gradle-plugin-internal/plugin-config.gradle
- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Motivation:
`gradle-pitest-plugin` is not an official plugin. Its latest version was released in Nov 2022. Gradle 8 complains that it uses deprecated API. Since we never actually used pitest, we should consider removing it.
Modifications:
- Remove `gradle-pitest-plugin` and its configuration;
- Wrap `sourceCompatibility/targetCompatibility` with `java` block, according to the guideline here:
https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#java_convention_deprecation
Result:
No warnings from Gradle 8 about using deprecated API.
> Remove `gradle-pitest-plugin`

- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
Motivation:
`LingeringRoundRobinLoadBalancerTest.expiringAHostDoesntRaceWithConnectionAdding()` can fail with `AssertionError`, see #1859.
Modifications:
- Add `NoActiveHostException` to the list of expected exceptions;
Result:
Fixes #1859
> `LingeringRoundRobinLoadBalancerTest`: adjust assertions

- servicetalk-data-jackson-jersey/src/main/java/io/servicetalk/data/jackson/jersey/JacksonSerializationExceptionMapper.java
- servicetalk-data-jackson-jersey/src/test/java/io/servicetalk/data/jackson/jersey/JacksonSerializationExceptionMapperTest.java
Motivation:
If we have a JsonMappingException during serialization,
for example an un-mappable type, we end up returning
a 415 error which suggests it was a problem with the
request whereas it's most like a server error.
Modifications:
Use the processor type that generated the exception to
distinguish between serialization and deserialization
exceptions.
> Map JsonMappingExceptions caused by a serializer to 500 responses

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/JavaNetSoTimeoutHttpConnectionFilterTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/JavaNetSoTimeoutHttpConnectionFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java
Motivation:
`java.net.Socket#setSoTimeout(int)` javadoc describes that zero value results in infinite timeout and all other values must be positive. Otherwise, `IllegalArgumentException` is thrown. We should align with this contract.
Modifications:
- Clarify javadoc for `JavaNetSoTimeoutHttpConnectionFilter`;
- Handle zero and negative timeout values;
- Enhance tests;
Result:
`JavaNetSoTimeoutHttpConnectionFilter` handles values similar to `java.net.Socket`.
> `JavaNetSoTimeoutHttpConnectionFilter`: handle zero and negative values

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetrySingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryWhenSingle.java
Motivation:
Some of the retry/repeat operators copy AsyncContext on subscribe and others doen't. We should consistently not copy in these operators and if copy is desired it can be implemented externally via another operator.
> Retry/repeat operators consistently not copy AsyncContext

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableSetContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherSetContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleSetContextOnSubscribe.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingToStreamingService.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToHttpService.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
RetryingHttpRequesterFilter uses the request across retry operations. The request's Publisher state is shared across retries and operators applied via transformMessageBody will therefore be reapplied on each retry. This typically isn't desirable from a semantics perspective but may also lead to StackOverflowException if enough retries are attempted.
Modifications:
- RetryingHttpRequesterFilter should reuse the original Publisher for request payload body on each retry attempt.
> RetryingHttpRequesterFilter use original Publisher avoid SOOE

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyPipelineSslUtils.java
Motivation:
Currently, `waitForSslHandshake` flag is defined by presence of `SslHandler` in the pipeline.
However, there could be a use-case when `DefaultNettyConnection` is added after handshake
is already complete and there is no need to wait for it anymore.
Modifications:
- Deprecate `NettyPipelineSslUtils.isSslEnabled(...)`, instead introduce
`NettyPipelineSslUtils.extractSslSessionAndReport(...)` overload that can extract `SSLSession`
if the handshake is already complete and avoid `waitForSslHandshake`;
- Use the new utility in `DefaultNettyConnection`, `H2ClientParentConnectionContext`,
and `H2ServerParentConnectionContext`;
- Enhance tests to make sure behavior for all use-cases does not change;
Result:
The last handler in the pipeline does not wait for handshake if it's already …
> Don't wait for handshake if it's already done when adding last handlers

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
If multiple client instances receive identical DNS records set, they will start connecting to the same upstream instances because the collection is always sorter.
Modifications:
- Shuffle the list before propagating to the load balancer;
Result:
More uniform distribution of the initial connections.
> Shuffle DNS records before propagating to `LoadBalancer`

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionClosedAfterIoExceptionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReserveConnectionTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
`NettyChannelPublisher` will force closure of the `Channel` in case of exception after the cause is propagated to users. In case users don't have offloading, there is a risk to retry on the same IO thread. We should notify `LoadBalancer` that this connection is closing to avoid retrying on the same connection.
Modifications:
- Invoke `connection.notifyOnClosing()` inside `exceptionCaught` before notifying `NettyChannelPublisher` about an error;
- Enhance `ReserveConnectionTest` to make sure reserved connection is closed in case of `IOException`;
- Add `ConnectionClosedAfterIoExceptionTest` to make sure retries use a different connection in case of `IOException` and the failed connection gets closed;
Result:
Retries always select a different connection if existing connection …
> Mark connection as closing on exception caught

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
Motivation:
For Http server I noticed a bug where the current context was still available even though the context was closed. Leading to the same request under the same trace.
Result:
The context will now be new for server requests and it will simply use a clean state.
> `OpenTelemetryHttpServerFilter`: use root context for new requests

- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingClient.java
- servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingServer.java
- servicetalk-examples/grpc/execution-strategy/src/main/java/io/servicetalk/examples/grpc/strategies/ExecutionStrategyServer.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyConfigurationFailuresTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java
Motivation:
offloadNever is deprecated, we should minimize its usage internally just for backwards compatability and testing.
> Remove more offloadNever usage

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
Motivation:
Publisher.multicast tracks the active subscriber with the least demand in order to control upstream demand. When cancel happens if the subscriber with minimum demand is removed the delta with the new minimum should be propagated upstream. However there is a bug where the initial demand offset isn't considered for late subscribers that get cancelled with may lead to not propagating demand upstream and "hanging".
> Publisher.multicast late subscriber cancel demand bug

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompositeExceptionUtils.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherSwitchMap.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SwitchMapSignal.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherSwitchMapTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherSwitchMapDelayErrorTckTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherSwitchMapTckTest.java
Motivation:
Publisher.switchMap can be used to flatten an async stream of
publishers while always taking results from the latest publisher
and cancelling the previous Publisher.
> Add Publisher.switchMap

- servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleUrlClient.java
- servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/alpn/HttpUrlClientWithAlpn.java
- servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/priorknowledge/Http2PriorKnowledgeUrlClient.java
- servicetalk-examples/http/mutual-tls/src/main/java/io/servicetalk/examples/http/mutualtls/HttpUrlClientMutualTLS.java
Motivation:
Some HTTP examples only use single-address client. It would be helpful to also provide multi-address client examples.
Modification:
- Create `DebuggingExampleUrlClient`
- Create `HttpUrlClientMutualTLS`
- Create `Http2PriorKnowledgeUrlClient`
- Create `HttpUrlClientWithAlpn`
Result:
Both single-address and multi-address clients are demonstrated in HTTP examples.
> Demonstrate multi-address client in HTTP examples

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java
Motivation:
1. Successful response to `CONNECT` never has a message body, and we are not interested in payload body for any non-200 status code. Drain it asap to free connection and RS resources before starting TLS handshake.
2. Result of the proxy tunneling is incorrectly offloaded, response offloading can be different from users-configured `ConnectExecutionStrategy`.
Modifications:
- Drain response message body before invoking `handleConnectResponse`;
- Use computed `ExecutionStrategy` to decide when `newConnection` should be offloaded, similar to what `AbstractLBHttpConnectionFactory` does;
- Update `ProxyConnectConnectionFactoryFilterTest` to assert new behavior;
Result:
Response to `CONNECT` request is drained and all publishers are released before starting any new activity on this …
> Drain proxy `CONNECT` response before starting TLS handshake

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1ProtocolConfigBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllersTest.java
Motivation:
`RequestConcurrencyController` is always applied as the top level wrapper of the connection (after all connection-level filters) before returning it back to the `LoadBalancer`. As the result, there is no need to make an earlier decision for `initialConcurrency` value at implementations of `AbstractLBHttpConnectionFactory` (when the final protocol may be unknown) because it can be inferred based on the resulting connection protocol at the time a new
`ReservableRequestConcurrencyController` is created. Early initialization as it's now makes it harder to switch protocols after proxy connect.
Modifications:
- Convert abstract method `AbstractLBHttpConnectionFactory.newConcurrencyController` into a private method;
- Compute `initialConcurrency` based on connection's protocol and …
> Calculate initial concurrency based on resulting connection protocol

- servicetalk-data-protobuf/src/test/java/io/servicetalk/data/protobuf/ProtobufSerializerFactoryTest.java
- servicetalk-data-protobuf/src/test/proto/test_message.proto
Motivation:
It is valid to not encode an empty map value and token, and we don't have a unit test to verify this behavior.
> protobuf: Add unit test for empty map value deserialization

- .github/workflows/ci-prb-reports.yml
- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq-reports.yml
- .github/workflows/ci-prq.yml
- build.gradle
- gradle.properties
- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
Modifications:
- Update mockito 4.11.0 -> 5.5.0 (only for jdk11+)
- Disable spotbugs on JDK21 or greater due to incompatibility
https://github.com/spotbugs/spotbugs/issues/2567
> CI: Enable jdk21 builds

- .github/workflows/ci-prb-reports.yml
- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq-reports.yml
- .github/workflows/ci-prq.yml
- build.gradle
- gradle.properties
- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
This reverts commit 5d9a29aba9d0754dd96624e953a47946c7460d53.
Pull requests (#2704) consistently failing with:
```
#
#
#
```
> Revert "CI: Enable jdk21 builds (#2702)"

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingMultiAddressHttpClientBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
Motivation
----------
At the moment, if no port number is explicitly provided, the default HTTP and HTTPS ports are used (80 and 443). In some environments it can be useful (i.e. if a client is always talking to a high port number) to not have to specify it on every request.
Modifications
-------------
This changeset introduces two new builder options to allow customizing the defaultHttpPort as well as the defaultHttpsPort and applying it if no explicit port is provided on the request itself.
Result
------
It is now possible to not specify the port number on every request if they diverge from the default 80 or 443 port numbers.
> Introduce defaultHttp(s)Port for MultiAddressHttpClientBuilder

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SniCompleteChannelSingle.java
Motivation:
`SniCompleteChannelSingle` closes the `ChannelHandlerContext` if it can not propagate an error to subscriber but does not use `ChannelCloseUtils` that will associate an error with a connection to correctly report `ConnectionObserver.connectionClosed` events.
> Use `ChannelCloseUtils` in `SniCompleteChannelSingle`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnChannelSingle.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyPipelineSslUtils.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SniServerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslClientChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslServerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslUtils.java
Motivation:
Observed that `AlpnChannelHandler` does not report handshake failure via `SecurityHandshakeObserver`. Moreover, `SslHandler` closes the `Channel` before propagating `SslHandshakeCompletionEvent` in case the handshake fails, which makes our reporting sequence incorrect (`ConnectionObserver.connectionClosed(Throwable)` is invoked before `SecurityHandshakeObserver.handshakeFailed(Throwable)`, but shouldn't).
Modifications:
- Instead of trying to intercept `SslHandshakeCompletionEvent` for all pipeline variations, add a listener for `SslHandler.handshakeFuture()` to reliably get notifications about handshake status before the `Channel` can be closed;
- Enhance `SecurityHandshakeObserverTest` to test failure case and verify ordering of events;
- Enhance `AlpnChannelHandler` to …
> TLS handshake failures are not reported to observers when ALPN is used

- gradle.properties
Motivation:
Netty 4.1.99 includes fixes that allow the use of JDK 21.
Modifications:
Upgrade Netty from 4.1.98 to 4.1.99.
> Upgrade Netty 4.1.98 -> 4.1.99

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyFilterableStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactoryTest.java
- servicetalk-http-netty/src/testFixtures/java/io/servicetalk/http/netty/ProxyTunnel.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/StacklessClosedChannelException.java
Motivation:
Currently, HTTP proxy `CONNECT` logic is prepended before user-defined `ConnectionFactoryFilter`s. Because user filters can wrap `FilterableStreamingHttpConnection`:
1. It makes it hard to upgrade the connection if ALPN agrees on a different protocol.
2. `ProxyConnectConnectionFactoryFilter` can not access Netty's `Channel` to trigger TLS handshake.
Modifications:
- Create `ProxyConnectLBHttpConnectionFactory` as an alternative to `PipelinedLBHttpConnectionFactory` that makes HTTP proxy `CONNECT` request after `PipelinedStreamingHttpConnection` is created;
- Keep `ProxyConnectConnectionFactoryFilter` only for the purpose of propagating `HTTP_TARGET_ADDRESS_BEHIND_PROXY` key upstream;
- Add internal `NettyFilterableStreamingHttpConnection` to get access to Netty `Channel` …
> Move HTTP proxy `CONNECT` logic before `ConnectionFactoryFilter`s

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcProxyTunnelTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnChannelSingle.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientChannelInitializer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactoryTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CopyByteBufHandlerChannelInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
Proxies that behave like blind forwarding tunnel do not care what protocol will be
used after the tunnel is established. Because we always enforce TLS for such tunnels,
we can rely on ALPN to negotiate expected protocol after the tunnel is established.
This will allow gRPC use cases to operate via tunneling proxies.
Modifications:
- Enhance `ProxyConnectLBHttpConnectionFactory` to take ALPN results into account
before finishing connection initialization;
- Enhance `HttpsProxyTest` to validate proxy tunnel works for any combination of the
configured protocols;
- Enhance `ProxyConnectLBHttpConnectionFactory` to validate new use-cases;
- Add `GrpcProxyTunnelTest`;
Results:
1. HTTP users can negotiate HTTP/2 after proxy tunnel is established.
2. gRPC users can use proxy tunnels. …
> Implement HTTP proxy CONNECT with ALPN

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactory.java
Motivation:
Remove some unused arguments and member variables.
> Minor cleanup of http proxy/handshake code

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProxyTest.java
Motivation:
Plaintext proxies operate as forwarding message proxies. They expect clients to send requests with absolute-form request-target to determine where to forward the message. This logic does not depend on the protocol version, it already works for HTTP/1.1 and should work for HTTP/2 the same way.
Modifications:
- `DefaultSingleAddressHttpClientBuilder`: remove check that does not allow users to use HTTP/2 prior-knowledge with a proxy over plaintext connections;
- Enhance `HttpProxyTest` to validate behavior consistency for both protocols;
Result:
Users can use plaintext HTTP/2 prior-knowledge clients to communicate via a forwarding message proxy.
> Support proxy for plaintext HTTP/2 clients with prior-knowledge

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SniCompleteChannelSingle.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
`SslHandler` automatically initiates the handshake and manages reads on the client-side. We need to initiate read only on the server-side.
Modifications:
- `DefaultNettyConnection.doChannelActive` read only if `!isClient`;
- Assert that channel is active when `AlpnChannelHandler` or `SniCompleteChannelHandler` are added and the read is forced;
Result:
No unnecessary read on client-side channels.
> Trigger channel read for TLS handshake only on the server-side

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReplayAccumulator.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReplayPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReplayStrategies.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReplayStrategy.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReplayStrategyBuilder.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ReplayPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherReplayTckTest.java
Motivation:
Publisher.replay provides the ability to keep state that is preserved for multiple subscribers and across resubscribes.
> Add Publisher.replay

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
`HttpClientBuildContext` takes a copy of
`DefaultSingleAddressHttpClientBuilder`. There is no need to worry that `ctx.builder.proxyAddress` can change. As the result, we can safely remove `ctx.proxyAddress`.
Modifications:
- Remove `HttpClientBuildContext.proxyAddress`;
Result:
Less code.
> Remove unnecessary `proxyAddress` from `HttpClientBuildContext`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpContextKeys.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
Motivation:
Prior to `ConnectionObserver.ProxyConnectObserver` added in #2711, the sequence of `ConnectionObserver` events was different between regular connections and connection to the proxy tunnels.
`HttpContextKeys.HTTP_TARGET_ADDRESS_BEHIND_PROXY` (#2169) was useful to distinguish when the correct callback inside `ConnectionObserver` before reporting that a new connection is ready to take traffic. After adding `ProxyConnectObserver`, there is no need in this custom key.
Modifications:
- Deprecate `HttpContextKeys.HTTP_TARGET_ADDRESS_BEHIND_PROXY` and describe what is an appropriate replacement for users;
Result:
We will be able to remove
`HttpContextKeys.HTTP_TARGET_ADDRESS_BEHIND_PROXY` in the future releases.
> Deprecate `HttpContextKeys.HTTP_TARGET_ADDRESS_BEHIND_PROXY`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/OnCompleteErrorPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/OnCompleteErrorPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherOnCompleteErrorTckTest.java
Motivation:
There are some scenarios where a stream terminating with onComplete is not expected, and translating to an error simplifies recovery.
> Add Publisher.onCompleteError

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatusException.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcProxyTunnelTest.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
- servicetalk-http-api/gradle/spotbugs/main-exclusions.xml
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConnectException.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConnectResponseException.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectChannelSingle.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyResponseException.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
Motivation:
`ProxyResponseException` is marked as `RetryableException`. However, not all response statuses are retryable. For example, it doesn't make sense to auto-retry if proxy responds with 4xx (proxy auth required, bad request, etc.).
Also, because proxy-related exceptions live in `servicetalk-http-netty`, gprc-api can not access them for better mapping into gRPC status code.
Modifications:
- Move `ProxyConnectException` from `http-netty` to `http-api`;
- Deprecate `ProxyResponseException`, introduce `ProxyConnectResponseException` instead in `http-api`;
- Use a retryable variant of `ProxyConnectResponseException` only for specific status codes from a proxy server are are intended to be retryable;
- Include Channel info in every thrown `ProxyConnectException`;
- Enhance …
> Improve exceptions thrown when an error happens during proxy `CONNECT`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/OptimizedHttp2FrameCodecBuilder.java
Motivation:
Netty 4.1.100 introduced a new feature for HTTP/2 to protect from DDoS vector (see
https://github.com/netty/netty/security/advisories/GHSA-xpw8-rcwv-8f8p) This is unknown if users of libraries that work on top of Netty may be impacted by false positives or not. For the next major release we should either remove these properties or promote them to public API.
Modifications:
- Temporarily introduce the following system properties to control underlying netty-codec-http2:
`-Dio.servicetalk.http.netty.http2.decoderEnforceMaxRstFramesPerWindow.maxConsecutiveEmptyFrames=200` `-Dio.servicetalk.http.netty.http2.decoderEnforceMaxRstFramesPerWindow.secondsPerWindow=30`
Result:
If necessary, users can control new netty options via system properties.
> Introduce tmp properties for Netty `decoderEnforceMaxRstFramesPerWindow`

- servicetalk-http-netty/build.gradle
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionClosedAfterIoExceptionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
Similar to #2675, `H2ParentConnectionContext.AbstractH2ParentConnection` should mark the `Channel` as closing on `exceptionCaught`. If there is no active `Subscriber`, it should enforce channel closure using `ChannelCloseUtils`.
In case users don't have offloading, there is a risk to retry on the same IO thread. We should notify `LoadBalancer` that this connection is closing to avoid retrying on the same connection.
Modifications:
- Invoke `parentContext.notifyOnClosingImpl()` inside `exceptionCaught` before notifying `transportError` and failing subscriber;
- Close the h2 channel if there is no active `Subscriber` to consume the error;
- Remove `H2ParentConnectionContext.hasSubscriber()` that does not seem required anymore;
- Enhance `ConnectionClosedAfterIoExceptionTest` to …
> Mark HTTP/2 connection as closing on exception caught

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
Motivation
There are cases where a TCP socket can be disconnected unexpectedly (terminated without adhering to the protocol), and when there is no interaction with the socket, the staleness will not be detected. Its commonly the case where TCP keep-alive is used as a counter measure for such cases, to force the socket to get into the right term state to reflect the actual condition.
Modifications
Changed ST default to always enable Keep-Alive socket option.
Results
Expectation is to always be able to detect stale sockets in the application space, and force streams attached to these socket to react on that condition.
> Enable Keep-Alive socket option by default

- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/CancellationTest.java
Motivation
----------
The CancellationTest#cancelOffload() is reportedly flaky and this PR attempts to solve it.
Modifications
-------------
Investigation found that it looks like on CI the sleeping of the action races with the cancellation of the service single. If the cancellation arrives before the service is executed, the thread sleep will never be triggered and so the test completes fine. If the cancellation does not arrive first, the sleep starts to happen and when the cancellation arrives afterwards the thread is interrupted as part of the cancellation which triggers the exception.
Since interrupts are expected on cancellations, this exception should be caught and ignored since it is legitimate.
Fixes #2036
> Fix Flaky CancellationTest

- servicetalk-http-netty/build.gradle
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
Motivation
----------
In a previous changeset, the HttpMessageDiscardWatchdogServiceFilter has been introduced which tries to proactively clean up orphaned/ discarded message body buffers: This works in some, but not all cases in a reliable fashion.
Modifications
-------------
Instead of trying to clean up the buffers (which might not work all the time), just WARN into the logs so users can take proactive action to fix their code.
The log level has been dropped from ERROR to WARN since it is not a fatal error but still needs to be taken seriously.
> Do not consume orphaned server response payloads, just warn

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogClientFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogClientFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
Motivation
----------
When a client makes a request and during response processing an exception is thrown, the exception bubbles up to the client but the message payload body is then not available to be consumed.
In this case, the underlying pooled connection will not be freed up and a new connection is created.
Modifications
-------------
By tracking the message payloads when responses are bubbled up through the filter chain, we can detect if an error happens and if detected the message payload body is being proactively drained.
This will free up the connection again so it can be reused by a subsequent request.
Result
------
More correct handling of message payload bodies if an exception happens during response filter processing.
> Clean up client response payloads on error to free up connections

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NewRoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/TestableLoadBalancer.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/EagerNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Motivation:
We are going to start refactoring our load balancing components
and in order to preserve the current stable form until we can build
confidence in it we're cloning RoundRobinLoadBalancer into another
class (currently identical other than name) which we can then start
to pull apart.
Modifications:
- Add a private interface TestableLoadBalancer to expose a generic
way of surfacing the current host set for tests.
- Clone RoundRobinLoadBalancer into NewRoundRobinLoadBalancer which
is currently identical to the original other than it's name.
- Thread through the option to switch round robin load balancer
implementation in the tests so we can detect regressions in the
new implementation without text-copying the tests. When we get to
the point we want to try it out we can start to …
> Clone the RR load balancer in preparation for refactoring

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
This changeset improves the javadocs for these two methods in clarifying how their behavior differs based on the number of elements and completion signal returned by the upstream Publisher.
> Improve javadocs for firstOrElse and firstOrError

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/OptimizedHttp2FrameCodecBuilder.java
Motivation:
#2728 introduces 2 properties to control Netty
`decoderEnforceMaxRstFramesPerWindow` settings:
`-Dio.servicetalk.http.netty.http2.decoderEnforceMaxRstFramesPerWindow.maxConsecutiveEmptyFrames=200` `-Dio.servicetalk.http.netty.http2.decoderEnforceMaxRstFramesPerWindow.secondsPerWindow=30`
The first property was named incorrectly, it must be `maxRstFramesPerWindow`.
Modifications:
- Add a new property: `-Dio.servicetalk.http.netty.http2.decoderEnforceMaxRstFramesPerWindow.maxRstFramesPerWindow=200`;
- Use previous `maxConsecutiveEmptyFrames` value as a fallback for backward compatibility;
Result:
Properties names are consistent with their names in Netty.
> Fix incorrect name of `decoderEnforceMaxRstFramesPerWindow` property

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/Host.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NewRoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
The RR load balancers define the selection logic for picking a member from the `Host` connection pool.
Modifications:
- Copy the old Host back into the old `RoundRobinLoadBalancer`, bringing it closer to it's original known-good state.
- Move the connection selection logic from `NewRoundRobinLoadBalancer` into `Host` making Host more of a connection pool and `NewRoundRobinLoadBalancer` less of a connection pool.
> Move selection out of NewRoundRobinLoadBalancer and into Host

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NewRoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
Motivation:
We want to be able to swap out load balancer algorithms but right
now that is in-lined in the same file as the host set management.
Modifications:
- Define the internal `HostSelector` interface.
- Extract the host selection algorithm into it's own class
`RoundRobinSelector`.
> Extract round-robin host selection from the NewRoundRobinLoadBalancer

- servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java
- servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
Motivation:
In order to trace batching, trace level logging will be helpful.
Modifications:
- Log every accumulation;
- Log every received span/list after encoding;
Result:
Easier to troubleshoot if there are any issues.
> `ZipkinReporter`: add trace logging for batching and encoded spans

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/Host.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NewRoundRobinLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/P2CSelectorTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/TestLoadBalancedConnection.java
Motivation
We have a round-robin selector but also want to support
a form of random selection. P2C is a common random
selection algorithm that gives us the ability to also distinguish
hosts based on a load metric, or score, which can help us
distribute load more evenly and avoid hosts that can be
considered outliers by a variety of mechanisms.
Modifications
- Make `Host` an interface and rename the existing version
to `DefaultHost` to make testing easier and the contract
explicit. This doesn't mean the contract won't change as we
continue to iterate.
- Add the `P2CSelector` type and it's tests.
Note: we are not yet integrating this selection algorithm into the
`NewRoundRobinLoadBalancer` which will entail a bunch of
questions around the API for doing so. That will be done as a
followup to …
> loadbalancer: Add a P2C host selector

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
Motivation:
There are some style and naming inconsistencies that can be cleaned up.
Modifications:
- rename `BaseSelector.noActiveHostsException` to `noActiveHosts`.
- Enforce constructor arguments to be non-null in `DefaultHost`.
> loadbalancer: Some style cleanups for the new LB

- servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryClient.java
- servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryUrlClient.java
Motivation:
Currently, this example shows that any 5xx response can be retryable and applies immediate retries. We should teach users in a conservative way to retry only specific status codes with exponential backoff and jitter.
Modifications:
- Retry only 429, 502, 503, 504 status codes;
- Apply exponential backoff with jitter;
Result:
Example teaches users better practices.
> Adjust `servicetalk-examples-http-retry`

- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractOffloadingTest.java
- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java
Motivation:
#2325 says that test failures are caused by
"Executor was not initialized" or `RejectedExecutionException`. This is the only test that uses `ExecutionMode.CONCURRENT` and `ExecutorExtension` for `APP_EXECUTOR_EXT` is not marked as class-level.
Modifications:
- Remove `ExecutionMode.CONCURRENT` from publisher/OffloadingTest;
- Use `setClassLevel` for all static `APP_EXECUTOR_EXT` in `AbstractOffloadingTest`;
- Adjust names of `ParameterizedTest`(s);
Result:
Resolves #2325.
> Fix flaky publisher/OffloadingTest

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcProxyTunnelTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingSingleAddressHttpClientBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpContextKeys.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConfig.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConfigBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConnectException.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConnectResponseException.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectChannelSingle.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectLBHttpConnectionFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReadOnlyHttpClientConfig.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMultiProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
Motivation:
After https://github.com/apple/servicetalk/pull/2697 moved HTTP proxy `CONNECT` logic before user-defined
`ConnectionFactoryFilter`s, users lost the ability to intercept
`CONNECT` requests for the purpose of adding custom headers, like auth,
tracing, etc.
Modifications:
- Introduce `ProxyConfig` and `ProxyConfigBuilder` in `http-api` that
can be used to provide additional options for proxy behavior;
- Add `SingleAddressHttpClientBuilder.proxyConfig(...)` overload that
takes `ProxyConfig`;
- Deprecate pre-existing `SingleAddressHttpClientBuilder.proxyAddress()`
method, recommend switching to new API;
- Enhance `HttpsProxyTest` to verify that new API can be used to send
`Proxy-Authorization` header;
Result:
Users have explicit API to alter HTTP `CONNECT` request headers, if …
> Add initializer API for headers of HTTP proxy CONNECT request

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/OptimizedHttp2FrameCodecBuilder.java
Motivation:
Netty 4.1.100 introduced a new feature for HTTP/2 to protect from DDoS vector, and we added system properties to control its settings in #2728. In version 4.1.101 Netty disabled this protection for clients by default, but due to how we use our system properties, that change won't automatically apply to ServiceTalk.
Modifications:
- `OptimizedHttp2FrameCodecBuilder.decoderEnforceMaxRstFramesPerWindow` now considers `isServer` flag to decide if the inferred values should be applied or not;
Result:
`decoderEnforceMaxRstFramesPerWindow` is enabled only for HTTP/2 servers.
> Disable `decoderEnforceMaxRstFramesPerWindow` for HTTP/2 clients

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/P2CSelectorTest.java
Motivation:
We should try to get existing connections from the non-preferred host if 
we fail to get connections from the preferred.
Modifications:
- adjust the selection logic
- add a test
- don't perform multiple selection attempts if there are only two hosts
- remove unnecessary `@Nullable` annotation since the method never returns null
> loadbalancer: follow ups to P2C selector logic

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
Motivation:
We've seen CI failures on this test. It looks like it's probably just a short timeout.
Modifications:
- Increase the timeout in CI to 5 seconds.
Result:
What is the result of this change?
> Increase timeout in flaky HttpMessageDiscardWatchdogServiceFilterTest

- servicetalk-grpc-utils/build.gradle
- servicetalk-grpc-utils/gradle/spotbugs/test-exclusions.xml
- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java
- servicetalk-grpc-utils/src/test/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserverTest.java
- servicetalk-http-utils/build.gradle
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserverTest.java
Motivation:
LoggingHttpLifecycleObserver and LoggingGrpcLifecycleObserver included a bug that prevented request exceptions to be logged.
Modifications:
- Update LoggingHttpLifecycleObserver and LoggingGrpcLifecycleObserver to include the Throwable as the last argument in the logger call
- Add tests for the two components
Result:
The Logger object will be called with a Throwable as last argument instead of null in case of request errors. Most logging frameworks implementing slf4j will print the full stacktraces in this situation.
> Fix bug in http/grpc logging observer that prevented request Throwables to be logged

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/Host.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NewRoundRobinLoadBalancer.java
Motivation:
Our current host update process is quadratic both in time and space due to
searching for hosts using list iteration and performing a COW for each entry
of the SD event set.
Modifications:
Make a Map<Address, SDEvent>. This lets us iterate through existing events
with O(M+N) complexity  instead of O(M*N) complexity. As a bonus, we can
now easily detect if we get multiple SD events for the same address in a batch.
Result:
We should see slightly worse performance in the small M*N case but
dramatically better performance in the large case. Since SD events shouldn't
be terribly common and making a hashmap is cheap relative to the total cost
of a SD update, this is the safer tradeoff.
> loadbalancer: better asymptotic behavior of host updates

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
Motivation:
Despite increasing the timeout, the test in HttpMessageDiscardWatchdogServiceFilterTest is still flaky and we're not sure why.
Modifications:
- emit the entire output that was missing the expected log entry.
Result:
It should be a bit easier to debug the cause of the flakyness.
> Enhance HttpMessageDiscardWatchdogServiceFilterTest output

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
Motivation:
We want to use P2C with the new load balancer system but it currently has 'RoundRobin' in the name.
Modifications:
- rename NewRoundRobinLoadBalancer to DefaultLoadBalancer
- add the HostSelector as a constructor param to DefaultLoadBalancer
- rename some symbols in it to reflect their units
> loadbalancer: rename NewRoundRobinLoadBalancer to DefaultLoadBalancer

- gradle.properties
Motivation:
There have been version bumps and we can now
upgrade our netty and grpc dependencies.
Modifications:
- bump netty from 4.1.100.Final to 4.1.101.Final
- bump netty io_uring from 0.0.23.Final to 0.0.24.Final
- bump grpc from 1.56.1 to 1.59.1
Fixes https://github.com/apple/servicetalk/issues/2585.
> Bump netty and grpc dependencies

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/SequentialExecutor.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/SequentialExecutorTest.java
Motivation:
We use an atomic field and CAS operations to manage concurrency in the DefaultLoadBalancer. Because the CAS operation has to succeed before changes have taken affect, it's not easy to make events coordinate with that model. A few examples:
- it will be awkward to add an event observer to the load balancer since we may end up re-doing server-set updates if we fail a CAS.
- there is also a question of ordering of observer events since the observer interactions may get out of order wrt the state mutations that induced them.
- we can't currently send an LOAD_BALANCER_NOT_READY_EVENT when the last host expires because we would risk the event racing with SD updates that triggered related events.
CAS failures may also be relatively common due to re-entrance: SD update events can …
> loadbalancer: Use a sequential execution concurrency model in DefaultLoadBalancer

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogClientFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
- servicetalk-log4j2-mdc-utils/src/testFixtures/java/io/servicetalk/log4j2/mdc/utils/LoggerStringWriter.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilterTest.java
- servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java
- servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java
- servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java
Motivation:
We have seen some flakyness in HttpMessageDiscardWatchdogServiceFilterTest that may be related to thread safety for the test log appender. Specifically,
- The sink, a StringWriter, is globally shared so it can be reset by concurrently running tests.
- The underlying StringWriter itself isn't thread safe and it's possible for it to be concurrent written to and read from.
Modifications:
- Make a new (thread safe) StringWriter for each thread. Based on the usage pattern for the LoggerStringWriter methods this should have the effect of having a unique writer per test.
- Make a thread-safe proxy for the StringWriter so it's safe to write and read from concurrently.
Closes https://github.com/apple/servicetalk/issues/2756. (hopefully)
> mdc-utils: Make LoggerStringWriter thread friendly

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientResolvesOnNewConnectionTest.java
Motivation:
When `DiscoveryStrategy.ON_NEW_CONNECTION` mode is used, LB will have a single unresolved entry, the actual IP address will be resolved by a `ConnectionFactory`. We should not run health-checking logic in this case because it can lead to "all unhealthy" state. We should run a new connection attempt all the time and fail with an exception from transport.
Modifications:
- Configure a custom `loadBalancerFactory` on a client builder when `DiscoveryStrategy.ON_NEW_CONNECTION` is used;
Result:
No health-checking for an unresolved address when
`DiscoveryStrategy.ON_NEW_CONNECTION` is used.
> Disable RRLB health-checking for `DiscoveryStrategy.ON_NEW_CONNECTION`

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
The generic types that represent the resolved address and the real type of the connection are generics to the _method_ of LoadBalancingPolicy.buildSelector. This means the the policy must support all types of addresses and connections making it more difficult to specialize.
Modifications:
Move the generics from the buildSelector method to the LoadBalancerPolicy type itself.
> loadbalancer: Change generics of LoadBalancerPolicy

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingConnectionFactoryTest.java
Motivation:
PR #2575 replaced colons with dots, but we may also see percentage-sign characters – `%` – in the IPv6 text representation, which would give us errors like the following:
```
java.security.cert.CertificateException: Illegal given domain name: localhost-0.0.0.0.0.0.0.0%0
at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:193)
at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:103)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:429)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted …
```
> Additional fix for IPv6-derived SNI hostnames

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryStrategies.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RetryStrategiesTest.java
Motivation:
If you pass in a jitter of 0 for the retry strategies with delta delay you'll get an `IllegalArgumentException` thrown by the `Random.nextLong(lower, upper)` method because the lower and upper are the same value. This is because the upper bound argument is non-inclusive.
Modifications:
Add 1 to each call to extend the range by 1 nanosecond and make the full delay range selectable. We also do this in the case of the `*FullJitter` methods to make the full delay an option instead of being limited to `delay - 1ns`.
Result:
Less illegal argument exceptions and (technically, although admittedly not practically important) correct delay ranges.
> concurrent-api: fix IllegalArgumentExcetion for zero jitter in RetryStrategies

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/SequentialExecutor.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LoadBalancerTestScaffold.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/P2CSelectorTest.java
Motivation:
For algorithms like weighted round robin and random we need to
build some data structures for each unique host set.
Modifications:
- Add a `.rebuild(List<Host>)` method to the `HostSelector`
interface. This lets a host potentially rebuild data structures it
needs to properly balance but only when there is a host set update.
- Add a `.isHealthy()` method to `HostSelector`. This cleaned up
some questions about which host list is used and may also be
helpful for future composition of selectors.
- Cleanup some thread safety considerations in DefaultLoadBalancer.
> loadbalancer: HostSelector can be rebuilt each time the DefaultLoadBalancer gets a host set update

- gradle.properties
Motivation:
To validate it works as expected with Netty 4.1.103.Final. This is a test dependency anyway.
> Revert grpc-java back 1.59.1 -> 1.56.1

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
Most observers have methods that start with 'on' for event methods. That didn't happen with LoadBalancerObserver.
Modifications:
- Fix the observer method names.
- Use the `onNoActiveHostsAvailable` event.
> loadbalancer: fix observer name pattern

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1ProtocolConfigBuilder.java
Motivation:
`H1ProtocolConfigBuilder` does not validate incoming int parameters.
> Add validation for `H1ProtocolConfigBuilder` setters

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/NormalizedTimeSourceExecutor.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/NormalizedTimeSourceExecutorTest.java
Motivation:
The time source normalizes itself using nanoseconds regardless
of what units the user is requesting.
Modifications:
- Always get the current time in nanos, normalize, then convert to
the desired units.
Result:
Better behavior if you request anything other than nanos.
> loadbalancer: fix NormalizedTimeSourceExecutor to work with units other than nanos

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
The HostSelector currently operates on a List<Host> which doesn't allow us to pass in lists of refined types. This means we need to make copies of lists just to pass them through if implementations want to store the refined types.
Modifications:
- Make the HostSelector operate on a List<? extends Host>. This continues to give implementations the ability to read the list entries, which is all it should do, while allowing users of the HostSelector to pass in a list of a refined type.
> loadblancer: HostSelector List variance

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLatencyTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LatencyTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RootSwayingLeafLatencyTracker.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LatencyTrackerTest.java
Motivation
Support latency tracking APIs and default EWMA based decay-able solutions to allow implementation of richer L7 circuit breakers for the load balancers.
Modification
Introduced the LatencyTracker API along with a default implementation.
> Latency tracking utilities to support LB L7 breakers

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
Motivation:
We currently use the ConnectionFactory in two places in DefaultHost:
- creating new connections
- health checking
Each of them has to go through the trouble of trying to add the newly
created connection to the connection pool and making sure the state
remains coherent.
Modifications:
DefaultHosts health checking feature now uses the `Host.newConnection`
method instead of using the factory directly.
Results: 
Using the `Host.newConnection(..)` method lets us reuse the connection
management properties already in `DefaultHost.newConnection`. It also
makes the path to extracting the health check from `DefaultHost` a bit
easier to envision.
> loadbalancer: Simplify ConnectionFactory usage in DefaultHost

- .github/workflows/ci-netty-snapshot.yml
We are trying to debug a case where it appears that the Netty snapshot workflow does not always run with the latest Netty snapshot. In order to debug, print the version that is being used so we can understand better what might be happening.
> Add a workflow step to print the Netty snapshot that is being used

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslCipherSuiteFilterTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfigBuilder.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SslConfig.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
Motivation:
Sometimes users can configure ciphers that are not supported by current `SSLEngine`. As a result, they are getting a runtime exception.
Modifications:
- Add new API `SslConfig.cipherSuiteFilter()` that allows users to configure how Netty should consume the configured ciphers: take them all as-is or filter out unsupported ciphers from the passed list;
- Test new behavior;
Result:
Users can configure `SslConfig` to filter out unsupported ciphers.
> Add `SslConfig.cipherSuiteFilter()`

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
Based on initial analysis the ClientInvokingThreadRecorder's state gets written and read from multiple threads, but not all of it is properly thread-safe. The invokingThreads and errors use thread-safe datastructures, but the offloadPoints do not.
Since the offloadPoints are on the critical path for the flaky test failures, let's start by making them thread safe and check if the errors still show up.
If they still persist, there might be more coordination needed between the recording and checking threads as well.
> ClientEffectiveStrategyTest: Attempt at fixing flakyness

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HealthChecker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HealthCheckerFactory.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HealthIndicator.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RequestTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RootSwayingLeafRequestTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultRequestTrackerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
There are a few places that can be tightened up in DefaultLoadBalancer.
Modifications:
- Fix some copyright dates that went stale over the new year
- Add some missing type parameters to avoid using raw types
- Make RequestTracker method names more uniform
- Cleanup some comments
Result:
Tighter code.
> loadbalancer: Some follow up feedback for DefaultLoadBalancer

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java
Motivation:
HTTP/2 stream/child channel use cases don't disable autoRead explicitly. This means we may read and queue more data than desirable.
Modifications:
- Disable auto read for h2 stream/child channels.
> h2: disable auto read for stream channels

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/ErrorClass.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RequestTracker.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RootSwayingLeafRequestTracker.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultRequestTrackerTest.java
Motivation:
RequestTracker has three observer methods: `onSuccess`, `onCancel`, and `onError`. onCancel is really a special case of `onError` but it can be helpful to distinguish them at times which leads to the more general problem: it is often helpful to know what kind of error it was so we can establish the origin.
Modifications:
- Add the `ErrorClass` enum for classifying `RequestTracker` errors.
- Consolidate the `onCancel` method into the `onError` method by having a `CANCELLED` variant of the `ErrorClass` enum.
- Also thread through an optional `Throwable` on the `onError` method so lower levels can log the specific cause, if it exists.
Result:
Less methods and more information about the origin of errors. This should also let us extract the L4 health checker from the DefaultHost …
> loadbalancer: Add the ErrorClass enum and use it in RequestTracker

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
Motivation:
The HttpMessageDiscardWatchdogServiceFilterTest test remains flaky. It appears that for the failing cases the output is totally empty. Maybe this means the logger wasn't initialized when the tests were actually ran.
Modifications:
- Improve the failing test output a bit more by bracketing the output with signal lines.
- Have the initialization of the test spin until we can verify that we can get some log output by injecting a known log and waiting for it to appear.
> servicetalk-http-netty: attempt to fix HttpMessageDiscardWatchdogServiceFilterTest

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/HealthChecker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/HealthCheckerFactory.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthChecker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthCheckerFactory.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/MockLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsHealthCheckerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsHealthIndicatorTest.java
Motivation:
The current HostObserver API requires one to pass in the ResolvedAddress on each callback. This means that every place we want to observer events also needs to know the address which can be a pain.
Modifications:
- Drop the type parameter from `HostObserver`
- Make `LoadBalancerObserver` take the address as a parameter of the `hostObserver(..)` method
- Modify the `HealthChecker` interfaces to take the `HostObserver` during construction of the associated `HealthIndicator`
> loadbalancer-experimental: HostObserver shouldn't need a type param

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthChecker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsHealthIndicatorTest.java
Motivation:
We currently set the ewma lifetime to 1 nanosecond in the XdsHealthTracker and it's not configurable.
Modifications:
- Add a lifetime field to the OutlierDetectorConfig type
- Give it a default of 10 seconds in the Builder
> loadbalancer-experimental: Thread through the EWMA half life in XdsHealthTracker

- gradle.properties
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
Motivation:
The tests are super flaky making it almost impossible to get a clean CI run. The problem was in netty and has been fixed but we're waiting on a release.
Modifications:
- Disable the flaky tests and add some notes to the netty dependency
Relates to #2117.
> http-netty: Disable some GraceulConnectionClosureHandling tests

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthCheckerFactory.java
Motivation:
There were a few more interfaces that need to be public before things are really usable.
Modifications:
Make them public.
> loadbalancer-experimental: make more interfaces public

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
Motivation:
We want to let users add custom observer logic but the interface is private.
Modifications:
Make the interface public.
> loadbalancer-experimental: Make LoadBalancerObserver public

- servicetalk-loadbalancer-experimental/README.adoc
Motivation:
We want to provide some documentation for the intended purpose, capabilities, etc for DefaultLoadBalancer.
Modifications:
- Add a readme.adoc to servicetalk-loadbalancer-experimental
> loadbalancer-experimental: Add some documentation for DefaultLoadBalancer

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultRequestTrackerTest.java
Motivation:
DefaultRequestTracker is intended to track how long requests are
taking but right now it can only add data once it gets a response.
As requests start to pile up we get a multiplicative effect but
we don't consider how long requests have remained outstanding.
Modifications:
- Keep track of how long a request has been pending by marking
its start time and considering it when computing score.
- Switch to a StampedLock and adjust our score method so we
can take a read-lock on the scoring path.
- Make our counters owned by the StampedLock: we have to take
the write lock again on `beforeRequestStart()` method but it
should be the same cost as atomics in the un-contended case.
Result:
We're more sensitive to sudden failures.
> loadbalancer-experimental: track the length of outstanding requests

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelegatingServiceDiscoverer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
`DelegatingServiceDiscoverer` is a helpful utility to reduce boilerplate when users need to implement a filter for `ServiceDiscoverer`. We provide "delegate" classes for other use-cases, would be helpful to have one for `ServiceDiscoverer` too.
Modifications:
- Add `io.servicetalk.client.api.DelegatingServiceDiscoverer`;
- Use new utility instead of internal variant inside `DefaultSingleAddressHttpClientBuilder`;
Result:
Easier for users to implement a filter for `ServiceDiscoverer`.
> Add `DelegatingServiceDiscoverer` to client-api

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientResolvesOnNewConnectionTest.java
Motivation:
Users who need multi-address client with
`DiscoveryStrategy.ON_NEW_CONNECTION` and a custom `ServiceDiscoverer`
implementation need a new overload, because this strategy does not allow
changing `ServiceDiscoverer` later.
Modifications:
- Add `HttpClients.forMultiAddressUrl(String, ServiceDiscoverer,
DiscoveryStrategy)` overload;
- Add a test case in `HttpClientResolvesOnNewConnectionTest` that
verifies the new overload can be used to customize `ServiceDiscoverer`;
Result:
Easier can customize `ServiceDiscoverer` when they need a multi-address
client with `DiscoveryStrategy.ON_NEW_CONNECTION`.
> Add `HttpClients.forMultiAddressUrl()` overload with `ServiceDiscoverer`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executors.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscoverers.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/InternalServiceDiscoverers.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ResolvingConnectionFactoryFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ForResolvedAddressTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientResolvesOnNewConnectionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
Motivation:
If users need to wrap a `ServiceDiscoverer` to apply a filtering logic, currently they have to create their own instance of DNS `ServiceDiscoverer`. As a result, their use-cases uses separate DNS cache, while other use-cases in the classpath that do not require wrapping use global instance and share DNS cache.
Modifications:
- Add 2 new static methods in `DnsServiceDiscoverers`: `globalARecordsDnsServiceDiscoverer()`, and
`globalSrvRecordsDnsServiceDiscoverer()`;
- Remove similar instances from `GlobalDnsServiceDiscoverer`, rename it to `InternalServiceDiscoverers`;
Result:
Users can grab a global DNS SD instance and apply wrapping/filtering if necessary.
> Expose global A/AAAA and SRV DNS `ServiceDiscoverer` instances

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
Motivation:
`DefaultLoadBalancerFactory` must implement `requireOffloads()` method to signal ST that it does not block.
> loadbalancer-experimental: disable offloading

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
Motivation:
japicmp report:
```
***! MODIFIED CLASS: PUBLIC FINAL io.servicetalk.loadbalancer.RoundRobinLoadBalancerFactory  (not serializable)
===  CLASS FILE FORMAT VERSION: 52.0 <- 52.0
===  UNCHANGED SUPERCLASS: java.lang.Object (<- java.lang.Object)
---! REMOVED METHOD: PUBLIC(-) io.servicetalk.client.api.LoadBalancer newLoadBalancer(io.servicetalk.concurrent.api.Publisher, io.servicetalk.client.api.ConnectionFactory, java.lang.String)
```
> Restore unintentionally removed `RoundRobinLoadBalancerFactory` API

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
It failed 3 times in a row for snapshot build and is blocking a release.
Related to #2756
> Disable flaky `HttpMessageDiscardWatchdogServiceFilterTest`

- scripts/release.sh
Motivation:
Sometimes it's required to re-run the release script if there was an error with a previous build. In this case, gh-pages are already generated and the 2nd run does not produce any new output. Script fails with "nothing to commit" message.
Modifications:
- Commit gh-pages only if there is a non-empty diff;
Result:
release.sh script does not fail if there are no updates for gh-pages.
> release.sh: skip if nothing to commit for gh-pages

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
Motivation:
An assert is worth a thousand comments.
Modifications:
Replace the comment about holding the lock in DefaultRequestTracker with an assert.
> loadbalancer-experimental: assert a lock instead of comment about it

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilter.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilterTest.java
Motivation:
The ContentEncodingHttpServiceFilter is meant to remove the `Content-Length` header if it does compression, because any such header from earlier stages will be incorrect after compression. An incorrect `Content-Length` header will then cause down-stream clients to be confused and potentially stall, timeout, or produce an unexpected close error, when they don't receive their promised number of bytes (most likely fewer than promised, due to compression).
Modifications:
The ContentEncodingHttpServiceFilter incorrectly removed the `Content-Length` header from the _request_ object, and this has been fixed so it now correctly removes the header from the _response_ object. There was a test for this behavior, but the test wasn't actually hitting this code because it used a client that …
> Fix Content-Length header removal after content compression

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
The LoadBalancerFactory has methods that are generic in type T extends LoadBalancedConnection which are deprecated. The generic type is infectious and doesn't serve a concrete purpose, thus why the methods are deprecated.
Modifications:
- drop support for the deprecated factory methods
- drop the generics that were required in the LoadBalancerPolicy interface
Result:
Cleaner code.
> loadbalancer-experimental: remove the generic load balancer factory methods

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/MockLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
The observers almost never care what the concrete type is and only use the resolved address via its `.toString()` and comparison operations.
Modifications:
Remove the type parameter.
Result:
Easer to use LoadBalancerObserver.
> loadbalancer-experimental: Remove type param from LoadBalancerObserver

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEmptyPayloadTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
Motivation:
CONNECT requests must only have an authority-form header per the spec (https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.3) but we have a
few tests that generate a series of tests cases that are setting relative form
request targets with that HTTP method.
Modifications:
Patch those tests to use authority form when generating requests.
> servicetalk-http-netty: fix some tests using relative request targets with CONNECT requests

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
Motivation:
There is an unused import in ContentHeadersTest that breaks checkstyle.
Modifications:
Remove it.
> http-netty: remove unused import breaking checkstyle

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
Motivation:
We want to ensure the default configuration for different HostSelector implementations is consistent.
Modifications:
- Centralize the definition of the default fail-open policy.
> loadbalancer-experimental: centralize the default value of LoadBalancingPolicy fail open

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorFactory.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetectorFactory.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsOutlierDetectorAlgorithmTest.java
Motivation:
We renamed the HealthChecker interface to OutlierDetector but didn't catch all the symbol names so there are still a few floating around in the code.
Modifications:
Remove them.
Result:
Less confusion.
> experimental-loadbalancer: rename 'healthChecker' symbols

- .github/workflows/ci-netty-snapshot.yml
Trying to understand if the env variable is being picked up as expected. We expect to see this step print out the latest SNAPSHOT but instead it is printing the latest "Final" version. This works in a local terminal so this step will help us determine whether the issue is with the gradle script of the action itself.
> Add debug echo statement in netty snapshot action

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/OptionalSslTest.java
Motivation
----------
The initial support for Optional TLS did only allow insecure connections if either H1 or H2 is enabled, but not protocols at the same time. This is a limitation when used together with ALPN on secure connections and can be improved.
Modifications
-------------
This changeset makes sure that ALPN support still works when optional TLS is configured. In the case where both H1 and H2 are enabled on the server side and a insecure connection has been negotiated, the code now falls back to H1 support only. This means that h2c cleartext upgrades are not supported, but they haven't been supported inside ServiceTalk anyways.
Result
------
Best possible ALPN support at the moment in combination with Optional TLS.
> Optimize protocol negotiation with Optional TLS

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpServerConfigTest.java
Motivation
----------
This changeset improves the set and reset functionality for sslConfigs inside the `TcpServerConfig`.
Modifications
-------------
After this change, the validation and defaults are done consistently and all converge in a central method. Tests are added to verify the intended functionality (especially around reset behavior).
> Enhance and test sslConfig reset in TcpServerConfig

- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ServiceLoaderUtils.java
Motivation:
Users should always see what `ServiceLoader` providers were available in the classpath and loaded. We should log it at `INFO` level.
Modifications:
- If `ServiceLoader` providers are loaded, log them at `INFO` level;
Result:
Users can always see if their classpath has `ServiceLoader` providers.
> Always log registered `ServiceLoader` providers at INFO level

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
The LoadBalancingPolicy interface suffers from the same problems that the OutlierDetectorFactory did, namely that it's more powerful than users need.
Modifications:
- Make the LoadBalancingPolicy an abstract class with package private constructor to let us control its proliferation for now.
Result:
A more constrained API. We can always open it up more later if we want to.
> loadbalancer-experimental: tighten up load balancing policy

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsOutlierDetectorTest.java
Motivation:
When cancelling the whole xDS outlier detector it first enters the sequential executor then has each child indicator cancel itself. It does this synchronously and then checks that the indicator set is empty. This doesn't work like that because each indicator tries to bounce itself through the sequential executor, so it won't actually be empty until after the method exits.
Modifications:
- Use the `sequentialCancel()` method instead: we know that we're in the sequential executor already.
- Add some tests.
> loadbalancer-experimental: fix broken assert in XdsOutlierDetector

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryStrategies.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RepeatStrategiesTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RetryStrategiesTest.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/RandomUtils.java
- servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/RandomUtilsTest.java
Motivation:
Many locations where we have a notion of jitter we require the
jitter to be non-zero. This is because we use
`ThreadLocalRandom.nextLong(lower, upper)` where with a zero
jitter the bounds are the same and we get an IAE.
Modifications:
- Add 1 to the upper bound most of our usages of `.nextLong(l,u)`
to account for the non-inclusive upper bound.
> Clean up some random number generation related to jitter

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilderTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
Motivation:
In #2888 we made it possible to have a zero length jitter but in a couple places we continue to assert the jitter is positive despite it being allowed to be 0.
Modifications:
- Fix a couple examples of this.
Result:
More jitters are allowed to be 0.
> Turn some jitter related ensurePositive to ensureNonNegative

- servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldExceptionMapper.java
- servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java
Motivation:
Add an example of how error mapping can be done with jax-rs to help users debug development and/or not issues.
Results:
Better example base
> Example with jax-rs error mapper

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
Experiments show that majority of ServiceDiscovery queries take only a few milliseconds. Jitter up to 8 seconds causes too long delay before the next retry. Based on observed numbers we can lower the value down to 2 seconds.
> Lower initial delay for ServiceDiscovery retries from 8 to 2 seconds

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
256 seconds seems like quite a long delay for retrying SD errors. We agreed to cut it down in half.
Follow-up for #2891
> Lower max delay for ServiceDiscovery retries from 256 to 128 seconds

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpClientConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
Motivation:
japicmp.sh flagged it like that:
```
Comparing binary compatibility of servicetalk-tcp-netty-internal-0.42.43-SNAPSHOT.jar against servicetalk-tcp-netty-internal-0.42.42.jar ***! MODIFIED CLASS: PUBLIC FINAL io.servicetalk.tcp.netty.internal.ReadOnlyTcpClientConfig  (not serializable)
===  CLASS FILE FORMAT VERSION: 52.0 <- 52.0
===  UNCHANGED SUPERCLASS: io.servicetalk.tcp.netty.internal.AbstractReadOnlyTcpConfig (<- io.servicetalk.tcp.netty.internal.AbstractReadOnlyTcpConfig)
---! REMOVED METHOD: PUBLIC(-) SYNTHETIC(-) BRIDGE(-) io.servicetalk.transport.api.SslConfig sslConfig()
***! MODIFIED CLASS: PUBLIC FINAL io.servicetalk.tcp.netty.internal.ReadOnlyTcpServerConfig  (not serializable)
===  CLASS FILE FORMAT VERSION: 52.0 <- 52.0
===  UNCHANGED SUPERCLASS: …
```
> Restore binary compatibility for `AbstractReadOnlyTcpConfig` impls

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscoverer.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscovererEvent.java
Motivation:
The ServiceDiscoverer API and the interpretation of the events is a little tough to find.
Modifications:
- Move the api interpretation to a more prominent place.
- Add some cross references.
- Add an example.
Result:
What is the result of this change?
> client-api: add an exmaple of how to use the ServiceDiscoverer API

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RichServiceDiscovererEvent.java
Motivation:
If we're going to use priority groups and weights we need a way of
sending that information down the load balancers.
Modifications:
Make a custom event in loadbalancer-experimental that carries that
priority information.
> loadbalancer-experimental: add a ServiceDiscovererEvent to carry weight and priority

- servicetalk-examples/http/defaultloadbalancer/src/main/java/io/servicetalk/examples/http/defaultloadbalancer/DefaultLoadBalancerClient.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CacheConnectionHttpLoadBalanceFactoryTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultHttpLoadBalancerProvider.java
Motivation:
There is nothing netty specific about DefaultHttpLoadBalancerFactory
but it lives in the servicetalk-http-netty package.
Modifications:
- Copy the class to the http-api package.
- Deprecate the http-netty version and forward logic to the http-api
implementation.
- Fix usages in servicetalk.
> Move DefaultHttpLoadBalancerFactory to http-api

- servicetalk-loadbalancer-experimental/license/LICENSE.grpc-java.txt
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/P2CSelectorTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinSelectorTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/SelectorTestHelpers.java
Motivation:
We want to support weighted but don't in the round-robin
HostSelector.
Modifications:
Add weight support to round-robin using the static stride
algorithm common to the grpc libraries.
> loadbalancer-experimental: add support for weights in round robin

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DelegatingDnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsNameResolverTimeoutException.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsResolverAddressTypes.java
- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererBuilder.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
- servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/TestRecordStore.java
Motivation:
The existing `DnsServiceDiscovererBuilder.queryTimeout` is applied per each UDP/TCP query. If resolution requires multiple CNAME resolutions, retries on a different NS server, or applies a list of search domains, the total time is not capped. As a result, resolution can take significantly longer than originally anticipated.
Modifications:
- Add `DnsServiceDiscovererBuilder.resolutionTimeout` option that can be used to cap total resolution duration with default value set to `2 x queryTimeout`;
- Add tests for `queryTimeout` and `resolutionTimeout`;
Result:
Users can configure the total resolution timeout.
> `DnsServiceDiscoverer`: add total resolution timeout

- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/AbstractTrafficResilienceHttpFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrackPendingRequestsHttpFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilter.java
Motivation:
1. Align naming with `TrafficResilienceHttpClientFilter` and `TrafficResilienceHttpServiceFilter`.
2. Don't call to `circuitBreakerPartitions` function if `CapacityLimiter` drops the request.
> `AbstractTrafficManagementHttpFilter`: rename and defer breaker prtns

- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerProviderConfig.java
Motivation:
We unnecessarily pass in and set a Properties in the DefaultLoadBalancerProviderConfig constructor that is only used in the constructor. This doesn't buy anything but noise.
Modifications:
Just use the System.getProperty and make methods static.
> loadbalancer-experimental-provider: use System.getProperty directly

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
There are use-cases when users need to perform an action before the retry, like updating meta-data or logging/metrics. Because all retry functions return `BackoffPolicy`, it's still not known inside the function of `BackoffPolicy` will retry or not because of the retry counts limit.
Modifications:
- Add `RetryingHttpRequesterFilter.Builder.onRequestRetry(BiConsumer)` that users can use to intercept every retry attempt;
- Test that the new callback works for request retries;
Result:
Users can see when the retry actually happens, after backoff time.
If there will be a similar use-case for `reserveConnection` in the future, we will add a separate callback.
> `RetryingHttpRequesterFilter`: add on request retry callback

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelayedRetry.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelayedRetryException.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
- servicetalk-traffic-resilience-http/build.gradle
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/DelayedRetryRequestDroppedException.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/RetryableRequestDroppedException.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java
Motivation:
Currently, `servicetalk-traffic-resilience-http` module must define `servicetalk-http-netty` as API dependency only to access `RetryingHttpRequesterFilter.DelayedRetry` interface. This can be avoided if we promote this interface to `servicetalk-client-api`.
Modifications:
- Introduce `io.servicetalk.client.api.DelayedRetry` interface;
- Deprecate `io.servicetalk.http.netty.RetryingHttpRequesterFilter.DelayedRetry`;
- Introduce `io.servicetalk.http.netty.RetryingHttpRequesterFilter.Builder.retryDelayedRetryExceptions(BiFunction)`;
- Deprecate `io.servicetalk.http.netty.RetryingHttpRequesterFilter.Builder.retryDelayedRetries(BiFunction)`;
- Update `DelayedRetryRequestDroppedException` to implement `io.servicetalk.client.api.DelayedRetry` instead of …
> Move `DelayedRetry` to `servicetalk-client-api`

- servicetalk-data-jackson-jersey3-jakarta10/build.gradle
- servicetalk-data-jackson-jersey3-jakarta9/build.gradle
- servicetalk-data-protobuf-jersey3-jakarta10/build.gradle
- servicetalk-data-protobuf-jersey3-jakarta9/build.gradle
- servicetalk-http-router-jersey3-jakarta10-internal/build.gradle
- servicetalk-http-router-jersey3-jakarta10/build.gradle
- servicetalk-http-router-jersey3-jakarta9-internal/build.gradle
- servicetalk-http-router-jersey3-jakarta9/build.gradle
- servicetalk-http-security-jersey3-jakarta10/build.gradle
- servicetalk-http-security-jersey3-jakarta9/build.gradle
Motivation:
Not all tasks were correctly disabled.
Modifications:
- Disable by task type;
Result:
All unnecessary tasks should be disabled for jakarta modules.
> Disable all quality tasks for jakarta modules

- servicetalk-examples/http/defaultloadbalancer/src/main/java/io/servicetalk/examples/http/defaultloadbalancer/DefaultLoadBalancerClient.java
- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerProviderConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/EagerNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/EagerP2CLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LingeringNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LingeringP2CLoadBalancerTest.java
Motivation:
- More detail could be provided for the P2C and RR `failOpen` configuration option since it might not be clear what fail-open mean in that context.
- We could use some helpers to make the different policies more discoverable.
Modifications:
- Adjust the docs for `.failOpen` to add more detail.
- Add LoadBalancerPolicies to aid discoverability of load balancer policies
> loadbalancer-experimental: adjust load balancer policy docs and helpers

- gradle.properties
Motivation:
The previous snapshot version was incorrect.
Modifications:
Fix it.
> Preparing for 0.42.45-SNAPSHOT development

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
Motivation:
Now that 0.42.44 is released we can remove the deprecated API's.
This includes making some LoadBalancingPolicy classes package
private and removing their internal builders.
Modifications:
Remove the deprecated API's.
> loadbalancer-experimental: remove deprecated API's

- servicetalk-examples/http/defaultloadbalancer/src/main/java/io/servicetalk/examples/http/defaultloadbalancer/DefaultLoadBalancerClient.java
- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerProviderConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/EagerNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/EagerP2CLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LingeringNewRoundRobinLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LingeringP2CLoadBalancerTest.java
Motivation:
The naming of LoadBalancerPolicies is inconsistent with what it builds which are `*LoadBalancingPolicyBuilder`s.
Modifications:
Rename `LoadBalancerPolicies` to `LoadBalancingPolicies`.
> loadbalancer-experimental: rename LoadBalancerPolicies to LoadBalancingPolicies

- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultHttpLoadBalancerProvider.java
- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserverFactory.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
We already have a standard resource identifier for use when logging load balancer concerns: lbDescrption. However, we don't use that for the LoadBalancerObserver type because we don't know it on construction.
Modifications:
- Change the LoadBalancerBuilder to take a factory of LoadBalancerObservers which will consume the lbDescription during load balancer construction.
- Deprecate the older API for a release cycle.
Result:
Better logging.
> loadbalancer-experimental: thread lbDescription into the LoadBalancerObserver

- servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/api/DefaultHttpHeadersNameValidationBenchmark.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeaders.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMethod.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
- servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/IllegalCharacterException.java
> Enhance header name validation exception message

- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
Motivation:
10 seconds feels like too high value to hold a connection attempt by waiting for TLS handshake to complete. Because TLS handshake happens before ST writes a request, it's always marked as `RetryableException` and is retried up to 3 times.
Modifications:
- Reduce `DEFAULT_HANDSHAKE_TIMEOUT` from 10 to 5 seconds;
Result:
Less wait time for TLS handshake process that hangs longer than expected.
> Reduce default TLS handshake timeout from 10 to 5 seconds

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Uri3986.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/Uri3986Test.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
Motivation:
`HttpRequestMetaData#scheme()` javadocs state the result will be lowercase, but this is not always the case because `Uri3986` parses the scheme as-is. As a result, `DefaultMultiAddressUrlHttpClientBuilder` may have more than 1 client instance for the same address if users use URI with different scheme letters case. 
See https://github.com/apple/servicetalk/issues/1423 for details.
Modifications:
- Convert scheme to lower case when parsing `Uri3986` reusing well-known schemes ("http" and "https")
Result:
Fixes #1423.
> Convert scheme to lower case when parsing URI

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java
- servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFromInputStreamTckTest.java
Motivation:
`FromInputStreamPublisher` attempts to read only 1 byte when `InputStream.available()` is not implemented. As a result, users of blocking streaming API with payload body as `InputStream` may write and flush by 1 byte if their `InputStream` implementation always returns 0 available bytes (default).
Modifications:
- Consider `available()` as a best effort to avoid blocking. If it returns 0 bytes, attempt to read up to `readChunkSize` bytes;
Result:
Improved efficiency of writing `InputStream` data for outgoing requests.
> Fallback to `readChunkSize` if `InputStream.available()` not implemented

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetector.java
Motivation:
The `healthStatusChanged()` method of `OutlierDetector` lacks documentation.
Modifications:
- Add a doc string.
> loadbalancer-experimental: add more documentation for OutlierDetector

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation
Because we use mutable state to represent the load balancing weight we need to make sure that it is reset back to the SD weight before we re-run hosts through the transformations. It's currently done when we set the SD weight via `servieDiscoveryWeight(double)` which happens even if it is unchanged, so we change the lb weight even if we don't plan to run it through the transformations again. We will still load balance correctly because we won't rebuild, but it could be really confusing to debug since the lb weight won't reflect transformations.
Modifications
- Separate setting the SD weight and LB weight and before we rebuild reset the LB weight to the current SD weight.
- Add some tests that ensure we set the weight correctly.
> loadbalancer-experimental: make loadBalancingWeight easier to debug

- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerProviderConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsHealthIndicatorTest.java
Motivation:
Cancellation is ambiguous as to why it was cancelled, although it is most likely due to timeouts. We should let users configure this.
Modifications:
- Make classification of cancellation as an error a configuration option.
- Thread it through, including in the providers.
Result:
More flexible classification of cancellation.
> loadbalancer-experimental: allow configuring whether cancellation is an error

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategyTest.java
Motivation:
We currently don't support priority sets that don't have sequential
groups numbers, eg we require groups 0, 1, 2, ... and will reject a
set of groups such as 0, 2, 3, ... This is an artificial constraint.
Modifications:
- Remove the constraint and switch to a TreeMap also make us more
resilient to an adversarial case of getting a group with a large.
- Close an open question and fail-open if no healthy hosts are found.
> loadbalancer-experimental: support non-sequential priorities

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategyTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
Logs are going to be exponentially more useful if we know which LB they're tied to but right now the DefaultHostPriorityStrategy is flying blind with regard to it's parent.
Modifications:
Follow the pattern of other components of DefaultLoadBalancer and pass the lbDescription into the construction of the HostPriorityStrategy.
Result:
Better observability.
> loadbalancer-experimental: Add lbDescription to host priority strategy

- servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferAllocator.java
- servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/ServiceTalkBufferAllocator.java
- servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/BufferAllocatorsTest.java
Motivation:
Default impl in `BufferAllocator` takes a slice of a wrapped original byte-array. We can avoid double wrapping with `NettyBuffer` if we implement this method in `ServiceTalkBufferAllocator`.
Modifications:
- Override `BufferAllocator.wrap(byte[], int, int)` to wrap with `NettyBuffer` only one time;
- Enhance `BufferAllocatorsTest` to validate wrapping and ensure the wrapped `Buffer` always has readerIndex set to 0;
Result:
Minus 2 object allocations when users wrap a byte-array partially.
> Reduce allocations for `ServiceTalkBufferAllocator.wrap(byte[], int, int)`

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CorePoolConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LinearSearchConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
We have a type ConnectionPoolStrategyFactory that is using the `targetResource` name for observability, contrary to the rest of the DefaultLoadBalancer which is using `lbDescription`. This happens because we accept a fully materialized ConnectionPoolStrategy in the DefaultLoadBalancer constructor instead of a factory like most everything else.
Modifications:
- Thread through the factory into the DefaultLoadBalancer constructor.
- Fix the parameter names to reflect that it's now lbDescription being used.
> loadbalancer-experimental: thread through the ConnectionPoolStrategyFactory

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
We use `lbDescription` all over the place for observing the
load balancer, but we use the `targetResource` for the HostSelector.
Modifications:
- Change the HostSelector types to use `lbDescription`.
- Thread the LoadBalancingPolicy into the DefaultLoadBalancer so we
can feed it the `lbDescription`.
> loadbalancer-experimental: thread the LoadBalancingPolicy into the DefaultLoadBalancer

- servicetalk-concurrent-api/gradle/checkstyle/suppressions.xml
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java
Motivation:
In #2949 we optimized a case when `available()` is not implemented and always returns `0`. However, we de-optimized a use-case when it's implemented because the last call to `available()` always returns 0, but we still allocate a buffer of size `readChunkSize` that won't be used.
Modifications:
- Enhance `doNotFailOnInputStreamWithBrokenAvailableCall(...)` test before any changes for better test coverage.
- Remove `byte[] buffer` from a class variable. It can be a local variable because it's never reused in practice. Only the last `buffer` won't be nullified, but we don't need it after that.
- When `available()` returns `0`, try reading a single byte and then recheck availability instead of always falling back to
`readChunkSize`.
- Adjust …
> FromInputStreamPublisher: avoid extra allocation of a buffer

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
Motivation:
Request target may contain sensitive information, like secret query parameters or tokens in path. We should not include it as-is when `MalformedURLException` is thrown.
Modifications:
- Change how `MalformedURLException` is generated to include only small substring of the request target in the exception message.
Result:
No risk to leak sensitive data in exception logs.
> Multi-address client: don't leak full request target in exception msg

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultHostAndPort.java
- servicetalk-transport-api/src/test/java/io/servicetalk/transport/api/HostAndPortTest.java
Motivation:
If two instances of `DefaultHostAndPort` are created with hostname in different case, they pass `equals` check but don't have a consistent `hashCode`. As a result, users can't query a `Map` entry with keys in different case.
Side-effect of that is a multi-address http client that may have multiple instances of a single-address client for the same hostname in different cases, preventing it from reusing connections.
Modifications:
- Implement `DefaultHostAndPort.hashCode()` in a consistent way with `InetSocketAddressHolder` where `hostName` hash is computed in case-insensitive mode.
- Re-generate `DefaultHostAndPort.equals(...)` implementation to allow a check by reference.
- Enhance `DefaultMultiAddressUrlHttpClientBuilderTest` to demonstrate that the problem went away.
Result: …
> `DefaultHostAndPort`: equals and hashCode are not consistent

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
Motivation:
`setHostHeader` method is too far from where it's used and IDE warns that `authority` might be `null`.
Modifications:
- Move `setHostHeader` to `CachingKeyFactory`;
- Pass host and port as arguments from the context where it's known that the `host` is non-null;
- Use `compareTo` for HTTP version check;
> Multi-address client: move setHostHeader to key factory, avoid NPE warn

- .github/workflows/ci-netty-snapshot.yml
Motivation:
Netty accidentally released 4.2.1.Alpha1-SNAPSHOT, which gets a higher priority. We need to pin 4.2.0.Alpha2+
> ci-netty-snapshot.yml: use 4.2.0.Alpha2+

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CorePoolConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LinearSearchConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionPoolStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilderTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/HealthCheckConfig.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
Motivation:
Our LoadBalancerFactory instances all use the default `.toString()` implementation, making them pretty difficult to debug since there are typically a series of proxies and settings that are not visible.
Modifications:
Make the `.toString()` implementations better. We use the standard format along with including the identity hash code to identify uniqueness.
> loadbalancer: better LoadBalancerFactory.toString() implementations

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/FailurePercentageXdsOutlierDetectorAlgorithm.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/SuccessRateXdsOutlierDetectorAlgorithm.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetectorAlgorithm.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsOutlierDetectorTest.java
Motivation:
We have signals from the OutlierDetector to the DefaultLoadBalancer that signals when our endpoints health changes. However, for XdsOutlierDetector, we compute this as the difference on each iteration but consecutive 5xx is tripped immediately, so it may not be captured, and neither will recoveries which are most likely going to flip outside of an outlier detector scan.
Modifications:
- Instead of checking before and after each scan, save the last health status and check if that changed since the last scan.
Result:
We catch health transitions every time instead of only when the happen during an outlier scan.
> loadbalancer-experimental: properly capture consecutive error signals

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
Motivation:
In version 4.2.x, Netty introduced new API
`SslContextBuilder.endpointIdentificationAlgorithm(String)` and flipped the default value to `HTTPS`.
Modifications:
- Detect presence of this new method and initialize it with the value from `config.hostnameVerificationAlgorithm()`.
- Verify `isOptionSupported` method works as expected before initializing its `MethodHandle`.
Result:
Hostname verification algorithm is enabled/disabled as expected for ST users with Netty 4.2.x in the classpath.
> Set `SslContextBuilder.endpointIdentificationAlgorithm` for Netty 4.2.x

- gradle.properties
We have to revert netty because of the issue with grpc-java: `https://github.com/netty/netty/issues/14126`.
Also reverting protobuf and commons protos to match versions from grpc-java 1.64.0.
> Revert dependency upgrades before the release

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslUtils.java
Motivation:
There are cases when default algorithm `HTTPS` can be reset if there are no `sniHostname` and no `peerHost`. See
`GrpcSslAndNonSslConnectionsTest` as a reproducer. This flow works well with Netty 4.1, but breaks with Netty 4.2 because Netty uses `HTTPS` by default. If we set it back to `null`, `sun.security.ssl.SSLEngineImpl` ignores it. To disable it later, we should use an empty string.
Modifications:
- Update `StreamingConnectionFactory.withSslConfigPeerHost` to use an empty string instead of `null` when it needs to reset `hostnameVerificationAlgorithm`;
Result:
We can override the previously set endpoint identification algorithm.
> `StreamingConnectionFactory` should set hostnameVerificationAlgorithm to an empty string

- servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
Motivation:
In rare occasions tests may fail with ambiguous errors. After hours of debugging, the root cause may end up an inability to load native libraries.
Modifications:
- Enforce `io.servicetalk.transport.netty.requireNativeLibs=true` for running tests.
Result:
Significantly simplifies finding the root cause for hanging tests.
> Always require native libraries for running tests

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ByteArrayMapper.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java
- servicetalk-data-jackson-jersey/src/main/java/io/servicetalk/data/jackson/jersey/JacksonSerializerMessageBodyReaderWriter.java
- servicetalk-data-protobuf-jersey/src/main/java/io/servicetalk/data/protobuf/jersey/ProtobufSerializerMessageBodyReaderWriter.java
- servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
- servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/AbstractMessageBodyReaderWriter.java
Motivation:
Existing `Publisher.fromInputStream(InputStream)` contract has a side effect of an extra allocation in case the pre-allocated byte-array was not completely full of data.
Modifications:
- Add `Publisher.fromInputStream(InputStream, ByteArrayMapper)` that allows users to decide how to use the buffer region with data;
- Deprecate pre-existing `Publisher.fromInputStream(InputStream)` and `Publisher.fromInputStream(InputStream, int)` overloads;
- Update all existing use-cases to use `BufferAllocator.wrap` as a method reference as a `ByteArrayMapper`;
Result:
No impact on throughput and latency for `BlockingStreamingHttpClient` requests with `InputStream` payload (8Kb, 16Kb, 24Kb), but significant reduction in memory allocations and number of GC runs per benchmark:
Allocations: …
> Add `Publisher.fromInputStream(InputStream, ByteArrayMapper)`

- gradle.properties
gprc-java released the fix for compatibility with Netty 4.1.111 in 1.64.1 and 1.65.0, we can upgrade netty now
> Update Netty 4.1.110 -> 4.1.111

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultRequestTrackerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsHealthIndicatorTest.java
Motivation:
The pending request penalty is a way to try to avoid connections with lost of pending requests which results in a more even request distribution. However, the penalty is currently fixed which doesn't allow us to choose how to prioritize between the fastest hosts vs the most fair request distribution.
Modifications:
Make the penalty factor configurable.
> loadbalancer-experimental: allow configuring the pending request penalty

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookieTest.java
This changeset aligns the "Set-Cookie" property names with the RFC6265 in the sense that according to the spec (see https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-4.1.1) where property names are using camel-case syntax instead of all lower case.
NOTE: The name of an attribute-value pair is not case sensitive. So while they are presented here in CamelCase, such as "HttpOnly" or "SameSite", any case is accepted. E.x.: "httponly", "Httponly", "hTTPoNLY", etc.
This means that this change is purely cosmetic and helps with consistency with other implementations, i.e. Netty.
> Align Set-Cookie attribute names with RFC6265 syntax

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/SequentialExecutor.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
Motivation:
We have a few warnings and errors that are popping up that can be
addressed. Most revolve around the use of raw types and nullability.
Modifications:
Fix the warnings and errors.
> loadbalancer-experimental: fix some linter warnings/errors

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
Motivation:
As DefaultLoadBalancer becomes the norm it can be helpful to track its activation via log messages.
Modifications:
- Emit a log message on startup that includes the lb description and important settings.
- Fix a bug where the cancellation penalty was inadvertently used for the error penalty.
- Cancel the update stream from the OutlierDetector when the lb closes.
> loadbalancer-experimental: DefaultLoadBalancer logs settings on startup

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
Looks like a historical leftover. In the current state, `address` can not be `null`.
Modifications:
- Remove `@Nullable` annotation from `DefaultSingleAddressHttpClientBuilder.address`;
- Remove unnecessary assertions;
Result:
Less null noise.
> Remove nullable from `DefaultSingleAddressHttpClientBuilder.address`

- servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/DefaultPartitionedClientGroup.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherGroupToManyTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Motivation:
Our load balancers have an ability to cancel and re-subscribe to the `ServiceDiscovery` publisher as an attempt to trigger re-discovery when LB turns into unhealthy state for all addresses. However, for `PartitionedHttpClient` it will result in `DuplicateSubscribeException` because `groupToMany` operator does not support re-subscribes.
Modifications:
- Apply `multicast` operator with `cancelUpstream=false` flag to allow LB of a single-address client to re-subscribe to the same group publisher;
- Disable a retry strategy for `ServiceDiscovery` at single-address client level for partitioned client;
- Implement `NoRetriesStrategy.toString()` for better logging;
- Reproduce described scenario in `PublisherGroupToManyTest`;
Result:
Single-address clients under partitioned client …
> Fix discovery flow for `PartitionedHttpClient`

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
Motivation:
We want all the fields initialized before we subscribe to the SD events so if something happens and an attempt is made to close before construction is complete we don't end up with a NPE somewhere.
Modifications:
- Move the outlier detection stream cancellation assignment to before the subscription.
> loadbalancer-experimental: subscribe is the last thing we do in DefaultLB constructor

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LoadBalancerTest.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
Currently, both implementations of the `LoadBalancer` assume 2 possibilities for the first events collection after re-subscribe: "state of the world" or "delta" and try to infer which one it is based on what event statuses are present in the collection. However, it doesn't provide any guarantees because even if SD impl keeps returning deltas after a re-subscribe, a delta can contain only `AVAILABLE` events, but it will be incorrectly interpreted as "state of the world".
Because of Reactive Streams rule clarified in #3002, `LoadBalancer` implementations should always expect "state of the world" for the first events after re-subscribe.
Modifications:
- Remove inference of the first collection of events after re-subscribe and always expect a new subscriber to start from "state of …
> LoadBalancer should always consider the first events as initial state

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LoadBalancerTestScaffold.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
#2514 added an ability for `LoadBalancer` to cancel discovery stream and
re-subscribe in attempt to trigger a new resolution when its internal
state became `UNHEALTHY`. However, it did not account for a possibility
of new events racing with cancellation or a Publisher not stopping
updates immediately. As a result, it's possible to end up in a corrupted
state if the old `EventSubscriber` receives new events after a new
`EventSubscriber` received a new "state of the world".
Modifications:
- Track the current `EventSubscriber` and process events only if it's
current.
- Enhance `resubscribeToEventsWhenAllHostsAreUnhealthy()` to simulate
the described behavior.
Result:
New "state of the world" can not be corrupted by events emitted for the
old `EventSubscriber`.
---
Depends on …
> Avoid race b/w ServiceDiscoverer events after cancel and re-subscribe

- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
Motivation:
It can be valuable to know what the current host set is but we don't have a way to directly observer that right now.
Modifications:
Add a method to the LoadBalancerObserver that can capture when the host set changes and use it in DefaultLoadBalancer.
> loadbalancer-experimental: add LB observer method for when the host set changes

- servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
- servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
- servicetalk-examples/http/files/build.gradle
- servicetalk-examples/http/files/src/main/java/io/servicetalk/examples/http/files/FilesClient.java
- servicetalk-examples/http/files/src/main/java/io/servicetalk/examples/http/files/FilesServer.java
- servicetalk-examples/http/files/src/main/resources/log4j2.xml
- servicetalk-examples/http/files/src/main/resources/response_payload.txt
- servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java
- servicetalk-examples/http/jaxrs/src/main/resources/response_payload.txt
- settings.gradle
Motivation:
There are no examples demonstrating serving response payload body from file.
> Add HTTP file serving examples

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscoverer.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscovererEvent.java
Motivation:
Some assumptions that are currently in place are not clarified in documentation for new implementations.
Modifications:
- Clarify that the returned publisher should never complete and must support re-subscribes to handle failures and cancellations.
- Clarify motivation for always starting with the "state of the world" for interpreting `ServiceDiscovererEvent`(s).
- Add recommendation to implement a `ServiceDiscoverer` using a single thread.
Result:
More details for expected behavior of a `ServiceDiscoverer` implementation.
> Enhance clarifications for `ServiceDiscoverer` contract

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/PartitionAttributes.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingServiceDiscoverer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PartitionedHttpClientTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingServiceDiscovererTest.java
Motivation:
Clients have a configurable `serviceDiscovererRetryStrategy` to guarantee a steady stream of events to the `LoadBalancer` that never fails. It's necessary at the client level to avoid hanging requests indefinitely and let requests observe failures from ServiceDiscoverer. Also, for `PartitionedHttpClient` it's necessary to guarantee that `GroupedPublisher` never fails.
Retry is effectively a re-subscribe. According to `ServiceDiscoverer` contract (clarified in #3002), each `Subscriber` receives a "state of the world" as the first collection of events. The problem is that the state may change significantly between retries. As a result, unavailable addresses can remain inside the `LoadBalancer` forever. Example:
T1. SD delivers [a,b]
T1. LB receives [a,b]
T1. SD delivers error …
> Incorrect state possible after retrying `ServiceDiscoverer` events

- servicetalk-examples/http/files/src/main/java/io/servicetalk/examples/http/files/FilesClient.java
Motivation:
Javadocs from FilesClient were copied from another example and not updated.
> FilesClient fix javadoc

- gradle.properties
This reverts commit e16b09ec6ca00eb5f6d7947650b6314ad34f532e.
We should be consistent with what version is used by Jersey.
> Revert "Update com.sun.xml.bind:jaxb-impl 2.3.3 -> 2.3.9"

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinSelectorTest.java
Motivation:
Round-robin algorithms very often suffer from bugs where the host after a healthy host will tend to get more traffic. This is because the algorithm will then try to advance to the 'next' index.
Modifications:
If we find a bad host attempt to advance the cursor so the next selection doesn't also pick it.
Result:
Less dogpiling behavior.
> loadbalancer-experimental: reduce dogpiling on hosts after healthy hosts

- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiter.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/CacheConnectionFactory.java
Motivation:
With java-21 and v-threads synchronization can cause deadlocks because carrier threads cannot release a v-thread that is in a synchronized block.
Modifications:
Identify the cases where we're using synchronization and move them to the equivalent v-thread safe ReentrantLock.
Result:
Better v-thread safety.
> Remove some uses of `synchronized`

- .github/workflows/ci-netty-snapshot.yml
Without the number we will always take the latest AlphaN version.
> `ci-netty-snapshot.yml`: remove Alpha number

- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/LatencyTracker.java
Motivation:
Division is much more expensive than multiplication, certainly when the compliler doesn't know the denominator and can do tricks to mitigate.
Modifications:
In the capacity limiter EMA we have a division operation where the denominator is always the same which is a good candidate for inverting once and turning into a multiplication operation.
> capacity-limiter-api: avoid division in EMA

- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/AllowAllCapacityLimiter.java
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/CapacityLimiter.java
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/CapacityLimiters.java
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/Classification.java
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/CompositeCapacityLimiter.java
This changeset mainly polishes javadocs as well as cleans up the implementations slightly without changing their behavior.
> capacity-limiter-api: polish javadocs and minor code modifications

- servicetalk-capacity-limiter-api/src/test/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiterTest.java
Motivation:
We have have any specific tests for the gradient capacity limiter.
Modifications:
Add a test class with a few starter tests. We can add more tests from there.
> capacity-limiter-api: add GradientCapacityLimiterTest

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
Motivation:
BeforeFinallyHttpOperator has the option to short-circuit and not emit a response if it has been cancelled. However, the response has a (potentially) stateful body that needs to be cleaned up and this isn't done if we happen to get an onSuccess after cancellation (which is an intrinsic race in RS).
Modifications:
- Always cleanup the response body if we receive it after a cancellation.
Result:
One less response body leak.
> http-utils: fix leak in BeforeFinallyHttpOperator

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
Motivation:
The Single.timeout(..) family of operations are part of a class of operations will short-circuit the response based on the cancellation pathway, specifically they will return a TimeoutException down the error path. Because cancellation and the result are intrinsically racy there is currently the possibility that the result will be generated but we cannot return it to the subscriber having already given them an Exception in the error pathway. For values that are stateful this can result in a resource leak. One such leak occurs in the AbstractTimeoutHttpFilter.
Modifications:
Modify the AbstractTimeoutHttpFilter to keep a handle on the resource and make sure we close it if we receive a cancellation. This is a localized fix but appears to be effective.
Result:
One less leak.
> http-utils: fix leak in AbstractTimeoutHttpFilter

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AmbSingles.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableAmbTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbWithAsyncTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/DelayedCancellable.java
Motivation
==========
Reactive Streams rule 2.3 mandates, that `Subscriber.onComplete() and Subscriber.onError(Throwable t) MUST NOT call any methods on the Subscription or the Publisher`.
Our current amb operator implementation also performs a cancellation on the Single that just completed, which violates the rule.
Modifications
=============
This changeset modifies the amb operator in a way that all but the one Single which got a termination signal (through `onNext` or `onError`) will get the cancellation propagated.
The test suite is enhanced to cover this scenario, both for `ambWith` as well as the static `amb` factory methods. Since the `Completable` also converts to `Single` underneath, the functionality is transitively available as well.
Result
======
The `amb*` operator variants …
> `Amb` operators for `Single` and `Completable` should respect reactive contract 2.3

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingle.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/JavaNetSoTimeoutHttpConnectionFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingleTest.java
Motivation:
Cancellation of the single may race with delivering the first element. If `cancel` wins, we already deliver `CancellationException` if someone subscribes to the payload publisher. However, if `cancel` arrives after  `dataSubscriber.onSuccess(...)` and before someone subscribes to the payload publisher, it's a strong indicator that there was a race and `dataSubscriber` is not interested in it anymore. Therefore, we should pessimistically assume that nobody will ever subscribe to the payload publisher, cancel upstream subscription, and deliver `CancellationException` is someone still subscribes.
Modifications:
- Cancel upstream subscription for both `null` and `PENDING` states if received data cancel;
- Upwrap code around `parent.packer.apply` to assert that this path happens …
> `SpliceFlatStreamToMetaSingle`: propagate cancel when races with data

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingSingleAddressHttpClientBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ProxyConfig.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfig.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TransportConfigInitializer.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportConfig.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportConfigBuilder.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ChannelInitializer.java
Motivation:
Users need a way to change low-level Netty settings, like `AdaptiveRecvByteBufAllocator` parameters. In the future, we can use this interface for more similar settings without the need to change client/server builder.
Modifications:
- Add `TransportConfig` and `TransportConfigBuilder` in `transport-api` module;
- Add methods on `SingleAddressHttpClientBuilder` and `HttpServerBuilder` to let users pass `TransportConfig`;
- Wire it up to propagate to `Tcp[Client|Server]ChannelInitializer` as `TransportConfigInitializer`;
Result:
Users can control `AdaptiveRecvByteBufAllocator` settings.
> Add `TransportConfig` to control low level transport settings

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatWhenSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Motivation:
Currently, `RepeatWhenSingle` uses its own static `END_REPEAT_EXCEPTION` object as an end marker. That static exception does not discard suppressed exceptions. If under any circumcises it unintentionally leaks, it may cause a memory leak if some path adds suppressed exceptions to it. Also, it's inconsistent with `RepeatStrategies`.
Modifications:
- Use `RepeatStrategies.TerminateRepeatException` instead that discards suppressed exceptions and doesn't write stacktrace.
- Cache failed `Completable` with `TerminateRepeatException` instance instead of allocating a new one on every repeat check.
Result:
1. Avoids static exception instance that may attach suppressed exceptions.
2. Consistency between all repeat operators and strategies.
> `Single.repeat`: use `TerminateRepeatException` as a terminal marker

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractSubmitCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractSubmitSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableProcessor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleProcessor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimerCompletable.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ChannelInitSingle.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingle.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingleTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyFutureCompletable.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
Motivation:
All original sources that implement `handleSubscribe` method should protect from a buggy `Subscriber` that may unexpectedly throw from `onSubscribe`. If they have any state or resource, it should be cleaned up.
Modifications:
- Find all `Publisher`/`Single`/`Completable` that implement `handleSubscribe` and use `handleExceptionFromOnSubscribe` utility;
The following sources clean up their state on exception:
- `FromInputStreamPublisher` closes `InputStream`;
- `SpliceFlatStreamToMetaSingle` cancels upstream `Subscription`;
- `TcpConnector` signals `ConnectionObserver.connectionClosed(t)`;
- `TcpServerBinder` cancels bind `Future` and closes `Channel` if necessary;
- `NettyChannelPublisher` registers `fatalError` and closes `Channel`;
- `DefaultNettyConnection`, …
> Subscribable sources: try-catch `onSubscribe` and cleanup state if any

- servicetalk-concurrent-api-internal/src/main/java/io/servicetalk/concurrent/api/internal/ConnectablePayloadWriter.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/TerminalNotification.java
Motivation:
`ConnectablePayloadWriter` uses a static `IOException` instance as a state and can propagate it to `Subscriber`. This opens a possibility for a memory leak if `Subscriber` or intermediate operators attach a suppressed exception to this static instance.
Modifications:
- Create `StacklessCancelledIOException` and always use a new instance in case of cancellation;
- Keep `cancel()` noop if `outer.closed != null`;
Result:
`ConnectablePayloadWriter` can not leak memory via static exception instance.
> `ConnectablePayloadWriter`: avoid static exception that may leak memory

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
Motivation:
The BeforeFinallyHttpOperator has a few shortcomings
- It doesn't honor the contract of calling the callbacks only once in the case of multiple subscribes.
- It won't honor a cancel if in the `PROCESSING_PAYLOAD` state, which has some weird callback lifetime questions.
Modifications:
- If we receive a cancellation on the Single<StreamingHttpResponse> before the message body has been subscribed, that counts as a cancel. Once the message body is subscribed ownership of the callbacks are fully transferred to it.
- Only the first body subscribe gets ownership of the callbacks.
> http-utils: cleanup the BeforeFinallyHttpOperator state

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
This changeset refactors the `HttpObjectDecoderTest` and its related classes to use the `ParameterizedTest` instead of manually delegating.
> gardening: parameterize HttpObjectDecoderTest and subclasses

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SourceToFuture.java
Motivation:
It can be very difficult to know if a thread is slow or completely stuck without taking multiple thread dumps and comparing them.
Modifications:
Try to mitigate this by saving the time stamp of the last blocking `.get()` call. This should then show up in heap dumps and we can at least compare them to see if they've all started blocking at about the same time or if there is a big spread. The latter would suggest they are truly stuck.
> concurrent-api: save the timestamp of the SingleToFuture.get() calls

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultRequestTrackerTest.java
Motivation:
There is a minor perf regression in the DefaultLB in compat mode compared to
the RR LB when under very high request rate and that is at least in part
attributable to lock contention for the health indicator EWMA.
Modifications:
Don't even create a health indicator if the EWMA half life is 0. In this case the
EWMA should theoretically always decay to 0 instantly so in effect, the EWMA
doesn't exist.
> loadbalancer-experimental: don't always pay for EWMA with noop detector

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequestMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpQuery.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMetaData.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractHttpRequestMetaDataTest.java
Motivation:
HttpRequestMetaData#hasQueryParameter(String) returns false when there is a query parameter with no value. This is incorrect and it should return true.
> HttpRequestMetaData#hasQueryParameter(String) implementaiton fix

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMetaData.java
Motivation:
Null key support was added for query parameters but the default method implementation was not updated, and so it returns incorrect results if a key has a null value.
Modifications:
- Use queryParametersKeys() to determine if key is present.
> HttpRequestMetaData#hasQueryParameter(String) default implementation fix

- .github/workflows/ci-netty-snapshot.yml
Motivation:
After we added lock files, Netty Snapshot pipeline started to fail because Netty version does not match the one in the lock file anymore.
Modifications:
- Add a step to Regenerate Lock Files;
Result:
Netty Snapshot pipeline should start working again.
> ci-netty-snapshot.yml: add Regenerate Lock Files step

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProviderTest.java
Motivation:
It's been out a while now and DefaultLoadBalancer can exactly behave as the old RoundRobinLoadBalancer. That means we can insert it in place of RoundRobinLoadBalancer.
Modifications:
Default to building a DefaultLoadBalancer in round-robin compatibility mode via the RoundRobinToDefaultLBMigrationProvider. We retain the flag for safety for a few releases but will eventually remove it and RoundRobinLoadBalancer.
> loadbalancer-experimental: make DefaultLoadBalancer the default RR implementation

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
When a client is talking to a very large cluster we may want to limit the number of hosts it talks to in order to reduce connection load.
Modifications:
Introduce the notion of random subsetting. The algorithm works by giving endpoints a random number, ordering the endpoint set by that number, and finally taking the first `subsetSize` health instances.
> loadbalancer-experimental: Add support for randomly subsetting hosts

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
Motivation:
We rely on some ordering of the TransportObserver to register listeners on the netty connect promise before the bootstrap has an opportunity to register it's own listener that will close the channel. Without that ordering we can sometimes miss that the connect operation failed.
Modifications:
Ensure ordering by listening from within the pipelines `.connect(..)` pathway. This will always be called from the channels event loop and before the bootstrap registers its listener.
Result:
One less flaky test.
Fixes #3060
> tcp-netty-internal: fix race in TcpConnector

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslContextFactory.java
Motivation:
Users reported that they can see:
```
io.servicetalk.transport.netty.internal.SslContextFactory - SslContextBuilder#endpointIdentificationAlgorithm(String) is available only starting from Netty 4.2.0.Final. Detected Netty version: 4.1.113.Final
java.lang.invoke.WrongMethodTypeException: expected (SslContextBuilder,String)SslContextBuilder but found (SslContextBuilder,Object)SslContextBuilder
at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523) ~[?:?]
at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:532) ~[?:?]
at io.servicetalk.transport.netty.internal.SslContextFactory.setEndpointIdentificationAlgorithm(SslContextFactory.java:126) ~[servicetalk-transport-netty-internal-0.42.48.jar:0.42.48]
at …
```
> Use invoke for `SslContextBuilder#endpointIdentificationAlgorithm(String)`

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslCertificateCompressionTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
- servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DeferSslHandler.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslClientChannelInitializer.java
Motivation
----------
This changeset adds the `SslConfig` if available to the `onSecurityHandshake`, similar to a change made to
`onTransportHandshakeComplete` where the full `ConnectionInfo` gets passed in. This allows to get
information about the config from the argument itself, without having to get it as an instance variable
from `onTransportHandshakeComplete`.
> Add SslConfig to onSecurityHandshake

- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilterTest.java
Motivation:
The TrafficResilienceHttpServiceFilterTest.testStopAcceptingConnections test is flaky (see issue #3076) and it could be as simple as CI being slower than usual.
Modifications:
Extend the timeout for the CI environment to see if this fixes the flakiness.
> traffic-resilience-http: extend connect timeout for CI

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
Motivation:
The ClientEffectiveStrategyTest suite has been flaky for a long time and multiple engineers have looked at it, without making progress. In the meantime, this suite causes a substantial fraction of the failed runs.
Modifications:
Mark the flaky test as `@Disabled`.
Result:
CI should be significantly less flaky.
Related to #2245.
> http-netty: Disable the ClientEffectiveStrategyTest suite

- servicetalk-buffer-netty/build.gradle
- servicetalk-dns-discovery-netty/build.gradle
- servicetalk-encoding-netty/build.gradle
- servicetalk-http-netty/build.gradle
- servicetalk-tcp-netty-internal/build.gradle
- servicetalk-transport-netty-internal/build.gradle
- servicetalk-transport-netty/build.gradle
Motivation:
Maven helped to identify that after #3055 generated pom.xml files are invalid. We forgot to include `netty-bom` in some modules that depend on `io.netty` without specifying netty version.
Also, noticed that some of our modules that use `io.netty` do not list all used netty dependencies as needed.
Modifications:
- For all modules that contain `-netty` in their names add missed `netty-bom` and some other netty dependencies that are used explicitly;
- `servicetalk-buffer-netty`: add missed `netty-common` dependency;
- `servicetalk-transport-netty`: remove unused `netty-common` dependency;
Result:
Gradle generates valid pom.xml files.
> Correct netty dependencies

- servicetalk-http-netty/build.gradle
- servicetalk-opentracing-http/build.gradle
Motivation:
1. `servicetalk-http-netty-test-fixtures` do not depend on `log4j`, `log4j-slf4j-impl` can be safely removed.
2. `servicetalk-opentracing-http` uses `log4j-core` as `testImplementation` dependency. Therefore, `log4j-bom` have to move from `testRuntimeOnly` to `testImplementation` scope.
> Correct log4j dependencies

- servicetalk-transport-netty/build.gradle
Motivation:
`servicetalk-transport-netty` does not depend on `concurrent-api` or `concurrent-internal`.
> Remove unused dependencies from `servicetalk-transport-netty`

- servicetalk-concurrent-api-internal/src/main/java/io/servicetalk/concurrent/api/internal/CloseableIteratorBufferAsInputStream.java
- servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CloseableIteratorBufferAsInputStreamTest.java
- servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/AbstractCloseableIteratorAsInputStream.java
Motivation:
`CloseableIteratorBufferAsInputStream` uses `CLOSED` as a marker for `isClosed()`. However, `fromAscii("")` returns a static reference to `EmptyBuffer`, which opens a risk of getting such `Buffer` via underlying iterator.
Modifications:
- Use `wrap` method that guarantees allocation of a new unique instance of a `Buffer`;
Result:
`CLOSED` marker is guaranteed to be a unique instance.
Additional cleanup of `AbstractCloseableIteratorAsInputStream`:
- Remove `len - toRead` that always results in `0`;
- Avoid arithmetic if `initialLen == len`;
> `CloseableIteratorBufferAsInputStream`: fix `CLOSED` marker instance

- servicetalk-examples/grpc/observer/src/main/java/io/servicetalk/examples/grpc/observer/LifecycleObserverServer.java
- servicetalk-examples/http/observer/src/main/java/io/servicetalk/examples/http/observer/LifecycleObserverServer.java
Motivation:
Server-side has 2 options on how to configure an observer.
Modifications:
- Demonstrate both options;
- Add more clarification comments and point to javadoc for more info;
- Make HTTP and gRPC observer examples consistent;
Result:
Observer examples show all possible configuration options and clarify differences.
> LifecycleObserver examples: clarify server-side ordering options

- .github/workflows/ci-netty-snapshot.yml
Netty 4.2 has moved on to the beta phase and we no longer release alpha versions.
https://netty.io/news/2024/11/04/4-2-0-Beta1.html
> Run snapshot tests with Netty 4.2.0 Beta versions

- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/AbstractTrafficResilienceHttpFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilter.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilterTest.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilterTest.java
Motivation:
Sometimes people will want to test out the capacity limiters without
actually rejecting any traffic. This can help them tune their system
and generally just feel more confident.
Modifications:
Add dry-run mode.
> traffic-resilience-http: Add dry-run mode for resilience filters

- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/AbstractTrafficResilienceHttpFilter.java
Motivation:
We accidentially removed the discardEventsAfterCancel flag in PR #3085.
Modifications:
Add it back.
> traffic-resilience-http: discard events after cancel in TrafficManagement

- servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java
Likely bcz of a copy-paste approach we currently have 2 endpoints with `multipartHello` name. The 2nd one should be named as `fileHello`.
> `HelloWorldJaxRsResource`: fix method name

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
Motivation:
`RedirectConfig` accepts user-defined functions and it's possible that some of them can throw. `RedirectSingle` expects it and applies a `try-catch` block, but we forgot to drain the response payload body before propagating the error.
Modifications:
- Drain response payload before propagating an exception during redirect processing;
- Enhance tests to validate expected behavior;
Result:
We do not leave undrained response payload if redirect fails with an exception.
> Fix response leak that can be caused by an exception during redirect

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogClientFilter.java
Motivation:
We already apply `HttpMessageDiscardWatchdogClientFilter` to single-address clients to detect response leaks that could be caused by unhandled exceptions in the filter chain. Multi-address client adds more logic around a client group and therefore also could leak responses if case on unexpected exceptions.
Modifications:
- Apply `HttpMessageDiscardWatchdogClientFilter` to multi-address client instances;
- Enhance `HttpMessageDiscardWatchdogClientFilter` to include unhandled exception in the logs to help narrow down the leak cause;
- `CleanerStreamingHttpClientFilterFactory`: replace `onErrorResume` with `whenOnError` to reduce RS overhead (avoids subscribe sequence for returned failed single);
Result:
Users will see warn message if their multi-address client leaks responses.
> Detect unexpected response leaks for multi-address client instances

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/Http2SettingsBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
Motivation:
By default we set values for `MAX_HEADER_LIST_SIZE` and `INITIAL_WINDOW_SIZE` settings at `H2ProtocolConfigBuilder` level. However, if users want to change only one setting (for example, `MAX_CONCURRENT_STREAMS`), they lose our defaults when they use `Http2SettingsBuilder`.
Modifications:
- Move defaults initialization from `H2ProtocolConfigBuilder` to `Http2SettingsBuilder`.
Result:
Users always start with consistent default `Http2Settings` and can use builder methods to override what they want.
> Preserve default `Http2Settings` when `Http2SettingsBuilder` is used

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
Behavior of `SslHandler` in Netty 4.1.115 changed. Now it can wrap data and flush them to the network even if flush was not requested. In result, it affected our test `ConnectionCloseHeaderHandlingTest.PipelinedRequestsTest.serverCloseSecondPipelinedRequestWriteAborted` that we had to disable in #3097 to proceed with the upgrade.
Debugging showed that when we receive `AbortWritesEvent`, the following behavior of `WriteStreamSubscriber` depends on how many `activeWrites` we have. With 4.1.115 netty will flush data, there will be 0 `activeWrites` and it will close (with reset) the outbound. In result, we lose data of the previous response in the pipeline that we haven't read yet.
Modifications:
- Use `listenerDiscard` instead of `channelClosed` that will make sure new writes …
> Discard new writes without closing connection on `AbortWritesEvent`

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
Motivation:
Redirect handling creates new requests, but copies only `HTTP_EXECUTION_STRATEGY_KEY`. As the result, next filters after redirect don't see a state associated with the request flow.
Modifications:
- Copy full `ContextMap` from each previous request to the next one;
Result:
Any context information is preserved for all redirected requests, like UUID, counters, execution strategy, etc.
> Preserve full request context while redirecting

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
Motivation:
We had previously disabled the clientStrategy test because it's flaky. According to the notes in the issue (#2245) it is only in one part, and that is in the Send stage which appears to be offloaded when it shouldn't be.
Modifications:
Re-enable the test and prune those errors, and log them.
> http-netty: Re-enable ClientEfectivenessStrategyTest.clientStrategy

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java
Motivation:
Publisher#flatMapConcatIterable may not emit some items due to race conditions and visibility issues. The iterator state is written to outside the scope of holding the lock. After a drain loop completes we may request 1 more iterator. However it is possible the thread emitting holds the lock while another thread invokes onNext(t). The emitting thread may not see the iterator, and instead see `EmptyIterator.instance()` and cause it to request 1 more item, but then the not-visible iterator contents won't be emitted.
Modifications:
- Make FlatMapIterableSubscriber iterator state volatile and atomically update it. There is only ever 1 valid iterator because only 1 outstanding demand is issued only after the current iterator `!hasNext()`. The iterator state is re-read on each drain …
> Publisher#flatMapConcatIterable may skip emitting items

- servicetalk-capacity-limiter-api/build.gradle
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiter.java
- servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiterBuilder.java
- servicetalk-capacity-limiter-api/src/test/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiterTest.java
Motivation:
We currently see callbacks to Observer.onLimitChange(..) only for the successful case, but it's perhaps even more important for the limit decrease case.
Modifications:
- Call the callbacks whenever the limit changes.
- Also call them on the failure case. Since we don't use the gradient and RTT params, we pass in -1.0. This also requires a change in the javadoc.
- Add some tests to make sure the observers are called.
> capacity-limiter-api: observer all gradient limit changes

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NonPipelinedStreamingHttpConnection.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedStreamingHttpConnection.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnClientTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
Motivation:
Currently we reset the flush strategy after a request is written and its response is received. If client starts writing another pipelined request on the same connection, it ends up using an overridden flush strategy of the previous request that is still waiting for its response.
Modifications:
- For client connections (pipelined and non-pipelined) move flush strategy reset from "after full request-response completion" to "before completion of the request write". Using `beforeFinally` we guarantee that reset will happen before any retry/repeat operator initiates a new request on the same connection. It's safe to use "before" because for in-flight request the effective `FlushStrategy` is captured at the beginning of the write and doesn't change regardless of the reset. Only a …
> Reset flush strategy after client request is written

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToOffloadedStreamingHttpService.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClearAsyncContextHttpServiceFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/OffloadingFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractAsyncHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java
Motivation:
If users put any data into `AsyncContext` inside `HttpLifecycleObserver` configured via `HttpServerBuilder.lifecycleObserver(...)` it won't be visible for filters and service because
`ClearAsyncContextHttpServiceFilter` is appended after `HttpLifecycleObserverServiceFilter` inside `applyInternalFilters`.
Modifications:
1. Move `ClearAsyncContextHttpServiceFilter` from the beginning of `noOffloadServiceFilters` to `applyInternalFilters`. However, this move discovered another bug in path that handles
`noOffloadServiceFilters.isEmpty()` case because it never adds `OffloadingFilter`.
2. Refactor `listenForService` method to always make a copy of filters lists, then prepend/append internal filters to those copies in easy to read/understand way, and construct a single filters …
> Server-side `AsyncContext` initialized in lifecycle observer is lost

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SimpleCompletableSubscriber.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SimpleSingleSubscriber.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Motivation:
Currently, users can consume the result or execute a `Runnable` for successful termination of a `Single`/`Completable`. Failures will be logged at debug level. Users can only use `whenOnError` operator to intercept the error, but it may result in duplicated logging or users simply forget to handle the error case.
Modifications:
- Add `Single.subscribe(Consumer<? super T>, Consumer<? super Throwable>)`;
- Add `Completable.subscribe(Runnable, Consumer<? super Throwable>)`;
- Modify `SimpleSingleSubscriber/SimpleCompletableSubscriber` to handle error when `errorConsumer` is provided.
Result:
Users can easily handle error cases when they subscribe to `Single` or `Completable`.
> `Single`/`Completable` `subscribe` overloads to handle failures

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
Use new `Single.subscribe(...)` overload introduced in [#3112](https://github.com/apple/servicetalk/pull/3112) that takes `errorConsumer` to avoid using extra operator `whenOnError`. It will also help to avoid logging those exceptions by `SimpleSingleSubscriber` (hard to relate to a real request) and instead they will only bubble up on the caller path.
> `RedirectSingle`: avoid extra operator for exception handling path

- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq.yml
- .github/workflows/ci-snapshot.yml
- .github/workflows/codeql-analysis.yml
Motivation:
Currently, GitHub Actions workflows run on every change in the PR, even if it's known the file won't affect the output.
Modifications:
- For each workflow, ignore files that won't affect its result.
Result:
Less workflows to run for small PRs.
> Ignore GitHub Actions for non-relevant files

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
We commonly use the term 'policy' in our API's but ConnectionPoolConfig is an outlier.
Modifications:
Rename `ConnectionPoolConfig` to `ConnectionPoolPolicy`.
Result:
More consistency.
> loadbalancer-experimental: rename ConnectionPoolConfig -> ConnectionPoolPolicy

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilterTest.java
Motivation:
The `TrafficResilienceHttpServiceFilterTest.testStopAcceptingConnections(..)` test is flaky and sometimes will find that a connection times out before it was expected to. These additional connections are made to account for intrinsic races as well as kernel connection backlog behavior which is really hard to control.
Modifications:
The timeout behavior is the desired result, it just happens before we expect it to. So, instead of trying to make exactly two connections that we expect to succeed followed by one that should fail, we instead can just perform a low iteration loop and demand that we eventually stop accepting connections, which is the desired behavior.
Closes #3076.
> traffic-resilience-http: Fix flaky testStopAcceptingConnections() test

- scripts/manage-antora-remote-versions.sh
This changeset makes sure that tags in the form of [a.b.c] are properly recognized. Previously they would only work if either no or at least two elements are in the tags list.
> Fix antora sed script to allow tags with single entry to work

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CorePoolConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LinearSearchConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/ConnectionSelectorHelpers.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/CorePoolConnectionSelectorTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/LinearSearchConnectionSelectorTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/P2CConnectionSelectorTest.java
Motivation:
The ConnectionPoolStrategy carries a lot of parallels with the HostSelector abstraction, in that it's goal is to select a connection. However, the names are dissimilar and 'Strategy' doesn't have as strong an implication of being capable of action and may suggest it's configuration.
Modifications:
Rename ConnectionPoolStrategy to ConnectionSelector to make its role more clear.
> loadbalancer-experimental: rename ConnectionPoolStrategy -> ConnectionSelector

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RichServiceDiscovererEvent.java
Motivation:
As we prepare to move the DefaultLoadBalancer out of experimental we need to scrutinize the API we expose as it effectively becomes permanent. RichServiceDiscovererEvent is one of those API's I don't think we want to commit to just yet.
Modifications:
Make RichServiceDiscovererEvent package private.
> loadbalancer-experimental: make RichServiceDiscovererEvent package private

- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/SelectorTestHelpers.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/XdsOutlierDetectorAlgorithmTest.java
Motivation:
We have a few raw types usages in loadbalancer-experimental tests.
Modifications:
Add the types.
> loadbalancer-experimental: fix some raw types usages

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CorePoolConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LinearSearchConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
We typically have a 'ies' class for the static helper methods, but right now we stuff all that into ConnectionPoolPolicy. We also tried to hide all the details by making the ConnectionPoolPolicy a data carrier instead of having any behavior, but that makes some extra noise around conversions.
Modifications:
- Make ConnectionPoolPolicy follow the pattern in LoadBalancingPolicy, in that it's a factory but the constructor and methods are package private to control proliferation.
- Remove the internal time ConnetionPoolFactory which is now subsumed by ConnectionPoolPolicy.
- Make ConnectionPoolPolicies to follow the pattern established patterns.
Result:
More consistent code.
> loadbalancer-experimental: make ConnectionPoolPolicy consistent

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionPoolPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultRequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/HealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilderProvider.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancers.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopOutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/OutlierDetectorConfig.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RichServiceDiscovererEvent.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicyBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/SequentialExecutor.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsOutlierDetector.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderProvider.java
Minor adjustments to indentation, validation, formatting, in code and javadoc.
Also reduced visibility where it was possible. Even if those methods are currently in pkg-private classes, it may help to start with minimal visibility on methods to avoid accidental API leaks when we make classes public in the future.
> loadbalancer-experimental: javadoc cleanup and minor fixes

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RequestTracker.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancingPolicy.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
Reduce public API that is not currently used.
Modifications:
- Make `LoadBalancingPolicy.name()` visibility pkg-private;
- Remove `RequestTracker.ErrorClass.isLocal()`;
> loadbalancer-experimental: remove/hide unused public API

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterableTest.java
- servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/BlockingIterable.java
This makes sure that if this method, or indirectly `next(long, TimeUnit)` is called and times out, the caller is able to retry the operation and also the upstream source will not be cancelled.
In the context of a `BlockingStreaming` server, this means that if a timeout is thrown on the incoming request, the outgoing response can still be modified since the underlying socket will not be immediately closed.
It also aligns the semantics with `Single#toFuture` where a blocking get with a timeout on the future also does not cancel the upstream `Single`.
A (temporary) system property is introduced which allows to fall back to the old behavior should incompatibilities be discovered in the wild.
A note for the reader who wonders how to close the subscription now: the close() method always did …
> Do not cancel subscription on BlockingIterable#hasNext(long, TimeUnit)

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/XdsHealthIndicator.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
Motivation:
We store the reason that a host enters the unhealthy/healthchecking state but we never use it.
Modifications:
- Include that info when we're creating the `DefaultHost.toString()` implementation.
> loadbalancer-experimental: include reason DefaultHost is unhealthy

- servicetalk-loadbalancer-experimental-provider/src/main/java/io/servicetalk/loadbalancer/experimental/DefaultLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/BaseHostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/Host.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/HostSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CSelector.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
As discussed in #3140, we need to adjust some of the LoadBalancerObserver callbacks to make the events more clear and also preserve important order characteristics.
Modifications:
- Remove the size parameters from the `onServiceDiscoveryEvent` method as that required us to either precompute the size change or emit the event later than host observer creation events.
- Change the `onHostSetChanged` method to take two collections: one reflecting the previous set and the new set, both after manipulations where done such as prioritization and subsetting.
> loadbalancer-experimental: change host set update events

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/Host.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/PrioritizedHost.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostPriorityStrategyTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
Motivation:
We have a few Host related weight methods, but they have slightly different names. Worse yet, we don't use them properly when adjusting weights.
Modifications:
Rename the LoadBalancerObserver.Host.loadBalancingWeight() to simply .weight()
> loadbalancer-experimental: Unify the Host.weight() methods

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionSelectorPolicies.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/ConnectionSelectorPolicy.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CorePoolConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LinearSearchConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/P2CConnectionSelector.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/RoundRobinToDefaultLBMigrationProvider.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
A ConnectionPoolPolicy doesn't actually control pooling, but selection from that pool. The name is also inconsistent with the thing it generates: a ConnectionSelector.
Modifications:
Rename the types to ConnectionSelector* for more consistincy.
> loadbalancer-experimental: Rename ConnectionPool* types to ConnectionSelector*

- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/CatchAllLoadBalancerObserver.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/NoopLoadBalancerObserver.java
Motivation:
We generally promise that if observers throw it won't mess up the greater state of the system. However, we don't currently do that in DefaultLoadBalancer.
Modifications:
- Add the CatchAllLoadBalancerObserver to catch exceptions thrown by the underlying underlying observers.
- Install it when using anything other than the NoopLoadBalancerObserver.
> loadbalancer-experimental: add CatchAllLoadBalancerObserver

- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterableTest.java
- servicetalk-concurrent-internal/src/testFixtures/java/io/servicetalk/concurrent/internal/DeliberateIOException.java
- servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/BlockingIterable.java
- servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/ThrowableUtils.java
The previous refactoring wrapped all non-runtime exception into a runtime exception to adhere to the unchecked singature of the method. Turns out, some code on top has been relying on the actual exception (i.e. an IOException) so wrapping, while correct, is not backwards compatible and in this case for us the latter is more important.
> Preserve exception type on BlockingIterable#forEach variants

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpResponse.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDataSourceTransformations.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpPayloadWriter.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingToStreamingServiceTest.java
Motivation:
Behavior was discovered as part of debugging #3148.
Currently, `BlockingStreamingHttpService` allocates trailers upfront and concatenates them after the payload body when protocol allows. In result, aggregation of `BlockingStreamingHttpResponse` does not lead to a single HTTP/2 frame because we always expect to receive trailers. However, adding trailers after users close payload writer is race. There are no guarantees that new trailers will be written to the network after close. Therefore, we can inspect the state after close and decide if we need to append trailers or not.
Modifications:
- Use `scanWithMapper` inside `BlockingStreamingHttpService` instead of always concatenating payload body with trailers;
- Create trailers on demand inside `BufferHttpPayloadWriter`, only …
> `BlockingStreamingHttpService`: drop trailers if users didn't create any

- gradle.properties
- servicetalk-opentelemetry-asynccontext/gradle.lockfile
- servicetalk-opentelemetry-http/gradle.lockfile
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/ServiceTalkHttpAttributesGetter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/ServiceTalkNetAttributesGetter.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilterTest.java
Motivation:
We're experiencing some degree of incompatibility with otel. This is happening because we're using otels alpha API's for the semconv package and they have walked on us.
Modifications:
Upgrade the dependency versions. Note that it seems like the 1.33.3-alpha boms are using the 1.38.0 non-alpha packages, which is odd but that is why the versions for alpha and non-alpha are different.
> Update OpenTelemetry 1.28.0 -> 1.38.0, instrumentation 1.28.0 -> 1.33.3

- build.gradle
- servicetalk-concurrent-api/build.gradle
- servicetalk-concurrent-internal/build.gradle
- servicetalk-concurrent-reactivestreams/build.gradle
- servicetalk-dependencies/build.gradle
- servicetalk-http-api/build.gradle
- servicetalk-http-netty/build.gradle
- servicetalk-http-router-jersey/build.gradle
- servicetalk-http-router-jersey3-jakarta10/build.gradle
- servicetalk-http-router-jersey3-jakarta9/build.gradle
- servicetalk-transport-netty-internal/build.gradle
Motivation:
Dependency-analysis plugin detected that some dependencies declared under incorrect scope. In this PR we only focus on test-fixtures dependencies.
Modifications:
- Update scope of dependencies as recommended by the plugin. Typically, it recommends to promote some `testFixturesImplementation` dependencies to `testFixturesApi`.
- Add exclusion rule for `com.google.code.findbugs:jsr305` for `onIncorrectConfiguration` rule as we don't want to promote it explicitly, it's handled by `servicetalk-annotations`.
- Exclude some false positives when the plugin recommends reducing scope, but `testFixturesApi` is actually required.
Result:
Addresses warning from dependency-analysis plugin that recommends different scope for test dependencies.
Risk for users:
None, because changes were made …
> Update scope of test-fixtures dependencies

- servicetalk-concurrent-api-internal/build.gradle
- servicetalk-concurrent-api-test/gradle.lockfile
- servicetalk-concurrent-test-internal/gradle.lockfile
- servicetalk-data-protobuf/build.gradle
- servicetalk-grpc-internal/gradle.lockfile
- servicetalk-grpc-utils/gradle.lockfile
- servicetalk-http-router-jersey-internal/build.gradle
- servicetalk-http-router-jersey3-jakarta10-internal/build.gradle
- servicetalk-http-router-jersey3-jakarta9-internal/build.gradle
- servicetalk-log4j2-mdc/build.gradle
- servicetalk-router-utils-internal/build.gradle
- servicetalk-serialization-api/gradle.lockfile
- servicetalk-serializer-utils/gradle.lockfile
- servicetalk-test-resources/gradle.lockfile
- servicetalk-transport-netty-internal/build.gradle
- servicetalk-utils-internal/build.gradle
Motivation:
Dependency-analysis plugin detected that some dependencies must be declared as `api` while they have more restrictive scope today.
Modifications:
- Update scope of dependencies to `api` as recommended by the plugin.
- Regenerate lock files.
Result:
Addresses warning from dependency-analysis plugin that recommend different scope for main dependencies.
Risk for users:
None, promotion to `api` is a safe change for users. It only brings more dependencies to their compile classpath rather than runtime but can not break the build.
> Promote dependencies to `api` where necessary

- servicetalk-http-netty/build.gradle
- servicetalk-http-router-jersey/build.gradle
- servicetalk-http-router-jersey3-jakarta10/build.gradle
- servicetalk-http-router-jersey3-jakarta9/build.gradle
- servicetalk-tcp-netty-internal/build.gradle
- servicetalk-transport-netty-internal/build.gradle
Motivation:
Previously identified "false positives" were actually not false. After fixing all other warnings, it's clear now that we can remove some of the suppressions and address those warnings too.
Modifications:
- Remove suppressions that can be addressed.
Result:
Less suppressions for dependency-analysis plugin checks.
> Remove unnecessary suppressions for dependency-analysis plugin

- build.gradle
Motivation:
All warnings from dependency-analysis plugin were addressed in prior PRs. We can enable the `fail` mode now.
Modifications:
- Change dependency-analysis plugin mode from `warn` to `fail`.
Result:
PRQ pipeline will fail if a new PR introduces warnings for dependencies.
> Change dependency-analysis plugin to `fail` mode

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogClientFilter.java
Motivation:
When we get a log entry from `HttpMessageDiscardWatchdogClientFilter`, there is little to no information to go on to start identifying which client this leak may be coming from. Adding some sort of context about the request like the connection id or remote socket address would at least help us correlate this leak to a particular client connection and eventually the code.
Modifications:
- Added `ConnectionInfo` or `request.effectiveHostAndPort()` info to the logger message.
Result:
Remote info is included in the log message.
> Adding remote info to logger message so clients can be tracked down

- scripts/release.sh
Motivation:
As part of the release process our script makes some changes to versions etc and then everything in the branch is committed. This is dangerous if there are uncommitted changes present.
Modifications:
As part of the release.sh script check if the tree is dirty and error out if so.
This was tested by running the release script before and after committing the change and it worked as expected.
> scripts/release.sh: ensure tree is clean before releasing

- servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/OptimizedHttp2FrameCodecBuilder.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java
Motivation:
Help users to debug what were the supplied values for system properties supported by `NativeTransportUtils`.
Modifications:
- Log every system property value that we read in `NativeTransportUtils`;
- Align logging format for system properties in other places;
Result:
Easier to see what values were loaded after `NativeTransportUtils` class initialization.
> Log runtime values for `NativeTransportUtils`

- .github/workflows/ci-netty-snapshot.yml
Netty 4.2 transitioned to RC state.
> Use Netty 4.2.0.RC+ snapshots instead of 4.2.0.Beta+

- servicetalk-concurrent-api-internal/build.gradle
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribePublisher.java
1. `AbstractNoHandleSubscribePublisher` has incorrect reference in javadoc.
2. `servicetalk-concurrent-api-internal` had a duplicate line for `servicetalk-concurrent-api` dependency.
> Small internal fixes to build and javadoc

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
- servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserverTest.java
Motivation:
We use the var-args logger in LoggingHttpLifecycleObserver and add the exception regardless of if one is generated which means when there is not an exception we put a `null` as the last argument. The logger can't tell this was supposed to be an exception so it gets angry because it found one more argument (a null) than it expected based on the format string.
Modifications:
Don't add the exception if it's null.
> http-utils: Fix bad logging when request and response are present

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribeCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribeSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/LiftSynchronousPublisherToSingle.java
Motivation:
`AbstractNoHandleSubscribe[Completable|Single|Publisher]` were used in the past not only to enforce non-standard context propagation but also an `Executor`. Then in 2020 we removed an `Executor` reference from operators chain, but did not reword these exceptions.
Modifications:
- Align exception type to always fail subscriber with `UnsupportedOperationException`.
- Align exception message to clarify it's intended to target `CapturedContext` instead of `Executor`.
- Simplify `LiftSynchronousPublisherToSingle` by extending `AbstractNoHandleSubscribeSingle`.
Result:
Updated and consistent behavior of `AbstractNoHandleSubscribe` sources.
> Update exceptions from `AbstractNoHandleSubscribe` sources

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
Motivation:
This method was accidentally made non-final in #1639. See diff for easier view:
https://patch-diff.githubusercontent.com/raw/apple/servicetalk/pull/1639.diff
Modifications:
- Add `final` modifier for `Publisher.subscribeInternal(Subscriber)`.
Result:
`subscribeInternal` definition is consistent across `Publisher`, `Single`, and `Completable`.
Risk:
Because this is very specific internal API, I don't expect anyone to depend on it. Users should operate with `subscribe` and/or `handleSubscribe` methods. At least, I could not find any use-case visible to me.
The risk of breaking anyone is quite low. If anyone reports it as a breaking change, we can change it back and re-release, notifying them that it will be marked as `final` anyway in the future major release.
> Mark `Publisher.subscribeInternal(Subscriber)` method as final

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribeCompletable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribePublisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractNoHandleSubscribeSingle.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableSetContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableShareContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherSetContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherShareContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleSetContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleShareContextOnSubscribe.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SourceAdapters.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SourceAdaptersTest.java
Motivation:
`SourceAdapters.toSource(...)` currently returns a source without implementing the original type. In result, operation like `fromSource(toSource(notSource))` returns double wrapped object instead of wrapping only once.
Modifications:
- `PublisherToPublisherSource` extends `Publisher`;
- `SingleToSingleSource` extends `Single`;
- `CompletableToCompletableSource` extends `Completable`;
- Enhance `SourceAdaptersTest` to cover all transformations (via cast and via wrapping).
Result:
Less wrapping layers for back and forth conversions and better test coverage for `SourceAdapters`.
> SourceAdapters should convert back and forth without allocation

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ConcurrentGrpcRequestTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractHttpMetaData.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/FilterableClientToClient.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConcurrentHttpRequestTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionAcceptingNettyHttpServerTest.java
Motivation:
Our `HttpRequestMetaData` object is mutable, and we expect users to create a new request every time they need to make a new call. Sequential retries are acceptable, but concurrent execution can corrupt internal state. While these expectations are more clear for HTTP users, with gRPC it gets less obvious that they can not subscribe to the same returned `Single<Message>` concurrently.
Modifications:
- Enhance `FilterableClientToClient` to protect users from concurrent execution of the same request, while still allowing sequential retries.
- Verify concurrent execution is not allowed for HTTP and gRPC.
Result:
Users get `RejectedSubscribeException` if they subscribe to the same Single that shares underlying meta-data object concurrently. This is the best effort to let users know …
> Prevent concurrent execution of the same mutable request object

- servicetalk-concurrent-api/gradle/checkstyle/suppressions.xml
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CapturedContextProviders.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultAsyncContextProvider.java
- servicetalk-log4j2-mdc-utils/src/test/java/io/servicetalk/log4j2/mdc/utils/ServiceTalkThreadContextMapTest.java
- servicetalk-log4j2-mdc-utils/src/test/resources/log4j2-test.xml
- servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java
Motivation:
The MDC utilities depend on the AsyncContext for storing properties. This can create a cyclical dependency since we try to log the loaded providers as part of the initialization.
Modifications:
Submit the logging to a different thread so that it will happen 'later' after the class initialization is complete.
> concurrent-api: defer logging during CapturedContextProviders initialization

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RandomSubsetter.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
Motivation:
We want to let users specify a random subset size so they can limit
the maximum number of backends they'll talk to. This feature is
already implemented, but not yet surfaced for users to configure.
Modifications:
Add a method to the LoadBalancerBuilder api.
> loadbalancer: surface random subsetting behavior in the LoadBalancerBuilder API

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
Motivation:
HTTP/2 protocol defines a set of error codes for its exceptions. Some of those are expected and can be logged at debug level, but others could be concerning. Giving higher visibility to users may help them identify problems earlier and identify misbehaving clients.
Modifications:
- Add special rule in `ErrorLoggingHttpSubscriber` to handle `Http2Exception`s;
Result:
Users have better visibility for unexpected HTTP/2 errors.
> Increase visibility for unexpected HTTP/2 errors on the server-side

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RandomSubsetter.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/Subsetter.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultLoadBalancerTest.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RandomSubsetterTest.java
Motivation:
It could be helpful for people to know what happened during subsetting.
Modifications:
Add some logging to RandomSubsetter. This required some extra changes so that we could pass in the load balancer description so it's easier to know which subsetter we're actually talking about.
Result:
Better observability.
> loadbalancer: add some logging to RandomSubsetter

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/OnErrorCompletableTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/OnErrorPublisherTest.java
- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/OnErrorSingleTest.java
Motivation:
`Publisher.onErrorReturn` and `Single.onErrorReturn` are using an async `onErrorResume` operator internally, which item supplier returns an async source. Even though it doesn't change the behavior of `AsyncContext` propagation because the returned async source is already complete/succeeded, it's worth using `shareContextOnSubscribe()` operator to avoid unnecessary copy of the `ContextMap`.
Modifications:
- Add `shareContextOnSubscribe()` inside item supplier for `Publisher.onErrorReturn` and `Single.onErrorReturn`.
- Add tests to demonstrate that `AsyncContext` is propagated synchronously between previous and subsequent operators around `onError*` mappings.
Result:
Less allocations when using `Publisher.onErrorReturn` and `Single.onErrorReturn` operators.
> Share context inside `Publisher.onErrorReturn` / `Single.onErrorReturn`

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CapturedContextProvider.java
Motivation:
The example became stale during method renames and had some other defects.
Modifications:
Fix it.
Result:
Example better aligns with reality.
> concurrent-api: Fix examples in CapturedContextProvider

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
- servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
Motivation:
Even though we pass a `Publisher` to `NettyConnection.write(...)` as another async source, we always use it in a way that expects a shared AsyncContext state between what we write and returned `Completable`. However, we can not apply `shareContextOnSubscribe()` on the passed `Publisher` because internally `write(...)` operation also applies `FlushSubscriber`.
Modifications:
- Add `shareContextOnSubscribe()` before subscribing to the write `Publisher`.
- Add a test to assert expected context propagation.
Result:
`AsyncContext` state is shared between the `Publisher` we write and returned `Completable`.
> `DefaultNettyConnection`: share AsyncContext state on write

- servicetalk-opentelemetry-http/build.gradle
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryFilter.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilterTest.java
Motivation:
`AbstractOpenTelemetryFilter` manually subscribes to response and its payload body but does not share context on subscribe. In result, `AsyncContext` propagation is incorrect when OTEL filters are in place.
Modifications:
- Add `shareContextOnSubscribe()` before subscribing response single and its payload Publisher.
- Add a test that uses our utility to verify correct AsyncContext propagation.
Result:
`AsyncContext` state is correctly propagated through stages of response processing when OTEL filters are in place.
> Fix `AsyncContext` visibility for OTEL filters

- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcEnforceTrailersOnlyResponseServiceFilterTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentEncodingHttpServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpExceptionMapperServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/OffloadingFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PayloadSizeLimitingHttpServiceFilterTest.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrackPendingRequestsHttpFilterTest.java
Motivation:
We have `AsyncContextHttpFilterVerifier` test fixture to validate that a `StreamingHttpServiceFilterFactory` does not break `AsyncContext` propagation. It's used to validate some of our service filters, but not all.
Modifications:
- Use `AsyncContextHttpFilterVerifier` to test: `GrpcEnforceTrailersOnlyResponseServiceFilter`,
`ContentEncodingHttpServiceFilter`, `HttpExceptionMapperServiceFilter`, `HttpLifecycleObserverServiceFilter`,
`HttpMessageDiscardWatchdogServiceFilter`, `KeepAliveServiceFilter`, `OffloadingFilter`, `PayloadSizeLimitingHttpServiceFilter`, `TrackPendingRequestsHttpFilter`.
Result:
All service filters are tested with `AsyncContextHttpFilterVerifier`.
> Test all service filters propagate `AsyncContext` correctly

- servicetalk-examples/http/service-composition/src/main/java/io/servicetalk/examples/http/service/composition/HttpResponseExceptionHandlingServiceFilter.java
- servicetalk-examples/http/service-composition/src/main/java/io/servicetalk/examples/http/service/composition/backends/ErrorResponseGeneratingServiceFilter.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpServiceFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilter.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthHttpServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConditionalHttpServiceFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentCodingTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/PayloadSizeLimitingHttpServiceFilter.java
Motivation:
It's recommended to use `delegate` for invoking the next filter in the chain rather than `super`. In the past, we had cases when the `super` implementation changed and it affected filter behavior.
Modifications:
- Replace all calls to `super.handle(...)` with `delegate().handle(...)` and `super.request(...)` with `delegate.request(...)`.
Result:
All filters consistently use `delegate`.
> Use `delegate` instead of `super` when calling the next filter

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExpectContinueTest.java
Motivation:
This test is flaky because of a race condition where we let the retry potentially happen before we assert that the request body hasn't been subscribed to. On the retry the entire request is sent without the expect: continue header so it should all be sent, and thus we expect the body to be subscribed to.
Modifications:
Don't let the first response continue until after the assertion. This should still test that the first `expect: continue` request doesn't subscribe to the body until it knows it's safe to proceed.
Result:
One less flaky test.
Fixes #2638
> http-netty: fix flaky ExpectContinueTest.retryExpectationFailed

- servicetalk-examples/grpc/compression/build.gradle
- servicetalk-examples/grpc/deadline/build.gradle
- servicetalk-examples/grpc/debugging/build.gradle
- servicetalk-examples/grpc/errors/build.gradle
- servicetalk-examples/grpc/execution-strategy/build.gradle
- servicetalk-examples/grpc/health/build.gradle
- servicetalk-examples/grpc/helloworld/build.gradle
- servicetalk-examples/grpc/keepalive/build.gradle
- servicetalk-examples/grpc/observer/build.gradle
- servicetalk-examples/grpc/protoc-options/build.gradle
- servicetalk-examples/grpc/request-response-context/build.gradle
- servicetalk-examples/grpc/routeguide/build.gradle
- servicetalk-grpc-protoc/README.adoc
- servicetalk-grpc-protoc/build.gradle
- servicetalk-grpc-protoc/gradle.lockfile
Motivation:
`servicetalk-grpc-protoc` generates stubs, and the generated code requires 2 dependencies to make it compilable:
`servicetalk-data-protobuf` and `servicetalk-grpc-protobuf`. `servicetalk-grpc-protoc` already adds the first one transitively, but not the second one. In our examples, it's used as a way to add required transitive dependencies for generated code and should have all required dependencies.
Modifications:
- Add `servicetalk-grpc-protobuf` as a transitive `api` dependency for `servicetalk-grpc-protoc`.
- Remove `servicetalk-grpc-protobuf` from all examples.
Result:
Users don't need to guess what dependencies they need for the generated code, they can simply add `servicetalk-grpc-protoc` as their dependency to bring everything that they need transitively.
> `servicetalk-grpc-protoc`: add `servicetalk-grpc-protobuf` transitively

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContext.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextProvider.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CapturedContextProvider.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CustomCaptureAsyncContextProvider.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultAsyncContextProvider.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/NoopAsyncContextProvider.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
- servicetalk-opentelemetry-asynccontext/src/main/java/io/servicetalk/opentelemetry/asynccontext/OtelCapturedContextProvider.java
Motivation:
Certain types of context is mutable. Examples include our own AsyncContext, MDC context, etc. For those situations we don't have a way to isolate the captured context boundaries from one another and it will ultimately bleed together.
Modifications:
Add a `captureContextCopy()` method to `CapturedContextProvider`. This will let the capture system know which type of context we're trying to acquire.
Result:
More consistent context capture system.
> servicetalk-concurrent-api: add CapturedContextProvider.captureContextCopy() method

- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DelegatingFlushStrategy.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/FlushStrategyHolder.java
Motivation:
This class is used only internally, no need to be public in the future releases.
> Deprecate `DelegatingFlushStrategy`

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractWhenFinallyHttpOperator.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AfterFinallyHttpOperator.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
Motivation:
Its binary compatibility was broken in #3231.
Modifications:
- Remove `final` modifier from `apply` method of the super class.
- Make its super class `abstract`.
Result:
`japicmp` is happy.
> `BeforeFinallyHttpOperator`: restore binary compatibility

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingExecutor.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
Motivation:
All other `Delegating*` classes are non-abstract.
Modifications:
- Drop `abstract` class modifier from `DelegatingExecutor`.
Result:
`DelegatingExecutor` is consistent with all other `Delegating*` classes.
> `DelegatingExecutor`: drop `abstract` class modifier

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelegatingConnectionFactory.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelegatingServiceDiscoverer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingExecutor.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingFilterableStreamingHttpLoadBalancedConnection.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingConnectionContext.java
Motivation:
#3239 added new `DelegatingListenableAsyncCloseable` class, but I was not able to use it because of some false positives from japicmp. Now I figured what was the problem and we can remove some boilerplate code.
Modifications:
- Use `DelegatingListenableAsyncCloseable` to simplify `DelegatingExecutor`, `DelegatingConnectionFactory`, `DelegatingServiceDiscoverer`, `DelegatingConnectionContext`, and `DelegatingFilterableStreamingHttpLoadBalancedConnection` implementations.
Result:
Less code to maintain delegating classes that implement `ListenableAsyncCloseable` interface.
Binary compatibility:
If you run `./gradlew assemble && ./scripts/japicmp.sh 0.42.55 local`, it won't report anything for `DelegatingExecutor`, but will report false positives for all other classes. This …
> Use `DelegatingListenableAsyncCloseable` where possible

- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/HttpRequestAutoDrainingServiceFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrackPendingRequestsHttpFilter.java
Motivation:
`discardEventsAfterCancel` flag for `[Before|After]FinallyHttpOperator` is useful only for cases when we don't want downstream users to see response `onComplete/onError` after cancellation to make sure output matches with callbacks (observability).
However, for `HttpRequestAutoDrainingServiceFilter` and `TrackPendingRequestsHttpFilter` we only need to track termination, influencing what users see for returned response is not necessary.
Modifications:
- Remove `discardEventsAfterCancel` flag from `HttpRequestAutoDrainingServiceFilter` and
`TrackPendingRequestsHttpFilter`;
Result:
`HttpRequestAutoDrainingServiceFilter` and
`TrackPendingRequestsHttpFilter` don't influence response output that users see.
> Don't use `discardEventsAfterCancel` when not necessary

- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelegatingConnectionFactory.java
- servicetalk-client-api/src/main/java/io/servicetalk/client/api/DelegatingServiceDiscoverer.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingAsyncCloseable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingExecutor.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingListenableAsyncCloseable.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/GlobalExecutor.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingFilterableStreamingHttpLoadBalancedConnection.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingConnectionContext.java
Motivation:
They typically serve a role of a base interface for specific closeable contracts. Having a parametrized `delegate()` method helps to avoid additional class variables in its subtypes.
Modifications:
- Add `T` parameter for `DelegatingAsyncCloseable` and `DelegatingListenableAsyncCloseable`.
Result:
Classes that extend `Delegating[Listenable]AsyncCloseable` don't need additional class variable to delegate its methods.
> Parametrize `Delegating[Listenable]AsyncCloseable`

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/ScopeTracker.java
Motivation:
We want to make sure that the events OTEL sees are the same that the user will see. If we use 'discardEventsAfterCancel=true' for the AfterFinallyHttpOperator then we're more likely to be aligned.
Modifications:
Set the flag.
> opentelemetry-http: use 'discardEventsAfterCancel' for ScopeTracker

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
Motivation:
We've made a lot of improvements to OpenTelemetryHttpServerFilter, but the order of the filter with respect to other filters in the stack is important to guarantee the correct context visibility and event ordering.
Modifications:
Adjust the docs.
> opentelemetry-http: Update OpenTelemetryHttpServerFilter docs

- .github/workflows/ci-prb-reports.yml
- .github/workflows/ci-prb.yml
- .github/workflows/ci-prq-reports.yml
- .github/workflows/ci-prq.yml
- .github/workflows/gradle-wrapper-validation.yml
- servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/BufferAllocatorsTest.java
- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Processors.java
- servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleUrlClient.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java
One of our tests did not take into account that on jdk24
no unsafe is present, in which case the PREFER_DIRECT allocator
would also fall back to heap allocations.
Also, some javadocs are now errors so those had to be fixed
as well.
> Add JDK 24 to the CI matrix and fix the build

- .github/workflows/ci-prb-reports.yml
Motivation:
#3234 added `macos-latest` to `ci-prb.yaml`, but forgot to add it to `ci-prb-reports.yaml` too.
> Add `macos-latest` to the `ci-prb-reports.yaml`

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/ServicetalkSpanStatusExtractor.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/ServicetalkSpanStatusExtractorTest.java
Motivation:
Our span status extraction is out of sync with the OTEL semantic conventions. Specifically, we should leave the span status (different from the HTTP status) unset a lot more often.
See https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status for details.
Modifications:
- Leave status unset for 1xx-3xx.
- Leave status unset for 4xx on the server side.
- Leave status unset for 600+ since we don't know what it means.
Result:
Better conformance with the spec.
> opentelemetry-http: make span status extraction conform to semconv

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpRequesterFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpServiceFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequesterFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServiceFilter.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServiceFilterTest.java
Motivation:
These filters don't follow the correct naming convention of *ServiceFilter and *RequesterFilter.
Modifications:
Rename them. We do so by creating a package private abstract base class and then extending it twice: once with the correct filter name and once with the old filter name for API compatibility. We also remove deprecated constructors for the new version.
Result:
Better organized code.
> opentelemetry-http: Rename the OTEL Request and Server filters

- .github/workflows/ci-prq-reports.yml
- .github/workflows/ci-prq.yml
Motivation:
We have a lot of jobs in our build and run each of them against every JDK version we want to support. The for quality checks, this is unnecessary because we only emit artifacts for JDK 8 and 11.
Modifications:
Reduce the PR quality checks to only run for JDK 8 and 11.
Result:
Less build work.
> Reduce PR quality matrix to just JDK 8 and 11

- servicetalk-log4j2-mdc-utils/build.gradle
- servicetalk-log4j2-mdc-utils/gradle.lockfile
- servicetalk-log4j2-mdc/build.gradle
Motivation:
In log4j-mdc, we have a dependency on log4j-core but don't include the bom. This can lead to issues since the transitive dependency is now not fully defined.
Modifications:
Add the bom dependency.
> log4j-mdc: Fix dependencies

- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CacheConnectionHttpLoadBalanceFactoryTest.java
Use `LoadBalancers` instead of deprecated `RoundRobinLoadBalancers`.
> CacheConnectionHttpLoadBalanceFactoryTest: Avoid using deprecated LB API

- servicetalk-concurrent-api/build.gradle
- servicetalk-http-router-jersey/build.gradle
- servicetalk-http-router-jersey3-jakarta10/build.gradle
- servicetalk-http-router-jersey3-jakarta9/build.gradle
- servicetalk-log4j2-mdc/build.gradle
- servicetalk-opentelemetry-asynccontext/build.gradle
- servicetalk-transport-netty-internal/build.gradle
This is a strategy for making it correct for both generated `pom.xml` and `*.module` files:
1. Add platform bom to the same scope that uses any of its dependencies.
2. There is no need to add a platform bom again under `*Implementation` scope if it was already defined under `*Api` scope.
Result:
Correctly produced `pom.xml` and `*.module` files.
> Correct how platform boms are defined

- .github/workflows/ci-netty-snapshot.yml
After 4.2.0.Final release, we should point to the next versions instead of the latest RC.
> ci-netty-snapshot.yml: point to Netty 4.2.+

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/DefaultHost.java
- servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/DefaultHostTest.java
Motivation:
When we create new connections we append them to the connection list. This means that oldest connections always have highest priority but this can cause trouble if there is correlated connection churn.
Modification:
Insert new connections into random positions in the list. This will still let unnecessary connections idle out, but new connections have a good chance at becoming a high use connection.
> loadbalancer: insert connections to host in random order

- servicetalk-bom/build.gradle
Motivation:
Currently, `servicetalk-bom` has 2 modules that should not be there:
1. `serialization` that leaks from `:servicetalk-examples:http:serialization`. This is a broken reference because we don't even publish it as an artifact.
2. `servicetalk-benchmarks` that we do not expect users to use.
See https://repo1.maven.org/maven2/io/servicetalk/servicetalk-bom/0.42.56/servicetalk-bom-0.42.56.pom
Modifications:
Adjust `findAll` closure in `servicetalk-bom/build.gradle`.
Result:
`servicetalk-bom` contains only published libraries that we expect users to use.
> Fix a list of modules inside `servicetalk-bom`

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/EarlyAndLateConnectionAcceptorTest.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/EarlyConnectionContext.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/EarlyConnectionAcceptor.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/LateConnectionAcceptor.java
Motivation:
There are use-cases, when users need to track a lifecycle of accepted connections. For example, maintaining a counter of open connections to make accept/reject decisions.
Modifications:
- Add `accept(ConnectionContext)` overload for `EarlyConnectionAcceptor` and `LateConnectionAcceptor`.
- Add default implementation to maintain backward compatibility.
- Change `TcpConnectionInfo` to `EarlyConnectionContext` and extend `NettyChannelListenableAsyncCloseable`.
- Update code references and tests to use the new method where possible.
Result:
Implementations of `EarlyConnectionAcceptor` and/or `LateConnectionAcceptor` can track connection lifecycle.
> Change `[Early|Late]ConnectionAcceptor` API to accept `ConnectionContext`

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpRequesterFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpServiceFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpRequesterFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilter.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentEncodingTest.java
Motivation:
The current behavior around the Vary HTTP header has two issues associated:
- It is a response-only header, so the client should not send it when sending a compressed payload.
- The Vary header describes the parts of the request message that influenced the content of the response it occurs in. This in practice means for a server to return Accept-Encoding, but we return Content-Encoding which is not correct.
Modifications:
This changeset first makes sure that the client actually never sends the vary header with its request, even if the payload is being compressed. Then, if the vary header is set by the server side it is not set to Content-Encoding but rather to Accept-Encoding, which influenced the compression decision on the response from the incoming request.
Result:
Vary …
> Tighten usage of Vary HTTP header

- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequesterFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServiceFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/TestHttpLifecycleObserver.java
Motivation:
We want to make sure our request observers are able to see the right spans and add attributes.
Modifications:
Reuse the TestHttpLifecycleObserver that we have built out for the server side.
Result:
Better test coverage.
> opentelemetry-http: Enhance OpenTelemetryHttpRequesterFilterTest

- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RandomSubsetter.java
Motivation:
The log message for the number of unhealthy elements is totally wrong.
Modifications:
Fix it.
Result:
More correct logs.
> loadbalancer: fix subsetting log

- .github/pull_request_template.md
When people outside our team contribute, they are not familiar with our PR description style.
- Adds `.github/pull_request_template.md` file.
GitHub UI will automatically pre-populate PR description with our template when someone opens a PR.
> Add a template for Pull Request descriptions

- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcLifecycleObserver.java
- servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/NoopGrpcLifecycleObservers.java
- servicetalk-grpc-netty/gradle/spotbugs/test-exclusions.xml
- servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcRequestTracker.java
- servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLifecycleObserver.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/NoopHttpLifecycleObservers.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpMessageDiscardWatchdogServiceFilter.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestTracker.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NoopHttpLifecycleObserver.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionObserverEventOrderTest.java
- servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/TestHttpLifecycleObserver.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
`[Http|Grpc]LifecycleObserver` and all other observers related to it, like `HttpExchangeObserver`, etc. have quite a lot of methods but users are not interested in all of them at the same time. However, the current interface definition forces users to maintain a lot of boilerplate code.
Modifications:
- Add default implementations for all `HttpExchangeObserver` methods and for methods of other related observers.
- Remove boilerplate from existing observer implementations.
Result:
`[Http|Grpc]LifecycleObserver` implementations that are interested only in subset of callbacks will be able to remove boilerplate code.
Similar to #3297.
> `[Http|Grpc]LifecycleObserver`: let users skip uninterested callbacks

- .github/workflows/ci-release.yml
Motivation:
We need to make a curl command to a specific central portal endpoint to perform what is analogous to the 'close' step in OSSHR.
Modifications:
Add that as a step in our release CI job.
> Run equivalent of 'closing' the repo after the publish job completes successfully

- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/AbstractTrafficResilienceHttpFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java
- servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilter.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilterTest.java
- servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilterTest.java
Motivation:
We don't currently track the request lifetime with our capacity limiters but these can be particularly relavent if we're streaming bidirectionally.
Modifications:
Also track the request body.
Result:
More correctness.
> traffic-resilience-http: Consider the request body for ticket lifetimes

- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
Motivation:
`DefaultHttpServerBuilder` is a pkg-private class that was marked as non-final in #3221 to accommodate access to `alterFilters` method for testing. However, all its other methods can be marked as `final`. That will avoid warning when ctor uses any of its methods, like in #3307.
Modifications:
- Mark all `DefaultHttpServerBuilder` methods as `final` except `alterFilters` that we use in tests.
Result:
No IntelliJ IDEA inspection warnings if `socketOption` method is used in constructor.
> Make all `DefaultHttpServerBuilder` methods `final` except one we need

- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FirstAndTailToPackedSingle.java
- servicetalk-data-jackson/src/main/java/io/servicetalk/data/jackson/ByteArrayJacksonDeserializer.java
- servicetalk-data-jackson/src/test/java/io/servicetalk/data/jackson/JacksonSerializationProviderTest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToBlockingStreamingHttpService.java
- servicetalk-http-api/src/test/java/io/servicetalk/http/api/StrategyInfluencerChainBuilderTest.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionFactoryFilterTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
- servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/resources/AsynchronousResources.java
- servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinSelector.java
- servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/DefaultSerializer.java
We use `@ElementsAreNonnullByDefault` annotation everywhere. There is no need to have `@Nonnull` annotations by default except some minor cases where we override `@Nullable` into `@Nonnull`.
- Remove all `@Nonnull` cases that repeat default behavior.
No redundant `@Nonnull` annotations in our codebase.
> Remove redundant `@Nonnull` annotations

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpRequest.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractHttpMetaData.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpContextKeys.java
- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequests.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
- servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpConnectionTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2StreamIdContextTest.java
Multiplexed protocols, such as HTTP/2 and HTTP/3, utilize virtual streams for each request. The stream ID is unknown upfront and is assigned by the protocol at the time client sends metadata (headers). Currently, there is no way for client-side to know what the stream ID assigned for a request was.
- Introduce `HttpContextKeys.STREAM_ID` key as a way to query stream ID value from request context, and adjust H2 codec to do so.
- Add tests to validate new behavior.
`STREAM_ID` value is assigned for a request context as soon as request metadata is sent. Users can extract it and correlate with other logs and events. The ID is updated on every retry of the same request instance.
> Propagate HTTP/2 streamId to request context

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/HttpAttributesGetter.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/HttpAttributesGetterTest.java
Network attributes are used for both client and server sides but we currently only extract them on the server side. This will cause client connection filters to unexpectedly miss the peer address info even though it's available.
Always extract the attributes.
> opentelemetry-http: HttpAttributesGetter should always try to extract network attributes

- servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
We rely on some behaviors of our RS implementation in StreamingHttpPayloadHolder. Those assumptions are unlikely to change so the best thing to do is document them.
Add a comment.
More understandable code for the next person who reads it.
> http-api: document assumptions in StreamingHttpPayloadHolder

- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
- servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java
We have copy constructors for our Tcp[Client|Server]Config types but they don't copy the mutable maps internal to them.
Copy the maps.
> tcp-netty-internal: copy maps in copy contructors

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpRequesterFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpServiceFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcClientAttributesExtractor.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcInstrumentationHelper.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcSemanticAttributesExtractor.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcServerAttributesExtractor.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/HttpInstrumentationHelper.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/InstrumentationHelper.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryFilterBuilder.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequestFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequesterFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServerFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServiceFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/OpenTelemetryOptions.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryGrpcFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequesterFilterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpServiceFilterTest.java
Filters were taking multiple separate parameters (OpenTelemetry, componentName, etc.) making the internal API verbose and difficult to extend. Need to consolidate these parameters for cleaner internal APIs and easier future extensibility.
Consolidated our configuration into filter builders. We use a shared internal class for common parameter configuration but still have separate builders for clients and servers so we can specialize.
Builders are now the main entry point.
> opentelemetry-http: consolidate filter parameters into OTEL filter builders

- servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/BlockingUdsServer.java
- servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
- servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcSemanticAttributesExtractor.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcServerAttributesExtractor.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/HttpAttributesGetter.java
- servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DomainSocketAddress.java
- servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
Motivation:
In ServiceTalk codebase we don't use "get/set" prefixes.
Modifications:
- Deprecate `DomainSocketAddress.getPath()` and introduce `DomainSocketAddress.path()` instead.
Result:
Consistent method naming.
> Deprecate `DomainSocketAddress.getPath()` in favor of `path()`

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpRequesterFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/AbstractOpenTelemetryHttpServiceFilter.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/HttpInstrumentationHelper.java
- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/RequestInfo.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/HttpAttributesGetterTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/HttpSpanStatusExtractorTest.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryHttpRequesterFilterTest.java
If users are inserting the OTEL requester filter as both a client filter and a connection filter it can be kind of confusing since both spans will look identical.
Prepend 'Physical ' to the connection level spans if we determine that there is a parent logical filter in place.
Clearer traces.
> opentelemetry-http: append 'Physical ' to physical span names

- servicetalk-opentelemetry-http/src/main/java/io/servicetalk/opentelemetry/http/GrpcSpanNameExtractor.java
- servicetalk-opentelemetry-http/src/test/java/io/servicetalk/opentelemetry/http/OpenTelemetryGrpcFilterTest.java
We prefix HTTP span names with 'Physical ' if we detect that we've inserted the filter in two positions. However, we forgot to do that for grpc.
Add that feature to the grpc filters.
More consistency.
> opentelemetry-http: add the 'Physical ' prefix to grpc spans
