apple/servicetalk

docs/modules/ROOT/pages/programming-paradigms.adoc
servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc

Motivation:
When the page is missing a 1st level header Antora can not infer a page
title and puts `Untitled` instead.
Modifications:
- Decrease level of headers on `Programming Paradigms`,
`HTTP Examples`, and `gRPC Examples` pages;
Result:
Antora correctly generates titles for `Programming Paradigms`,
`HTTP Examples`, and `gRPC Examples` pages.
---
For example, see https://apple.github.io/servicetalk/servicetalk-examples/0.19/http/index.html
Antora generates `Untitled :: ServiceTalk Docs` for tabs in the browser.

Fix missed titles in Antora docs

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy

Motivation:
For cases when publishing repositories are configured by the environment
we should not configure sonatype repo.
Modifications:
- Configure `sonatype` publishing repo only if no other repos are
configured;
- Name for this `sonatype` repo;
Result:
`sonatype` publishing repo will be configured only if there are no other
repos.

Don't configure sonatype repo if another repository is already configured

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java

Motivation:
The whitespace between the `:` and a header value is optional [1] but we
consider it as required [2] hence skip a character after the `:`. As a result,
a header value may miss the first character.
[1] https://tools.ietf.org/html/rfc7230#section-3.2
[2] `header-field = field-name ":" OWS field-value OWS`
Modifications:
- Do not skip a character after `:`;
- Add more tests for headers with no whitespace and for mixed
whitespaces;
Result:
Headers parser does not skip the first value character when there is no
whitespace after `:`.
Resolves #854

Parse headers with no whitespaces

---

README.adoc
servicetalk-grpc-gradle-plugin/README.adoc

__Motivation__
ServiceTalk is now available through Maven Central.
- Include coordinates and badge for maven central
- Remove coordinates for Bintray
__Result__
Folks can get artifacts from the default respositories

Update README with maven-central info

---

scripts/publish-docs.sh

Motivation:
When Antora generates a new docs website it overrides `index.html` page
for all existing javadocs with its placeholder. The script should
discard changes of `index.html` for older versions.
Modifications:
- Discard changes of `index.html` files for older javadoc versions;
Result:
Antora does not override javadoc with its placeholder.

Do not override older javadoc with anotra's placeholder

---

CONTRIBUTING.adoc
README.adoc

__Motivation__
We encourage people to use GitHub issues for communication with project maintainers but the information is arguably hidden in `CONTRIBUTING.adoc`.
Move `Project Communication` section to the `README.adoc`
__Result__
Users have a better view of how they are expected to communicate with project maintainers.

Make "project communication" guideline more discoverable

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BlockingGrpcClient.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionContext.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/FilterableGrpcClient.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClient.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientCallFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFilterFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionContext.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java

__Motivation__
HTTP clients provides a way to fetch the `ExecutionContext` with which the client was created. This was missed for gRPC.
- Add `executionContext()` method for `GrpcClient` and `BlockingGrpcClient`.
- In order for the generated clients to provide this information, we need to provide the same in `GrpcClientCallFactory`.
- For generated clients that delegate to filters, in order to provide this information, we need to make it as part of generated filterable clients. Generated filterable clients were not using any interface which made it hard to add this new method. Added a new interface `FilterableGrpcClient` which provides contract for filterable clients.
- Generated filterable clients (and filters) were incorrectly having the blocking `close()` method,which …

gRPC clients do not provide `ExecutionContext`

---

servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/DefaultFallbackServiceStreaming.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/DefaultFallbackServiceTest.java

Motivation:
Currently `DefaultFallbackServiceStreaming` returns response without specifying the charset parameter in the `Content-Type` header. This would confuse the client when it needs to parse the payload. Extra response handling logic is needed on client side to either abort parsing or guess the character encoding.
Modifications:
- Set charset to UTF-8 in the `Content-Type` header.
Result:
Character encoding is specified explicitly.

Declare character encoding in responses returned from fallback service

---

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ThrowableUtil.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingUtils.java

__Motivation__
BlockingUtils should not assume the cause of ExecutionException is not null.
Add method `BlockingUtils.executionExceptionCause` that returns nonnull
cause or original throwable.
__Result__
Fixes #870.

BlockingUtils should not assume the cause of ExecutionException is not null #870

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
Currently `HeaderUtils.hasContentType` returns true if headers contain `application/x-www-form-urlencoded; charset=UTF-8`, no matter what the expected charset is. This causes `FormUrlEncodedHttpDeserializer` with UTF-16 charset attempting to deserialize UTF-8 encoded payload.
Modifications:
- Fix evaluation order in `HeaderUtils.hasContentType`
Result:
Method behaves as expected.

Fix evaluation order in HeaderUtils.hasContentType

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseStatus.java

Motivation:
Add missed HttpResponseStatus constants
Modifications:
Add http status codes:
- 103 Early Hints
- 208 Already Reported
- 226 IM Used
- 451 Unavailable For Legal Reasons
- 508 Loop Detected
Result:
Fixes #871

Add missed HttpResponseStatus constants #871

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultClassHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultTypeHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpStringDeserializer.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/FormUrlEncodedHttpDeserializerTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
When users attempt to deserialize a response that has the wrong content-type, they receive an exception that lists all the headers, but with `<filtered>` as the value, making it hard to diagnose.
Modifications:
- Add a new debug filter `DEFAULT_DEBUG_HEADER_FILTER` to the class `HeaderUtils`.
- Modify the following classes [`DefaultClassHttpDeserializer`, `DefaultTypeHttpDeserializer`, `FormUrlEncodedHttpDeserializer`, `HttpStringDeserializer`] and change the method `checkContentType` to call `headers.toString(DEFAULT_DEBUG_HEADER_FILTER)`.
- Add tests to cover the new SerializationException messages.
Result:
Better debugging info in `SerializationException` when attempting to deserialize invalid
`content-type`.
Fixes #878

Add http headers values to serialization exception message

---

gradle.properties
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
Update grpc-java to 1.25.0
Modifications:
added `assertFallbackStatus` method to check new behaviour of `io.grpc.protobuf.StatusProto.fromStatusAndTrailers`
Result:
Fixes #877

Update grpc-java to 1.25.0 #877

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultClassHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultTypeHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedHttpDeserializer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpStringDeserializer.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
Currently there is duplication in checkContentType in:
- `DefaultClassHttpDeserializer`
- `DefaultTypeHttpDeserializer`
- `FormUrlEncodedHttpDeserializer`
- `HttpStringDeserializer`
where `checkContentType` method is identical in all classes.
Modifications:
- Remove `checkContentType` from `DefaultClassHttpDeserializer`
- Remove `checkContentType` from `DefaultTypeHttpDeserializer`
- Remove `checkContentType` from `FormUrlEncodedHttpDeserializer`
- Remove `checkContentType` from `HttpStringDeserializer`
- Add `checkContentType(HttpHeaders, Predicate<HttpHeaders>)` to
`HeaderUtils`
- Replace calls to `checkContentType(headers)` with calls to
`HeaderUtils.checkContentType(headers, checkContentType)`
in all 4 HttpDeserializers
Result:
Less code duplication.
Resolves: #886

Refactor check content type http api

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseStatus.java

Motivation:
Enhance javadoc for HTTP status code constants in HttpResponseStatus
class with links to the related RFC sections.
Example:
```
/**
* 100 Continue
*
* @see <a href="https://tools.ietf.org/html/rfc7231#section-6.2.1">RFC7231, section 6.2.1</a>
*/
public static final HttpResponseStatus CONTINUE = new HttpResponseStatus(100, "Continue");
```
Results:
Resolves #884

Add RFC links for each HttpResponseStatus constant

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponseFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseStatus.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponseFactory.java

Motivation:
`http-api` `HttpResponseStatus` error codes 413, 414, 416, 425 do not
follow the most recent standards, defined by:
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
therefore we should update the `HttpResponseStatus` error code names.
Modifications:
- update the following fields in `HttpResponseStatus`:
- 413 `REQUEST_ENTITY_TOO_LARGE` to `PAYLOAD_TOO_LARGE`.
- 414 `REQUEST_URI_TOO_LONG` to `URI_TOO_LONG`.
- 416 `REQUESTED_RANGE_NOT_SATISFIABLE` to `RANGE_NOT_SATISFIABLE`.
- 425 `UNORDERED_COLLECTION` to `TOO_EARLY`.
- update `private static HttpResponseStatus valueOf(int)` to return
the updated `HttpResponseStatus` for 413, 414, 416, 425.
- update `HttpResponseFactory` to create the updated error codes.
- update `BlockingStreamingHttpResponseFactory` …

Adhere http api response status error code names to rfc standards

---

servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableDirectByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeDirectByteBuf.java

Motivation:
ServiceTalk doesn't expose reference counting and relies upon GC for memory
reclamation. Buffer objects are resizable an in the event a buffer is resized
(e.g. a write operation needs to expand the buffer) this will result in
allocating new memory and Netty will attempt to deallocate the old memory.
Applications may be multi-threaded and it is possible another thread will still
have a reference to this old memory location due to visibility constraints. We
should prevent Netty from force-freeing this old memory and instead rely upon GC
to avoid undefined behavior.
Modifications:
- ServiceTalk DirectByteBuf implementations to override freeDirect(ByteBuffer)
and do nothing.
Result:
Less risk for resize operation resulting in referencing freed memory.

DirectByteBuf implementations should not force free memory

---

servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableDirectByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeDirectByteBuf.java

Motivation:
0c4280dcc59dd2a8c21f29ddf12f04a1e85c4141 attempted to avoid reclaiming of old
memory when resized for cases where the memory maybe shared by multiple threads.
However modifying a Buffer accross mulitiple threads may lead to visibility
issues where the reference to the new array maybe visible before the memory is
copied into the array, and in general requires external synchornization.
Modificiations:
- Revert the freeDirect(ByteBuffer) override introduced in
0c4280dcc59dd2a8c21f29ddf12f04a1e85c4141
Result:
We can reclaim intermediate memory from resize operations again.

Revert 0c4280dcc59dd2a8c21f29ddf12f04a1e85c4141

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponseFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponseFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseFactoryStatusCodeTest.java

Motivation:
Add 5 http status methods for HttpResponseFactory, BlockingStreamingHttpResponseFactory and StreamingHttpResponseFactory
Modifications:
add methods to BlockingStreamingHttpResponseFactory
add methods to HttpResponseFactory
add methods to StreamingHttpResponseFactory
add test HttpResponseFactoryStatusCodeTest
Result:
Fixes #889

Add recently added new status codes to response factories #889

---

servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/netty/HttpResponseDecoderBenchmark.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/ServiceTalkBufferAllocator.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableCompositeByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableDirectByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableHeapByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeDirectByteBuf.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ByteToMessageDecoder.java

Motivation:
ServiceTalk attempts to effectivley disable Netty's reference counting by using
a strategy similar to Netty's `UnreleasableByteBuf` to short circit operations
which attempt to modify the reference count, and therefore prevent the reference
count from reaching zero and prematruley freeing memory. ServiceTalk's
ByteBuf instances will therefore always have a `refCnt() == 1`. However Netty's
ByteToMessageDecoder uses `refCnt() > 1` to determine if the cumulation ByteBuf
maybe shared, and if not it may compact data in place. This compacting data in
place may result in a corrupted view of data from the perspective of offloaded
threads in ServiceTalk, and for example result in failures to decode HTTP/2 data
such as gRPC frames.
ServiceTalk's `ByteToMessageDecoder` uses Netty's …

HTTP/1.x and HTTP/2.0 decoder Buffer visibility and data corruption

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java

Motivation:
https://tools.ietf.org/html/rfc7230#section-3.2.4 specifies that spaces are
prohibited between the end of the header-name and the colon. Our header parsing
is currently liberal and allows a space. This may leave us vulnerable to HTTP
request smuggling.
Modifications:
- HttpObjectDecoder should prevent white space before the colon when paring
header-name field
Result:
HTTP/1.x header parsing follows
https://tools.ietf.org/html/rfc7230#section-3.2.4

Disallow space after header name and colon

---

servicetalk-grpc-protoc/build.gradle

Motivation:
Currently, `:servicetalk-grpc-protoc:buildExecutable` task runs after
`classes` task. `classes` task depends on `compileJava`. Therefore,
when we do `./gradlew clean compileJava` it doesn't trigger
`:servicetalk-grpc-protoc:buildExecutable` and grpc examples compilation
fails.
Modifications:
- Finalize `:servicetalk-grpc-protoc:compileJava` task by `buildExecutable`;
Result:
`./gradlew clean compileJava` works fine.
Follow up for #823

Run protoc:buildExecutable task right after `compileJava`

---

servicetalk-concurrent-reactivestreams/src/main/java/io/servicetalk/concurrent/reactivestreams/ReactiveStreamsAdapters.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/ReactiveStreamsAdaptersTest.java

__Motivation__
As part of reviewing https://github.com/apple/servicetalk/pull/904 following issues were observed in `ReactiveStreamsAdapters`:
- One method Javadoc had a typo linking to the wrong class.
- Name of internal classes were not consistently indicating the intent.
- Internal class `PublisherToRSPublisher` is redundant, we can instead use `PublisherSourceToRSPublisher`
- Fixed javadoc
- Renamed classes to follow [Rs, St]To[Rs, St][Publisher, Subscriber, Subscription] format
- Inlined a variable in the test.
__Result__
Better readability for `ReactiveStreamsAdapters`

Minor updates to reactive-streams adapter

---

scripts/publish-docs.sh

__Motivation__
A prior fix to avoid overwriting javadoc indexes for older versions with the antora placeholders introduced an issue where SNAPSHOT docs were no longer being updated.
- Change the approach to filtering which ensure only the javadocs indices are reset
- Fix an issue with javadocs for SNAPSHOT not cleaning up older versions of removed or renamed classes
__Result__
Correct docs.

Publishing of docs didn't update SNAPSHOT versions.

---

servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java

__Motivation__
gRPC generated code uses an `Enum` to define all RPC paths. It is convenient to have all paths together but they are detached from the actual RPC methods for which the paths are defined.
- Remove `RpcPaths` `Enum` from generated code.
- Generate a `PATH` constant for all individual RPC interfaces.
- Async interfaces defines the `PATH` constant with the actual path `String`.
- Blocking interfaces define the `PATH` constant which referr to the async `PATH` constant.
__Result__
RPC paths are attached to the associate RPC interfaces.

Move RPC paths to generated RPC interfaces

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
Many existing services don't include charset in `Content-Type` header.
Therefore it would be convenient to have a default (UTF-8) deserializer
that can handle payload if charset is UTF-8 or no charset is specified.
Modifications:
- Add a rule to `hasContentType` method to accept no charset case when
the expected charset is UTF-8.
Result:
The default `textDeserializer` and `formUrlEncodedDeserializer` can
deserialize payload of request/response with no charset in
`Content-Type` header.

Allow default deserializers to handle payload without specified encoding

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/AbstractBasicAuthSecurityContextFilterTest.java

Motivation:
`HttpRequestMethod` and `HttpResponseStatus` are classes with static
constants, not enums. We should use `equals` to compare them. Otherwise,
users' implementation of these classes won't work correctly.
Modifications:
- Replace all `==` and `!=` for `HttpRequestMetaData.method()` and
`HttpResponseMetaData.status()` with `equals`;
Result:
Correct comparison of `HttpRequestMethod` and `HttpResponseStatus`
objects.

Do not compare request methods and response statuses by reference

---

servicetalk-concurrent-jdkflow/gradle/spotbugs/main-exclusions.xml

__Motivation__
ServiceTalk `Subscriber` allows passing `null` values in `onNext` but JDK flow does not provide any guidance hence defaulting to non-null. Spotbugs does not like this inconsistency but does not complain consistently (ironically 🙂)
As this is an expected situation for the JDK flow adapter, add a spotbugs exclusion.
__Result__
Spotbugs does not complain for this intentional inconsistency.

Spotbugs exclusion for JDK flow

---

servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/protoc/GeneratorTest.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java

Generated gRPC RPC interfaces should be annotated as `@FunctionalInterface` #908
Motivation:
Generated gRPC RPC interfaces should be annotated as `@FunctionalInterface` #908
Modifications:
- Add `@FunctionalInterface` to generated interfaces as part of the method addServiceRpcInterfaces():
Result:
Fixes #908

Generated gRPC interfaces should be annotated as `@FunctionalInterface`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteSingleSubscriber.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteSingleSubscriberTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

__Motivation__
WriteStreamSubscriber is not aware of payload boundaries, hence when a Channel becomes suddenly inactive (closed or output shutdown) it could only assume the write failed. In case of H2 the codec would perfom an output shutdown after observing and emitting trailers. This output shutdown would race with write publisher completion and occasionally result in WriteStreamSubscriber failing the write with an error even though it actually completed normally.
- H1/H2 codecs emit payload boundaries via CloseHandler
- CloseHandler triggers a new UserEvent on outbound payload end
- DefaultNettyConnection intercepts above event and notifies WriteListener (WriteStreamSubscriber)
- WriteStreamSubscriber responds to 2 triggers for write source stream completion …

Protocol emits payload boundary event

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkRootPlugin.groovy

Motivation:
`servicetalk-concurrent-jdkflow` depends on JDK9+, we have
to exclude it from gradle's `javadocAll` task that we create
for the root project.
Modifications:
- Exclude `servicetalk-concurrent-jdkflow` from JDK8 javadoc;
Result:
`javadocAll` doesn't fail on JDK8.

Exclude `servicetalk-concurrent-jdkflow` from JDK8 javadoc

---

scripts/publish-docs.sh

Motivation:
As part of the docs website publication we add additional
git worktree and branch. After the publication is complete we
clean up this state. However, if the script failed with an
error, the second run will start from the intermediate git state.
Modifications:
- wrap clean up steps to a function
- invoke the clea up function before and after the docs publication;
Result:
We can safely re-run `publish-docs.sh` script even if the previous
run failed.

Clean up the state before and after docs publication

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
gRPC protocol requires a server to send trailers after the response
payload body to notify a client about the status of this response
processing. We add trailers for all service APIs except
`BlockingStreamingRoute` when service responds successfully.
Modifications:
- Add trailers with `grpc-status: 0` if `BlockingStreamingRoute`
responds without errors;
Result:
Server sends a complete response with trailers from
`BlockingStreamingRoute`.

Add trailers after gRPC `BlockingStreamingRoute` response

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFactory.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java

Motivation:
gRPC server allows users to register routes in different ways:
- using multiple instances of `ServiceFactory`;
- using `ServiceFactory.Builder` with different
`GrpcExecutionStrategy` configuration;
- using `ServiceFactory.Builder` with different API variants;
Users can accidentally misconfigure the router by registering
the same RPC more than once. Currently, gRPC server silently
overrides the old RPC with the new one. It may lead to
unexpected behavior in production and hard to diagnose issues.
Modifications:
- Throw `IllegalStateException` when users register an RPC for
the same path more than one time;
- Add tests to verify that exceptions will be thrown;
Result:
Users will be notified at the build time if they registered
multiple RPC implementations for the same path.

Prevent misconfigurations for gRPC router

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java

Motivation:
When gRPC-server doesn't have a requested route it should respond
with an error status `UNIMPLEMENTED` to propagate the error to the
client.
Modifications:
- Change `NOT_FOUND_SERVICE` to return `UNIMPLEMENTED` grpc-status;
- Add required `content-type` header for not-found response;
- Add a test to verify that client throws `GrpcStatusException`
when it requests a route that is not registered on the server;
Result:
Client throws `GrpcStatusException` when it requests a route that
is not registered on the server.

gRPC-server should return `UNIMPLEMENTED` when route is not found

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java

__Motivation__
When using H2 as the transport with HTTP clients, if query parameters are present in the request, they get ignored while writing the request on the network.
`H2ToStH1ClientDuplexHandler` is using `request.path()` as the value for the `:path` pseudo-header in H2. `path()` omits query parameters. Now using `requestTarget()`.
__Results__
Query parameters are preserved when using H2 transport.

H2 client ignores query parameters

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouteConversions.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTestServices.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
When users append a service filter using `ServiceFactory`, it
reconstructs the `GrpcService` interface from registered routes,
wraps it with the filter, and re-registers the service again as
independent routes. This logic does not preserve the execution
strategy that was used to register the original route and it
uses the default strategy for a route.
Modifications:
- Save the route execution strategy if it was configured for the
original route;
- Use the saved execution strategy when we re-register filtered
routes;
- Add tests to verify the execution strategy configuration when
users apply a filter;
- Add tests to verify grpc router does not extract execution strategy
annotations from filters;
- Close `GrpcPayloadWriter` in the conversion layer from
`BlockingStreamingRoute` …

gRPC filters override configured execution strategy for the route

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatusCode.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java

Motivation:
gRPC protocol requires server to send grpc-status code as part
of the response. It may come in headers (when there is no
payload body) or in trailers. Current implementation considers
responses without `grpc-status` as legit responses.
Modifications:
- Ensure that the response object contains `grpc-status` code;
- Tests to verify that client throws an exception when server
does not send `grpc-status`;
Result:
gRPC-client throws an exception when server does not send
`grpc-status`.

gRPC-client should fail responses without grpc-status code

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ByteToMessageDecoder.java

Motivation:
`ByteToMessageDecoder` does not release the received
`ByteBuf` message when it copies data to the cumulation
buffer. It's not an issue at this moment, because we always
see unpooled buffers here (because `CopyByteBufHandler`
copies data to unpooled memory), but we should release
any way to prevent memory leaks if this assumption changes.
Modifications:
- Add `try-finally` block to release inbound `ByteBuf` after
we copied it to the cumulation buffer;
Result:
No memory leaks in `ByteToMessageDecoder`.

Avoid potential memory leak in `ByteToMessageDecoder`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeaderNames.java

**Motivation**
Enhance javadoc for HTTP header name constants in HttpHeaderNames class with links to the related RFC sections.
**Modifications**
Adding `@see` like:
```
@see <a href="https://tools.ietf.org/html/rfc7230#section-6.1">RFC7230, section 6.1</a>
```
in `HttpHeaderNames.java` file for constants.
**Result**
javadoc for HTTP header name constants will be updated with related RFC sections.
Fixes: https://github.com/apple/servicetalk/issues/885

Adding RFC links for standardised HttpHeaderNames constants in javadoc

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java

Motivation:
`HttpObjectEncoder` internally allocates buffers that will be
passed to the transport or `OPENSSL` handler, both require direct
memory for processing. We should explicitly allocate direct memory
in outbound handler to prevent from slowing down (by introducing
additional copying from heap to direct memory) when users specify
`io.netty.noPreferDirectFlag=true` system property.
Modifications:
- Explicitly allocate direct pooled buffers in `HttpObjectEncoder`;
Result:
Buffers allocated in `HttpObjectEncoder` will always use direct
pooled memory and won't be copied by transport or `OPENSSL` handler.

`HttpObjectEncoder` should always allocate direct outbound buffers

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

**Motivation**
Missing `when*` operators for async sources `Publisher`, `Single` and `Completable`
**Modifications**
Defining: 
**Result**
Above Operators will behave like `after*` .
Fixes: https://github.com/apple/servicetalk/issues/926

`when*` operators for async sources

---

docs/modules/ROOT/pages/performance.adoc
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConcurrentRequestsHttpConnectionFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpAuthConnectionFactoryClientTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionEmptyPayloadTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerMultipleRequestsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionDrainTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/CancellationTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java

Motivation:
In some cases we need to consume payload body and trailers.
We usually use `payloadBody().ignoreElements()` pattern.
However, since the request or response comes from the network,
it's more efficient to do `payloadBodyAndTrailers().ignoreElements()`
to avoid splitting trailers from payload body.
Modifications:
- Replace all `payloadBody().ignoreElements()` usages with
`payloadBodyAndTrailers().ignoreElements()`;
- Do the same in tests for consistency;
- Update `performance.adoc` to demonstrate `payloadBodyAndTrailers`
for the draining use-case;
Result:
Less overhead when we need to drain payload body.

Use `payloadBodyAndTrailers()` to drain payload body

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java

Motivation:
To notify server-side that ST client currently does not support
server push, client should send `ENABLE_PUSH=false` setting when it
connects to the server.
If server sends a `PUSH_PROMISE` frame, client should send `GO_AWAY`
before closing the connection.
Modifications:
- Add `ENABLE_PUSH=false` and `MAX_CONCURRENT_STREAMS=0` to
the set of initial h2 settings;
- Send `GO_AWAY` frame with `PROTOCOL_ERROR` if client receives a
`PUSH_PROMISE` frame from server;
Result:
H2 client notifies server that it does not support server push and
sends `GO_AWAY` frame before closing the connection, if server sends
a push.

H2 client should send `ENABLE_PUSH=false` setting for new connections

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilterTest.java

Motivation:
`HostHeaderHttpRequesterFilter` adds a `Host` header only for HTTP/1.1.
It leads to unnecessary parsing of request-target in
`H2ToStH1ClientDuplexHandler.write` as an attempt to fill `:authority`
pseudo-header and results in missing `:authority` pseudo-header
required by gRPC protocol.
Modifications:
- Do not add `Host` header only for HTTP/1.0 in
`HostHeaderHttpRequesterFilter`;
- Enhance `HostHeaderHttpRequesterFilterTest` to account for HTTP
version;
Result:
gRPC request has `:authority` pseudo-header, no overhead for parsing
request-target.

`HostHeaderHttpRequesterFilter` does not work for HTTP/2

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java

Motivation:
We use `ArrayDeque` to temporary part `channelRead` events until
we receive a `Subscription` for `NettyChannelPublisher`. By default
it allocates a queue for 16 elements, but in most cases, we have only
a few elements: headers only or headers + payloadBody + trailers.
Modifications:
- Allocate a smaller `ArrayDeque` that may fit one full request or
response object with headers + payloadBody + trailers;
Result:
Less memory allocation.

Allocate smaller `ArrayDeque` for `NettyChannelPublisher.addPending`

---

servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProvider.java
servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProviderBuilder.java

Motivation:
Current implementation of `ProtoBufSerializationProvider` has a
few performance issues:
1. `ProtoDeserializer` may create an intermediate copy of the composite
buffers and then copy it again inside proto parser.
2. `DefaultSerializer.DEFAULT_SIZE_ESTIMATOR` inaccurately predicts
size for destination `Buffer`. For aggregated API we may use
`getSerializedSize()` to allocate enough bytes for destination
`Buffer`.
3. `MessageLite.writeTo(OutputStream)` creates an internal copy of
data that could be avoided if we create `CodedOutputStream` from
internal data storage of destination `Buffer`.
Modifications:
- Create optimized version of `CodedInputStream` for
`ProtoDeserializer` to do less copying during proto deserialization;
- Provide a number of `bytesEstimate` for serialization …

Optimize `ProtoBufSerializationProvider` by minimizing copying

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteSingleSubscriber.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteSingleSubscriberTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Motivation:
The WriteListener interface has grown over time and its naming conventions have
become less clear. For example "closeGracefully" implies that some action is
expected to be taken to account for pending writes, but in reality this is just
a notification that the transport's outbound side has been closed and should be
interpreted accordingly by the implementation.
Modifications:
- Rename WritableListener to ChannelOutboundListener. Rename method names on
this interface to indicate they are notification of channel events and
implementations can react however they need to.
- DefaultNettyConnectionTest writes a static buffer, but doesn't duplicate() on
each use. The test now duplicates the buffer to avoid shared indexes.
- Avoid forcing error logs from WriteSingleSubscriber because …

WriteStreamSubscriber and WriteListener cleanup

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/BlockingApiCorrectnessTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java

Motivation:
gRPC `BlockingResponseStreamingRoute` is implemented as a conversion
based on `BlockingStreamingRoute`, but must ensure that there is
only one proto item in the request and fail if there are more.
Otherwise, it does not drain request `BlockingIterable` and may lead
to the leaked resources.
Modifications:
- Throw if `BlockingResponseStreamingRoute` sees the second item
in the request `BlockingIterable`;
- Throw if `BlockingResponseStreamingRoute` sees no items in the
request `BlockingIterable`;
- Make exception messages of `ResponseStreamingRoute` consistent
with `BlockingResponseStreamingRoute`;
- Add tests to verify that these cases work as expected and
blocking/async API behavior is consistent;
Result:
`BlockingResponseStreamingRoute` fails if a client sends more than
one …

gRPC `BlockingResponseStreamingRoute` expects only one request item

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/PendingStreamingClosureTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentChannelInitializer.java

__Motivation__
By default when an H2 channel is closed, netty sends go away frames as required by the spec. However, ServiceTalk provides separate close and graceful close modes for closing a connection and implements go away frame handling when graceful closure is requested by the user.
Currently, as we do not disable netty's default of go away handling, a force close also behaves like graceful closure (by sending go away frames) and we set the graceful closure timeout to `-1` for netty. This makes it such that if a request is pending (magnified for long lived streams) a client/server never closes.
Disable graceful closure for netty and add tests to verify that server and clients are eventually closed.
__Result__
H2 servers and clients can be closed even with pending …

Disable netty's go away handling for H2.

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java

__Motivation__
`ResponseCancelTest` is flaky due to a race condition that successful response or cancel will race to get to the connection filter and the result will either be success or failure.
- `cancel()` and `cancelAfterSuccessOnTransport()` tests were both doing same actions unintentionally. Modified the test to reflect the intentions.
- `cancelAfterSuccessOnTransport()` can either result in success or failure after the first request, modified test to verify the same.
__Result__
Fix tests.

Fix flakiness in `ResponseCancelTest`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpConfig.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java

Motivation:
If `MultiAddressUrl` was used to send an HTTPS request over secure
connection, all other requests to new non-secure servers will fail
with `DecoderException`. It happens because we incorrectly copy the
`HttpClientBuilder` template. We did not create a new instance of
`TcpClientConfig` and `HttpConfig`.
Modifications:
- Add copy ctor for `HttpConfig`;
- Use copy ctors for `TcpClientConfig` and `HttpConfig` in
`HttpClientConfig`;
- Add test to verify that `MultiAddressUrl` client can connect to
insecure server after connecting to a secure server and vice versa;
Result:
`HttpClientConfig` makes a full copy of `TcpClientConfig` and
`HttpConfig` that prevents the `HttpClientBuilder` template from
modifications. `MultiAddressUrl` client correctly copies the
builder template without …

MultiAddressUrl client fails to send http request after https request

---

README.adoc

Motivation:
Maven Central requires `https` schema.
Modifications:
- Change schema for Maven Central: `http` -> `https`;
Result:
Link for Maven Central works correctly.

Fix link for Maven Central

---

docs/generation/gradle/validateSite.gradle

Motivation:
We had to exclude a few links from docs website validation
because these links required additional authentication.
Now they are public and can be removed from exclusion.
Modifications:
- Remove links from `excludedLinks` list that are public now;
Result:
Better links validation for docs website.

Update list of excluded links for docs website validation

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RangeIntPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/FromIntRangePublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RangeIntPublisherTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRangeStrideTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRangeTckTest.java

Motivation:
The canonocal way to do an asynchornous for lop with integer indexes in reactive streams is to use a range() operator. We currently don't have a range operator.
Modifications:
- Add Publisher#range(int begin, int end)
- Add Publisher#range(int begin, int end, int stride)
Result:
For loops with integer indexes can be done directly with Publisher#range(..)

Publisher#range operator

---

servicetalk-client-api/docs/modules/ROOT/pages/service-discovery.adoc

Motivation:
`netty-resolver-dns-native-macos` dependency requires the `osx-x86_64`
classifier to be set.
Modifications:
- Add `osx-x86_64` classifier for `netty-resolver-dns-native-macos`
dependency in `Service Discovery` docs;
Result:
Correct dependency declaration for `netty-resolver-dns-native-macos`.

Add a classifier for `netty-resolver-dns-native-macos` in docs

---

scripts/publish-docs.sh

Motivation:
If we publish docs update for SNAPSHOT version only, `publish-docs.sh`
mistakenly overrides javadoc `index.html` page for all older versions,
because `grep -v $version` filter produces empty output when the
`$version` is empty.
Modifications:
- Apply `grep -v $version` filter only when the `$version` is not empty;
Result:
SNAPSHOT docs publication does not break older versions of the docs.

publish-docs.sh overrides javadoc for older versions when it publishes SNAPSHOT update

---

scripts/publish-docs.sh

Motivation:
Different JDK versions produce different website style for
javadoc.
Modifications:
- Make sure the current Java version is 1.8 before running
`publish-docs.sh`;
Result:
Javadoc website always published with the consistent format
and style.

Enforce JDK8 when running `publish-docs.sh`

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCollectingCompletableSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/ChannelSetTest.java

Motivation:
ChannelSetTest is flaky because it doens't wait for events to occurr that it validates.
Modifications:
- Introduce TestCollectingCompletableSubscriber which allows for tests to wait for specific conditions before delivering events and validation.
- Use this in ChannelSetTest
Result:
ChannelSetTest is more reliable.

Fix ChannelSetTest async issues

---

buildSrc/src/main/java/io/servicetalk/internal/build/ExecutableBuilder.java

Motivation:
The gRPC protoc unix script is expected to execute in a /bin/sh environment, but it depends upon pushd/popd which may not be available in /bin/sh. This may lead to a 'pushd: not found' error.
Modifications:
- Avoid using pushd in the unix script and manually save/restore the directory
Result:
gRPC protoc script can execute in limited /bin/sh environments without
failure.

gRPC protoc script pushd not found

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java

Motivation:
NettyChannelPublisher allows for resubscribes, and delivers queued data to the new Subscriber. If the previous Subscriber consumed some data and cancelled this may lead to the new Subscriber receiveing partial data from the last request.
Modifications:
- NettyChannelPublisher should discard any pending data, and deliver an error to new Subscribers if a previously active Subscriber cancels.
Result:
Resubscribes to NettyChannelPublisher won't get partial data for previous requests, like in the case of client pipelinining.

NettyChannelPublisher cancel active subscriber should terminate

---

gradle.properties
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SimpleCompletableSubscriber.java
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
servicetalk-gradle-plugin-internal/src/main/resources/io/servicetalk/gradle/plugin/internal/checkstyle/checkstyle.xml
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/RoleProtectedBasicAuthSecurityContextFilterTest.java

Modifications:
- Upgrade versions of all quality tools;
- Enable new rules for checkstyle;
- Address errors found by new checkstyle rules;

Update versions of quality tools

---

servicetalk-examples/grpc/helloworld/build.gradle
servicetalk-examples/grpc/routeguide/build.gradle
servicetalk-grpc-gradle-plugin/src/main/groovy/io/servicetalk/grpc/gradle/plugin/ServiceTalkGrpcPlugin.groovy
servicetalk-grpc-netty/build.gradle

Motivation:
There are a few issues with `servicetalk-grpc-gradle-plugin`.
Modifications:
- Fix incorrect plugin name in exception message;
- Correctly verify that `serviceTalkVersion` has correct value as
it's always not empty, but may have unprocessed value;
- Do not add `serviceTalkVersion` to the `scriptExecutableFile`
name as it's not necessary;
- Generate script only for projects that use
`servicetalk-grpc-gradle-plugin` instead of the root project;
- Do not looks for `serviceTalkGrpcProtocGenerateScript` task
before creating it;
- Delete generated script file when users run `clean` task;
- Recreate executable script file on every run to avoid having
an outdated file (for example if gradle changes the hash for
cached artifacts or if users run another project with and
without …

Follow-up enhancements for `servicetalk-grpc-gradle-plugin`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/CharSequences.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSetCookie.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java

Motivation:
There is a revision of the HTTP cookies RFC (6265) in review which adds
a new SameSite attribute
https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#section-5.3.7.
Modifications:
- Add the SameSite attribute support to the SetCookies related APIs
Result:
HttpSetCookies now support the SameSite attribute.

Add support for SameSite attribute in Cookies

---

gradle/wrapper/gradle-wrapper.properties

Motivation:
Gradle 6.3 supports JDK 14 https://docs.gradle.org/6.3/release-notes.html

Update to Gradle 6.3

---

servicetalk-buffer-netty/build.gradle
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableCompositeByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableDirectByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableHeapByteBuf.java
servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeDirectByteBuf.java
servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/BufferAllocatorsTest.java

Motivation:
For cases when `AbstractByteBuf` wraps `ByteBuf`(s) allocated by ST
with another interface (slice/duplicate/readOnly) we wrap them one
more time with `UnreleasableByteBuf`. However, this is not necessary
as our `ByteBuf`(s) are always unreleasable and final. There is no
way it can be unwrapped and released. Therefore, `UnreleasableByteBuf`
is useless and just creates more garbage for GC.
Modifications:
- Remove all methods that apply `Unpooled.unreleasableBuffer` for
returned results;
- Remove unnecessary overrides for methods that return retained
slice or duplicate;
- Add missed `final` modifiers for methods of
`UnreleasableHeapByteBuf`;
- Enhance tests to cover all API that may return a new `ByteBuf`
or a new wrapped `ByteBuf`;
- Assert that all `Buffer`s allocated by ST …

Do not wrap unreleasable ByteBuf(s) with `Unpooled.unreleasableBuffer`

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ForEachSubscriber.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PubToCompletable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ReduceSingle.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToBlockingStreamingHttpService.java

Motivation:
There are some operators which convert from Publisher to Completable or
Single. Since the demand for Completable and Single is implicit on
subscribe(..) these operators need to simulate the demand in
onSubscribe. In order to prevent concurrent access on the Subscription
with the downstream Subscriber and the synchornous requestN call it is
wrapped in a ConcurrentSubscription. However ConcurrentSubscription has
to coordinate between two methods and is inheritly more complicated than
DelayedCancellable. We can use DelayedCancellable which is a simpler
operation at the cost of requesting demand before propagating
synchronous cancel operation. This isn't perceived as a deal breaker
because demand is implicit anyways, and cancel is best effort.
Modifications:
- When converting from …

Replace ConcurrentSubscription with DelayedCancellable when synchronous request(Long.MAX_VALUE)

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/ScoreSupplier.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StaticScoreHttpProtocolBinder.java

__Motivation__
`ScoreSupplier#score()` returns a `float` today with an intent to have precisions for slightly varying scores. However floating point arithmentic adds more complexity in score computations. Instead we can use `int`s and use bigger scores for precision (eg: multiply by `1000`)
Make `ScoreSupplier#score()` return an `int`.
__Result__
Simpler score calculations.

Use `int`s as scores for `ScoreSupplier`

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableConcatWithCompletable.java

Motivation:
Completable#concatWith(Completable) currently uses an atomic operation to transition subscribe() from the first Completable to the second. However this is done in the contex of a Subscriber and the events should be sequenced in a [serial](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#1.3) fashion.
Modifications:
- Completable#concatWith(Completable) to use a regular variable instead of volatile/atomic operation to switch subscribers
Result:
Less atomic operations in Completable#concatWith(Completable).

Completable#concatWith(Completable) remove atomic operation

---

servicetalk-log4j2-mdc-utils/src/testFixtures/java/io/servicetalk/log4j2/mdc/utils/LoggerStringWriter.java
servicetalk-opentracing-asynccontext/src/main/java/io/servicetalk/opentracing/asynccontext/AsyncContextInMemoryScopeManager.java
servicetalk-opentracing-asynccontext/src/test/java/io/servicetalk/opentracing/asynccontext/AsyncContextInMemoryScopeManagerTest.java
servicetalk-opentracing-http/build.gradle
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/AbstractTracingHttpFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpServiceFilter.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TestUtils.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java
servicetalk-opentracing-http/src/test/resources/log4j2-test.xml
servicetalk-opentracing-log4j2/src/main/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMap.java
servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java

Motivation:
AsyncContextInMemoryScopeManager currently doesn't restore the previous
Scope when the current Scope is closed. This behavior is provided for
ThreadLocalScope and allows users to use try-with-resources type
constructs to create sub-spans more easily.
Modifications:
- AsyncContextInMemoryScopeManager to save/restore the previous Scope
when a new Scope is activated
- AsyncContextInMemoryScopeManager to remove the currentScope() hack so
lifetime of Scopes is more narrowly/correctly constrainted. This means
that filter ordering is important and use of after* operators should be
done with care!
Result:
AsyncContextInMemoryScopeManager has more consistent behavior with
ThreadLocalScope, and lifetimes of Scopes are more narrowly/correctly
constrainted.

AsyncContextInMemoryScopeManager to restore previous Scope on close()

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/AbstractTracingHttpFilter.java

Motivation:
BeforeFinallyOnHttpResponseOperator include the 'On' terminology which
doesn't make sense in this context as the event name doesn't include
'On' (e.g. onSubscribe). The 'Response' component can also be dropped to
simplify the naming.
Modifications:
- Rename BeforeFinallyOnHttpResponseOperator to
BeforeFinallyHttpOperator
Result:
More concise naming of BeforeFinallyHttpOperator.

Rename BeforeFinallyOnHttpResponseOperator to BeforeFinallyHttpOperator

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/SpScPublisherProcessorTest.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/FromInMemoryPublisherAbstractTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/FromSingleItemPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToPublisherTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java

Motivation:
The when* operators provide call backs to take action when that action
isn't sensitive to execution order. The current implementation of the
when* operators uses after* semantics, despite the order being explicitly
undefiend by the API. The after* semantics may result in user code
executing in unexpected times, espeically when local state is involved.
For example tracing filters utilize AsyncContext and trigger the state
cleanup on the response payload Publisher termination. This filter must
be appended first in order for the trace information to be initialized
correctly and if any subsequent filters apply a payload Publisher
transformation with after* semantics the terminal methods will be
invoked after the tracing Scope has been closed. If subsequent operators
use before* …

Change when* operators to before* instead of after*

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AmbSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompositeCancellable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleAmbWith.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableAmbTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeCancellableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbSubscribeThrowsTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbWithAsyncTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleAmbTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleAmbWithTckTest.java

__Motivation__
[`amb`](http://reactivex.io/documentation/operators/amb.html) is a useful operator for trying multiple sources and using the first result. Few cases that are common;
- Use as a windowing scheme (number of items or time as window boundarirs)
- Backup/hedge requests for clients.
Use two flavors of these operators:
- Static factory where an arbitrary number of sources can be ambiguated.
- Operator to ambiguate a source with other.
__Result__
More operators, more fun!

Add `ambWith` and `amb` methods for `Single` and `Completable`

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

Motivation:
Dangling subscribes is usually a bad idea. As RRLB is not composing the
subscribe, it will still keep closing the connection after it returns a failure.
Worse if the closure does not complete, it will keep this subscribe around
forever (and so the resources associated with the subscribe).
Modification:
- Compose new connection closure with the `Single.failed` returned from
`flatMap`;
- Add a test to verify that new connection is closed if it's rejected by
selector;
Result:
A new connection is closed before RRLB fails the returned `Single` from
`selectConnection`.

`RoundRobinLoadBalancer` should compose connection closure with error response

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AfterFinallySingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BeforeFinallySingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RunnableSingleTerminalSignalConsumer.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RunnableTerminalSignalConsumer.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleTerminalSignalConsumer.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TerminalSignalConsumer.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/AbstractWhenFinallyTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/AfterFinallyTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/BeforeFinallyTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java

Motivation:
TerminalSignalConsumer for Completable and Publisher is a top level
type, but Single has an internal type for the same purpose. This makes
it more challenging to expose utilities classes in a consistent manner
and also may lead to naming collisions.
Modifications:
- Move Single.TerminalSignalConsumer to a top level interface and rename
to SingleTerminalSignalConsumer to avoid naming collisions.
- Expose RunnableTerminalSignalConsumer and re-use it in
BeforeFinallyOnHttpResponseOperator.
Result:
More consistent type definition scheme for TerminalSignalConsumer and
SingleTerminalSignalConsumer and ability to expose conversion/utility
methods outside the scope of the Source.

Promote Single.TerminalSignalConsumer to top level interface

---

gradle.properties
servicetalk-opentracing-zipkin-publisher/build.gradle
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/LoggingReporter.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/package-info.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisherTest.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyFutureCompletable.java

Converting ZipkinPublisher to use a zipkin2.Reporter interface for reporting spans.
Motivation:
The existing ZipkinPublisher isn’t readily extensible with different off the shelf reporters
and adopting that interface will allow users to drop in their own reporters.
Modifications:
- Modifying ZipkinPublisher to report spans to a Reporter<Span> interface.
- Moving the UDP implementation out to a UdpReporter
Result:
ZipkinPublisher can now accept other zipkin2 Reporters as publishing targets.

Converting ZipkinPublisher to use a zipkin2.Reporter interface for reporting spans

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java

Motivation:
In case of any error or cancellation, `ProxyConnectConnectionFactoryFilter`
does not close the connection to the proxy.
Modifications:
- Add tests to verify different failure scenarios for
`ProxyConnectConnectionFactoryFilter`;
- Close connection when `CONNECT` request or SSL handshake failures;
- Do not drain the response payload body in case of error, because the
connection will be closed anyway;
Result:
`ProxyConnectConnectionFactoryFilter` does not leak connections.

`ProxyConnectConnectionFactoryFilter` leaks connection in case of errors

---

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java

Motivation:
SubscriberUtils#calculateSourceRequested uses a conditional which can be reduced to a Math.min method call.

Use Math.min in SubscriberUtils

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/CollectTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/CollectTest.java

Motivation:
There are 2 CollectTests (one for Completable, one for Single) that make
assumptions about the second source not being subscribed to if the first
source fails. However there is no guarantee from the operator about
subscribe ordering so this test criteria can be relaxed.
Modifications:
- remove assumption that collect/merge operators subscribe in a
sequential manner
Result:
CollectTests focused on verifying API contract instead of current
implementation.

CollectTest remove assumption about subscribe ordering

---

gradle.properties

Motivation:
Sonatype/Nexus/Maven Central do not support SHA256 and SHA512 checksums.
Therefore, staging repo can not be promoted to Maven Central because it
can not override the following files for each artifact:
maven-metadata.xml.sha256
maven-metadata.xml.sha512
Modifications:
- Use Gradle's system property to disable SHA256 and SHA512 checksums;
Result:
Published artifacts can be promoted to Maven Central.

Disable SHA256 and SHA512 checksums for published artifacts

---

servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/LoggingReporter.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java

Motivation:
`servicetalk-opentracing-zipkin-publisher` has a few things that
can be improved.
Modifications:
- Make `LoggingReporter.Builder.loggerName` variable final;
- Add javadoc for `LoggingReporter.Builder`;
- Make `UdpReporter.buildBootstrap` static;
- Remove info about default value from
`UdpReporter.Builder.ioExecutor` javadoc;

Minor improvements for `servicetalk-opentracing-zipkin-publisher`

---

servicetalk-opentracing-zipkin-publisher/build.gradle

Motivation:
All modules must declare a dependency as `api` in `build.gradle` if any
class from that dependency is exposed as part of the public API of the
current module.
Modifications:
- Define `servicetalk-concurrent-api`, `servicetalk-transport-api`,
`io.zipkin.zipkin2:zipkin`, and `io.zipkin.reporter2:zipkin-reporter`
dependencies as `api`;
Result:
Users of `servicetalk-opentracing-zipkin-publisher` module do not need
to bring these dependencies manually to fix compiler errors.

`servicetalk-opentracing-zipkin-publisher`: declare `api` dependencies

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

__Motivation__
When a host used by `RoundRobinLoadBalancer` is unregistered from service discovery, we force close the connection. This means any outstanding requests on the connection will get interrupted. Since service discovery status is a hint we should err on the side of caution and let the outstanding requests complete gracefully.
A fallout of this decision is that a connection may actually be dead and an absence of writes may mean that the we will never detect closure hence graceful closure will never complete.
This is a trade-off between interrupting requests which may otherwise be successfully completed vs not force closing requests that may never complete. As requests could be infinitely latent in general, we assume that users have configured timeouts on the requests and hence …

`RoundRobinLoadBalancer` should close connections gracefully

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultKeepAlivePolicy.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2KeepAlivePolicies.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAliveManager.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/KeepAlivePolicies.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/KeepAliveManagerTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java

__Motivation__
HTTP/2 PING frames are useful to keep a connection alive relatively cheaply in presence of long running streams. ServiceTalk should support adding this functionality for both clients and servers.
- Add `KeepAlivePolicy` to `H2ProtocolConfig` that can be configured to enable keep-alive behavior on either clients or servers. Following features are provided:
-- Specify an idleness threshold, after which a PING frame will be sent on the connection to detect liveness.
-- Specify an ack timeout, within which we expect an ack for the sent PING. If no ack is received, the connection is closed.
-- Specify whether PING frames should be sent even when there are no active streams. This defaults to `false`.
__Result__
Keep alive behavior can be enabled for either client …

Introduce HTTP/2 keep alive

---

CONTRIBUTING.adoc
GOVERNANCE.adoc
MAINTAINERS.adoc

Motivation:
The governance section of the project is currently light weight, and may
create confusion for community members.
Modifications:
- Add GOVERNANCE.adoc
- Add MAINTAINERS.adoc
- Clarify CONTRIBUTING.adoc
Result:
Governance and scope of contributions to the ServiceTalk repository are
more clearly defined.

Clarify Governance and Contribution guidelines

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AfterFinallySingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BeforeFinallySingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TerminalSingleTerminalSignalConsumer.java

Motivation:
Not every consumer needs the onSuccess value.
Modifications:
- Added whenFinally/beforeFinally/afterFinally that takes a TerminalSignalConsumer
- Extended the type bounds for SingleTerminalSignalConsumer
Result:
- Can now call Single.whenFinally(TerminalSignalConsumer) if users don't need the onSuccess value
- Compiler will allow you to pass a SingleTerminalSignalConsumer typed with a super type to whenFinally/etc

Adding TerminalSignalConsumer for Single.whenFinally et al

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2KeepAlivePolicies.java

__Motivation__
`H2KeepAlivePolicies` enforces limits on the idle timeout duration which is limiting for users. We should avoid providing synthetic limits and trust users to use sensible values.
- Remove the synthetic limits.
- Reduce timeouts for `KeepAliveTest` and enable the test for CI
__Result__
No synthetic limits.

Remove keep alive duration limits

---

CONTRIBUTING.adoc

Motivation:
d8ac3002939a5739803631b128fcbe2cf717afcc moved the Project Communication section from CONTRIBUTORS.adoc to README.adoc. The table of contents is not auto generated so the corresponding entry needs to be removed.

Remove Project Communication section from CONTRIBUTORS.adoc ToC

---

servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/concurrent/ConcurrentSubscriptionBenchmark.java
servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/concurrent/ConcurrentSubscriptionReentrantBenchmark.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ConcurrentUtilsTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/internal/ConcurrentSubscriptionTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ConcurrentSubscription.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ConcurrentUtils.java
servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/DelayedSubscriptionTest.java

Motivation:
ConcurrentSubscription currently propagates invalid demand without any
concurrency protection. In general this is invalid use of the API but
may invalidate underlying data structures that are not thread safe and
result in undefined results.
Modifications:
- Use a simpler locking scheme inspired by Publisher#flatMapMerge design
which allows for re-entry and also notification is another thread has
attempted to acquire the lock which will trigger re-processing.
Result:
ConcurrentSubscripiton no longer allows any concurrent access and uses a
more common/shareable locking utility.

ConcurrentSubscripiton avoid concurrent access for invalid demand

---

GOVERNANCE.adoc

Motivation:
The Governance doc included provisions for voting on a new Maintainer
that required binary yes/no voting. This provision should have been put
in the Decision-Making and Voting section as it applies to all votes.
Modifications:
- Move yes/no vote requirements to the Decision-Making and Voting
section
Result:
Governance general voting clarified as binary yes/no.

Governance - clarify yes/no vote

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java

__Motivation__
If invalid calls to request-n are made for `Single.concat(Publisher)` before the `Single` result is propagated, we first emit the result and then propagate the invalid demand.
For cases, when the concatenated `Publisher` completes inline with `subscribe()`` (eg: `Publisher.empty()`), this means we will never deliver an error for the invalid demand.
Deliver error when invalid demand is made in the above case instead of `Single`'s result and do not subscribe to the concatenated `Publisher`
__Result__
Invalid demand always terminates the `Subscriber` with an error.

`SingleConcatWithPublisher` and invalid request-n

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractProcessorBuffer.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractPubToSingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractPublisherProcessorSignalsHolder.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultBlockingProcessorSignalsHolder.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastUtils.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PubFirstOrError.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SubscriberApiUtils.java

Motivation:
SubscriberApiUtils exposes a NULL_TOKEN to the concurrent.api package
and usages share common code to wrap/unwrap the null token. This could
could be shared into methods instead of duplicated.
Modifications:
- Make SubscriberApiUtils#NULL_TOKEN private
- Add SubscriberApiUtils wrapNull and unwrapNull methods
Result:
More shared code in concurrent.api for wrapping/unwrapping NULL_TOKEN.

Consolidate concurrent.api NULL_TOKEN usage

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategies.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/BufferStrategy.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherBuffer.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferConcurrencyTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherBufferTckTest.java

__Motivation__
[`buffer`](http://reactivex.io/documentation/operators/buffer.html) operator is useful for batching.
Add `buffer()` operator for `Publisher` to buffer based on arbitrary buffer boundaries or based on size + time duration.
__Result__
Users can buffer events from a `Publisher`.

Add `Publisher#buffer` operator

---

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/DelayedSubscription.java

Motivation:
DelayedSubscription allocates a ConcurrentSubscription internally to
avoid concurrent access on the subscrption when setting the delayed
subscription. This introdcues additional object allocations that can be
avoided.
Modifications:
- DelayedSubscription no longer uses ConcurrentSubscription
Result:
Less object allocation overhead introduced by DelayedSubscription.

DelayedSubscription no longer uses ConcurrentSubscription internally

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

__Motivation__
For quicker lookups on receiving Service discovery events,  `RoundRobinLoadBalancer` keeps a sorted list of addresses. This results in the same order of hosts for all client instances hence potentially creating hot spots. As, the sorting is not required functionally, we should avoid doing that.
Use unsorted address list and let service discoverer maintain order of addresses.
__Result__
`RoundRobinLoadBalancer` does not store sorted addresses.

`RoundRobinLoadBalancer` should not sort the addresses

---

servicetalk-opentracing-zipkin-publisher/build.gradle
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/Codec.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporterTest.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/SpanUtils.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java

__Motivation__
We do not currently provide a zipkin reporter implementation for HTTP collectors. Providing an HTTP reporter using ServiceTalk HTTP client will be useful when ServiceTalk HTTP client is used otherwise in applications.
Add an `HttpReporter` with configurable batching strategy.
__Result__
Users can use ServiceTalk HTTP client to publish spans to a Zipkin collector.

Introduce HTTP Zipkin reporter

---

servicetalk-benchmarks/build.gradle
servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/loadbalancer/RoundRobinLoadBalancerSDEventsBenchmark.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

Motivation:
RoundRobinLoadBalancer currently prevents duplicates from being
inserted. However the ServiceDiscoverer is responsible for filtering
duplicates in the typical use case. Allowing duplicates at the LB layer
allows to give more weight to specific addresses if desired.
Modifications:
- RoundRobinLoadBalancer simplify addition/removal to forgo duplicate
detection
Result:
RoundRobinLoadBalancer code simplified to ignore duplicate detection,
addition doesn't require linear search.

RoundRobinLoadBalancer to allow duplicate addresses

---

servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporterTest.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java

Motivation:
Zipkin's `Component` has a method `check()` that verifies if the
operations on this current component are likely to succeed. But
`UdpReporter` always reports `OK`.
Modifications:
- `UdpReport` returns `OK` only when the channel is active;
- Test to verify new behavior;
Result:
When `UdpReporter` is closed and `Channel` becomes inactive,
`check()` method starts returning `CheckResult#failed`.

Implement `Component#chek()` for `UdpReporter`

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompositeException.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeExceptionTest.java

Motivation:
CompositeException's finishAndThrow method implies that it directly
throws an exception. While this is possible if the internal transfer
encounters an exception, it is not the expected use case. The method
name causes confusion on first glance and requires more investigation to
understand throwing is not expected.
Modifications:
- CompositeException rename finishAndThrow to
transferPendingToSuppressed
Result:
CompositeException method name is clarified and more readable.

CompositeException rename finishAndThrow to transferPendingToSuppressed

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java

Motivation:
Publisher#flatMapMergeSingle currently enqueues all signals before
emitting to the downstream Subscriber. Going through the queue leverages
the concurrency controls around the queue to prevent concurrent
emissions and also provides an ordering of emissions. The ordering of
emissions is only necessary for terminal completion events to ensure we
process all outstanding signals before terminating, and otherwise there
is no ordering requirements between independent mapped Singles.
Modifications:
- add PublisherFlatMapSingle#tryEmitSignal which supports a fast path
for direct emission without going through the queue if there is no
concurrency detected.
Result:
Publisher#flatMapMergeSingle uses less memory and avoids queuing signals
if no concurrency.

Publisher#flatMapMergeSingle avoid queue if no concurrency

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyResponseException.java

Motivation:
Non 2xx response codes from the proxy fail the connection initialization.
Therefore, it should be a subclass of `IOException`.
Also, `ProxyResponseException` means that client did not start writing
the request and should be marked as `RetryableException`.
Modifications:
- Change the parent class of `ProxyResponseException` from
`RuntimeException` to `IOException`;
- Add `RetryableException` marker interface for `ProxyResponseException`;
Result:
`ProxyResponseException` will indicate problems with the IO and will be
automatically retried by default retrying filter.

Mark `ProxyResponseException` as retryable `IOException`

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberFutureListenersTest.java

__Motivation__
`WriteStreamSubscriber` uses a single `Promise` for all writes done through it. As we add listeners to each write, the listeners get accumulated in the promise till the `WriteStreamSubscriber` terminates. For servers since we do a single write for the connection, these listeners are retained for the connection lifetime.
- Manage listeners in `AllWritesPromise` as opposed to delegating them to `DefaultWritePromise`.
- Listeners are managed over the specific write boundaries.
- Each time a write is complete, listeners added since last write are terminated and removed from the list.
__Result__
Listeners are retained by `WriteStreamSubscriber` for the duration of each write.

`WriteStreamSubscriber` retains listeners for the lifetime of the source

---

servicetalk-opentracing-inmemory/build.gradle
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpanBuilder.java
servicetalk-opentracing-inmemory/src/test/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTracerTest.java

Motivation:
OpenTracing semantics defines a FOLLOWS_FROM relationship which is an
alternative means of representing a parent relationship. However
AbstractInMemorySpanBuilder doesn't respect this Reference type and only
recognizes CHILD_OF.
Modifications:
- AbstractInMemorySpanBuilder#parent() should also match References
against FOLLOWS_FROM
Result:
AbstractInMemorySpanBuilder#parent() respects the FOLLOWS_FROM
relationship.

AbstractInMemorySpanBuilder to respect FOLLOWS_FROM

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequestFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequestFactory.java

Motivation:
`StreamingHttpRequestFactory` and `BlockingStreamingHttpRequestFactory`
miss a method that creates `HttpRequestMethod#PUT` request.
Modifications:
- Add `put(String)` method for `StreamingHttpRequestFactory` and
`BlockingStreamingHttpRequestFactory`;
Result:
Users can use a short cut method to create `HttpRequestMethod#PUT`
requests for `StreamingHttpClient` and `BlockingStreamingHttpClient`.

Method to create PUT requests for [Blocking]StreamingHttpRequestFactory

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/BuilderUtilsTest.java

Motivation:
Users of `HttpClients.forResolvedAddress(HostAndPort)` API could end up
using blocking JDK DNS resolution if they pass unresolved hostname.
Modification:
- Add `BuilderUtils.toResolvedInetSocketAddress(HostAndPort)` that creates
a resolved `InetSocketAddress` without DNS resolution;
- Add tests for new utility method;
- Use this new utility for `HttpClients. forResolvedAddress` instead of
`new java.net.InetSocketAddress`;
Result:
Users who pass unresolved hostname will see `IllegalArgumentException`
with `UnknownHostException` cause and should use `HttpClients.forAddress`
instead that performs async DNS resolutions using netty-dns-resolver.

Avoid blocking JDK DNS resolutions

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java

Motivation:
`Throwable.getCause()` may be expensive.
Modifications:
- Unwrap the cause only when the original exception is an instance of
`DecoderException`.
Result:
Do not access cause of exceptions that we are not interested in unwrapping.
Follow-up for #1075.

Unwrap the cause only for `DecoderException`

---

gradle.properties
servicetalk-opentracing-zipkin-publisher/build.gradle

Motivation:
servicetalk-opentracing-zipkin-publisher has an explicit dependency on
io.zipkin.reporter2:zipkin-reporter and io.zipkin.zipkin2:zipkin.
However the former has a transitive dependency on the latter and exposes
its APIs. Adding an explicit dependency on both means we have to make
sure the versions are properly synchronized or build tools may have
issues resolving the version conflicts.
Modifications:
- remove explicit io.zipkin.zipkin2:zipkin dependency from
servicetalk-opentracing-zipkin-publisher
Result:
No need to keep zipkin versions synchronized in ServiceTalk.

Zipkin Publisher remove explicit io.zipkin.zipkin2:zipkin dependency

---

servicetalk-examples/grpc/helloworld/build.gradle
servicetalk-examples/grpc/routeguide/build.gradle
servicetalk-examples/http/helloworld/build.gradle
servicetalk-examples/http/http2/build.gradle
servicetalk-examples/http/jaxrs/build.gradle
servicetalk-examples/http/metadata/build.gradle
servicetalk-examples/http/serialization/build.gradle
servicetalk-examples/http/service-composition/build.gradle
servicetalk-gradle-plugin-internal/plugin-config.gradle
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkCorePlugin.groovy
servicetalk-grpc-gradle-plugin/plugin-config.gradle
servicetalk-grpc-protoc/build.gradle
servicetalk-http-router-jersey/build.gradle
servicetalk-http-security-jersey/build.gradle
settings.gradle

#992 upgraded the ServiceTalk build to use Gradle 6.3. Several deprecation warnings are presented when running builds with version 6.3 (I haven't confirmed whether they were present with older versions however). A complete list is available in the details disclosure below from before the commit in this pull request is applied.
This pull request updates all usages which present deprecation warnings with their forward-compatible replacements.
- Replace the `runtime` directive with the `runtimeOnly` directive for runtime inclusion of `log4j` and `boringssl` in several examples.
- Replace the `testRuntime` directive with the `testRuntimeOnly` directive in `servicetalk-http-security-jersey/.build.gradle`.
- Replace the `compile` directive with the `implementation` directive in …

Fix all deprecation warnings from Gradle 6.3

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AutoRetryTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java

__Motivation__
`LoadBalancerFactory#newLoadBalancer()` does not allow for the passed `ConnectionFactory` to influence type of the `LoadBalancedConnection` managed by the returned `LoadBalancer`. This forces users of this API (Http client builder implementations) to do an explicit cast.
Improve generics of `LoadBalancerFactory#newLoadBalancer()` to infer the returned `LoadBalancer` generics from the passed `ConnectionFactory`
__Result__
No explicit casts while using `LoadBalancerFactory#newLoadBalancer()`.

Improve `LoadBalancerFactory#newLoadBalancer()` generics

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastUtils.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java

__Motivation__
```java
Publisher<Integer> multi = Publisher.range(1, 10)
.beforeRequest(n -> System.out.println("Requested from main source: " + n))
.multicastToExactly(2, 1);
multi.forEach(t -> System.out.println("From first => " + t));
multi.forEach(t -> System.out.println("From second => " + t));
```
Produces the output:
```
Requested from main source: 1
From first => 1
From second => 1
```
This shows that `multicastToExactly()` is not requesting more than `queueSize()` items unless the subscriber requests more.
- Remove the conditional request-n call in `MulticastUtils.updateRequestN()` based on `drainCount`. Since drained item count is already included in `emitted`, this additional constraint is not required.
- `SubscriberUtils.calculateSourceRequested()` did not …

Fix incorrect request-n management for `Publisher.multicast()`

---

docker/docker-compose.yaml
gradle.properties
servicetalk-gradle-plugin-internal/plugin-config.gradle
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkCorePlugin.groovy

Motivation:
Starting from version 0.20.0 we publish ServiceTalk artifacts to
Maven Central and do not use Bintray anymore.
Modifications:
- Remove commented dead code related to Bintray plugin configuration
that we do not use;
Result:
Less code in `servicetalk-gradle-plugin-internal`.

Remove bintray plugin

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProxyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java

Motivation:
When client observes "Connection: close" header it shutdowns the output
channel as soon as request is written. Some servers interpret FIN from
the client as an indicator that it lost interest in their data and
therefore, server just closes the second half of the connection asap.
As the result, connection may be closed before client receives the full
response from the server.
Modifications:
- Reproduce this scenario using a simple proxy tunnel that is not aware
of HTTP protocol semantics;
- Defer connection closure on the client side until it completes the
full request-response iteration;
- Fail all subsequent or pipelined requests on the connection that moves
to the "closing" state;
- Adjust `RequestResponseCloseHandlerTest` to not expecting outbound
half-closure on the client …

Do not shutdown output channel until client receives the full response

---

servicetalk-examples/grpc/helloworld/src/main/java/io/servicetalk/examples/grpc/helloworld/async/HelloWorldClient.java
servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/async/RouteGuideClient.java
servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/async/streaming/RouteGuideRequestStreamingClient.java
servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/async/streaming/RouteGuideResponseStreamingClient.java
servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/async/streaming/RouteGuideStreamingClient.java
servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldClient.java
servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldUrlClient.java
servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingClient.java
servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingUrlClient.java
servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async/PojoClient.java
servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async/PojoUrlClient.java
servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async/streaming/PojoStreamingClient.java
servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async/streaming/PojoStreamingUrlClient.java

__Motivation__
We currently use `whenFinally` to decrement the countdown latch. As `whenFinally` uses `beforeFinally`, latch is decrementing before the output is printed.
Use `afterFinally` instead of `whenFinally`
__Result__
Examples print the output correctly.

Use `afterFinally` in examples

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java

Motivation:
Because the server's executor is closed before the server, all tests
from `AbstractNettyHttpServerTest` subclasses print
`TaskBasedSignalOffloader - Failed to execute task on the executor`
errors that pollute logs and make the build log unreadable.
Modifications:
- Close `ServerContext` before `Executor` in `AbstractNettyHttpServerTest`;
Result:
No `TaskBasedSignalOffloader` errors in test logs.
---
Example of the polluted logs:
```
io.servicetalk.http.netty.NettyHttpServerConnectionAcceptorTest > testAcceptConnection[ssl=false client=IMMEDIATE server=CACHED DELAY_REJECT_ALL] STANDARD_OUT
2020-07-22 17:50:53,190       client-io-executor-13-12 [ERROR] TaskBasedSignalOffloader       - Failed to execute task on the executor …
```

Close ServerContext before Executor in AbstractNettyHttpServerTest

---

servicetalk-http-netty/gradle/spotbugs/test-exclusions.xml
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyTunnel.java

Motivation:
Current tests for handling of `connection: close` header focused on the client
side, missing some of the interesting server-side use-cases when request or
response payload is delayed.
Modifications:
- Summarize all tests related to `connection: close` header in one class:
`ConnectionCloseHeaderHandlingTest`;
- Share secure proxy tunnel related code between `ConnectionCloseHeaderHandlingTest`
and `HttpsProxyTest`;
- Parametrize tests in `ConnectionCloseHeaderHandlingTest` to cover all
combinations of request-response ordering;
Result:
Enhanced test coverage for `connection: close` handling logic.

Enhance `connection: close` tests to cover more use-cases on the server-side

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java

Motivation:
If service handle method throws an exception, server does not add an empty
trailers as a marker of response end. Therefore, client can not drain the
response payload body when HTTP/2 is used.
Modifications:
- Add `EmptyHttpHeaders.INSTANCE` as the last item for rrror handler in
`NettyHttpServer`;
Result:
Client sees `endStream=true` and completes payload body publisher for HTTP/2.

HTTP server does not complete the response if handler method throws

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java

Motivation:
NettyPipelinedConnection uses a merge operation to ensure errors are
propagated from the read and write operation. From a purely full-duplex
perspective it maybe unexpected that the response async source doesn't
complete until the write completes.
Modifications:
- Add comments in NettyPipelinedConnection to clarify rational for this
behavior
- Cleanup ConnectionCloseHeaderHandlingTest for tests which were ignored
to work around this behavior
Result:
NettyPipelinedConnection clarifies duplex rational in comments."

Add comments to clarify Client duplex behavior

---

servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java

Motivation:
DefaultDnsClientTest.repeatDiscoverNxDomain attempts to assert that an
UnknownHostException is eventually received. However the test initial
state has the address available, and the test harness eventually removes
the address in the background. The test doesn't wait for the error event
to happen before asserting the error condition.
Modifications:
- Increase the test latch countdown to wait for the error to be received
Result:
Fixes https://github.com/apple/servicetalk/issues/1102

DefaultDnsClientTest.repeatDiscoverNxDomain test failure

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyTunnel.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextRule.java

Motivation:
When client observes users request to close the connection gracefully it
shutdowns the output channel if the in-flight request is already written,
then awaits for the incoming response to close the full channel.
Some servers interpret FIN from the half-closed client as an indicator that
it lost interest in their data and therefore, server may closes the second
half of the connection asap. As the result, connection may be closed before
client receives the full response from the server.
Modifications:
- Reproduce this scenario using a simple proxy tunnel that does not support
half-closed connections;
- Close the proxy tunnel when it sees EOF or an error to propagate closure
to the other side of the tunnel;
- Defer connection closure on the client-side until it completes the full …

Do not half-close outbound channel on graceful client closure

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultServiceDiscovererEvent.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategyTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java

__Motivation__
Service discovery errors are retried by clients to avoid transient failures cause request errors. DNS service discoverer eagerly clears addresses for errors of type `UnknownHostException` but such errors can also be transient. This DNS discoverer behavior effectively defeats the retries done by the client as it results in request errors.
We should avoid service discovery implementations to react pessimistically to service discovery errors as service discovery results are just a hint and do not effectively represent the current state of the servers. Server availability may change asynchronously and may not accurately be reflected in service discovery result due to delays at multiple levels. Instead, we should assume that all service discovery errors are transient and retain …

Retain addresses on service discovery failure

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java

Motivation:
Some methods are not overridden in `BaseSingleAddressHttpClientBuilder`
and `MultiAddressHttpClientBuilder`. Users have to cast if they use
those missed methods on this builders.
Modifications:
- Add overrides for `BaseSingleAddressHttpClientBuilder`: `executionStrategy`
and `appendClientFilter`;
- Add overrides for `MultiAddressHttpClientBuilder.java`: `protocols`;
Result:
Users can use fluent builder API without need to cast builder types.

Add missed overrides for the client builders

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java

Motivation:
HTTP uses a non-binary framing layer that is subject to request
smuggling. Our decoding relies upon the terminal newline characters to
frame requests and we should have tests to exercise behavior in cases
where a request is injected into a header value.
Modifications:
- Add HttpObjectDecoder tests which attempt to smuggle
requests/responses in headers
Result:
More tests verifying smuggling behavior.

Add tests for HTTP request smuggling in headers

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java

Motivation:
Assertions from non-main thread (e.g. inside the service handle method)
do not fail the test.
Also, existing tests do not verify that `SSLSession` is set on the client
side.
Modifications:
- Assert server-side state in the main thread;
- Assert that `ConnectionContext` is set correctly on the client-side;
- Avoid using deprecated jUnit API;
Result:
Better test coverage for ALPN use cases.

Improve tests for ALPN

---

servicetalk-client-api-internal/src/test/java/io/servicetalk/client/api/internal/partition/PowerSetPartitionMapTest.java

Method signature is `assertEquals(String message, long expected, long actual)`

Fix assertEquals expected & actual order

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/BiTransportObserver.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java

Motivation:
1. `StreamObserver` lacks `streamEstablished` event similar to
`connectionEstablished`.
2. `StreamException` during stream initialization are not visible for
`StreamObserver`.
Modifications:
- Add `StreamObserver#streamEstablished()` event;
- Rename `ConnectionObserver#established` ->
`ConnectionObserver#connectionEstablished`;
- Rename `ConnectionObserver#establishedMultiplexed` ->
`ConnectionObserver#multiplexedConnectionEstablished`;
- Update tests to account for a new event;
- Report `StreamObserver#streamClosed` from `channelInactive` event
instead of stream close future;
- Test that "Maximum active streams violated for this endpoint" exception
is reported using `StreamObserver#streamClosed(Throwable)` event;
Results:
1. `ConnectionObserver` and `StreamObserver` API are …

Report `streamEstablished` event, improve `streamClosed` handling

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TestServiceStreaming.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DeferSslHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyPipelineSslUtils.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SslClientChannelInitializer.java

Motivation:
Usage of Channel's attributes increase a shared state of the `Channel`.
`SecurityHandshakeObserver` can be propagated without using it.
Modifications:
- When `SslHandshakeCompletionEvent` arrives, look up for
`ConnectionObserverHandler` to access previously initialized
`SecurityHandshakeObserver`;
- Add `SecurityHandshakeObserverTest` to verify that
`SecurityHandshakeObserver` is working with different configurations:
HTTP/1.1, HTTP/2, ALPN, secure proxy tunnel;
- Improve `TestServiceStreaming` to echo content-type header;
Result:
Less state on the `Channel` instance.

Propagate `SecurityHandshakeObserver` without channel attribute

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/TransportObserverConnectionFactoryFilter.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportObservers.java

Motivation:
Users who need to report events to two `TransportObserver`s simultaneously
on the server-side or who need their own variant of
`TransportObserverConnectionFactoryFilter` will find it useful.
Modifications:
- Move `BiTransportObserver` from `client-api` to `transport-api`;
- Convert passes first and second observers into safe observers;
- Add public `TransportObservers.biTransportObserver` factory;
Result:
Users can easily report events to two `TransportObserver`s.

Provide a public factory for `BiTransportObserver`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedHttpSerializer.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/FormUrlEncodedHttpSerializerTest.java

Motivation:
When multiple maps are passed through a publisher to the serializer, then the resulting
encoding is incorrect, missing "&" in between the parts.
Modifications:
The serialization uses a local state to track continuations and prefix the serialized part with
the ampersand symbol.
Fixes: https://github.com/apple/servicetalk/issues/1120

Allow for continuations in streamed form-url-encoded params during serialization

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java

Motivation:
We have two places in `DefaultNettyConnection` when we may need to wrap
the error with known close reason. We can share this logic in both places
consistently.
Modifications:
- Use `wrapIfReasonIsKnown` for `RetryableClosureException`;
- Improve `wrapIfReasonIsKnown` to skip wrapping if the error is already
wrapped with the same reason;
Result:
Consistent wrapping.

Improve wrapping with the close reason

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java

Motivation:
`HttpTransportObserverTest.serverFailsResponsePayloadBodyBeforeRead[protocol=HTTP_2]]`
may fail because `serverReadObserver` may emit `readFailed` event.
Modification:
- Verify that either `readCancelled` or `readFailed` events are expected on
`serverReadObserver`;
Result:
Test is not flaky anymore.
---
Seen:
1. https://ci.servicetalk.io/job/servicetalk-java11-prb/1499/testReport/io.servicetalk.http.netty/HttpTransportObserverTest/serverFailsResponsePayloadBodyBeforeRead_protocol_HTTP_2_/
2. https://ci.servicetalk.io/job/servicetalk-java11-prb/1498/testReport/junit/io.servicetalk.http.netty/HttpTransportObserverTest/serverFailsResponsePayloadBodyBeforeRead_protocol_HTTP_2_/

Fix flaky test in `HttpTransportObserverTest`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientValidatesContentTypeTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/HtmlResponseUponGrpcRequestTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/HttpResponseUponGrpcRequestTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java

**Motivation:**
When an h1/h2 response comes back, not following the gRPC protocol (eg. due to proxy error), the exception thrown to the client is not informative. It only mentions that a grpc-status wasn't found.
We can improve this to include the HTTP status code along side the header names to help identify what went wrong.
**Modifications:**
Introduced a new function that validates the content type. If an HTML type is found (text/plain or text/html) we throw the new more informative error. The check happens both for headers & trailers.
**Result:**
Before
```
io.servicetalk.grpc.api.GrpcStatusException: INTERNAL: Response does not contain grpc-status header or trailer
```
After
```
io.servicetalk.grpc.api.GrpcStatusException: INTERNAL: HTTP  status code: 400 Bad Request
invalid …
```

Provide informative exceptions upon gRPC calls when plain h2/h1 resp

---

servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/DefaultPartitionedClientGroup.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcClients.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PartitionedHttpClientTest.java

__Motivation__
`SingleAddressHttpClientBuilder` is used as a template for partitioned and multi-address builders for which SD event types is different. Although, users are not expected to use a ServiceDiscoverer with different event type, we accommodate this usage in our public APIs. Accomodating this usage further trickles down to builder implementation and the external facing `ServiceDiscoveryRetryStrategy`. It also complicates generic handling whenever we change `ServiceDiscoverer` APIs.
Further the partitioned builder uncheck casts the service discovery stream while using which hides type issues.
- Remove the `? extends` in the `ServiceDiscoverer` event type while accepting a `ServiceDiscoverer` in the builders. When a different event type is required (partitioned …

Simplify ServiceDiscoverer generics in client builders

---

servicetalk-examples/grpc/helloworld/src/main/resources/log4j2.xml
servicetalk-examples/grpc/routeguide/src/main/resources/log4j2.xml
servicetalk-examples/http/helloworld/src/main/resources/log4j2.xml
servicetalk-examples/http/http2/src/main/resources/log4j2.xml
servicetalk-examples/http/jaxrs/src/main/resources/log4j2.xml
servicetalk-examples/http/metadata/src/main/resources/log4j2.xml
servicetalk-examples/http/serialization/src/main/resources/log4j2.xml
servicetalk-examples/http/service-composition/src/main/resources/log4j2.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentChannelInitializer.java
servicetalk-test-resources/src/main/resources/log4j2.xml
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyLoggerUtils.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WireLoggingInitializer.java

Motivation:
When enableWireLogging and h2 frameLogger are set on the builder we
always log at TRACE level regardless of what level the logging
configuration specifies. The h2 frameLogger has conditional logic which
limits the amount of data logged for levels less than TRACE, and it is
generally unexpected to log at a different level than configured by the
user.
Modifications:
- When Http2FrameLogger and LoggingHandler are created we should get the
log level from SL4J and pass the translated Netty LogLevel upon
construction
Result:
Debug logging uses the same log level as configured by the user.

Set the correct log level for wire logging and h2 frame logging

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/AsyncContextAwareHttpServiceFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java

Motivation:
Each HttpService should get an empty AsyncContext. This will happen if
the AsyncContext at the root level is empty, which it typically is.
However it is possible that the AsyncContext maybe modified before this
time (e.g. MDC) and if this happens that may result in shared state
between requests (if values are modifiable).
Modification:
- Wrap each service in a filter that explicitly clears the AsyncContext
before executing the user's service filter chain
Result:
AsyncContext is empty when the user service/filter chain is invoked.

Clear AsyncContext before invoking HttpService

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java

Motivation:
`StreamObserverTest.maxActiveStreamsViolationError()` test expects that
client already received a new value of `MAX_CONCURRENT_STREAMS` from the
server when the connection is established. But actually, the server
sends settings frame after the first request.
Modifications:
- Await until the client receives `MAX_CONCURRENT_STREAMS` value from
the server before starting the second request;
Result:
`StreamObserverTest.maxActiveStreamsViolationError()` test is not flaky.
Fixes #1148.

Fix flaky `StreamObserverTest.maxActiveStreamsViolationError()`

---

servicetalk-examples/http/uds/build.gradle
servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/BlockingUdsClient.java
servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/BlockingUdsServer.java
servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/UdsUtils.java
servicetalk-examples/http/uds/src/main/java/io/servicetalk/examples/http/uds/blocking/package-info.java
servicetalk-examples/http/uds/src/main/resources/log4j2.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
settings.gradle

Motivation:
UDS is supported by ServicetTalk by passing in a DomainSocketAddress
address. However the HttpClientBuilder had some restrictions/assumptions
about the address type which prevented its use.
Modifications:
- Relax assumptions/restrictions in the HttpClientBuilder to allow for
DomainSocketAddress
- Add unit test to demonstrate UDS
- Add example for UDS
Result:
UDS client is now working and tested.

Unix Domain Sockets HttpClientBuilder fixes

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/QueueDynamicCompositeCancellable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SetDynamicCompositeCancellable.java

Motivation:
The DynamicCompositeCancellable may return true even if they failed to
add the Cancellable to the collection and invoked cancel(). The javadoc
says the method should return false in this scenario.
Modifications:
- Return false if the internal queue/set is full and the underlying add
fails
Result:
SetDynamicCompositeCancellable and QueueDynamicCompositeCancellable more
correctly implement the DynamicCompositeCancellable#add(..) API.

DynamicCompositeCancellable queue full return value fix

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/FlowControlUtils.java
servicetalk-concurrent-internal/src/test/java/io/servicetalk/concurrent/internal/FlowControlUtilsTests.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeDelayErrorTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeTckTest.java

Motivation:
Publisher#flatMapMerge is a basic building block for each element of a
Publisher to map into another Publisher.
Modifications:
- Add Publisher#flatMapMerge operator
Result:
Each item emitted on a Publisher can be mapped to another Publisher.

Add Publisher#flatMapMerge operator

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java

Motivation:
`RequestResponseCloseHandler.protocolPayloadEndOutbound` callback triggers
`ProtocolPayloadEndEvent` when server is in closing state without accounting
for pending requests. As the result, server will not send a response for the
second pipelined request, will not transition to the idle state, and will never
complete close the connection.
Modifications:
- Account for `pending` value before emitting `ProtocolPayloadEndEvent`;
- Renamve `ProtocolPayloadEndEvent` -> `OutboundDataEndEvent`;
- Add a test to verify server does not trigger `OutboundDataEndEvent`
while requests are pending;
- Add more tests to verify that `PROTOCOL_CLOSING_INBOUND`,
`PROTOCOL_CLOSING_OUTBOUND`, and `USER_CLOSING` events are
correctly handled for pipelined server connection;
Result:
Server responds to …

Do not complete server write if there are still pending requests

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java

Motivation:
Publisher#flatMapMerge may not drain the queue if an item is enqueued
and the item doesn't require demand. This may happen for example if the
mapped subscriber exhausts its demand, and had signals previously
queued. This may lead to dead lock and lack of progress.
Modifications:
- Modify tryEmitItem to only lock for item delivery. For other cases
that go through the queue use enqueueAndDrain which will enqueue,
acquire the drain lock, and drain the queue.
Results:
No more deadlock and smaller lock critical section in tryEmitItem for
Publisher#flatMapMerge.

Publisher#flatMapMerge queue not drained bug

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/AddressUtils.java

Motivation:
`CloseHandler.forPipelinedRequestResponse` enables half-closure only for
`SocketChannelConfig`. `DomainSocketChannel` does not use this config.
As the result, half-closure does not work for UnixDomainSockets.
Modifications:
- Use `ALLOW_HALF_CLOSURE` socket option to enable half-closure for the
`Channel`;
- Assert in `RequestResponseCloseHandler` that `Channel` implements
`DuplexChannel` and also has `ALLOW_HALF_CLOSURE` socket option enabled;
- Enhance `ConnectionCloseHeaderHandlingTest` to test the same scenarios
for `DomainSocketAddress`;
- Move `newSocketAddress()` utility to `AddressUtils`;
Result:
Half-closure is enabled for `DomainSocketChannel`.

Support half-closure for UnixDomainSockets

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
servicetalk-transport-netty-internal/build.gradle
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherRefCountTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/EmbeddedDuplexChannel.java

Motivation:
`RequestResponseCloseHandler` requires a `Channel` to implement `DuplexChannel`
interface. To reliably reproduce some racy behavior on the network we use
`EmbeddedChannel` to control all the network events manually, but it does
not implement `DuplexChannel`. Therefore, we can not use it to verify
the behavior of `RequestResponseCloseHandler`.
Modifications:
- Implement `EmbeddedDuplexChannel` test fixture that extends
`EmbeddedChannel` and implements `DuplexChannel` interface;
- Use a new variant in all tests that require an `EmbeddedChannel` with
`RequestResponseCloseHandler`;
- Update `RequestResponseCloseHandler` to support any `DuplexChannel`
implementations that has `ALLOW_HALF_CLOSURE` socket option enabled;
Result:
Better test coverage for `RequestResponseCloseHandler`, …

Add an `EmbeddedChannel` that supports `DuplexChannel` interface

---

docs/generation/gradle/validateSite.gradle

Motivation:
`https://netty.io/wiki/forked-tomcat-native.html` started return 520 status
code, resulting in frequent PRB failures.
---
Example: https://ci.servicetalk.io/job/servicetalk-quality-prb/1120/console

Exclude netty.io from validateHtmlLinks task

---

servicetalk-http-netty/gradle/spotbugs/test-exclusions.xml
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionAcceptorTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java

Motivation:
AbstractNettyHttpServerTest attempts to validate that the payload is
read in the same boundaries that it was written. This is not guaranteed
and the payload maybe chunked differently than written.
Modifications:
- Verify the aggregated payload is received as expected so we are
agnostic to intermediate patching.
Result:
More reliable verification of payload contents.

AbstractNettyHttpServerTest payload validation bug

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/ReadOnlyBufferAllocator.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionContextSocketOptionTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SupportedBufferAllocatorsTest.java

Motivation:
ServiceTalk provides a default `BufferAllocator` backed by netty's
`ByteBufAllocator`, but also provides a `ReadOnlyBufferAllocator`
implementation that does not depend on netty. `AbstractH2DuplexHandler`
currently supports only `ServiceTalkBufferAllocator`.
Modifications:
- Share `encodeAndRetain` logic between HTTP/1.x and HTTP/2 encoders;
- Add a test that verified both HTTP versions support all `BufferAllocator`s;
- Share `HttpProtocol` enum between different tests;
- Implement `ReadOnlyBufferAllocator.toString()` for better output for test
parameters;
Result:
HTTP/2 encoder supports `Buffer`s produced by `ReadOnlyBufferAllocator`.

Support write of read-only `Buffer`(s) for HTTP/2

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultNettyHttpConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionContextToStringTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingConnectionContext.java

Motivation:
HTTP/1.1 `ConnectionContext.toString()` includes netty's `Channel` ID.
It helps to correlate the `ConnectionContext` with events in netty when
debug logging is enabled or with wire logging. HTTP/2 `ConnectionContext`
does not implement `toString()`.
Modifications:
- Implement `toString()` for all `ConnectionContext` implementations;
- Test that client's `ConnectionContext` and server's `ConnectionContext`
print netty's channel id for any HTTP protocol version;
Result:
All `ConnectionContext` implementations backed by netty print `Channel` id.

`ConnectionContext.toString()` prints Netty's channel id

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceTest.java

Motivation:
BlockingStreamingHttp[Response|Response] allow a user to get the payload
body as an InputStream. However the user is not able to set the payload
body as an InputStream. This requires manual conversion from the user
perspective and raises the bar to entry.
Modifications:
- BlockingStreamingHttp[Response|Response] supports an additional method
to set the payloadBody as an InputStream
Result:
BlockingStreamingHttp[Response|Response] APIs are more InputStream
friendly.

BlockingStreamingHttp[Response|Response] to support InputStream setter

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java

Motivation:
These tests were temporarily disabled until #1141 implements a proper discard
of further inbound data that were read from the network but were pending in
previous handlers.
Modifications:
- Unignore temporary disabled tests in `ConnectionCloseHeaderHandlingTest`;
Result:
Better test coverage.

Unignore temporarily disabled tests that require full discard of inbound data

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
servicetalk-test-resources/src/main/resources/log4j2.xml

Motivation:
Wire logger and h2 frame logger are controlled by the logger configuration
after #1123. It allows us to use these logger names in tests and enabled them
via system property when required for local debugging.
Having 2 different logger names for client and server controlled by a single
system property does not help much. We can use a thread name to understand
if a logger statement belongs to a client or to a server. A single logger name
simplifies usage in tests.
Modifications:
- Keep only a single `servicetalk-tests-wire-logger` logger name;
- Add `servicetalk-tests-h2-frame-logger` logger name and
`servicetalk.logger.h2FrameLogLevel` system property to control visibility
for h2 frames;
- Update all tests to use new names;
Result:
Separate system properties to control wire …

Improve `servicetalk-test-resources/log4j2.xml`

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/grpc/protoc-options/README.adoc
servicetalk-examples/grpc/protoc-options/build.gradle
servicetalk-examples/grpc/protoc-options/src/main/java/io/servicetalk/examples/grpc/protocoptions/BlockingProtocOptionsClient.java
servicetalk-examples/grpc/protoc-options/src/main/java/io/servicetalk/examples/grpc/protocoptions/BlockingProtocOptionsServer.java
servicetalk-examples/grpc/protoc-options/src/main/java/io/servicetalk/examples/grpc/protocoptions/package-info.java
servicetalk-examples/grpc/protoc-options/src/main/proto/helloworld.proto
servicetalk-examples/grpc/protoc-options/src/main/resources/log4j2.xml
settings.gradle

Motivation:
We recently added a new option to servicetalk-grpc-protoc, but don't
have an example to demonstrate its use and validate correct behavior.

Add grpc protoc options example

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java

Motivation:
`GracefulConnectionClosureHandlingTest` provides a comprehensive testing
for graceful closure with HTTP/1. We need to make sure, the same cases
work correctly when users switch to HTTP/2.
Modifications:
- Add `HttpProtocol` parameter for `GracefulConnectionClosureHandlingTest`;
Result:
All use-cases of `GracefulConnectionClosureHandlingTest` are tested with
HTTP/1.x and HTTP/2.

Verify that all graceful closure use-cases also work with HTTP/2

---

servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
Verify that when `expectedCharset` is `null` it can recognize the `content-type`
header value that contains `charset=UTF-8` with and without space after `;`.
Modifications:
- Add more test scenarios at `HeaderUtilsTest.java.hasContentType()`;
Result:
Better test coverage for `HeaderUtils#hasContentType`.

Add more test scenarios for `HeaderUtils#hasContentType`

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc

Motivation:
The mutual-tls and uds examples were added recently but the example docs index doesn't include them.

Update http example docs index

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java

Motivation:
`HttpObjectDecoder` throws `DecoderException` if it sees malformed data.
We should make sure, the current HTTP message does not fail and processed
correctly if malformed data arrive right after the message.
Modifications:
- Add `MalformedDataAfterHttpMessageTest` to verify client and server
scenarios;
Result:
Better test coverage.

Verify HTTP message is processed if it is followed by malformed data

---

servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextRule.java

Motivation:
`ExecutionContextRule` creates an `IoExecutor` with `DefaultThreadFactory`,
but it should use `IoThreadFactory`.
Modifications:
- Use `IoThreadFactory` for `IoExecutor` in `ExecutionContextRule`;
Result:
`ExecutionContextRule` uses correct `ThreadFactory` for `IoExecutor`.

Use `IoThreadFactory` for `IoExecutor` in `ExecutionContextRule`

---

servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java

Motivation:
UDP packet may be truncated if it exceeds the maximum payload size of 4096
bytes. In this case, DNS ServiceDiscoverer will retry with TCP. However,
users should be able to configure higher capacity of the datagram packet
buffer.
Modifications:
- Add `DefaultDnsServiceDiscovererBuilder#maxUdpPayloadSize` method;
- Fix `IllegalArgumentException` message for `minTTL` option;
Result:
Users can control the capacity of the datagram packet buffer.

Option to configure capacity of the datagram packet buffer for DNS SD

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeaders.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiMap.java

Motivation:
For HTTP null header values are not allowed. An exception is thrown but
doesn't include the key which makes it more difficult for users to
understand the root cause.
Modifications:
- Enrich the null value exception to include the key
Result:
More informative exceptions.

Enhance null header value exception

---

servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/api/QueryAddBenchmark.java
servicetalk-benchmarks/src/jmh/java/io/servicetalk/http/api/QueryStringEncodingBenchmark.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequestMetaData.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpQuery.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/UriUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractHttpRequestMetaDataTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpRequestMetaDataTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpQueryTest.java

Motivation:
DefaultHttpRequestMetaData has methods that focus on mainpulating the
query string such as addQueryParameters and setQueryParameter. These
methods all re-encode the entire query string and request target on each
modification. However these methods are often used multiple times
sequentially, and the duplicate encoding is wasteful.
Modifications:
- Defer encoding the query string and request target until other methods
on the DefaultHttpRequestMetaData require it (e.g. requestTarget() and
other query accessor methods).
Result:
Less overhead for DefaultHttpRequestMetaData#addQueryParameters and
related query manipulator methods.

Improve DefaultHttpRequestMetaData query manipulator methods

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SubscriberUtils.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/TaskBasedSignalOffloader.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ThreadBasedSignalOffloader.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
Publisher#flatMapConcatIterable rethrows any exceptions from donwstream
onNext delivery, but it does not attempt to drain pending demand.
Because this operator holds on to demand internally (e.g. requests 1
after each element is processed) that may result in deadlock due to
demand being swallowed in the event of exception and upstream
recoverWith continues control flow.
Modifications:
- PublisherConcatMapIterable should attempt to request more from the
subscription if demand is still pending.
- Offloaders should dispatch exception before cancellation. This will
allow control flow to get a more meaningful exception based upon
application control flow (e.g. instead of CancellationException).
Result:
Publisher#flatMapConcatIterable does not swallow demand in the event of …

Publisher#flatMapConcatIterable drain demand on onNext exception

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompositeException.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeExceptionTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java

Motivation:
Publisher#flatMap*DelayError operators will queue exceptions and add
them all as suppressed exceptions once the upstream source and all
mapped publishers have terminated. However this operator maybe used for
unbounded streams, with retry operators, and this may result in a large
amount of exceptions which will exhaust memory over time.
Modifications:
- Limit the number of exception that is accumulated, and allow users to
override the default value.
Result:
Publisher#flatMap*DelayError bounds the number of accumulated exceptions
and will not exhaust memory for infinite streams.

Publisher#flatMap*DelayError limit queued exceptions

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryStrategies.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RedoStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RepeatStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RetryStrategiesTest.java
servicetalk-examples/http/service-composition/src/main/java/io/servicetalk/examples/http/service/composition/GatewayServer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategyTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractEchoServerBasedHttpRequesterTest.java

Motivation:
[Retry|Repeat]Strategies provides utility methods with strategies that
can apply a jitter to a delay scheme (e.g. fixed, exponential). However
we currently only offer "Full Jitter" variants which vary delay in the
range [0, max delay]. This works well to maximize variance of client
request arrival for exclusive resource operations (e.g. all clients
attempt to lock the same row in a DB) but may not be optimal in cases
which don't require mutual exclusion and instead value more predictable
and faster repeat intervals.
Modifications:
- [Retry|Repeat]Strategies rename the existing jitter methods to
"FullJitter"
- [Retry|Repeat]Strategies now include an alternative jitter method
"DeltaJitter" which applies a delta to the base distribution
[delay-jitter, delay+jitter].
Result:
More …

[Retry|Repeat]Strategies add jitter delta methods 

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java

Motivation:
We currently don't handle the Http2SettingsAckFrame. We should ignore it
but instead let it propagate to the end of the pipeline and get a
warning debug message from Netty.
Modifications:
- Ignore the Http2SettingsAckFrame as we don't do anything with it.
Result:
Fixes https://github.com/apple/servicetalk/issues/1122.

Ignore Http2SettingsAckFrame frame

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpResponseDecoder.java

Motivation:
RFC7230 defines `obs-text` as `%x80-FF` (any negative byte value), and
reason-phrase as `*( HTAB / SP / VCHAR / obs-text )`.
Modifications:
- Adjust `isObsText` and reason-phrase validation according to RFC7230;
- Verify that the passed `closeHandler` is non-null;
Result:
`HttpObjectDecoder` is more robust and RFC7230 compatible.

Make `HttpObjectDecoder` more RFC7230 compatible and other improvements

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java

Motivation:
If invalid demand is received by the Single#concat(Publisher) operator
before the single completed the invalid demand may be overwritten by a
subsequent request instead of propagating an error.
Modifications:
- Invalid demand should cancel the subscription and propagate an error.
Result:
Single#concat(Publisher) is more robust and follows rule 3.9 of the
reactive streams spec.

Single#concat(Publisher) invalid demand hang

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutCompletable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutSingle.java

Motivation:
Publisher, Single, and Completable have a idleTimeout operator which
accepts a io.servicetalk.concurrent.api.Executor to implement the
underlying timeout. However the implementation only requires the
io.servicetalk.concurrent.Executor interface.
Motivation:
- Change Publisher, Single, and Completable idleTimeout method to accept
a io.servicetalk.concurrent.Executor instead of
io.servicetalk.concurrent.api.Executor.
Result:
Less complex type required for idleTimeout operator.

idleTimeout operator to use io.servicetalk.concurrent.Executor

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/UriUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpResponseDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
servicetalk-utils-internal/gradle/spotbugs/test-exclusions.xml
servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/IllegalCharacterException.java
servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/IllegalCharacterExceptionTest.java

Motivation:
`HttpObjectDecoder` and its subclasses may throw an exception if the received
HTTP message violates the RFC and can not be parsed. However, exception messages
are short and hard to understand, without any pointers to what part of the
message caused an exception. Those cases are hard to debug and usually require
knowledge of RFC.
Modifications:
- Introduce `IllegalCharacterException` type that shows an illegal character as
a `char` and in hex format, as well as expected values;
- `try-catch` an `IllegalCharacterException` and wrap it with `DecoderException`
that clarifies where the illegal character was found;
- Adjust tests for new exception messages;
Result:
More understandable exception messages from `HttpObjectDecoder`.
Depends on #1227.

Improve exception messages from `HttpObjectDecoder`

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CloseableIteratorBufferAsInputStreamTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/AbstractCloseableIteratorAsInputStream.java

Motivation:
Users of `InputStream#read()` API expect to see return values in -1..255 range.
However, we do not apply this constraint when we cast `byte` to `int` for impls
that convert `Publisher` to `InputStream`.
Modifications:
- Apply `& 0xFF` when we cast `byte` to `int`;
Result:
Our `InputStream` implementations return values within expected range.

`Publisher` to `InputStream` adapters should return a read byte in -1..255 range

---

servicetalk-data-jackson/src/main/java/io/servicetalk/data/jackson/ByteArrayJacksonDeserializer.java

Motivation:
`ByteArrayJacksonDeserializer` may access an underlying `byte` array if the heap
`Buffer` was passed. However, it does not account for the `buffer.readerIndex()`
for the offset.
Modifications:
- Change `offset` to `buffer.arrayOffset() + buffer.readerIndex()`;
Result:
`ByteArrayJacksonDeserializer` correctly computes the offset.

`ByteArrayJacksonDeserializer` does not account for `readerIndex`

---

servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractNonParameterizedJerseyStreamingHttpServiceTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/SynchronousResourceTest.java

Motivation:
DefaultJerseyStreamingHttpRouter must create two URI objects in order to
initialize Jersey's ContainerRequest object. URI creation will also do
validation, and may throw. In this case we should return a 400 response
instead of a 500 internal server error.
Modifications:
- DefaultJerseyStreamingHttpRouter to try/catch creation of URIs and
return a 400 if an exception is thrown.
Result:
More correct error returned in the event of invalid URI when using
Jersey.

Jersey to return 400 response for invalid URI

---

servicetalk-concurrent-reactivestreams/src/main/java/io/servicetalk/concurrent/reactivestreams/ReactiveStreamsAdapters.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/ReactiveStreamsAdaptersTest.java

Motivation:
ReactiveStreamsAdapters currently only supports Publisher type. Users
can manually convert from Single and Completable to Publisher, but this
isn't a streamlined approach.
Modifications:
- Add conversion methods for Single and Completable to RS Publisher in
ReactiveStreamsAdapters
Result:
Direct conversions from all concurrent-api types to RS Publisher.

ReactiveStreamsAdapters support for Single and Completable

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractPubToCompletable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PubCompletableOrError.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PubToCompletableIgnore.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/PubCompletableOrErrorTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/PubToCompletableIgnoreTest.java

Motivation:
We have Publisher#ignoreElements which ignores any onNext signals
emitted from the Publisher. However there are use cases where the
conversion should be more strict and fail if there are any onNext
signals.
Modifications:
- Add Publisher#completableOrError method to do a strict conversion.
Share code with Publisher#ignoreElements operator.
Result:
Operator exists which does a strict conversion from Publisher to
Completable.

Add Publisher#completableOrError operator

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java

Motivation:
The additional content-type check in`canAddContentLength`, was added due to a bug, addressed [here](**url**)  
Modifications:
Removed the additional check
Result:
Behavior restored as pre http compression feature.

Relax can-add-content-length check

---

servicetalk-client-api/docs/modules/ROOT/pages/service-discovery.adoc
servicetalk-dns-discovery-netty/build.gradle

Motivation:
`macOS` users frequently experience problems with DNS resolutions without
this dependency. Those problems are hard to debug and understand without
knowing implementation details of netty's DNS codec. We can safely include
it by default, because the load of its classes is performed only on `macOS`
platform.
Modifications:
- Include `netty-resolver-dns-native-macos` dependency in `runtimeOnly`
classpath;
- Update `service-discovery.adoc`;
Result:
`macOS` users have correct DNS setup by default.

Include `netty-resolver-dns-native-macos` dependency by default

---

servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ServiceDiscovererUtils.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserver.java
servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserverTest.java
servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/TestRecordStore.java

Motivation:
`DnsResolutionObserver#resolutionCompleted` returns incorrect numbers for
`ResolutionResult` when some addresses become unavailable.
Modifications:
- Fix metrics bug in `ServiceDiscovererUtils.calculateDifference`;
- Add tests to verify we correctly report numbers when DNS returns different
resolution updates;
- Use `BlockingQueue` instead of `List` in `DnsServiceDiscovererObserverTest`;
Result:
`DnsResolutionObserver#resolutionCompleted` correctly reports number of
available and unavailable records.

Fix incorrect numbers reported by `DnsResolutionObserver#resolutionCompleted`

---

.github/workflows/prb.yml

Motivation:
For the pull_request event the permissions for the GITHUB_TOKEN in
forked repositories is read-only. This means that pull requests from
forks will not be able to publish updates to the pull request. This
means that test results, checkstyle, and other reports will fail to
publish on pull requests, making debugging more difficult.
Modifications:
- use pull_request_target [3] instead of pull_request.
Result:
PRs from forks will be able to publish test results, checkstyle, and
other quality reports.
[1] https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
[2] https://docs.github.com/en/free-pro-team@latest/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
[3] …

Github Actions PRB, use pull_request_target event

---

.github/workflows/prb.yml

Motivation:
Task names for generated reports don't indicate they are just the
published reports, and don't represent the actual analysis execution.
Modifications:
- Include "report" in the name for these tasks to clarify
Result:
Task names for reports are more clear that they just represent the
report/visualization.

Github Actions PRB clarify report task names

---

scripts/publish-docs.sh
scripts/release.sh

Motivation:
The release process has changed and now involved Github actions.
Previously the CI ran the release.sh script an a user manually ran the
publish-docs.sh script. This split came from a time when publishing docs
was more complicated, but it no longer needs to be manually orchistrated
in two different steps.
Modifications:
- release.sh should invoke publish-docs.sh
- publish-docs.sh should force docs to be published with JDK11 to get
newer javadocs (including search).
Results:
Single script to prepare release and generate artifacts.

release.sh to also publish docs

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DynamicCompositeCancellable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/QueueDynamicCompositeCancellable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SetDynamicCompositeCancellable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AbstractDynamicCompositeCancellableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/QueueDynamicCompositeCancellableTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/FlowControlUtils.java

Motivation:
DynamicCompositeCancellable are used in operators that keep a collection
of Cancellable objects (e.g. flatMap, merge, etc.). The implementations
are intended to be thread safe between adding Cancellables and
cancelling Cancellables that have been previously add (and not removed).
The DynamicCompositeCancellable implementations rely upon
reading volatile state after an element is added to a concurrent
collection to cancel the new element if there is a race. However the add
thread is not gaurenteed to observe a write from the cancel thread, and
if this is the case an element maybe added and never cancelled.
Modifications:
- The add thread should attempt to read/modify state in coordination
with the cancel thread to gaurentee that element will be cancelled.
Result:
More correct …

DynamicCompositeCancellable race condition fix

---

servicetalk-concurrent-api-test/src/main/java/io/servicetalk/concurrent/api/test/StepVerifiers.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/CompletableStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/PublisherStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/SingleStepVerifierTest.java

Motivation:
`FirstSteps` is harder to discover compare to `StepVerifiers` factory.
Follow up for #1240.

Rename `FirstSteps` -> `StepVerifiers`

---

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/FlowControlUtils.java

Motivation:
FlowControlUtils is an internal class, and there are methods which are
no longer used.
Modifications:
- Remove subtractIfPositive, and addWithOverflowProtection variants that
take Atomic*Updater arguments
Result:
Less unused code in FlowControlUtils.

FlowControlUtils remove unused methods

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ChannelInitializer.java

Motivation:
`ChannelInitializer` has exactly one abstract method and should be marked as
`@FunctionalInterface`.

Add `@FunctionalInterface` annotation for `ChannelInitializer`

---

servicetalk-transport-netty-internal/build.gradle
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RetryableClosureException.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ServiceTalkWireLogger.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NoopExecutionStrategy.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertClientHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java

Motivation:
TLS protocol defined `close_notify` alert message [1], which notifies that the
sender will not send any more messages on this connection. `SslHandler`
generates `SslCloseCompletionEvent` in this case, then transport emits
`ChannelInputShutdownReadComplete` event when the FIN is received. There is a
race between these 2 user events and sending a new request on the client-side.
We MUST close down the connection immediately, discarding any pending writes,
and preventing new requests. We should also mark that the connection is
closing asap to prevent LB from selecting this connection.
1. https://tools.ietf.org/html/rfc5246#section-7.2.1
Modifications:
- Handle `SslCloseCompletionEvent` in `DefaultNettyConnection`;
- Add tests to verify client and server behavior when …

Handle `close_notify` TLS alert

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpCookiePair.java

Motivation:
DefaultHttpCookiePair#parseCookiePair doesn't check for overflow when
calculating the value starting index.
Modifications:
- Check for overflow when calculating overflow index.
Result:
More robust overflow detection in DefaultHttpCookiePair#parseCookiePair.

DefaultHttpCookiePair#parseCookiePair more strict overflow detection

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableProcessor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ConcurrentStack.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleProcessor.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableProcessorTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ConcurrentStackTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleProcessorTest.java

Motivation:
CompletableProcessor and SingleProcessor maintain a queue and an
independent state for termination. It is possible that a Subscriber
maybe added on different thread than is terminating the Processor, and
the terminal state may not be visible yet such that the Subscriber never
gets terminated.
Modifications:
- The thread adding the the queue should attempt to read/modify state in
coordination with the thread terminating to gaurentee the new Subscriber
will be terminated.
- Allow for out of order termination in the event that the processor
completes before the subscribe operation happens.
Result:
Fixes https://github.com/apple/servicetalk/issues/1033

CompletableProcessor and SingleProcessor race condition fix

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpCookiePair.java

Motivation:
DefaultHttpCookiePair#parseCookiePair methods are currently public, but
users are unlikely to interact directly with these APIs and are instead
encouraged to interact with HttpCookiePair objects via the HttpHeaders
API.
Modifications:
- Make DefaultHttpCookiePair#parseCookiePair methods package private
Result:
Less public API surface that isn't necessary and duplicates capabilities
provided by other public APIs.

DefaultHttpCookiePair#parseCookiePair public -> package private 

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java

Motivation:
Existing approach for adding `HostHeaderHttpRequesterFilter` in
`DefaultSingleAddressHttpClientBuilder` keeps reference to the
`hostToCharSequenceFunction` at the time of class initialization. However,
`hostToCharSequenceFunction` can be changed later (in a proxy ctor or
`unresolvedAddressToHost` builder method). In these cases,
`hostHeaderFilterFactoryFunction` keeps the reference to the old
`hostToCharSequenceFunction`.
Modifications:
- Use a `boolean` to know when `HostHeaderHttpRequesterFilter` should be
applied;
- When `HostHeaderHttpRequesterFilter` is added, use the latest reference to
the `hostToCharSequenceFunction`;
Result:
`HostHeaderHttpRequesterFilter` uses the latest version of
`hostToCharSequenceFunction` to determine the fallback value for the `host`
header.

`DefaultSingleAddressHttpClient` may add incorrect `host` header by default

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterableTest.java

Motivation:
`PublisherAsBlockingIterable` uses an intermediate queue to keep the received
items from the `Publisher` until users consume them. However, `onNextQueued`
counter is updated when users consume `next()` item, but it's actually removed
from the queue inside `hasNext()`. As the result, `QueueFullException` is
generated when the queue is still able to fit one more element.
Modifications:
- Removed unnecessary `maxBufferedItems` internal variable;
- Update `onNextQueued` counter together with `itemsToNextRequest` counter
inside `hasNext()`;
- Enhance
`PublisherAsBlockingIterableTest#replenishingRequestedShouldHonourQueueContents()`
test to account for this use-case;
Result:
`PublisherAsBlockingIterable` correctly updates `onNextQueued` counter.

Avoid incorrectly throwing `QueueFullException` from `PublisherAsBlockingIterable`

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ServiceTalkWireLogger.java

Motivation:
`ServiceTalkWireLogger` is a rework if netty's `LoggingHandler` which allows
us to control logging of user data. However, the output format was a bit
different from netty, making it harder to compare netty and ST logs. Also,
it has a few minor issues with the output.
Modifications:
- Align output format with `LoggingHandler`;
- Make internal methods `static` when possible;
- Do not print extra new line when buffer is empty;
- Log how `Channel`'s writability changed;
- Do not log `localAddress` when it's `null`;
Result:
Output of `ServiceTalkWireLogger` and `LoggingHandler` is aligned.

Make `ServiceTalkWireLogger` consistent with `LoggingHandler`

---

servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpAuthorityFormUriTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/Uri3986Test.java

Motivation:
AHC recently was exposed to CVE-2020-13956 [1] incorrectly handling
malformed authority component. They fixed it in [2]. Let's make sure
ST doesn't have the same issue.
Modifications:
- Add tests for our `Uri` impls for the same case as [2];
Result:
Confidence that our `Uri` impls correctly handle malformed authority
component.
1. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13956
2. https://github.com/apache/httpcomponents-client/commit/e628b4c5c464c2fa346385596cc78e035a91a62e

Make sure our `Uri` parsers correctly handle malformed authorities

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilterTest.java

Motivation:
`HostHeaderHttpRequesterFilter`, `AbsoluteAddressHttpRequesterFilter`,
and `AbstractStreamingHttpConnection` modify the request outside of the
asynchronous execution chain. In case of repeat or retry, if the
`request`'s state was reset or a new `request` was created, we loose
the state applied by those classes.
Modifications:
- Use `Single.defer` operator in all these cases to execute the logic
for each retry/repeat operation;
Result:
Filters logic always applied on each retry/repeat.

Some filters won't be executed on retry/repeat

---

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RequestTargetDecoderHttpServiceFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RequestTargetEncoderHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RequestTargetEncoderHttpServiceFilter.java

Motivation:
`RequestTarget*Filter`(s) use `Single.defer` operator to modify the
request-target on each subscribe, however it doesn't share the
`AsyncContext`. As the result, context changes made during request
processing won't be visible during processing response payload body.
Modifications:
- Add `subscribeShareContext()` operator for all `RequestTarget*Filter`(s);
Result:
Correct `AsyncContext` propagation in `RequestTarget*Filter`(s).

Share `AsyncContext` when `RequestTarget*Filter`(s) are used

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnServerContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TestServiceStreaming.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpConnectorTest.java
servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java

Motivation:
Users who want to correlate `TransportObserver#onNewConnection()` events with
the request object may use `AsyncContext` to propagate correlation key.
However, `AsyncContext` is not visible from `TransportObserver#onNewConnection()`
because it runs from IO-thread. It's also important to invoke
`TransportObserver#onNewConnection()` callback earlier on the client-side.
Modifications:
- Trigger `TransportObserver#onNewConnection()` as soon as someone subscribes to
`TcpConnector#connect` single on the client-side to get access to the caller's
thread `AsyncContext`;
- Trigger `TransportObserver#onNewConnection()` at the beginning of `initChannel`
on the server-side for consistency with the client-side;
- Update internal classes and tests to use new API;
- Add tests to verify …

Make `AsyncContext` visible from `TransportObserver#onNewConnection()`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceContext.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcServiceContextProtocolTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpConnectionContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpConnectionContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpProtocolVersion.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/TestHttpServiceContext.java
servicetalk-http-netty/build.gradle
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultNettyHttpConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ResponseCancelTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionContextProtocolTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseCancelTest.java

Motivation:
`LoadBalancedStreamingHttpClient` pessimistically assumes the connection
that serves a request should be closed on request cancellation. However,
in case of HTTP/2 it closes the parent TCP connection instead of a stream
(because stream is not accessible from the connection API). It also fails
all other in-flight requests on the same connection.
Modifications:
- In case of HTTP/2 and above mark request as finished instead of closing
the connection when cancellation happens;
- Test that request cancellation doesn't close parent TCP connection for
HTTP/2 protocol;
- Change `HttpConnectionContext#protocol()` to return `HttpProtocolVersion`;
- Change `GrpcConnectionContext.GrpcProtocol` to return `HttpProtocolVersion`;
Result:
HTTP/2 request cancellation doesn't close the TCP …

Don't close entire HTTP/2 connection when request is cancelled

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/Http2Exception.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberFutureListenersTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberOutOfEventloopTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Motivation:
Netty's `Http2Exception` and `Http2FrameStreamException` extend `Exception`
instead of `IOException`. `IOException` provide better user-experience for
interception of HTTP/2 errors and more compatible with exception handling
logic in other libraries.
Modifications:
- Create a new `io.servicetalk.http.netty.Http2Exception` class that extends
`IOException`;
- Wrap all netty's HTTP/2 related exceptions with this new type;
- Change pre-existing `H2StreamRefusedException` and `H2StreamResetException`
to also extend the new type;
- Include streamId in `H2StreamRefusedException` and `H2StreamResetException`
exception messages;
- Update tests that expect netty exception types;
Result:
All HTTP/2 related exceptions extend `IOException`.

Wrap all netty's HTTP/2 related exceptions with `IOException`

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ResponseCancelTest.java

Motivation:
`H2StreamResetException` was moved in #1304, but used old location in #1307.
Those PRs were merged concurrently without updating the import.
Modifications:
- Update import for `H2StreamResetException` in `H2ResponseCancelTest`;
Result:
Build does not fail.

Update import for `H2StreamResetException`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/Http2Exception.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java

Motivation:
HTTP/2 codec may throw an exception when it creates a stream in some cases:
- When there is a concurrency between closing the parent h2 connection and
creating a new stream;
- When stream IDs are exhausted for this endpoint;
- When maximum active streams violated for this endpoint;
In all this cases it's safe to retry the request because we do not start
writing it on the wire. When parent connection is closing concurrently, we
won't hit this error again because it will be marked as "closing" and LB
won't select this connection again.
Modification:
- Wrap `Http2Exception`(s) with `Http2Error.REFUSED_STREAM` as retryable;
- Wrap `Http2NoMoreStreamIdsException` as retryable;
Result:
`HttpClient` will automatically retry recoverable HTTP/2 exceptions.

Identify retryable `Http2Exception`(s) generated by netty

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java

Motivation:
We introduced
`H2ProtocolConfigBuilder#enableFrameLogging(String, LogLevel, BooleanSupplier)`
a few releases ago but forgot to mark the original
`H2ProtocolConfigBuilder#enableFrameLogging(String)` as deprecated.
Modifications:
- Mark `H2ProtocolConfigBuilder#enableFrameLogging(String)` as deprecated;
Result:
`H2ProtocolConfigBuilder#enableFrameLogging(String)` is marked as deprecated and
prepared to be removed in future releases.

Mark `H2ProtocolConfigBuilder#enableFrameLogging(String)` as deprecated

---

servicetalk-concurrent-internal/src/testFixtures/java/io/servicetalk/concurrent/internal/ServiceTalkTestTimeout.java

Motivation:
During testing/development it is often useful to limit the test value
below the default value. This allows test failures to occur more quickly
when running a sequence of tests, and the developer can then narrow in
on the failing tests and identify patterns. However
ServiceTalkTestTimeout currently enforces a lower bound on the timeout
to the default value (currently 10 seconds per test).
Modifications:
- Remove lower bound in ServiceTalkTestTimeout
Result:
ServiceTalkTestTimeout can set lower timeout values during development.

ServiceTalkTestTimeout remove default min timeout limit

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnIds.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultBlockingStreamingHttpResponseFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpResponseFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultStreamingHttpResponseFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestEncoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseFactoryStatusCodeTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpClientConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java

Motivation:
HTTP/1.x protocol requires the version is included in the request and
response. When generating requests/response objects in the application
we tend to default to HTTP_1_1 despite the protocol and user
preferences. This may result in additional conversions and confusion
when using version accessors.
Modifications:
- For request/response factories that can derive the real version from
the transport they should use the real version
- For use cases that don't know which protocol will be used (e.g. Client
where h1, h2, etc. is requested) use the version most preferred
locally. Worst case additional conversions will be required if the
preferred protocol isn't used.
Result:
HttpVersion in request/response objects will be more accurate and less
conversions will be required.

Infer HttpVersion in requests/responses based upon protocol selection

---

servicetalk-concurrent-api-internal/src/main/java/io/servicetalk/concurrent/api/internal/ConnectablePayloadWriter.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/ConnectableBufferOutputStreamTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/ConnectablePayloadWriterTest.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouteConversions.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProviderBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingToBufferHttpPayloadWriter.java
servicetalk-oio-api/src/main/java/io/servicetalk/oio/api/PayloadWriter.java

Motivation:
In some scenarios the PayloadWriter wraps a Subscriber (e.g.
ConnectablePayloadWriter), and the close may occur as a result of an
error that needs to be propagated to the Subscriber.
Modifications:
- Add close(Throwable) to the PayloadWriter API
- ConnectablePayloadWriter calls subscriber.onError(cause) for the
close(Throwable) method
- BlockingStreamingToStreamingService to use close(Throwable) for more
robust cleanup
Result:
PayloadWriter use cases can close while indicating the error reason.

Add PayloadWriter#close(Throwable)

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableToPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/OnSubscribeIgnoringSubscriberForOffloading.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleToPublisher.java

Motivation:
93165f04398085600a628e5af9d5de625b37aa2f made a change to ensure invalid
requestN demand is propagated to the associated Subscriber. However
OnSubscribeIgnoringSubscriberForOffloading#offloadWithDummyOnSubscribe
is used in such a way that a terminal event will already be delivered
and demand is validated externally. This usage is so the offloader has
the expected onSubscribe method invoked, but the Subscription will not
actually be used. The usage can therefore be simplified to use
EMPTY_SUBSCRIPTION and avoid potential for duplicate terminal delivery
to the Subscriber.
Modifications:
- OnSubscribeIgnoringSubscriberForOffloading#offloadWithDummyOnSubscribe
to use EMPTY_SUBSCRIPTION.
Result:
Avoid potential for duplicate terminal event delivery in …

OnSubscribeIgnoringSubscriberForOffloading empty subscription usage

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherAsBlockingIterableTest.java

Motivation:
PublisherAsBlockingIterable applies back pressure in two different ways.
First it limits the amount of demand it issues to the Subscription, and
second it enforces a limit on the number of elements in the internal
queue. Only one of these is necessary.
Modifications:
- Just limit the demand to the Subscription and remove the internal
limits on the number of items in the queue.
Result:
Simplified backpressure management in Publisher
[toIterable | toInputStream].

Publisher [toIterable | toInputStream] simplify initernal queue limit

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToBlockingStreamingHttpService.java

Motivation:
StreamingHttpServiceToBlockingStreamingHttpService (used by
HttpJerseyRouterBuilder.buildBlockingStreaming) doesn't apply any
backpressure and also may not propagate error status correctly in the
event the StreamingHttpResponse fails.
Modifications:
- PayloadPump uses the new PayloadWriter.close(Throwable) method to
propagate status in the event the StreamingHttpResponse fails.
- PayloadPump requests in chunks of 64 by default to apply backpresusre.
That way if the blocking PayloadWriter APIs block, the source
providing data will be limited to 64 chunks at most.
Result:
HttpApiConversions.toBlockingStreamingHttpService(StreamingHttpService)
applies backpressure and propagates error status to the PayloadWriter.

HTTP StreamingService to BlockingStreaming backpressure and error propagation fixes

---

servicetalk-data-jackson-jersey/docs/modules/ROOT/pages/index.adoc

Motivation:
The public URL for the JAX-RS 2.1.X API documentation has moved to the Eclipse Jakarta EE
site. This has broken links to the documentation in the published ServiceTalk.io site and
prevents successful validation of generated site documentation for local builds.
Modifications:
The broken URL is updated to match the current published location for JAX-RS API
documentation.
Result:
Validation succeeds for local documentation builds and the link is no longer broken.

URL fix for JAX-RS API documentation

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableMergeWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableMergeWithPublisherTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletableMergeWithPublisherDelayErrorTckTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NonPipelinedStreamingHttpConnection.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java

Motivation:
The HTTP client control flow merges the resule of the write Publisher
(a Completable) and the read Publisher via Completable#merge(Publisher).
However when offloading is enabled it is possible events will be
delivered out of order which may result in dropped data/trailers.
Modifications:
- Introduce the Completable#mergeDelayError(Publisher) operator
- Use new mergeDelayError(..) operator instead of merge(..) so that both
streams must complete which ensures all the read data is delivered to
the application before any errors. It is assumed that if the write
Publisher fails that the read publisher will also fail due to transport
failure.
Result:
No more dropped data/trailres on HTTP client due to write failure (e.g.
connection closure) being delivered before read data due to …

Completable#mergeDelayError(Publisher) and HTTP client control flow

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingExecutor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MergedOffloadPublishExecutor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MergedOffloadSubscribeExecutor.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java

Motivation:
Global instances of `IoExecutor` and `Executor` are shared across all client
and server instances by default (unless users provide custom executors).
Closing them may affect all other clients and servers that depend on them.
The only legit way of closing global executors is when everything else that
depends on it is already closed. We should notify users if they close
global instances.
Modifications:
- Wrap global `IoExecutor` and `Executor` instances and log when users
subscribe to their `closeAsync()` or `closeAsyncGracefully()` methods;
- Change `NettyIoExecutors#createIoExecutor` methods return type to
`EventLoopAwareNettyIoExecutor`;
Result:
Users who closed global `IoExecutor` or `Executor` in incorrect order and debug
issues caused by this closure will see a debug …

Log when global `IoExecutor` or `Executor` instance gets closed

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableMergeWithPublisher.java

Motivation:
CompletableMergeWithPublisher currently uses an atomic counter to
control when the downstream subscriber should be terminated, and also a
ConcurrentTerminalSubscriber to protect the downstream subscriber from
concurrent invocation. These two concurrency controls can be merged into
a single atomic variable to reduce the number of atomic operations.
Modifications:
- Remove ConcurrentTerminalSubscriber from
CompletableMergeWithPublisher. The counter only needs to track two
completion events which can be represented as a bitmask which permits
immediate error propagation but requires both complete events.
- onNext can now avoid locking/unlocking if the completable has
terminated because there will be no concurrency.
Result:
Optimized concurrency control in …

Completable#merge(Publisher) subscriber concurrency updates

---

servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java

Motivation:
The
[gRPC protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests)
does not use request trailers. This means the server is allowed to drop
trailers if any are present. This may provide a performance benefit as
request transformation operations do not have to worry about preserving
trailers.
Modifications:
- DefaultGrpcServerBuilder to use the allowDropRequestTrailers(true)
method.
Result:
gRPC Server is allowed to drop the request trailers, requiring less work
to preserve trailers (which don't exist) through request transform
operations.

gRPC Server allow drop of request trailers

---

docs/generation/README.adoc
servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/grpc/compression/README.adoc
servicetalk-examples/grpc/compression/build.gradle
servicetalk-examples/grpc/compression/src/main/java/io/servicetalk/examples/grpc/compression/CompressionExampleClient.java
servicetalk-examples/grpc/compression/src/main/java/io/servicetalk/examples/grpc/compression/CompressionExampleServer.java
servicetalk-examples/grpc/compression/src/main/java/io/servicetalk/examples/grpc/compression/package-info.java
servicetalk-examples/grpc/compression/src/main/proto/compression.proto
servicetalk-examples/grpc/compression/src/main/resources/log4j2.xml
servicetalk-examples/http/compression/build.gradle
servicetalk-examples/http/compression/src/main/java/io/servicetalk/examples/http/compression/CompressionFilterExampleClient.java
servicetalk-examples/http/compression/src/main/java/io/servicetalk/examples/http/compression/CompressionFilterExampleServer.java
servicetalk-examples/http/compression/src/main/resources/log4j2.xml
settings.gradle

Motivation:
Provide an example demonstrating use of the content encoding compression features.
Modifications:
- A new HTTP example, Compression
- Additional documentation
Result:
No further need to reference test code to understand how to use compression features.

Examples for HTTP and gRPC compression

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NonPipelinedCloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NonPipelinedCloseHandlerTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java

Motivation:
HTTP/2 child channels currently use a static CloseHandler instance which
will immediately close the connection upon detecting inbound channel
closing. This event may occur as a result of an exception being thrown
in error code, which may then write data (e.g. error code in response
trailers). Using the static CloseHandler may result in writing a stream
reset frame followed by subsequent data/headers frames which violates
the HTTP/2 protocol.
Modifications:
- Introduce a CloseHandler implementation that can be used in scenarios
that don't require half-closure or DuplexChannel types. This
CloseHandler can be used for HTTP/2 to delay any pending close
operations until after any pending writes complete.
Result:
No more HTTP/2 protocol violations due to writing RST_STREAM frame …

HTTP/2 CloseHandler avoid writing after channel closed

---

servicetalk-log4j2-mdc-utils/gradle/checkstyle/suppressions.xml
servicetalk-log4j2-mdc-utils/src/main/java/io/servicetalk/log4j2/mdc/utils/ServiceTalkThreadContextMap.java
servicetalk-log4j2-mdc/src/main/java/io/servicetalk/log4j2/mdc/DefaultServiceTalkThreadContextMap.java
servicetalk-log4j2-mdc/src/main/java/io/servicetalk/log4j2/mdc/package-info.java
servicetalk-log4j2-mdc/src/main/resources/META-INF/log4j-provider.properties

When multiple MDC providers are available in the cp, then unless the user specifies one through a system property, we can't know which one will be used. 
Add conflict check on ST's default provider, to detect presence of the other provider, and throw an exception.
**Result**:
Fast fail for common conflicts in the class path.
**Example output**:
```
Detected multiple ServiceTalk MDC adapters in classpath. The [io.servicetalk.log4j2.mdc.DefaultServiceTalkThreadContextMap, io.servicetalk.opentracing.log4j2.ServiceTalkTracingThreadContextMap] MDC adapters should not be loaded at the same time. Please exclude one from your dependencies.
ERROR StatusLogger Unable to locate or load configured ThreadContextMap …
```

Add MDC ThreadContextMap conflict check on ST default provider

---

servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/AbstractZipContentCodec.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpServiceFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BaseContentCodingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentCodingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkEmptyContentCodingTest.java

When a payload publisher on the response flow is not emitting any items, the encoder will not emit the header, thus a client will not be able to decode the response.
Make sure the header is emitted even for empty publishers.
Extra checks where added to skip encoding & headers when the request doesn't support body-messages.
**Result**:
Clients will be able to decode correctly encoded response payload, even when empty.

Fix broken encoding when publisher has no content

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java

Motivation:
HTTP/1.1 tries to prevent messages with more than one `content-length`
header values. The recipient must either reject the message or drop
duplicate values. See https://tools.ietf.org/html/rfc7230#section-3.3.2
Because we translate HTTP/2 messages into HTTP/1.1 API, we should follow
the same principles. In addition, HTTP/2 RFC7540 says: A request or response
is also malformed if the value of a content-length header field does not
equal the sum of the DATA frame payload lengths that form the body.
See https://tools.ietf.org/html/rfc7540#section-8.1.2.6
Modifications:
- Add `HeaderUtils#contentLength` utility which guard against multiple
`Content-Length` headers;
- Use the new utility in `HttpObjectDecoder` and `AbstractH2DuplexHandler`;
- Calculate and verify actual DATA with …

Reject HTTP messages with malformed `content-length` value(s)

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpResponseEncoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseEncoderTest.java

Motivation:
If a message is received with both a Transfer-Encoding and a
Content-Length header field, the Transfer-Encoding overrides the
Content-Length.  Such a message might indicate an attempt to
perform request smuggling (Section 9.5) or response splitting
(Section 9.4) and ought to be handled as an error.  A sender MUST
remove the received Content-Length field prior to forwarding such
a message downstream.
See https://tools.ietf.org/html/rfc7230#section-3.3.3
Modifications:
- Remove `content-length` header when `transfer-encoding: chunked`
is present in incoming (`HttpObjectDecoder`) and outgoing
(`HttpObjectEncoder`) messages;
- Add tests to verify the behavior;
Result:
HTTP/1.1 codec follow RFC7230 3.3.3 item 3: removes Content-Length
header when "Transfer-Encoding: chunked" is …

Remove `content-length` when `transfer-encoding: chunked` is present

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java

Motivation:
When RRLB receives an inactive event from `ServiceDiscoverer`, it initiates
graceful closure of all connections to the host that became inactive. Give
some visibility to this logic.
Modifications:
- Add `DEBUG` log statement when RRLB closes connections to inactive host;
Result:
Users can debug when RRLB initiates connection closure.

Debug-log when `RoundRobinLoadBalancer` closes connections to inactive addresses

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/CharSequencesTest.java
servicetalk-encoding-api-internal/src/main/java/io/servicetalk/encoding/api/internal/HeaderUtils.java
servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/CharSequences.java

CharSequences#split needed some improvements to avoid extra allocations for trimming (externally) and conversion to String due to calls to subsequence.
This PR improves the helper to support trimming individual tokens without additional allocations, and also better utilizes AsciiBuffer internals to avoid unnecessary conversions.
**Result**:
API can now handle representations that contain whitespaces in between delimiters.
Fixes: https://github.com/apple/servicetalk/issues/1216

Improve CharSequences#split to support trim and min copies

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpQuery.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/UriUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractHttpRequestMetaDataTest.java

Motivation:
HttpRequestMetaData#queryParameter(String) could incounter index out of
bounds conditions if an empty value was the last entry in the query
string.
Modifications:
- Fix indexing for name/value start/end indexes and add tests for empty
values.
Result:
No more index out of bounds for
HttpRequestMetaData#queryParameter(String).

HttpRequestMetaData query string empty value parsing fix

---

.github/workflows/ci-prb-reports.yml
.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml

Motivation:
The bot updated the action-surefire-report plugin in
c4de9b721a793b9fee4c9f239736e36299098815 and there is an out of date
comment indicating the version.

Github actions remove out of date version comment

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java

Motivation:
Responses to the HEAD request method (Section 4.3.2 of [RFC7231]) never
include a message body because the associated response header fields
(e.g., Transfer-Encoding, Content-Length, etc.), if present, indicate
only what their values would have been if the request method had been
GET (Section 4.3.1 of [RFC7231]).
All other requests and responses should fail if the `content-length`
header is present when there is only a single `HEADERS` frame with
`END_STREAM` flag.
https://tools.ietf.org/html/rfc7230#section-3.3
Modifications:
- Adjust `H2ToStH1ClientDuplexHandler` to allow receiving responses to
`HEAD` requests with `content-length` header;
- Fail any other request or response with `content-length` header when
it consist of only a single `HEADERS` frame with `END_STREAM` …

Allow HEAD requests with content-length header over HTTP/2

---

scripts/publish-docs.sh
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ExecutorRule.java
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkRootPlugin.groovy

Motivation:
When users use search features of the javadoc website, they are redirected
to the broken link. This is due to the bug in JDK:
https://bugs.openjdk.java.net/browse/JDK-8215291
Modifications:
- Add `-no-module-directories` option for `javadocAll` task to workaround
the bug for JDK11;
- `javadocAll` task should depend on `javadoc` taks from each submodule;
-  `publish-docs.sh` should clean the project before generating javadoc;
Result:
Search feature works for javadoc website.

Fix search feature for javadoc website

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java

Motivation:
1. `AbstractLBHttpConnectionFactory` shares a single instance of
`emptyAsyncCloseable()` between all `ConnectionFactory` instances.
Each should have its own `emptyAsyncCloseable()`.
2. `DefaultPartitionedHttpClientBuilder#NoopPartitionClient`
implements `ListenableAsyncCloseable`, but does not use
`emptyAsyncCloseable()`.
Modifications:
- Create a new instance of `emptyAsyncCloseable()` for each
`ConnectionFactory` in `AbstractLBHttpConnectionFactory`;
- Create a new instance of `emptyAsyncCloseable()` for each
`DefaultPartitionedHttpClientBuilder#NoopPartitionClient`;
Result:
Correct use of `emptyAsyncCloseable()` in all
`ListenableAsyncCloseable` implementations.

Correctly use `emptyAsyncCloseable()`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java

Motiviation:
The existing tests for HTTP header validation do not cover some important header cases.
While adding the missing tests does not reveal any faults in the current header validation
it is important to include the tests for regression checking purposes.
Modification:
Additional tests for more invalid HTTP header cases are added as well as additional
documentation.
Result:
Regressions in HTTP header validation would be more likely detected.

Add additional tests for checking correct validation of HTTP headers

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java

Motivation:
HTTP/2 allows sending a request/response message in a single `HEADERS`
frame with `END_STREAM` flag if it doesn't have payload body. Those
messages may contain `content-length: 0` header. However,
`AbstractH2DuplexHandler` mistakenly rejects them as malformed.
Modifications:
- `H2ToStH1ClientDuplexHandler` and `H2ToStH1ServerDuplexHandler` shoudl
throw unexpected `content-length` exception for single-frame
request/response only if its `content-length` header value is greater
than zero;
- Add test to verify this scenario;
Result:
`AbstractH2DuplexHandler` allows single-frame HTTP/2 messages with zero
content-length header value.

Do not fail HTTP/2 single-frame messages with zero content-length

---

servicetalk-opentracing-zipkin-publisher/build.gradle
servicetalk-tcp-netty-internal/build.gradle
servicetalk-transport-netty-internal/build.gradle
servicetalk-transport-netty/build.gradle

Motivation:
ServiceTalk includes implementation dependendencies on Netty's native
modules so users will get runtime dependencies for free. We don't yet
include the linux-aarch64 dependency for epoll.
Modifications:
- add the epoll linux-aarch64 dependency
- remove redundant native dependencies from packages that will bring in
the dependencies transitively
Result:
linux-aarch64 linux use cases get native epoll transport for free.

Add Netty epoll dependency for linux-aarch64

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultPayloadInfo.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PayloadInfo.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractConversionTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/RequestConversionTests.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/ResponseConversionTests.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java

Motivation:
5832d5d65ec26b181fa14ed457eab9864a9ce30b deprecated the following
methods:
- payloadBodyAndTrailers
- transformRawPayloadBody
- transformRaw
These methods can now be removed as alternatives exist.
Modifications:
- Remove the deprecated methods from all http request/response types
- Simplify StreamingHttpPayloadHolder logic which now only expects
Buffer payload manipulation.
- Remove PayloadInfo#onlyEmitsBuffer methods which are no longer
relevant.
Result:
Less deprecated methods for HTTP types, more narrow API that is more
representative of what is actually supported (e.g. Buffer type).

Remove deprecated methods from HTTP request/response types

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpCookiePair.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpCookiePairTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookieTest.java

Motivation:
RFC6265 implicitly defines that cookie names are case-sensitive. All
browsers treat cookie names as case-sensitive, see [1, 2].
Cookie values are always case-sensitive.
1. https://stackoverflow.com/questions/11311893/is-the-name-of-a-cookie-case-sensitive
2. https://github.com/playframework/playframework/issues/2241
Modifications:
- Change `equals` and `hashCode` impl of `DefaultHttpCookiePair` to compare
cookie name and value case-sensitively;
- Change `equals` and `hashCode` impl of `DefaultHttpSetCookie` to compare
cookie name case-sensitively, also include cookie value;
- Add tests to verify changes;
Result:
`HttpCookiePair` implementations correctly implement `equals` and `hashCode`.

`HttpCookiePair` impls should treat name and value case-sensitively

---

servicetalk-http-netty/gradle/spotbugs/main-exclusions.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingHttpRequestWithContext.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java

Motivation:
In #1307 we changed `LoadBalancedStreamingHttpClient` to not close the
connection on cancel for HTTP/2 protocol, because our existing API does
not expose methods for closing h2 stream instead of h2 connection.
Instead, we had to _prematurely_ mark the request as finished, because
in case of cancellation, there is no guarantee we will receive a terminal
signal on the response. Also, the stream is not aware of
`LoadBalancedStreamingHttpConnection` API and therefore it can not mark
the request as finished when it closes the stream.
That change significantly increased the probability users see
"Maximum active streams violated for this endpoint." Even though it's a
`RetryableException`, it creates pain and still may pop up after
auto-retry strategy used all attempts.
Modification: …

Avoid "Maximum active streams violated for this endpoint" at the client level

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferOutputStream.java

Motivation: BufferOutputStream.write(final int b) writes a byte as int which is wrong.
Modifications:
* in write(final int b){..} method body buffer.writeInt(b) is changed to buffer.writeByte(b)
Result:
Fixes the above bug. Only internal changes and no API changes.

BufferOutputStream.write(int b) should write as byte and not int

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HeaderUtilsTest.java

Motivation:
This code uses `CharSequence.equals` that does not have well-defined equals behavior. Such a call to equals may return false in cases where equality was expected.
https://errorprone.info/bugpattern/UndefinedEquals
Modifications:
replaced call to `CharSequence.equals` with `CharSequences.contentEquals`
Result:  
unit test comparing 2 different implementation of `CharSequences` is now passing

`HeaderUtils#pathMatches` incorrectly compares two different `CharSequence` implementations

---

docs/modules/ROOT/pages/performance.adoc
servicetalk-concurrent-api/docs/modules/ROOT/pages/blocking-implementation.adoc
servicetalk-concurrent-api/docs/modules/ROOT/pages/blocking-safe-by-default.adoc
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SignalOffloader.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ThreadBasedSignalOffloader.java
servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/PublisherSource.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingle.java

Motivation:
ServiceTalk relies upon and conforms to version 1.0.3 of the Reactive Streams
specification (see gradle.properties), but some of the Javadoc documentation references
the earlier 1.0.2 version of the specification.
Modification:
Documentation URLs are updated to reference 1.0.3
Result:
No discrepancy between version of Reactive Streams supported and version referenced in
documentation.

Reference Reactive-Streams 1.0.3 in Javadoc

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/AbstractContentCodec.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpCookiePair.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpCookiePairTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookieTest.java

Motivation:
CharSequence.equals does not have well-defined equals behavior. Such a call to equals may return false in cases where equality was expected.
https://errorprone.info/bugpattern/UndefinedEquals
Modifications:
replaced call to CharSequence.equals with CharSequences.contentEquals
temporarily using CharSequences.caseInsensitiveHashCode until CharSequences.hashCode is implemented
Result:
Comparing 2 different implementation of CharSequences created with the same chars returns true

Replace CharSequence equality checks with contentEquals

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/gradle/spotbugs/test-exclusions.xml
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcClients.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
servicetalk-grpc-netty/src/test/proto/helloworld.proto
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java

Motivation:
gRPC client builders do not expose methods to easily configure UDS
address.
Modifications:
- Add GrpcClients.forResolvedAddress(..) method that allows for passing
a UDS type of SocketAddress.
Result:
gRPC Clients can more easily be built for UDS.

gRPC Unix Domain Socket Client Support

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingHttpRequestWithContext.java

Motivation:
`LoadBalancedStreamingHttpClient` uses `StreamingHttpRequestWithContext`
wrapper to deliver `Runnable` to the underlying HTTP/2 transport level.
However, if we do not unwrap the request as soon as transport receives
it, the wrapper hides `PayloadInfo` interface of the original request
object and the following request processing can not apply required
optimizations for the payload body and flush strategy.
Modifications:
- Unwrap the original request object as soon as
`StreamingHttpRequestWithContext` finished its mission;
Result:
HTTP processing again sees `PayloadInfo` and can apply optimizations for
aggregated API (flush on end).

`LoadBalancedStreamingHttpClient` should not hide `PayloadInfo` of requests

---

servicetalk-concurrent-api-test/src/main/java/io/servicetalk/concurrent/api/test/StepVerifiers.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/CompletableStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/PublisherStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/SingleStepVerifierTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ResponseCancelTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertClientHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java

Motivation:
`stepVerifier` is not a verb and may reduce the developer ergonomics.
`StepVerifiers.create` expresses better what’s happening. It also more
consistent with other reactive-streams libraries.
Modifications:
- Copy `Verifiers` factory and rename it to `StepVerifiers`;
- Deprecated `Verifiers` class and reference `StepVerifiers` as a replacement;
- Update existing tests to use `StepVerifiers`;
Result:
Better developer's experience for our test utilities.

Change `Verifiers.stepVerifier` back to `StepVerifiers.create`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java

Motivation:
If the client receives a response with no grpc-status we return an error
as [required by the spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).
However we currently return a status code of INTERNAL but the UNKNOWN
status code is more appropriate [1][2].
[1] https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
> Error parsing returned status, UNKNOWN, Client
[2] https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md
> 200 is UNKNOWN because there should be a grpc-status in case of truly OK response.
Modifications:
- Change error status code to UNKNOWN if the grpc-status is not present.
Result:
More appropriate error code when grpc-status is missing from the
response on the client side.

gRPC missing grpc-status error code update

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContext.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextMap.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ConcurrentAsyncContextMap.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CopyOnWriteAsyncContextMap.java

Motivation:
The AsyncContext API and implementation are inconsistent on how null
values are treated for the put(key, value) method.
Modifications:
- Make the AsyncContext and AsyncContextMap APIs consistent with
java.util.Map API relative to null values. The API allows null values
and permits the implementation to not support it.
Result:
AsyncContext APIs have the same semantics as java.util.Map for null
values on the put(key, value) method.

Clarify AsyncContext put API relative to @Nullable

---

.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml
build.gradle
servicetalk-concurrent-jdkflow/build.gradle
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkRootPlugin.groovy

Motivation:
The concurrent-jdkflow requires JDK9+ in order to build, but our release
currently only builds on JDK8. The concurrent-jdkflow artifacts are
currently not published during the release process as a result.
Modifications:
- Add task in ci-release which builds on JDK11 and publishes the
concurrent-jdkflow artifacts
Result:
concurrent-jdkflow will be published in the next release.

Publish concurrent-jdkflow artifacts during release

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/grpc/errors/README.adoc
servicetalk-examples/grpc/errors/build.gradle
servicetalk-examples/grpc/errors/src/main/java/io/servicetalk/examples/grpc/errors/ErrorExampleClient.java
servicetalk-examples/grpc/errors/src/main/java/io/servicetalk/examples/grpc/errors/ErrorExampleServer.java
servicetalk-examples/grpc/errors/src/main/java/io/servicetalk/examples/grpc/errors/package-info.java
servicetalk-examples/grpc/errors/src/main/proto/errors.proto
servicetalk-examples/grpc/errors/src/main/resources/log4j2.xml
settings.gradle

Motivation:
How to return an application level error over the gRPC transport is a
common question, and we don't have an isolated example for this case.
Motivation:
- Add an example which demonstrates the server returning an application
level error over the gRPC transport
Result:
Example exists demonstrating server returning application level error
via the gRPC transport.

Add gRPC application level error example

---

servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java

Motivation:
TcpConnector logs an error message if a connection attempt fails and we
aren't able to propagate the exception. This may commonly happen in the
event of cancellation as Netty will propagate a CancellationException to
Future listeners.
Modifications:
- Remove error log statements from TcpConnector if we are unable to
complete async control flow
Result:
Less noise in log statements from TcpConnector.

TcpConnector reduce log noise

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java

Motivation:
GrpcRouter and GrpcServerBuilder will catch exceptions and translate
them into errors which get propagated into trailers. The exception path
is the expected way for servers to return application level errors to
clients. These methods also log error level log messages which is noisy
and can be replicated via a filter or in the application level if
necessary.
Modifications:
- Remove error level logging in GrpcRouter and CatchAllHttpServiceFilter
Result:
Less error level logging on exception paths which maybe expected by the
application.

gRPC Router reduce error log noise

---

servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ReflectionUtils.java

Motivation:
There are some extension modules that would benefit from the safety
provided by trySetAccessible(..) which avoids JDK9+ warnings about
reflection access going away. However this method is currently package
private.
Modifications:
- Make ReflectionUtils#trySetAccessible(..) internal utility public
Result:
ReflectionUtils#trySetAccessible(..) remains an internal utility
(subject to change in the future) but is now publicly accessible.

Make ReflectionUtils#trySetAccessible(..) internal utility public

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcServiceContextProtocolTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpService.java

Motivation:
The HTTP blocking streaming APIs passes ownership of the
HttpPayloadWriter to the user to close. The user may process the stream
on another thread after the handle method has returned, or close the
stream with an exception status. The gRPC blocking streaming handle
method always force closes the stream after the user code returns.
Modifications:
- Remove the force closure in gRPC blocking streaming routing layer
- Fix tests which were not invoking close()
Result:
HTTP and gRPC blocking streaming APIs are more consistent, and the user
has the ability to control when the GrpcPayloadWriter is closed.

Require gRPC blocking streaming services to close GrpcPayloadWriter

---

servicetalk-concurrent-api/docs/modules/ROOT/pages/asynchronous-primitives.adoc

Motivation:
Interoperability with pre-existing asynchronous sources is common for
pre-existing code. Our docs provide general advice but no practical
examples for how to convert between hot/eager sources and ServiceTalk's
lazy/cold sources.
Modifications:
- Add a section in the docs which provides example code to convert from
hot/eager sources.
Result:
Docs provide more information about conversion between hot/eager sources
to ServiceTalk cold/lazy sources.

Add Lazy Execution Interoperability section to docs

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/FromInputStreamPublisherTest.java

Motivation:
An `InputStream` with an arbitrary number of bytes available to be read
must be usable as a supply for payload body on a request.
However, supplying an `InputStream` with available bytes greater than
VM array size limit [1]. Results in `java.lang.OutOfMemoryError:
Requested array size exceeds VM limit` being thrown.
1. https://plumbr.io/outofmemoryerror/requested-array-size-exceeds-vm-limit
Modifications:
- Limited the max size of the buffer into which `InputStream` is read
to 64kb.
Result:
Providing an `InputStream` with available bytes greater than max VM
array size no longer results in an `OutOfMemoryError`.

`FromInputStreamPublisher` should apply an upper bound to temporary buffer size

---

servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java

Motivation:
Other modules (HTTP, gRPC, etc.) use
`enableWireLogging(String, LogLevel, BooleanSupplier)` variant.
Modifications:
- Introduce
`UdpReporter.Builder#enableWireLogging(String, LogLevel, BooleanSupplier)`;
- Deprecated `UdpReporter.Builder#enableWireLogging(String)`;
- Use `enableWireLogging` in `UdpReporterTest`;
Result:
Wire-logging configuration for `UdpReporter.Builder` is consistent with
builders in other modules.

Make `UdpReporter.Builder#enableWireLogging` consistent with other modules

---

gradle.properties
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java

Motivation:
Netty recently added content-length header validation [1]. ServiceTalk's
content-length validation is now duplicate logic and no longer
necessary.
[1] netty/netty@89c241e
Modifications:
- Remove AbstractH2DuplexHandler state and logic related to validation
of the content-length header
- Remove `io.servicetalk.http2.allowInvalidContentLength` system
property. Note that Netty has `io.netty.http2.validateContentLength`
which serves a similar purpose (and also likely to be removed in a
release).
Result:
HTTP/2 content-length validation is enforced in a single spot.

Remove HTTP/2 content-length header validation

---

servicetalk-grpc-netty/build.gradle
servicetalk-tcp-netty-internal/build.gradle
servicetalk-transport-netty-internal/build.gradle

Motivation:
We currently have `implementation` dependencies on Netty's native
transport modules with the architecture qualifier. However we only need
a runtime dependency on these artifacts. This isn't expected to change
behavior from an end user perspective but will allow for local Netty
development on one specific architecture without having all native
artifacts (e.g. local snapshot builds).
Modifications:
- All `implementation` scoped dependencies on Netty's native modules
are divided into two dependencies. An `implementation` which has no
scope/architecture qualifier (for java compilation), and a
`runtimeOnly` which does have the scope/architecture qualifier.
Result:
Gradle dependencies on Netty's native modules are more correct, allowing
for easier local Netty development.

Update Netty gradle dependencies to runtimeOnly

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionHttpClientBuilderConfigurator.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PartitionedHttpClientTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java

Motivation:
PartitionedHttpClientBuilder and MultiAddressHttpClientBuilder replicate
methods that exist on SingleAddressHttpClientBuilder as well as
providing a mechanism to directly access the
SingleAddressHttpClientBuilder for each new client to configure it. We
only need one of these mechanisms and the direct access to
SingleAddressHttpClientBuilder reduces duplication and is the more
flexible approach.
Modifications:
- Deprecate all methods on PartitionedHttpClientBuilder and
MultiAddressHttpClientBuilder which can be otherwise controlled via
appendClientBuilderFilter(..).
- Deprecate PartitionHttpClientBuilderConfigurator in favor of
PartitionedHttpClientBuilder.SingleAddressInitializer which is now
consistent with MultiAddressHttpClientBuilder.SingleAddressInitializer
Result: …

Deprecate MultiAddress and Partitioned client builder methods

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java

Motivation:
We added `socketOption(CONNECT_TIMEOUT, 1)` in the past to make some
tests pass on Windows with a comment that Windows uses seconds for the
timeout value. However, Linux uses milliseconds and the `CONNECT_TIMEOUT`
socket option says it have to be in milliseconds. 1ms timeout makes
these tests flaky on Linux and macOS. Let's revisit when we will have
Windows CI pipeline and understand why this socket option is not consistent
on different OS.
Modifications:
- Remove `CONNECT_TIMEOUT` from `H2PriorKnowledgeFeatureParityTest`
and `MultiAddressUrlHttpClientTest`;
Result:
Fixes #1363. Tests do not fail due to 1ms connect timeout on Linux.

Remove 1ms connect timeout in tests

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java

Motivation:
`Content-Length` header values must contain only digits, according to [1].
However, our existing parser allows signed (positive or negative) CL
values, like: `+n` or `-n`.
Some servers may ignore those values and forward it as-is, some may treat
`+n` as `n`. A combination of those two servers can yield an HTTP Request
Smuggling vulnerability.
1. https://tools.ietf.org/html/rfc7230#section-3.3.2
Modifications:
- Fail HTTP messages with signed `Content-Length` header values;
- Add tests to validate this behavior;
- Fix the way `HeaderUtils.contentLength` generates an exception
message for multiple CL header values;
Result:
Signed `Content-Length` header values are prohibited and fail the message
parsing.

Fail parsing signed `Content-Length` header values

---

servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/CodecDecodingException.java
servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/CodecEncodingException.java
servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyChannelContentCodec.java

Motivation:
Align the order or arguments with standard JDK classes and throw these
types in all cases.
Modification:
- Swap `message` and `cause` arguments order to make them similar to the
superclass;
- Throw `CodecDecodingException/CodecEncodingException` when the codec is
closed;
- Remove unnecessary `requireNonNull` for aggregated encode and decode;
Result:
Aligned exceptions API and consistent exception type thrown from the codec.

Improvements for `ContentCodec` exceptions

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java

Motivation:
`H2ToStH1ServerDuplexHandler` uses incorrect `>=` check instead of `!= null`
for the nullable `Long` content-length variable.
Modifications:
- Reproduce the scenario in the test;
- Use `contains` to verify if the CL header is present;
- Rename `canAddResponseTransferEncodingProtocol` -> `serverMaySendPayloadBodyFor`;
- In `AbstractH2DuplexHandler` implementations do not add `content-length: 0`
- when it's not expected;
Result:
No NPE when HTTP/2 server receives `TRACE` request.

Fix NPE when `TRACE` request doesn't have content-length header for HTTP/2

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ClientSecurityConfig.java

Motivation:
Trust material is optional for the client-side security configuration
and we should allow using the default JDK truststore.
Modifications:
- If users of deprecated `ClientSecurityConfig` did not specify a
trust material, use default `ClientSslConfigBuilder` ctor;
Result:
Users of deprecated `ClientSecurityConfig` can create a security config
with default JDK truststore.

Allow client security configuration without trust material

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/From2Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/From3Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/From2PublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/From3PublisherTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFrom2TckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFrom3TckTest.java

Motivation:
Publisher.from(..) with 2 or 3 arguments is becoming more common in
control flow, and we currently have to allocate an array in these
scenarios. Specialized implementations for this operator can avoid array
allocation and more complex index/state management.
Modifications:
- Add Publisher.from(T, T) and Publisher.from(T, T, T)
Result:
Publisher.from(..) is less resource intensive for 2 and 3 arity use
cases.

Add Publisher.from(..) 2 and 3 arity overloads

---

README.adoc
build.gradle
buildSrc/build.gradle
docs/generation/build.gradle
docs/generation/gradle/validateSite.gradle

Motivation:
jcenter is deprecating bintray, and it will soon stop serving artifacts
eventually.
Modifications:
- Remove all references to jcenter from the build
Result:
No more direct references to jcenter from the build avoids dependency on
soon to be decommissioned repository.

Remove jcenter dependencies from build

---

servicetalk-encoding-api-internal/src/main/java/io/servicetalk/encoding/api/internal/HeaderUtils.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProviderBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java

Motivation:
`grpc-accept-encoding` and `grpc-encoding` headers can be skipped when the only value associated with is `identity`. The spec allows this relaxation and we can save processing and wire time.
Modifications:
Skip the relevant headers when the value is only `identity`.
Result:
Less headers and less processing done to handle unnecessary data.

Skip grpc-accept-encoding when the only option is identity

---

servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/AbstractZipContentCodec.java
servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/ContentCodec.java
servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/IdentityContentCodec.java
servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyChannelContentCodec.java
servicetalk-encoding-netty/src/test/java/io/servicetalk/encoding/netty/NettyChannelContentCodecTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProvider.java

Motivation:
Deprecate the `ContentCodec` APIs that receive offset & length. User's can slice if needed.
Modifications:
Deprecate API & relevant changes to accommodate the change.
Result:
Less API surface.

Deprecate ContentCodec API with offest & length

---

.github/workflows/ci-prb-reports.yml
.github/workflows/ci-prq-reports.yml

Motivation:
ec26d27e0212e1449e163dec90194bc24e1acb6b updated
dawidd6/action-download-artifact which changed the default behavior of
workflow_conclusion from "completed" to "completed,success". This may
result in failure of downloading test results for pull request builder.
Modifications:
- explicitly set workflow_conclusion to "completed"
Result:
Unit test and quality results  are downloaded to generate reports.

Github Actions dawidd6/action-download-artifact set workflow_conclusion

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RangeIntPublisher.java

Motivation:
RangeIntPublisher relies upon an implict case from long to int which is
gaurded by a `min(int, long)` (where the int is non-negative). CodeQL
highlights this as a warning.
Modifications:
- Add an explicit cast to int to be more clear this is intentional
Result:
CodeQL warning is resovled.

RangeIntPublisher add explicit cast to int

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy

Motivation:
The current JVM options used for running ServiceTalk tests have not recently been updated
to reflect current recommendations.
Modifications:
Remove "-XX:+AggressiveOpts", "-XX:+TieredCompilation", "-XX:+UseBiasedLocking",
and "-XX:+OptimizeStringConcat" options.
"-XX:+TieredCompilation" and "-XX:+OptimizeStringConcat" are now default behaviour
"-XX:+AggressiveOpts" is likely to slow performance and was removed in JDK12.
"-XX:+UseBiasedLocking" is likely to slow performance for ServiceTalk workloads and was
removed in JDK15
Result:
ServiceTalk tests executed with JVM options which more likely to reflect typical current
production usage.

Remove obsolete and unproductive JVM options

---

.github/workflows/codeql-analysis.yml

Motivation:
Add CodeQL to CI workflow to get additional static code analysis.
Modifications:
- Add codeql-analysis github actions work flow which runs on PRs and
pushes to the main branch
Result:
More static code analysis.

Github Actions Add CodeQL Analysis

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml
.github/workflows/codeql-analysis.yml

Motivation:
Our github action scripts explicitly set --max-workers but gradle can
automatically infer the value based upon number of processors [1].
[1] https://docs.gradle.org/current/userguide/command_line_interface.html
> Default is number of processors.
Modifications:
- Remove --max-workers param from github action scripts
Result:
Gradle will automatically determine the number of workers to use based
upon available processors.

Github Actions Remove --max-workers gradle param

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncCloseables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableExecutorPreservationTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleExecutorPreservationTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/TimeoutCompletableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/AbstractFutureToSingleTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/TimeoutSingleTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherTimeoutTckTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionDrainTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java

Motivation:
Publisher, Single, Completable have an idleTimeout operator. The "idle"
was meant to highlight that the timeout applies to any signals (e.g. not
time to terminal event). However other rx implementations (reactor,
rxjava) just use "timeout" for this operator name which is consistent
with the [1] reactivex operator naming convention. Using the "idle"
makes the operator more difficult to discover for folks familiar with
existing concepts.
[1] http://reactivex.io/documentation/operators/timeout.html
Modifications:
- Rename idleTimeout to timeout, deprecate idleTimeout
Result:
More consistent operator naming for timeout operator.

Publisher, Single, Completable rename idleTimeout -> timeout

---

servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProvider.java
servicetalk-grpc-protobuf/src/test/java/io/servicetalk/grpc/protobuf/ProtoDeserializerTest.java

__Motivation__
`ProtoBufSerializationProvider.ProtoDeserializer` when extracting NIO buffers incorrectly reads all bytes from the buffer instead of the length of one message.
Read only the bytes representing a single message (`decodedLengthOfData`) while extracting the NIO buffers.
__Result__
gRPC deserializer works with buffers having multiple NIO buffers and multiple proto messages.

gRPC deserializer, multiple nio buffers with multiple messages

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryStrategies.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RepeatStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RetryStrategiesTest.java

__Motivation__
When using `[retry,repeat]WithExponentialBackoffDeltaJitter()` if the `maxDelay` is closer to `initialDelay`, it may so happen that after a few retries the `baseDelayNanos` (delay before jitter) becomes greater than `maxDelayNanos`. While getting the random jitter we make sure to not exceed `maxDelayNanos` for the upper bound but lower bound may exceed `maxDelayNanos` hence making the call to `nextLong()` invalid.
Add a cap on `baseDelayNanos` such that it never exceeds `maxDelayNanos` and hence the call to `nextLong` always has the lower bound smaller than the upper bound.
__Result__
`[retry,repeat]WithExponentialBackoffDeltaJitter()` can work with smaller `maxDelay` values.

Smaller max delays and retry/repeat strategies with delta jitter

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SignalOffloaders.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherTimeoutTerminalTckTest.java
servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/Executor.java

Motivation:
The existing `Publisher.timeout(Duration)` operator restarts the timer for each received item and will only timeout if no items are emitted during the timeout duration. In some cases the total time for all items to be emitted is of more interest. An operator to timeout based on the entire elapsed time since subscribe is needed.
Modifications:
Add a new Publisher operator, `timeoutTerminal(Duration)`, that terminates the Publisher with a TimeoutException if the Publisher does not terminate before the specified time duration.
Result:
A new timeout option is available.

Add Publisher.timeoutTerminal(Duration) operator

---

gradle.properties
servicetalk-concurrent-api/build.gradle
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy

Motivation:
Let developers to create new JUnit 5 tests in modules not yet converted to JUnit5
Modifications:
added dependency on  `org.junit.vintage:junit-vintage-engine`
Result:
JUnit 4 and JUnit 5 tests can be mixed in one module 
To add new JUnit 5 tests to non converted test module,  the following dependencies news to be present:
`testImplementation "org.junit.jupiter:junit-jupiter-api:$junit5Version"`
`testImplementation "org.junit.jupiter:junit-jupiter-params:$junit5Version"`  (optional if using parameterized tests)
`testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit5Version"`

Run JUnit 4 based tests using junit-vintage-engine

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java

Motivation:
The private utility method `toNanos()` could be declared static but is
not.
Modifications:
The method is made static.
Result:
Method is invoked statically.

Publisher.toNanos(Duration) should be static

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/NetUtils.java

Motivation:
Minimize exposed CharSequences API and don't expose internal detail.
Modifications:
Deprecate `isAsciiString` and replace it's usages.
Result:
Cleaner API.
----
Also attempted a solution with an `IndexOfExtractor` interface exposed directly from `CharSequences` and bench marked the two. The benefit was negligible (assuming that the JIT optimized for that particular case ie. `CharSequence`) so I chose to keep simple.
For reference:
```
CharSequencesBenchmark.isValidIpV4Address     thrpt    5  37734929.772 ±  935310.988  ops/s
CharSequencesBenchmark.isValidIpV4AddressNew  thrpt    5  38000362.771 ± 2153374.472  ops/s
```
_* isValidIpV4AddressNew is with the IndexOfExtractor approach_

Deprecate isAsciiString and replace its internal usages

---

gradle.properties
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Modifications:
- Remove workarounds in ProtocolCompatibilityTest for
https://github.com/grpc/grpc-java/issues/7953

Update grpc-java 1.36.0 -> 1.36.1 (compatibility testing)

---

docs/generation/build.gradle
docs/generation/gradle.properties
docs/generation/gradle/buildSite.gradle
docs/generation/gradle/validateSite.gradle
docs/generation/site-local.yml
docs/generation/site-remote.yml

Motivation:
The documentation produced for the servicetalk.io website uses plugins
and tools which have been updated. Where practical recent versions of
these dependencies should be used.
Modifications:
Plugins and tool dependencies used for generating and verifying the
servicetalk.io site are updated to current or more recent versions.
Result:
Updated versions are used for generating documentation

Update dependencies for site documentation

---

build.gradle
servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/http/debugging/build.gradle
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
servicetalk-examples/http/debugging/src/main/resources/log4j2.xml
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
settings.gradle

Motivation:
ServiceTalk has purpose-built features for improving the debugging
experience for both applications and for ServiceTalk itself. An example
with explanatory comments would improve exposure of these features.
Modifications:
A new HTTP debugging example is provided demonstrating wire logging,
disabling offloading, disabling async context.
Result:
ServiceTalk debugging features are more visible.

Add a ServiceTalk debugging utilities example

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java

Motivation:
Most of the write HTTP messages have 3 listeners, because it consist of
headers, one payload body chunk (can be empty), and trailers. `ArrayDeque`
defines `MIN_INITIAL_CAPACITY = 8` internally. It's sufficient for most
use-cases. Messages with large streaming payload body may have more
listeners, but those messages have higher overhead anyway (flush-on-each,
etc.). Therefore, it's ok for them to resize the queue, if necessary.
Modifications:
- Define the default size of 8 for `listenersOnWriteBoundaries` in
`WriteStreamSubscriber.AllWritePromise`;
Result:
Less allocation per each message write.

Reduce initial size of listeners queue in `WriteStreamSubscriber`

---

servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
servicetalk-examples/http/debugging/src/main/resources/log4j2.xml

Motivation:
Fixing a few typos, adding links to appropriate features in javadoc,
clarifying the difference between wire-logger and h2-frame-logger.
Modifications:
- Fix typos in `index.adoc` and `log4j2.xml` name;
- Add links in javadoc for all demonstrated features;
- Use a different name for h2 frame logger;
- Use another comment style to highlight comments for demonstrated
features and let IDE use shortcut to uncomment the code line;
- Add `CLOSE/INACTIVE/UNREGISTERED` wire logger events;
Result:
More details in the example.

Follow-up for debugging example added in #1459

---

gradle.properties
servicetalk-benchmarks/build.gradle

Motivation:
0.5.x plugin version can not run newer JMH versions.

Update JMH 1.28 -> 1.29 and me.champeau.jmh plugin 0.5.3 -> 0.6.3

---

gradle.properties
servicetalk-benchmarks/build.gradle
servicetalk-benchmarks/src/jmh/java/io/servicetalk/buffer/api/CharSequencesParseLongBenchmark.java
servicetalk-buffer-api/build.gradle
servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/CharSequencesTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseStatus.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java

Motivation:
Our `HttpHeaders` API uses `CharSequence`. In order for users to parse
the value (like, `Content-Length`) they have to convert `CharSequence`
to `String` for `Long.parseLong(String)` API. This approach does an extra
copy of data from underlying `Buffer`. We can avoid it.
Modifications:
- Add `CharSequences#parseLong(CharSequence)` API that does not force
`CharSequence#toString()` conversion;
- Add tests to validate new API;
- Use the new API in all places when we parse an `AsciiBuffer` or
`AsciiString`;
Result:
Less allocations of `String`.
This PR depends on #1468 (ignore first commit).

Implement `CharSequences#parseLong(CharSequence)`

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpRequesterFilter.java

Motivation:
Currently the method `CharSequences.newAsciiString` takes a String
argument but the implementation is fine with any CharSequence. Allowing
the method to accept CharSquence avoids some cases of unncessary
conversion to String.
Modifications:
The String argument is replaced with a more general CharSequence.
Existing code using this method will need to be recompiled.
Result:
CharSequences.newAsciiString() generality is improved.

CharSequences.newAsciiString accept CharSequence

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MutualSslTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TcpFastOpenTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServiceTalkSocketOptions.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SocketOptionUtils.java

Motivation:
Netty recently added support for
[TCP fast open](https://tools.ietf.org/html/rfc7413) on the client, and
has had server support for a while. We currently don't expose the
necessary configuration knobs to enable this feature, but it may be able
to reduce round trips and reduce connection setup latency.
Modifications:
- Add socket options to configure client and server TCP fast open.
- Add mechanism to configure the listen/acceptor socket options, and use
this for the backlog option which was an outlier.
Result:
TCP Fast Open can be enabled for client and server. Note that it is only
supported by Netty's native EPOLL transport on linux, and only
initiated on the client when TLS is enabled.

Add TCP Fast Open support

---

servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/CancellationTest.java

Motivation:
The `EntityInputStream` is not thread safe, and the cancellation is triggering a `close` from any thread, while the access path is through the offloaded thread. 
Modifications:
Extend the `ContainerRequest` to capture close and handoff it to the offloaded thread if a read is already in progress, or close it atomically otherwise.
Result:
Better thread visibility and serialization of events in case of a read is in progress.
Fixes: #999

FlakyTest: CancellationTest - Improve close handling

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithLifetimeMapper.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithLifetimePublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithMapper.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ScanWithPublisherTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherScanWithLifetimeTckTest.java

The existing Publisher.scanWith(...) operator is not exposing cancellations to the end user. Use cases that need to control resource lifetimes (ie. clean-up), can't do so on cancel.
Add a new Publisher operator, scanWithLifetime(ScanWithLifetimeMapper), that also captures cancellation and invokes an afterFinally callback on all terminal signal (complete, error & cancel).
**Result**:
A new lifetime aware scanWith operator.

Add Publisher.scanWithLifetime(ScanWithLifetimeMapper) operator

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1SpecExceptions.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientChannelInitializer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpResponseDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java

Motivation:
The HTTP/1.x spec allows for optional support to accept LF without
proceeding CR as a valid separator in some scenarios [1]. Some older
implementations rely upon this behavior and interoperability would be
improved by allowing opt-in support.
[1] https://tools.ietf.org/html/rfc7230#section-3.5
Although the line terminator for the start-line and header fields is
the sequence CRLF, a recipient MAY recognize a single LF as a line
terminator and ignore any preceding CR.
Modifications:
- Update HttpObjectDecoder to support LF without CR
Result:
H1SpecExceptions allows for opt-in support for  LF without proceeding
CR.

H1SpecExceptions add option to allow LF without proceeding CR

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java

Motivaiton:
H2PriorKnowledgeFeatureParityTest allows for ClosedChannelException in
some scenarios which should be a Http2Exception. This issue has since
been fixed in netty and the workaround can be reverted.
Modifications:
- Remove .or(instanceOf(ClosedChannelException.class)) clause in
H2PriorKnowledgeFeatureParityTest
Result:
H2PriorKnowledgeFeatureParityTest test verifies expected exception for
h2.

H2PriorKnowledgeFeatureParityTest remove exception verification workaround

---

servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/AbstractSslConfigBuilder.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSslConfigBuilder.java

Motivation:
We ask key/trust materials at the constructor because they are required
arguments to build an `SslConfig`. However, users may use a single builder
to build multiple `SslConfig` instances with different materials. We should
let them override these arguments, if necessary.
Modifications:
- Make `trustManager` and `keyManager` methods public in `AbstractSslConfigBuilder`;
- Add `final` modifier to all methods of `AbstractSslConfigBuilder`;
Result:
Users can override key/trust materials at `[Client|Server]SslConfigBuilder`.

Allow overriding key/trust managers on `SslConfig` builders 

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/AbstractDelegatingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultPayloadInfo.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDataSourceTransformations.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PayloadInfo.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthAndTrailersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PayloadBodyModificationsTest.java

Motivation:
In many cases users do not set payload body when they create an HTTP
request (like `GET`) or response (like, 204). We can optimize flush
strategy and HTTP/1.1 encoding in these cases.
Modifications:
- Introduce `PayloadInfo#isEmpty()` flag that tells internal layers when
an HTTP message contains payload body;
- Use this flag to choose a flush strategy and set `content-length` header;
- Adjust existing `content-length` tests to verify new use-cases with
empty payload body;
- Enhance existing `FlushStrategyOnServerTest` to verify empty responses
flush on end;
- Filter out empty payload body buffer when converting between types;
- Add more tests to verify users can keep using different ways to set payload;
Behavior changes:
- Users cannot write more data into a payload body …

Optimize HTTP messages with empty payload body

---

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java

Motivation:
The default clock used by `java.time.Instant` is not monotonic. This
could result in deadlines not being correctly managed if the clock is
adjusted during the course of timeout executing.
Modifications:
Replace use of `Instant` with `System.nanoTime()`
Result:
Timeout HTTP filters have monotonic behaviour.

Use only monotonic clock in deadline calculations

---

servicetalk-examples/http/service-composition/src/main/java/io/servicetalk/examples/http/service/composition/GatewayServer.java
servicetalk-examples/http/timeout/src/main/java/io/servicetalk/examples/http/timeout/TimeoutServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseTimeoutTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java

Motivation:
There are two timeout filters for HTTP, `TimeoutHttpRequesterFilter`
and `TimeoutHttpServiceFilter` but they have differing defaults for the
behaviour of whether the timeout applies to the entire response or only
the response metadata.
Modifications:
Both filters now have the same set of constructors and defaults.
Result:
Reduced opportunity for API misuse due to inconsistent behaviour.

Use consistent defaults for HTTP Timeout filters

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
Ignore these tests until #1489 is resolved. Otherwise, it blocks other PRs.

Ignore flaky timeout tests in `ProtocolCompatibilityTest`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientMetadata.java
servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ResponseCancelTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseTimeoutTest.java
servicetalk-http-utils/build.gradle
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpServiceFilterTest.java
servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/DurationUtils.java
servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/DurationUtilsTest.java

Motivation:
`Duration#compareTo` is hard to understand, the result of comparison
depends on the order of arguments. This lead to a bug in
`TimeoutHttpRequesterFilter` and `TimeoutHttpServiceFilter` which always
fails payload body publisher with `TimeoutException`. Use a shared
utility to make `isPositive` check for `Duration` consistent across all modules.
Also, `TimeoutHttpRequesterFilter` and `TimeoutHttpServiceFilter` logic
is identical, we can reduce duplication and share the logic.
Modifications:
- Introduce a shared `DurationUtils` class for common operations with
`Duration`;
- Use this utility to reduce mistakes when we check that the passed
`Duration` must be positive;
- Introduce `AbstractTimeoutHttpFilterTest` to share timeout logic
between `TimeoutHttpRequesterFilter` and …

Fix duration comparison bug in timeout filters and reduce code duplication

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/DurationUtils.java

Motivation:
`Publisher` is already a complicated class. We should not expand its
scope by additional utilities, even if they are internal. We have a
better place for `Publisher#toNanos` now - `DurationUtils`.
Modifications:
- Move `Publisher#toNanos` to `DurationUtils`;
Result:
Less utilities in `Publisher`, all `compareTo` operations for
`Duration` are in a single place.

Move `Publisher#toNanos` to `DurationUtils`

---

gradle.properties

Motivation:
We had to disable SHA256 and SHA512 checksums until Sonatype and Maven Central
support them. The referenced issues were closed. We can start publishing artifacts
with SHA256 and SHA512 checksum files.
Modification:
- Remove a parameter from `gradle.properties` that did disable this feature;
Result:
Gradle will generate  SHA256 and SHA512 checksum files for published artifacts.

Enable back SHA256 and SHA512 checksums for published artifacts

---

servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/CancellationTest.java

Motivation:
As part of this [fix](https://github.com/apple/servicetalk/pull/1404) an error setter was missed, which can still cause the test to fail.
Modifications:
Filter out the racy close exception. 
Result:
Fixes https://github.com/apple/servicetalk/issues/1473

Filter out missed racy close on CancellationTest

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java

Motivation:
With a recent optimization we missed a message-body subscription which had as a result some operations to not run.
Modifications:
Subscribe in the empty message-body.
Result:
All message-body operators should now run.

Fix unsubscribed message-body when isEmpty

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientMetadata.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/DurationUtils.java
servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/DurationUtilsTest.java

Motivation:
gRPC module checks if the timeout is considered infinite or not in
multiple places. All use different way of `compareTo` check.
Modifications:
- Introduce `DurationUtils#isInfinite` utility and test it;
- Use the new utility in all places where required;
Result:
Consistent approach to verify when timeout should be handled as infinite.

Add `DurationUtils#isInfinite` utility

---

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java

Motivation:
AbstractTimeoutHttpFilter can now apply a timeout on the metadata and
the message body level. If the message body level timeout triggers the
interval is taken as the user will see a value which is different than
the originally supplied timeout duration.
Modifications:
- Add a MappedTimeoutException that can wrap a TimeoutException and
allows for specifying the original timeout value
- Remove pre-check conditions on timeout duration which is enforced by
the timeout operators.
Result:
HttpTimeoutFilter exception includes the original timeout duration.

HttpTimeoutFilter include original timeout on message body timeout

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java

Motivation:
For `HeaderUtils#setContentLength(...)`, when the `messageBody` is exactly
`Publisher.empty()` there are no operators applied for the `messageBody`.
In this case we do not need concatenation.
Modifications:
- Skip concatenation when `messageBody == empty()`;
- Add tests when payloadBody is not set at all;
Result:
Less operators applied during request/response processing when not
necessary.

Do not concatenate `Publisher.empty()` message body

---

scripts/release.sh

Motivation:
Current version of the release script identifies the remote after the
`DRYRUN` mode overrides `git` command. As the result, logs do not show
which remote will be used when the `DRYRUN` mode will be off.
Modifications:
- Move lines that identify `remote` before the `DRYRUN` mode check;
- Print a message when `DRYRUN` mode is enabled;
Result:
`DRYRUN` mode correctly shows the git remote.

release.sh: identify the remote before switching to `DRYRUN` mode

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java

Motivation:
Client fires `SslHandshakeCompletionEvent` before the server. Therefore,
client my already return the reserved connection before server's
`ConnectionAcceptor` is invoked. As the result, test may initiate graceful
closure before `onClosing` event is registered, leading to the test timeout
exception.
Modifications:
- Use another `CountDownLatch` to wait until server invokes
`ConnectionAcceptor` before proceeding to the test scenario;
Result:
Fixes #1200.

Fix flaky `GracefulConnectionClosureHandlingTest#closeIdleBeforeExchange` test

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java

Motivation:
In ServiceTalk 0.39.0 the method
`CharSequences.newAsciiString(CharSequence)` was introduced which
replaced `CharSequences.newAsciiString(String)`. This was a source
compatible, but binary incompatible change. All existing uses of the
`String` overload could be recompiled to use the `CharSequence`
overload. Existing binary code expected the `String` overload to be present
and fails with `NoSuchMethodError` at runtime.
Modifications:
For cases where the libraries and applications using ServiceTalk cannot
be recompiled conveniently the `CharSequences.newAsciiString(String)`
overload is restored.
Result:
Binary compatibility with libraries and applications which use
`CharSequences.newAsciiString(String)` and are compiled against
versions of ServiceTalk before 0.39.0 is restored.

Restore CharSequences.newAsciiString(String)

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java

Motivation:
This test is affected by a race between propagating `onError` through
`DefaultNettyConnection#enrichError` and receiving FIN from the server
(`ChannelInputShutdownReadComplete`). The exception is always correct, but
it can be wrapped with `CloseEventObservedException` if the FIN reached the
client.
Modifications:
- Improve test's assertion to check the exception or its cause;
Result:
Fixes #1224.

Fix flaky `PrematureClosureBeforeResponsePayloadBodyTest#notAllHeadersReceived()`

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy

Motivation:
The gradle currently produces voluminous test output in the default
configuration. This change reduces the default verbosity to only show
test failures. The test report still contains full output from failed
tests.
Modifications:
default test logging output verbosity is reduce to show only failed
cases and hide standard out/err from console. Additional configuration
is provided for gradle `--warn` mode which provides slightly more
output than the current default.
Result:
Terse build output making warnings and failures more obvious

Reduce test logging output from build

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java

Motivation:
`HttpObjectDecoderTest` uses `UnpooledByteBufAllocator.DEFAULT`. While the
memory allocated by this allocator is unpooled and technically does not
require to be released, the netty's leak detector expects that all netty
`ByteBuf` instances have to be released.
Modifications:
- Use `ServiceTalkBufferAllocator` instead of
`UnpooledByteBufAllocator.DEFAULT` that does not use leak detector;
Result:
No warnings in test logs about leaked `ByteBuf`.

Fix `ByteBuf` leak in `HttpObjectDecoderTest`

---

servicetalk-test-resources/README.adoc

Motivation:
Describe the resources in the module.
Modifications:
Adds a readme file which documents the resources provided by the
module: a log4j.xml configuration file and a set of test certificates
and keys for use by other tests.
Result:
Basic description of test resources now included.

Add README.adoc to servicetalk-test-resources

---

servicetalk-loadbalancer/gradle/spotbugs/main-exclusions.xml
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java

Motivation:
RoundRobinLoadBalancer's Host class maintains a list of active
connections in a copy-on-write fashion. However when an item is added or
removed their is an additional copy operation due to initial state not
accounting for 1 more/less element.
Modifications:
- Host class uses an array for copy-on-write storage and allocates
exactly the required amount of space on add/remove.
Result:
Less resize/copy operations on connection established/closed.

RoundRobinLoadBalancer reduce copy/resize for connection add/remove

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleZipper.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleZip3Test.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleZip4Test.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleZip5Test.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleZipWithTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleZip3DelayErrorTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleZip4DelayErrorTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleZip5DelayErrorTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleZipWithDelayErrorTckTest.java

Motivation:
We have Single#zip but not the zipDelayError variant.
Modifications:
- Add Single#zipDelayError operator to match Single#zip use cases
Result:
Single#zipDelayError operator exists.

Add Single#zipDelayError operator

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java

Motivation:
A mapped source sending multiple terminal signals is in violation of the
Reactive Streams specification [1]. However if there is a faulty source
this may happen, and Publisher#flatMapMergeSingle will fail on an
assertion due to the activeMappedSources being 0 in
decrementActiveMappedSources. The assertion doesn't provide any
additional context as to what went wrong, and the downstream source may
not be completed as a result. This can be difficult to debug the root
cause and understand where the duplicate terminal signal originates
from.
[1] https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#1.7
Modifications:
- Enhance Publisher#flatMapMergeSingle and Publisher#flatMapMerge to log
a warning when a duplicate terminal signal is detected, and still …

Publisher#flatMapMergeSingle mapped source duplicate terminal improved visibility

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java

Motivation:
Buffer array(), hasArray(), and arrayOffset() methods are coupled.
However the javadocs don't clearly indicate their relationship which may
lead to confusion.
Modifications:
- Clarify the relationship between Buffer array(), hasArray(), and
arrayOffset() in javadocs.
Result:
Buffer byte[] accessor javadocs clarify the relationship between related
methods.

Enhance Buffer byte[] accessor methods javadoc

---

servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpHeadersFormatter.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpan.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContext.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceState.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceStateFormat.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpan.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemoryTracer.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemorySpanContext.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTraceState.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/SingleLineFormatter.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/TextMapFormatter.java
servicetalk-opentracing-log4j2/src/main/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMap.java
servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java

Motivation:
Missing B3 sampled header (OpenTracing) from upstream translates to no sampling but according to the [spec](https://github.com/openzipkin/b3-propagation#sampling-state-1) absent should translate to receiver's choice.
Modifications:
Split class relation between span and trace-state and allow for trace state to have a Nullable sampled field, which in turn allows the sampler to take the right decision. The decision will propagate downstream.
Result:
Sampled field is now not required and sampler is allowed the make the right choice. That choice propagates downstream.

Respect missing B3 sampled headers

---

docs/modules/ROOT/pages/async-context.adoc

Motivation:
To have the async-context.adoc file with correct grammar and without misspelled words.
Modifications:
Minor grammar corrections on async-context.adoc
Result:
The async-context.adoc file with correct grammar and without misspelled words.

Minor grammar corrections on async-context.adoc.

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy

Motivation:
The default behaviour of Gradle is to stop the build with an error in
the first module with a test failure. In some cases it is useful to
run all tests to get a survey of which tests are failing. It can also
be annoying if flaky tests are stopping the build from completing.
Modifications:
This change allows configuration of the Gradle test `ignoreFailures`
option to continue the build after test failures. The `ignoreFailures`
test configuration is initialized from the system property 
`servicetalk.test.ignoreFailures` allowing for command line
configuration. `./gradlew -Dservicetalk.test.ignoreFailures=true build`
Result:
Dynamically configurable ignoreFailures. This feature should not be
used for CI builds as it will mask build failures. Build results
should always be …

Config test ignoreFailures via system property

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NonPipelinedCloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java

Motivation:
Before `RequestResponseCloseHandler` invokes `shutdownOutput()`, it forces
`SslHandler` to close `SSLEngine` and send `close_notify` to the remote peer.
Because `SSLEngine` is closed, `SslHandler` will generate
`SslCloseCompletionEvent` on the next read regardless of receiving the
`close_notify` alert from the remote peer or not. This premature event is
handled incorrectly by the `DefaultNettyConnection` and forces the channel
closure, breaking graceful closure and `connection: close` handling on the
server-side.
Modifications:
- Move handling of `SslCloseCompletionEvent` to the `CloseHandler` that is
aware of the current state;
- `RequestResponseCloseHandler` now ignores `SslCloseCompletionEvent` if it
knows that the outbound was shutdown. It will wait for the `FIN` from …

`shutdownOutput()` for SSL connections prematurely closes the Channel

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthAndTrailersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TestServiceStreaming.java

Motivation:
We can infer from the `PayloadInfo` when HTTP message does not contain
payload body or trailers. In this case, we can write it in a single frame.
Also, we do not need to write `Http2DataFrame`(s) for empty `Buffer`(s)
or process `HttpHeaders` when it's empty.
Modifications:
- Detect if the `HttpMetaData` can be written in a single frame;
- Emit `CloseHandler#protocolPayloadEndOutbound` on `endStream`;
- Ignore empty `Buffer`(s) when writing `Http2DataFrame`(s);
- Do not process `HttpHeaders` when they are empty;
- Add tests for new behavior;
Result:
Less `Http2StreamFrame`(s) allocated and written on the wire, results in
+10% RPS, -12% latency for some HTTP/2 use-cases.

Optimize encoding of HTTP/2 frames to write less on the wire

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Refactoring of offloading is expected to remove these methods so it is
important to give users forewarning to migrate to other methods.
The `publishOnOverride`, `subscribeOnOverride` and
`publishAndSubscribeOnOverride` methods of `Publisher`, `Single` and
`Completable` are deprecated as well as the internal methods they call
are marked deprecated and an alternative suggestion is provided.
**Result**:
Users are forewarned of upcoming API change.

Deprecate publishAndSubscribeOnOverride methods

---

docs/modules/ROOT/pages/blocking-safe-by-default.adoc

Motivation:
To have the blocking-safe-by-default.adoc file with correct grammar and without misspelled words.
Modifications:
- Minor grammar corrections on blocking-safe-by-default.adoc
Result:
The blocking-safe-by-default.adoc file with correct grammar and without misspelled words.

Minor grammar corrections on blocking-safe-by-default.adoc.

---

servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java

Motivation:
TLS 1.0 and 1.1 were disabled in the latest JDK releases because they are
no longer considered secure [1, 2]. As the result of this JDK upgrade,
`SecureTcpTransportObserverErrorsTest.testSslErrors` started to fail when
it uses JDK provider with TLSv1.1.
1. https://www.oracle.com/java/technologies/javase/8u291-relnotes.html
2. https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html
Modifications:
- Use TLSv1.3 instead of TLSv1.1 for `SecureTcpTransportObserverErrorsTest`;
Result:
Fixes #1530.

Do not use TLSv1.1 in tests

---

servicetalk-concurrent-internal/src/testFixtures/java/io/servicetalk/concurrent/internal/ServiceTalkTestTimeout.java

Motivation:
We set 90s timeout for CI a while ago, when we used a custom CI server.
With GitHub Actions there is no need for that high timeout value. It
only slows down the overall build duration if any timeout happens, but
does not provide much value. The default timeout for jUnit5 tests is
already 30s.
Modifications:
- Change `ServiceTalkTestTimeout.DEFAULT_TIMEOUT_SECONDS` to 30 when
`CI == true`;
Result:
Shorter timeout for jUnit4 tests when build runs on CI.

Reduce default test timeout on CI to 30s for jUnit4

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java

Motivation:
1. Do not try to load native libraries when it's known that OS does not
support it.
2. Log when OS supports native transport, but native lib cannot be
loaded.
3. Prevent class loading of any classes related to native transport when
it's not available.
Modifications:
- Enhance `NativeTransportUtils` to protect class loading when it's
known that OS does not support a specific type of transport;
- Log when native transport can not be loaded;
Result:
1. Less unused classes are loaded in memory.
2. Users are notified when native transport can be used but is not
loaded properly.

Don't load netty-transport-native classes when native lib isn't available

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientMetadata.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java

Motivation:
All public API breaking changes should be deferred until 0.41.0.
Modifications:
- Restore `grpc-api` that was removed in #1501.
Result:
No public API changes for 0.40.0.

Restore public API changes for `grpc-api`

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java

Motivation:
All public API breaking changes should be deferred until 0.41.0.
Even for internal modules there is a risk of having mixed version
numbers in the classpath.
Modifications:
- Restore `BuilderUtils#useEpoll` and `BuilderUtils#useKQueue` methods
that were removed in #1539.
Result:
No public API changes for 0.40.0.

Restore public API changes for `transport-netty-internal`

---

servicetalk-examples/http/jaxrs/build.gradle
servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsApplication.java
servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java

Motivation:
Include an example of a Jersey resource that supports `mulitpart/form-data` requests.
Modifications:
A new handler in the existing greetings resource.
Result:
More examples for users who want to support multipart file uploads.

Jersey example with multipart file upload support

---

scripts/japicmp.sh

Motivation:
It's hard to track API/ABI changes and list everything correctly in
release notes. This script produces summary of all changes made between
versions.
Modifications:
- Add `./scripts/japicmp.sh`;
Result:
Scripts that summarizes all API/ABI changes.

Script that checks API/ABI compatibility between versions

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentChannelInitializer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentChannelInitializer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java

Motivation:
`KeepAliveManager#pingReceived` always acks PING frames. Netty's auto
ack produces additional PING-ack frames that are not necessary and
confusing.
Modifications:
- Use `Http2FrameCodecBuilder#autoAckPingFrame(false)` on client and
server sides;
Result:
No duplicated PING frames written with ack=true.

Disable auto ack for HTTP/2 PING frames by netty

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyTunnel.java

Motivation:
ProxyTunnel was returning the `localhost` hostname instead of the IP-address, which in some configurations
where the IPv4 is preferred but the DNS resolves in both IPv4 and IPv6 for the loopback hostname,
cause connectivity issues.
Modifications:
Modified the ProxyTunnel to always return the IP-address for the clients to connect to.
Result:
More stable test.

Fix ProxyTunnel to always use the address instead of the hostname.

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java

Motivation:
`closePipelinedAfterTwoRequestsSentBeforeAnyResponseReceived` may be in
a situation when the 2nd request actually gets written after client
receives `GO_AWAY` frame from the server. Therefore, `Http2Exception` is
also excepted. We will use `IOException` for simplicity and consistency.
Modifications:
- `assertClosedChannelException` should expect either
`ClosedChannelException` or `IOException`;
Result:
`closePipelinedAfterTwoRequestsSentBeforeAnyResponseReceived` is not
flaky.

Fix flaky `closePipelinedAfterTwoRequestsSentBeforeAnyResponseReceived`

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/ExecutorThrowsTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/PublishAndSubscribeOnTest.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java

The method used for ensuring thread affinity used by the HTTP/gRPC builders, `offloadWithThreadAffinity()` will be removed in a near future version of ServiceTalk. The offered alternative is to use a single threaded executor which provides the same affinity guarantee.
The  `offloadWithThreadAffinity()` builder methods are marked deprecated. Some existing tests which reference the thread based signal offloader are converted to the default signal offloader.
**Result**:
Deprecation warning provided for methods which will eventually be removed.

Deprecate HTTP/gRPC offloadWithThreadAffinity

---

servicetalk-http-api/src/test/java/io/servicetalk/http/api/SimpleHttpRequesterFilterTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpRequesterFilterTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpServiceFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RedirectingClientAndConnectionFilterTest.java

Motivation:
`testFixtures` are expected to be used by other modules.
After #1521 refactoring, visibility of some methods was reduced.
Modifications:
- Revert `protected` modifiers for `AbstractHttpRequesterFilterTest` and
`AbstractHttpServiceFilterTest` methods;
- Do not override `sslSession()` without a special need;
Result:
Modules that depend on these testFixtures classes can continue to work.

Make `http-api:testFixtures` usable in other modules

---

docs/modules/ROOT/pages/performance.adoc

Motivation:
Existing `performance.adoc` has hardcoded version of netty-tcnative
which is already outdated.
Modifications:
- Change the hardcoded version number to a parameter and link where
users can find the latest version number;
Result:
No outdated version constant in docs.

Do not hardcode netty-tcnative version in docs

---

servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/BufferInputStreamTest.java

Motivation:
Had an assumption that `BufferInputStream#skip(long)` has a bug.
Modifications:
- Add `BufferInputStreamTest` class that tests `skip(long)` method;
Result:
Confidence that `BufferInputStream#skip(long)` is implemented correctly.

Test `BufferInputStream#skip(long)`

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/DefaultExecutorTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/InvalidMetadataValuesTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentCodingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkToNettyContentCodingCompatibilityTest.java

Motivation:
During migration to jUnit5 in #1521, some of the "assume" statements
were moved before the initialization of parameters. As the result,
those "assume" statements did not work.
Modifications:
- `NettyHttpServerTest`: move `ignoreTestWhen` after `setUp`;
- `ServiceTalkToNettyContentCodingCompatibilityTest` execute `start()`
after "assume" checks;
- Minor cosmetic changes in other test classes: make methods `static`,
use static import, etc.
Result:
`NettyHttpServerTest` is kept ignored for now.

Fix "assume" statements in tests

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
servicetalk-http-netty/build.gradle
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/testFixtures/java/io/servicetalk/http/netty/AsyncContextHttpFilterVerifier.java
servicetalk-test-resources/src/main/java/io/servicetalk/test/resources/TestUtils.java

Motivation:
On some erroneous cases we can optimise the gRPC response to return TrailerOnly [1] when headers aren't written to the wire yet. 
Modifications:
gRPC router was altered to generate a TrailersOnly response when an error happens before headers are sent out.
Result:
An optimised response that contains only a single frame.
[1] https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

Produce a TrailersOnly response when gRPC endpoints throw an error.

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactoryFilter.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsClientFilterFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceFilterFactory.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/ConditionalHttpClientFilterTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/ConditionalHttpConnectionFilterTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpRequesterFilterTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/ConditionalFilterFactory.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/FilterFactoryUtils.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthHttpServiceFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java

Motivation:
All `*FilterFactory` interfaces currently implement default `append`
method that helps to chain filters in order of append. Because
internally it uses wrapping approach, it can hide
`HttpExecutionStrategyInfluencer` implementation of the passed filter
factory. To avoid that, users have to use a method on the client/server
builder instead.
Modifications:
- Deprecate `append` method on all filter factories;
- Add `FilterFactoryUtils` test fixture as the replacement utility for
tests;
Result:
Users won't hide `HttpExecutionStrategyInfluencer` impl when they chain
filters.

Deprecate `append` method on all filter factories

---

scripts/release.sh

Motivation:
To prevent scenarios like #1580, let's enhance validation of input
parameter for the `release.sh` script.
Modifications:
- Compare passed next version with the current version from
`gradle.properties`, fails fast if they are equal;
Result:
Enhanced validation of next version parameter.

release.sh: check that the next version doesn't equal to the current one

---

scripts/japicmp.sh

Motivation:
If we check API compatibility with a snapshot, always force maven to
check for updated snapshots on remote repositories.

Force a check for updated snapshots on remote repositories for japicmp

---

servicetalk-test-resources/src/main/java/io/servicetalk/test/resources/TestUtils.java

Motivation:
Converting some existing code to use `assertNoAsyncErrors` I found
cases where the error queue was `AssertionError` not `Throwable` and
some cases where the message was used to provide more specific info
about the source/context of the errors.
Modifications:
Add additional overload for message and allow wildcard for queue type.
Result:
More useful `assertNoAsyncErrors`.

assertNoAsyncErrors more queue types and msg arg

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategyTest.java

Motivation:
When `DefaultServiceDiscoveryRetryStrategy` retains addresses till
success and recovers from the previous SD error, it doesn't check which
of new addresses were previously retained. As the result, it may
propagate duplicated "available" events to `RoundRobinLoadBalancer`.
RRLB does not support duplicated entries. It may lead to retaining
duplicated addresses after they become unavailable, causing failures
of requests.
Modifications:
- Filter out previously retained events when we recover from SD-error;
- Do not return duplicated `unavailable` events on subsequent SD-errors;
- Enhance tests to catch these use-cases;
Result:
`DefaultServiceDiscoveryRetryStrategyTest` does not emit duplicated SD
events for the same availability state => RRLB does not retain duplicated
entries.

`DefaultServiceDiscoveryRetryStrategy` may emit duplicated SD events

---

servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java

Motivation:
`DefaultDnsServiceDiscovererBuilder#maxUdpPayloadSize` throws an
`IllegalArgumentException` with incorrect value in the message.
Modifications:
- Use `maxUdpPayloadSize` instead of `minTTLSeconds`;
Result:
Correct value in `IllegalArgumentException` msg for `maxUdpPayloadSize`
validation.

`DefaultDnsServiceDiscovererBuilder#maxUdpPayloadSize` validation msg fix

---

servicetalk-buffer-netty/build.gradle
servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/BufferAllocatorsTest.java
servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/BufferUtilTest.java
servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/NettyAsciiBufferTest.java
servicetalk-buffer-netty/src/test/java/io/servicetalk/buffer/netty/ReadOnlyBufferTest.java

Migrate servicetalk-buffer-netty tests to JUnit 5 (#1568)

---

servicetalk-buffer-api/build.gradle
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/AsciiBufferTest.java
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/BufferInputStreamTest.java
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/CharSequencesTest.java
servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/ReadOnlyByteBufferTest.java
servicetalk-buffer-api/src/testFixtures/java/io/servicetalk/buffer/api/Matchers.java

Migrate servicetalk-buffer-api tests to JUnit 5 (#1568)

---

gradle.properties

Motivation:
The current Gradle build makes use of some parallelism for execution of tasks, but less than optimal. Builds would complete more quickly with full parallelism enabled.
Modifications:
Adds parallel configuration to Gradle settings. Some of the existing GitHub Actions already manually configure the parallel option so this change has already been in effect for some builds--this change just makes fully parallel builds the default.
Result:
On average, faster Gradle builds due to increased parallelism.

Execute Gradle tasks in parallel

---

servicetalk-transport-api/build.gradle
servicetalk-transport-api/src/test/java/io/servicetalk/transport/api/ConnectionAcceptorTest.java

Migrate servicetalk-transport-api tests to JUnit 5 (#1568)

---

servicetalk-transport-netty-internal/build.gradle
servicetalk-transport-netty-internal/gradle/spotbugs/test-exclusions.xml
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractOutOfEventloopTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractWriteTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/BuilderUtilsTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/ChannelSetTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/CopyByteBufHandlerTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/EWMAWriteDemandEstimatorTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushOutsideEventloopTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushStrategiesTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushStrategyHolderTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushWithExecutorTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/GlobalExecutionContextTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseableTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherRefCountTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyServerContextTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NonPipelinedCloseHandlerTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/OverlappingCapacityAwareEstimatorTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RandomDataUtilsTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertClientHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberFutureListenersTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberOutOfEventloopTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Migrate servicetalk-transport-netty-internal tests to JUnit 5 (#1568)

---

servicetalk-opentracing-asynccontext/build.gradle
servicetalk-opentracing-asynccontext/src/test/java/io/servicetalk/opentracing/asynccontext/AsyncContextInMemoryScopeManagerTest.java

Migrate servicetalk-opentracing-asynccontext tests to JUnit 5 (#1568)

---

servicetalk-opentracing-http/build.gradle
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TestUtils.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java
servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java

Migrate servicetalk-opentracing-http tests to JUnit 5 (#1568)

---

servicetalk-opentracing-log4j2/build.gradle
servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapLog4jProviderTest.java
servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java

Migrate servicetalk-opentracing-log4j2 tests to JUnit 5 (#1568)

---

servicetalk-opentracing-zipkin-publisher/build.gradle
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisherTest.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporterTest.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/SpanUtils.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporterTest.java

Migrate servicetalk-opentracing-zipkin-publisher tests to JUnit 5 (#1568)

---

servicetalk-dns-discovery-netty/build.gradle
servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DefaultDnsClientTest.java
servicetalk-dns-discovery-netty/src/test/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserverTest.java

Migrate servicetalk-dns-discovery-netty tests to JUnit 5 (#1568)

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseEncoderTest.java

Motivation:
When `HttpObjectEncoder` encodes meta-data or trailers an error may
happen, which will cause a leak of internal `ByteBuf`. It may happen if
any of the encoding object throw or if it tries to expand the size of
that internal `ByteBuf` without success.
Modifications:
- try-catch meta-data and trailers encoding and release the tmp
`ByteBuf` in case of any failures;
Result:
Internal `ByteBuf` does not leak in case of an error in
`HttpObjectEncoder`.

Prevent memory leak if HTTP/1.1 encoding fails

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java

Motivation:
When we have a null msg-body and call transform, then the callbacks of the trailer
transformer are invoked on the calling thread rather than the subsciption.
Modifications:
Used defer to defer the invocation.
Result:
Better error handling in case of erroneous trailer transformer (ie. trailers validations)
and deferred execution of the callbacks.
Fix: https://github.com/apple/servicetalk/issues/1576

Defer trailer transformer callbacks on null msg-body to subscription.

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java

Motivation:
Single#concat(Publisher) doesn't catch exceptions from downstream
Subscriber#onNext and relies upon upstream to propagate exceptions.
However upstream is a Single and has already terminated by the time the
exception is caught so it cannot send a duplicate terminal signal.
Modifications:
- Single#concat(Publisher) catches exceptions from downstream
Subscriber#onNext and propagates an error.
Result:
Single#concat(Publisher) is more robust with respect to exception
handling.

Single#concat(Publisher) onNext error propagation

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java

Motivation:
Publisher#flatMapMergeSingle relies upon the upstream source to catch
unexpected exceptions, cleanup necessary state, and propagate an error
back downstream. However in the event the upstream source is a Single it
will not be able to propagate an error downstream because it has already
sent a terminal signal (multiple terminal signals not allowed by the
RS spec). This means the upstream can at best log/swallow the error and
downstream may not be notified of the failure.
Modifications:
- Publisher#flatMapMergeSingle exception handling is modified to instead
of propagating the exception upstream, exceptions are caught, upstream
is cancelled, and the exception is propagated downstream.
Result:
Publisher#flatMapMergeSingle usages where downstream operators may throw
will cancel …

Publisher#flatMapMergeSingle catch an propagate unexpected errors downstream

---

servicetalk-client-api/build.gradle
servicetalk-client-api/src/test/java/io/servicetalk/client/api/DefaultAutoRetryStrategyProviderTest.java
servicetalk-client-api/src/test/java/io/servicetalk/client/api/DefaultClientGroupTest.java
servicetalk-client-api/src/test/java/io/servicetalk/client/api/LimitingConnectionFactoryFilterTest.java

Migrate `servicetalk-client-api` tests from jUnit4 to jUnit5

---

gradle.properties
servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java

Motivation:
Some users reported that ServiceTalk was incompatible with Jersey 2.34
release. Updating revealed that an API change in Jersey is responsible;
the `Configuration` object may no longer be null for
`InboundMessageContext`.
Modifications:
Dependency is updated. Providing a default `ResourceConfig` appears
to be sufficient for `InboundMessageContext`.
Result:
Jersey updated.

Update Jersey 2.32 -> 2.34

---

.github/workflows/ci-release.yml
scripts/release.sh

Motivation:
The sonatype repository appears to potentially exhibit a race condition when uploading
artifacts that causes multiple staging repositories to be created.
Modifications:
This change hopefully avoids the apparent race condition by executing publish tasks
serially.
Result:
Successful sonatype upload.

run GitHub release action publish task without parallel

---

servicetalk-concurrent-jdkflow/build.gradle
servicetalk-concurrent-jdkflow/src/test/java/io/servicetalk/concurrent/jdkflow/JdkFlowAdaptersTest.java

Migrate servicetalk-concurrent-jdkflow tests to Junit 5 (#1568) 

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyConnectionContext.java

Motivation:
`NettyConnectionContext` is internal API. We do not expect users to use
it directly. If they do, they have to go through the casting of types and take
care about offloading or use it in a non blocking way.
We applied the same strategy for `NettyConnectionContext#onClosing()` in
#1585.
Modifications:
- Update javadoc for `NettyConnectionContext#transportError()`;
- Remove `publishOn(executor)` from its implementation in
`DefaultNettyConnection` and `H2ParentConnectionContext`;
Result:
Internal API of `NettyConnectionContext#transportError()` does not
apply offloading by default.

Disable offloading for `NettyConnectionContext#transportError()`

---

servicetalk-concurrent-reactivestreams/build.gradle
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/ReactiveStreamsAdaptersTest.java

Migrate servicetalk-concurrent-reactivestreams tests to Junit 5 (#1568)

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactoryFilter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceFilterFactory.java

Motivation:
`append` method on each filter factory was deprecated in #1578 and can
be removed now.
Modifications:
- Remove `append` method from `ConnectionFactoryFilter`,
`GrpcServiceFilterFactory`, `MultiAddressHttpClientFilterFactory`,
`StreamingHttpClientFilterFactory`, `StreamingHttpConnectionFilterFactory`,
`StreamingHttpServiceFilterFactory`.
Result:
No deprecated methods on filter factory API.

Remove `append` methods that were deprecated in #1578

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/CharSequences.java

Motivation:
The `newAsciiString(String)` and `isAsciiString(CharSequence)`
methods have been previously deprecated and may now be removed.
The `newAsciiString(String)` is not marked as deprecated because
it is provided for binary compatibility only; the removal is source
compatible because the more general newAsciiString(CharSequence)
method is provided.
Modifications:
Deprecated methods of `CharSequences` are removed.
Result:
Obsolete methods no longer supported.

Remove deprecated CharSequences methods

---

servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java

Motivation:
`enableWireLogging(String, LogLevel, BooleanSupplier)` method was
mistakenly marked as `@Deprecated` in `DefaultGrpcClientBuilder`.
Modifications:
- Remove `@Deprecated` annotation from
`DefaultGrpcClientBuilder#enableWireLogging`;
Result:
No misleading annotation.

Remove mistaken `@Deprecated` annotation from `DefaultGrpcClientBuilder#enableWireLogging`

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java

Motivation:
PublisherFlatMapSingle was recently changed to better handle excpetions, but the changes
affected the way the drain counter was updating, which as a result created wrong demand upstream.
Modifications:
Init the counter inside the loop to reset it everytime there is contention and the lock is re-acquired.
Result:
Proper counting of delivered items and thus proper demand requests.

Fix PublisherFlatMapSingle's demand handling

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1SpecExceptions.java

Motivation:
`H1SpecExceptions.Builder#allowPrematureClosureBeforePayloadBody()`
option was deprecated in #1475 and can be removed now. Users can use
`allowPrematureClosureBeforePayloadBody(boolean)` overload as an
alternative.
Modifications:
- Remove `H1SpecExceptions.Builder#allowPrematureClosureBeforePayloadBody()`;
Result:
No deprecated
`H1SpecExceptions.Builder#allowPrematureClosureBeforePayloadBody()` API.

Remove `allowPrematureClosureBeforePayloadBody()` that was deprecated in #1475

---

servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java

Motivation:
`ClientSslConfigBuilder#disableHostnameVerification()` option was
deprecated in #1561 and can be removed now. Users can use
`hostnameVerificationAlgorithm("")` as an alternative, but should avoid
disabling hostname verification in general.
Modifications:
- Remove `ClientSslConfigBuilder#disableHostnameVerification()`;
Result:
No deprecated `ClientSslConfigBuilder#disableHostnameVerification()` API.

Remove `disableHostnameVerification()` that was deprecated in #1561

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java

Motivation:
`backlog(int)` builder option was deprecated in #1375 and can be removed
now. Users should use `listenSocketOption(SocketOption, Object)` as an
alternative.
Modifications:
- Remove `backlog(int)` from all server builders;
Result:
No deprecated `backlog(int)` server builder option.

Remove `backlog(int)` server builder option that was deprecated in #1375

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
`recoverWith` operators for `Publisher` and `Single` were deprecated in
#1435 and can be removed now.
Modifications:
- Remove `Publisher#recoverWith`;
- Remove `Single#recoverWith`;
Result:
No deprecated operators on `Publisher` and `Single` API.

Remove `recoverWith` operators that were deprecated in #1435

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/CompletableConcatWithPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSubscription.java

Motivation:
`TestSubscription#requestedEquals` depends on the passed `value` and if
`value == 0` it does not check the current cumulative value of requested
elements, it only checks if `request(long)` was ever invoked or not.
Modifications:
- Fix validation in `TestSubscription#requestedEquals`;
- Adjust existing tests to account for new behavior;
Result:
`TestSubscription#requestedEquals(0)` validates that `request(long)` was
invoked and the current cumulative value if equal to `0`.

`TestSubscription#requestedEquals(0)` incorrectly validates the value

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleConcatWithPublisherTest.java

Motivation:
Single#concat(Publisher) may result in deadlock if demand comes after
the Single completes, and the next Publisher blocks in its subscribe
method. This may happen if blocking APIs are used (e.g.
ConnectablePayloadWriter) and the control flow involves
Single#concat(Publisher). ServiceTalk currently only uses this operator
for use in the Publisher#buffer(..) operator.
Modifications:
- SingleConcatWithPublisher#request(long) should deliver demand to super
class before delivering downstream demand and subscribing. Ordering of
downstream signals will be preserved because
DelayedCancellableThenSubscription won't propagate demand upstream
until onSubscribe is called.
Result:
If downstream requests sufficient demand it will be available to the
concat Publisher as soon as it is …

`Single#concat(Publisher)` potential demand deadlock fix

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
Changes in the offloading behavior make this operator much less useful
and, combined with the behavior change, may produce unexpected results.
Instead the `subscribeOn()` and `publishOn()` operators can be used
independently to achieve the same effect.
Modifications:
The `publishAndSubscribeOn()` operator is removed from `Publisher`,
`Single` and `Completable`.
Result:
Deprecation of problematic operator method.

Deprecate publishAndSubscribeOn

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-snapshot.yml
.github/workflows/codeql-analysis.yml

Motivation:
`0.41` branch will be used for a while until we stabilize API. We plan
to backport all bux fixes and improvements that do not impact API into
that branch. We need to enable CI in order to provide snapshots of
`0.41.X` versions and validate any PRs that we will need to open for
that branch.
Modifications:
- Add `0.41` to the list of branches for all CI configurations;
Result:
CI will publish snapshots for `0.41` branch and validate all PRs.

Enable CI for `0.41` branch

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleConcatWithPublisher.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleConcatWithPublisherDeferSubscribeTckTest.java

Motivation:
To mitigate #1652 issue, temporary limit the mutual recursion between
`onNext` and `request` to a depth of 1 for `ConcatDeferNextSubscriber`.
Modifications:
- Introduce additional `SINGLE_DELIVERING` state to understand if the
`request` was invoked while we deliver result of the `Single`;
- Remove `boundedDepthOfOnNextAndRequestRecursion()` override from
`SingleConcatWithPublisherDeferSubscribeTckTest`;
Result:
1. `SingleConcatWithPublisher` has a maximum recursion depth of 1.
2. Less risk of encountering issue #1652.

`SingleConcatWithPublisher`: limit recursion depth to 1

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromNPublisher.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFrom2TckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFrom3TckTest.java

Motivation:
To mitigate #1652 issue, temporary limit the mutual recursion between
`onNext` and `request` to a depth of 1.
Modifications:
- Use the left 4 bits of the `state` to limit recursion depth to 1;
- Remove `boundedDepthOfOnNextAndRequestRecursion()` override from
`PublisherFrom2TckTest` and `PublisherFrom3TckTest`;
Result:
1. `FromNPublisher` has a maximum recursion depth of 1.
2. Less risk of encountering issue #1652.

`FromNPublisher`: limit recursion depth to 1

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/CloseHandler.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RetryableClosedChannelException.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Motivation:
If the `Channel` is already closed before we attempt the first write, we
wrap it with `AbortedFirstWrite` in `WriteStreamSubscriber` and re-wrap
with `RetryableClosureException` in `DefaultNettyConnection`. This
approach has a couple of disadvantages:
1. `AbortedFirstWrite` is not a `RetryableException` and if the
`closeReason` is not known in `DefaultNettyConnection`, the original
exception will be propagated as-is without `RetryableException` marker;
2. `WriteStreamSubscriber` prematurely sets `written` flag before we
attempt the first write, that may also fail even if the `Channel` is not
closed;
Modifications:
- `WriteStreamSubscriber`: mark internal state as `written` only after
the first msg successfully goes through the outbound channel pipeline;
- Rename …

Mark any exception before the first message is written as retryable

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryRequestWithNonRepeatablePayloadTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberFutureListenersTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberOutOfEventloopTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Motivation:
Because `WriteStreamSubscriber` requests >1 items for new requests and
`meta-data.concat(messageBody)` subscribes to the `messageBody` asap,
it's not safe to retry these requests if the payload body does not
support multiple subscribes (non-replayable).
Modifications:
- Reproduce described behavior in a test;
- `WriteStreamSubscriber` requests only one item on the client-side and
requests more only if the first write succeeds;
- Use new operator `Single.concat(Publisher, boolean)` for
`AbstractStreamingHttpConnection` and `NettyHttpServer`;
- Remove unused `requested` counter from `WriteStreamSubscriber`;
Result:
Client subscribes to the message body only if the request meta-data is
written successfully. Otherwise, `RetryableException` is propagated.

HTTP request may become non-retryable when first write fails

---

servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc

Motivation:
Documentation validation fails due to several errors in the GRPC
Examples documentation. These problems should be fixed.
Modifications:
Link targets are adjusted to pass validation.
Result:
Validation succeeds.

Fixes issues with GRPC Examples documentation

---

docs/generation/gradle/validateSite.gradle

Motivation:
When validating local docs validate everything but only validate
the current SNAPSHOT when validating remote docs. Remote docs
likely include legacy docs which will fail validation but cannot
be updated.
Modifications:
HTML files path is now customized based on validation location.
Result:
Cleaner, narrower validation.

Remove SNAPSHOT from validation path for docs

---

servicetalk-benchmarks/build.gradle
servicetalk-client-api-internal/build.gradle
servicetalk-concurrent-api-internal/build.gradle
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/AbstractHandleSubscribeOffloadedTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/ExecutorThrowsTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/ReduceOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/TaskBasedSignalOffloaderExecutorRejectionTests.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/AbstractCompletablePublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/HandleSubscribeOffloadedTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/PublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractPublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CloseableIteratorBufferAsInputStreamTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/ConnectableBufferOutputStreamTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/ConnectablePayloadWriterTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublisherPublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/HandleSubscribeOffloadedTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/PublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/AbstractSinglePublishAndSubscribeOnTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/HandleSubscribeOffloadedTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/PublishAndSubscribeOnTest.java
servicetalk-concurrent-api-test/build.gradle
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/CompletableStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/PublisherStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/SingleStepVerifierTest.java
servicetalk-concurrent-test-internal/build.gradle
servicetalk-concurrent-test-internal/src/test/java/io/servicetalk/concurrent/test/internal/TestCompletableSubscriberTest.java
servicetalk-concurrent-test-internal/src/test/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriberTest.java
servicetalk-concurrent-test-internal/src/test/java/io/servicetalk/concurrent/test/internal/TestSingleSubscriberTest.java

Migrate servicetalk-concurrent-* tests to junit5

---

servicetalk-grpc-api/build.gradle
servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/api/CatchAllHttpServiceFilterTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ClosureTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyConfigurationFailuresTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientValidatesContentTypeTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcServiceContextProtocolTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/HttpResponseUponGrpcRequestTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/PendingStreamingClosureTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/protoc/GeneratorTest.java
servicetalk-grpc-protobuf/build.gradle
servicetalk-grpc-protobuf/src/test/java/io/servicetalk/grpc/protobuf/ProtoDeserializerTest.java
servicetalk-grpc-protoc/build.gradle
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/StringUtilsTest.java
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictMultiService.java
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictRpc.java
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictService.java
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestMulti.java
servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestSingle.java

Modifications:
Unit tests have been migrated from JUnit 4 to JUnit 5 …

Migrate servicetalk-grpc-* tests to junit5

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java

Motivation:
`TestExecutor` can improve the testing of the code under test by
requiring that tasks it runs correctly handle saving and restoring of
the `AsyncContext`. It would also be useful to set the thread name
so that it can be captured by the tasks and to make the execution
context clear for logging or debugging.
Modifications:
Before any task is run the active (if any) `AsyncContext` is saved and
a special hostile instance is substituted that detects improper
access. The name of the executing thread is also adjusted while running
the task to identify the `TestExecutor` instance.
Result:
Additional testing capability for `TestExecutor` users.

Enforce correct AsyncContext use and name "thread"

---

servicetalk-data-jackson/build.gradle
servicetalk-data-jackson/src/test/java/io/servicetalk/data/jackson/JacksonSerializationProviderTest.java
servicetalk-data-jackson/src/test/java/io/servicetalk/data/jackson/TestPojo.java
servicetalk-data-protobuf/build.gradle
servicetalk-data-protobuf/src/test/java/io/servicetalk/data/protobuf/ProtobufSerializationProviderTest.java
servicetalk-encoding-netty/build.gradle
servicetalk-encoding-netty/src/test/java/io/servicetalk/encoding/netty/NettyChannelContentCodecTest.java
servicetalk-log4j2-mdc-utils/build.gradle
servicetalk-log4j2-mdc-utils/src/test/java/io/servicetalk/log4j2/mdc/utils/ServiceTalkThreadContextMapTest.java
servicetalk-log4j2-mdc/build.gradle
servicetalk-log4j2-mdc/src/test/java/io/servicetalk/log4j2/mdc/ServiceTalkThreadContextMapLog4jProviderTest.java
servicetalk-serialization-api/build.gradle
servicetalk-serialization-api/src/test/java/io/servicetalk/serialization/api/BlockingIterableFlatMapTest.java
servicetalk-serialization-api/src/test/java/io/servicetalk/serialization/api/DefaultSerializerDeserializationTest.java
servicetalk-serialization-api/src/test/java/io/servicetalk/serialization/api/DefaultSerializerSerializationTest.java
servicetalk-tcp-netty-internal/build.gradle
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpConnectorTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpServerBinderConnectionAcceptorTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
servicetalk-test-resources/build.gradle
servicetalk-test-resources/src/test/java/io/servicetalk/test/resources/DefaultTestCertsTest.java
servicetalk-utils-internal/build.gradle
servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/DurationUtilsTest.java
servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/IllegalCharacterExceptionTest.java

Migrate tests to junit5 - Step 4

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
servicetalk-http-router-predicate/build.gradle
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/BaseHttpPredicateRouterBuilderTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/DefaultFallbackServiceTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderCookieTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderHeaderTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderQueryTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpServerOverrideOffloadingTest.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
servicetalk-http-security-jersey/build.gradle
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/AbstractBasicAuthSecurityContextFilterTest.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/BasicAuthSecurityContextFiltersTest.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilterTest.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/NameBindingBasicAuthSecurityContextFilterTest.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/RoleProtectedBasicAuthSecurityContextFilterTest.java
servicetalk-http-utils/build.gradle
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/HttpRequestUriUtilsTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RequestTargetEncoderHttpServiceFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilterTest.java

Migrate servicetalk-http-* tests to junit5

---

gradle.properties
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy

Motivation:
For Gradle modules which are not part of ServiceTalk butuse the ServiceTalk Gradle plugin it is necessary to include the versions referenced in the `Versions.groovy` file because they cannot reference the `gradle.properties` of the main ServiceTalk project.
Modifications:
`PITEST_VERSION` and `PITEST_PLUGIN_JUNIT5_VERSION` added to `Versions.groovy`
Result:
Modules using servicetalk-gradle-plugin build

Specify PITest version in `Versions.groovy`

---

servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsServiceDiscovererBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BaseGrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFactory.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseHttpBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptor.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptorFactory.java

Motivation:
The javadoc for quite a few methods includes use of `=&gt;` to
approximate an arrow for diagrams in small figures. Converting these to
unicode characters is cleaner, makes the source the same as the
rendered output and is more accessible.
Modifications:
Use of `=&gt;` is replaced with `⇒`
Result:
Cleaner source.

Convert "ASCII-art" arrows to unicode arrows

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/VerificationTestUtils.java
servicetalk-examples/http/http2/src/main/resources/log4j2.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnChannelSingle.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ChannelInitSingle.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReadOnlyHttpServerConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SniCompleteChannelSingle.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AlpnClientAndServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java

Motivation:
H2 server with SNI enabled current does not work. Netty's SniHandler
does not queue writes in the same way that the SslHandler does. The h2
handler is added and writes a settings frame immediately on the server,
which is written to the socket before the handshake is completed. This
results in a handshake failure.
Modifications:
- Defer adding h2 protocol handlers to the pipeline until after the SNI
selection is made.
Result:
H2 Server with SNI now works as expected.

Fix H2 Server with SNI bug

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerChainBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java

Motivation:
The parameterization pattern used for both `ClientEffectiveStrategyTest` and `ServerEffectiveStrategyTest` makes it difficult to understand the configuration under test because the configuration is built imperatively rather than as a set of declarative options.
Modifications:
Restructured test parameterization. One specific case is improved; for the cases where no offloading to provided executor is to be performed the test now explicitly ensures that the test fails if the executor is used.
Result:
Easier to understand test with easier to understand test cases.

`ClientEffectiveStrategyTest` and `ServerEffectiveStrategyTest` cleanups

---

servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpan.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContext.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceState.java

Motivation:
We are going through an effort to re-visit the OpenTracing APIs and the implementations
as part of a fix related to B3 sampling.
Modifications:
Deprecating APIs that will be removed or replaced where needed in a follow up breaking-api release.
Result:
Cleaner API, consistent & leaner state without duplication.
Link for breaking changes: https://github.com/apple/servicetalk/pull/1640

Deprecate OpenTracing APIs that will be removed later through a breaking-api release.

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java

Motivation:
The ReactiveStreams specification says that onSubscribe(Subscription)
must be called prior to any other signals being delivered [1]. However
in practice user code may throw in onSubscribe which may stop the
propagation. In this case Publisher#flatMapConcatIterable has an
assertion which may prevent the error from propagating downstream and
result in a control flow deadlock.
[1] https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#1.9
Modifications:
- Move assertion in Publisher#flatMapConcatIterable to allow for null
subscription, add a runtime check before it is used.
Result:
More robust error propagation for Publisher#flatMapConcatIterable in the
precense of Reactive Streams specification violations.

Publisher#flatMapConcatIterable propagate error even if no onSubscribe

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java

As observed by @chemicL
Motivation:
The `TestExecutor` was recently enhanced to install an invalid
`AsyncContextMap` when executing `Runnable` tasks to check for tasks
which did not properly save/restore the appropriate async context. The
invalid map should allow itself to be copied, producing an empty map,
for usages which want to initiate a new subscribe operation.
Modifications:
`copy()` returns a new empty map rather than generating an exception.
Result:
Now possible to subscribe() within a `Runnable` without providing an
`AsyncContextMap`.

Permit copy for `TestExecutor` `AsyncContextMap`

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TcpFastOpenTest.java

Motivation:
Netty had a bug when TFO was enabled with ALPN [1]. Let's make sure ST
works with any HTTP protocols combination when TFO is enabled.
1. https://github.com/netty/netty/pull/11472
Modifications:
- Add more arguments for `TcpFastOpenTest`;
Result:
`TcpFastOpenTest` runs for various protocols combinations.

Verify that TFO works with all protocols combinations

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpPayloadHolder.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderDrainTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java

Motivation:
StreamingHttpPayloadHolder is a package private class with an unused
argument on the constructor.
Modifications:
- Remove the http protocol version argument from the constructor.
Result:
All arguments for the StreamingHttpPayloadHolder constructor are used.

StreamingHttpPayloadHolder remove unused constructor argument

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SequentialSubscription.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SequentialSubscriptionTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRepeatTckTest.java

Motivation:
SequentialSubscription didn't expect reentry, which triggered an
assertion. This may happen when synchronous sources are used, terminal
events are delivered, and operators which use SequentialSubscription
attempt to deliver demand to the next Subscriber. For example:
`Publisher.from(1).repeat(i -> i < 10)`.
Modifications:
- Enhance SequentialSubscription to accommodate reentry switchTo calls
Result:
Operators which use SequentialSubscription (concat, onErrorResume,
repeat*, retry*) now support reentry switching between async sources.

SequentialSubscription reentry bug fix

---

servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/FeaturesFinder.java
servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsApplication.java

Motivation:
Some of the examples contains imports that are never use by the code.
Thus the imports are not needed.
Modifications:
Remove unused imports.
Results:
No unused imports are left in the examples anymore. There's no change
to any of the running code.

Remove unused imports from examples

---

servicetalk-grpc-api/docs/modules/ROOT/pages/index.adoc

Motivation:
The docs say that gRPC is an active work in progress and not yet
performance tested. Nightly benchmarks are run on HTTP transport now,
and this statement is no longer accurate.
Modifications:
- Remove caveat about not being performance tested from docs
Result:
Docs on gRPC more accurately reflect the current state.

Remove gRPC not performance tested statement from docs

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CallableSingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RunnableCompletable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/RunnableCompletableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/CallableSingleTest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingToStreamingService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingUtils.java

Motivation:
There are duplicate implementations of Completable#fromRunnable and
Single#fromCallable inside the code base. We should consolidate them and
make them consistent.
Modifications:
- Make RunnableCompletable package private
- Make RunnableCompletable and CallableSingle use pre-existing
implementations from BlockingUtils
Result:
Less duplicate code and more consistent handling of exception path.

Consolidate Completable#fromRunnable and Single#fromCallable implementations

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RunnableCompletable.java

Motivation:
RunnableCompletable is an implementation detail of
Completable#fromRunnable(Runnable), but the class is public. This API
shouldn't be exposed to users.
Modifications:
- Deprecate RunnableCompletable
Result:
Internal API marked as deprecated to clarify users shouldn't rely upon
it directly.

Deprecate RunnableCompletable

---

servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRepeatWhenTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRetryTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRetryWhenTckTest.java

Motivation:
Current TCK tests for `Publisher` operators `repeatWhen`, `retry`, and
`retryWhen` do not actually use these operators. They just pass through
items from `Publisher.range(...)`.
Modifications:
- Adjust these TCK tests to actually go through operators logic and
re-subscribe to the original `Publisher`;
Result:
Correct TCK tests for `Publisher` operators `repeatWhen`, `retry`, and
`retryWhen`.
Follow-up for #1676.

Improve TCK tests to actually use `repeatWhen`, `retry`, `retryWhen`

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RetryStrategies.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java

Motivation:
AbstractRetryingFilterBuilder currently allows configuration with no
jitter, but this will trigger an assertion error at build time. In
practice most use cases are encouraged to use some form of jitter so we
should deprecate the non-jitter build methods and make sure they don't
trigger an assertion error.
Modifications:
- Deprecate buildWithImmediateRetries, buildWithConstantBackoff, and
buildWithConstantBackoff methods on AbstractRetryingFilterBuilder.
- Enhance jitter bounds upfront validation in RepeatStrategies and
RetryStrategies to throw early if we can easily detect invalid
arguments.
Result:
No more assertion error in AbstractRetryingFilterBuilder due to lack of
jitter, users encouraged to use jitter in retry strategies.

AbstractRetryingFilterBuilder to require jitter

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java

Motivation:
#1629 deprecated `RoundRobinLoadBalancer.RoundRobinLoadBalancerFactory`
and introduced a new top-level `RoundRobinLoadBalancerFactory` class.
While the deprecated one still exists, we should take it into account
when we compute execution strategy influencer.
Modifications:
- `DefaultHttpLoadBalancerFactory` considers deprecated
`RoundRobinLoadBalancer.RoundRobinLoadBalancerFactory`;
Result:
Deprecated `RoundRobinLoadBalancer.RoundRobinLoadBalancerFactory` does
not enforce offloading.

Inspect deprecated `RoundRobinLoadBalancerFactory` for execution strategy computation

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletionStageTest.java
servicetalk-test-resources/src/main/resources/junit-platform.properties

Motivation:
The JUnit5 tests are currently all run serially which is slower than
would generally be possible on most configurations.
Modifications:
Add junit-platform execution parameters for allowing tests to run
concurrently if suitably configured to improve test execution
performance.
Result:
Tests are annotated with `@Execution(CONCURRENT)` will execute
concurrently. There are no changes for existing un-annotated
tests which not explicitly opt-in to parallel execution.

Allow JUnit 5 tests to execute concurrently

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

Motivation:
`AllWritesPromise` is closed when a channels becomes inactive or the
output side of the channel is shutdown. We should not try to write
more messages after that, even if a subscriber is not terminated yet.
Modifications:
- Consider `AllWritesPromise` as non-writable if any of the `state` flag
is set, including `CLOSE_OUTBOUND_ON_SUBSCRIBER_TERMINATION`;
- Add a test to verify further writes are discarded after
`WSS#channelClosed` is invoked;
Result:
No failed writes on netty pipeline after the channel is closed.

`AllWritesPromise` should not be writable after channel is closed

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java

Motivation:
`HttpRequestDecoderTest.unexpectedContentAfterNoContentHeaders()` uses
random bytes for unexpected content. If the first two random bytes are an
upper-case letter followed by a whitespace, `HttpObjectDecoder` may
consider it as a legit HTTP method name (if there is no CRLF) and won't
throw a `DecoderException`.
Modifications:
- Use non-random content that can not be considered as a valid input
for the next request;
- Make some internal methods `static`, where possible;
Result:
Fixes #1694.

Fix flaky `HttpRequestDecoderTest.unexpectedContentAfterNoContentHeaders()`

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
Some javadocs in Publisher, Completable, Single could be clarified. One
usage of a generic type is missing the dimond operator.
Modifications:
- Enhance javadocs for "amb" related operators.
- Add diamond operator for generic type usage in ScanWithPublisher
Result:
Minor code/javadoc cleanup.

Minor javadoc updates and generics usage fix

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java

Motivation:
The earlier PR #1662 (and followon #1675),  were intended to resolve
issues with handling of AsyncContextMap and
`TestExecutor.execute(Runnable)` but the nature of the problem was
misunderstood. In those cases the observed problem was that causing
tasks to execute using `TestExecutor.executeNextTask()` from a
different thread than that which enqueued the task resulted in a
new empty AsyncContextMap being used rather than the correct
AsyncContextMap. The solution in #1662 was intended to detect the
case where the map was not correctly being set by the wrapping of
the Subscription or Subscriber in the operator chain. It missed
that the behavior of TestExecutor was itself inconsistent with other
ServiceTalk executors. Executors are supposed to propagate the
AsyncContextMap from …

TestExecutor Runnable preserve AsyncContextMap

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java

Motivation:
PublisherFlatMapSingleTest#testConcurrentEmissions creates a new
executor however the test suite already has an Executor available for
use.
Modifications:
- Remove executor from testConcurrentEmissions
Result:
Less threads required in the PublisherFlatMapSingleTest test suite.

PublisherFlatMapSingleTest reuse existing Executor

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java

Motivation:
If the BooleanSupplier throws in some situations we don't offload and in
others we do offload. This is a user error, but it may result in
inconsistent ordering of signals. This can be prevented if we always
offload in the event an exception is thrown.
Modifications:
- Introduce a safeShouldOffload method that returns true if an exception
is thrown, and use it consistently in TaskBasedAsync*Operator
Result:
More consistency around exception handling for conditional offloading.

Conditional offload consistent exception handling

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/http/redirects/build.gradle
servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/ManualRedirectClient.java
servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/RedirectWithStateUrlClient.java
servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/RedirectingServer.java
servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/SimpleRedirectUrlClient.java
servicetalk-examples/http/redirects/src/main/resources/log4j2.xml
settings.gradle

Motivation:
Demonstrate how users can handle redirects with ServiceTalk, describe
what is not copied from the original request automatically, and how
users can redirect with headers and payload body.
Modifications:
- Add `servicetalk-examples-http-redirects` module;
- Add links in documentation for the new example;
Result:
Users can see different ways how to handle redirects.

Add examples for redirect handling

---

servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Main.java
servicetalk-grpc-protoc/src/test/proto/test_single.proto

Motivation:
protobuf 3.15 changed optional field support from experimental to
on-by-default. It also requires plugins to opt-in indicating the feature
is supported or else it throws an error and prevents usage of the
plugin.
[1] https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0
Modifications:
- indicate the feature is supported, although services don't interact
with the optional keyword
Result:
ServiceTalk gRPC protoc plugin can be used when the "optional" proto3
keyword is present.

gRPC protoc plugin proto3 optional support

---

servicetalk-examples/grpc/deadline/src/main/java/io/servicetalk/examples/grpc/deadline/DeadlineClient.java
servicetalk-examples/grpc/deadline/src/main/java/io/servicetalk/examples/grpc/deadline/DeadlineServer.java
servicetalk-examples/grpc/helloworld/src/main/java/io/servicetalk/examples/grpc/helloworld/async/HelloWorldClient.java
servicetalk-examples/grpc/helloworld/src/main/java/io/servicetalk/examples/grpc/helloworld/async/HelloWorldServer.java
servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java

Motivation:
`./gradlew javadoc` command fails due to some javadoc rules violations
in examples.
Modifications:
- Don't use self-closing tags;
- Fix a link attribute for `a` tag;
- Use `<pre>` + `{@code ...}` to not worry about manual chars escape;
Result:
`./gradlew javadoc` command is happy.

Fix javadoc in example

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
Clarify differences between conditional and unconditional implementation
of `publishOn` and `subscribeOn` operators.
Modifications:
- Add notes that clarify the difference;
- Add `@see` tag to reference each other;
- Clarify that `shouldOffload` is a `Supplier`;
- Make the first line and `@return` message consistent;
- Fix typos;
Result:
Improved documentation of `publishOn` and `subscribeOn` operators.

Conditional `publishOn` and `subscribeOn` javadoc clarification

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java

Motivation:
The `invokeService` method is to be obsoleted by the upcoming
OffloadingFilter
Modifications:
`invokeService()` is deprecated
Result:
Warning provided of future method removal.

Deprecate `HttpExecutionStrategy.invokeService`

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java

Motivation:
The conditional offloading API of `publishOn()` and `subscribeOn()`
use of a `Supplier<? extends BooleanSupplier>` to be invoked once per
subscribe can be instead used more conventionally with a simply a
`BooleanSupplier`. If per-subscribe `BooleanSupplier` is needed it can
be provided instead in a defer() operator.
Modifications:
Replaces `Supplier<? extends BooleanSupplier>` with `BooleanSupplier`
for conditional `publishOn` and `subscribeOn`.
Ensures that the source is cancelled if the `BooleanSupplier `throws
an exception.
Result:
Simpler conditional offload API. More consistent cancel behavior.

Simplify conditional offloading

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ClearAsyncContextHttpServiceFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ExecutionContextOverridingServiceContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/NoOffloadsHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/OffloadingFilter.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingToStreamingServiceTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyMergeTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerFilterOrderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NoOffloadsStrategyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/InOrderRouter.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilterTest.java

Motivation:
Some filters may wish to run early in the request process before the request has been offloaded.
Modifications:
A new API, `HttpServerBuilder.appendNonOffloadingServiceFilter(StreamingHttpServiceFilterFactory)` is provided for registering filters which will not be offloaded. Offloading will will be handled in the filter chain by the new 
`OffloadingFilter` which is logically inserted between the non-offloading and offloading filters.
Result:
New options for filters.

Add support for nonOffloading HTTP Server Filters

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java

Motivation:
The current offloading operators have the possibility to call
`onSubscribe` twice if the `onSubscribe` method throws an exception.
This should be avoided.
Modifications:
Introduces a new safeHandleSubscribe static method that is invoked in
a slightly different context that avoids the possibility of double
calls to `onSubscribe`.
Result:
Better conformance to reactive specification.

Safer offloading handleSubscribe invocation

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java

Motivation:
The `PartitionedHttpClientBuilder` includes an initializer method for
individual underlying clients. Most of the methods of the outer client
builder were deprecated. This PR removes those methods.
Modifications:
- `PartitionedHttpClientBuilder` no longer depends on `BaseSingleAddressHttpClientBuilder`,
- Converted `PartitionedHttpClientBuilder` to an interface,
- Similarly to `MultiAddressHttpClientBuilder`, added extension of
`ExecutionContextAwareHttpBuilder` and de-deprecated its` methods
(`ioExecutor`, `executionStrategy`, and `bufferAllocator`),
- Copied over javadoc of `serviceDiscoverer` and `retryServiceDiscoveryErrors`
methods as they are now not inherited,
- Corrected `HttpClients` javadoc for creating a partitioned client to
mention …

Cleanup of PartitionedHttpClientBuilder

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SignalOffloader.java

Motivation:
Several files contain javadoc which uses HTML features that are
incompatible with Java 16 javadoc
Modifications:
Update javadocs which fail the more strict validation of Java 16
Result:
CI builds succeed

javadoc fixes for JDK 16 compatibility

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IoThreadFactory.java

Motivation:
The `IoThreadFactory` default constructor creates non-daemon threads
by default. For some types of servers a non-daemon thread is
advantageous where the initial thread starts the server and eventually
exits. The server thread then keeps the JVM running as long as The
server continues to accept connections. As ServiceTalk applications
don't rely on this behaviour all ServiceTalk threads should be daemon
threads.
Modifications:
`IoThreadFactory(String threadNamePrefix)` constructor changed to
create daemon threads.
Result:
ServiceTalk IO Threads will no longer keep JVM alive if application
threads have quit.

IoThreadFactory create daemon threads by default

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MutualSslTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TcpFastOpenTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SocketOptionUtils.java

Motivation:
1. Netty offers a new transport-agnostic channel option for TFO:
`ChannelOption.TCP_FASTOPEN`;
2. macOS impl of client-side TFO has a bug, which affects some of our
existing tests: https://github.com/netty/netty/pull/11588
Modifications:
- Use `ChannelOption.TCP_FASTOPEN` instead of deprecated
`EpollChannelOption.TCP_FASTOPEN`;
- Skip tests that use `ServiceTalkSocketOptions.TCP_FASTOPEN_CONNECT`
when run on macOS;
Result:
No deprecated netty API is used, not test failures on macOS.

Account for recent TFO changes in netty 4.1.67 for macOS

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java

Motivation:
Some gRPC servers may add `grpc-encoding: identity` in response headers.
ST gRPC client should consider it in the same way as not having this
header.
Modifications:
- Improve `GrpcUtils.readGrpcMessageEncodingRaw` to allow
`grpc-encoding: identity`;
- Avoid hiding exceptions for the failed tests;
Result:
gRPC client accepts requests with `grpc-encoding: identity` header.

Correctly accept responses with `grpc-encoding: identity`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyPipelinedConnection.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionInfoTest.java

Motivation:
`ConnectionInfo` has different implementations and may be wrapped. We
want to make sure its `toString()` method is always consistent.
Modifications:
- Add test that verifies `ConnectionInfo#toString()` format;
- Adjust `ConnectionInfo` implementations to pass the test;
- Implement `DefaultGrpcProtocol#toString()`;
Result:
`ConnectionInfo#toString()` format is always consistent.

Make sure `ConnectionInfo#toString()` format is consistent

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCancellable.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyPipelinedConnectionTest.java

Motivation:
The current usage of `awaitCancelledUninterruptibly()` catches
`InterruptedException` and silently discards it. jUnit5 uses
thread interrupt to stop tests after the timeout expires. As a
result, these tests may hang forever as the `InterruptedException`
is not propagated.
Modifications:
- use `awaitCancelled()`, which throws `InterruptedException`
- Declare `InterruptedException` on method declaration.
Result:
The `InterruptedException` is propagated to the test methods,
which allows jUnit5 to stop a hanging test when the test's
timeout expires.
This is related to #1684. The plan for the future is to propagate
`InterruptedException` by changing the usage of the other methods 
described in the issue. This is my first contribution and I am not
100% sure if I understood the issue …

Propogate InterruptedException to the NettyPipelinedConnectionTest tests

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerMultipleRequestsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslProvidersTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractJerseyStreamingHttpServiceTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoThreadFactory.java
servicetalk-transport-netty-internal/gradle/spotbugs/main-exclusions.xml
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IoThreadFactory.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoThreadFactory.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextExtension.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextRule.java
servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java

Motivation:
Future versions of ServiceTalk will require that all IoExecutor threads
implement the `IoThreadFactory.IoThread` marker interface so that the
threads can be recognized for offloading. Usages pf existing APIs which
accept a `ThreadFactory` need to be replaced to use variants that
accept an `IoThreadFactory`.
Modifications:
Introduces `IoThreadFactory` which will be required in the future for
`IoExecutor`. Adds new methods accepting `IoThreadFactory` and
deprecates existing `IoExecutor` creation APIs which accept
`ThreadFactory`.
Result:
API and deprecations anticipate future required behavior.

Deprecate `IoExecutor` create w/ `ThreadFactory`

---

servicetalk-loadbalancer/build.gradle
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/EagerRoundRobinLoadBalancerTest.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

Motivation:
Modifications:
- Unit tests of `servicetalk-loadbalancer` …

Migrate `servicetalk-loadbalancer` module tests to jUnit5

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSubscription.java
servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyChannelContentCodec.java
servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyCompressionSerializer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentEncodingCompatibilityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkToNettyContentCodingCompatibilityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java

Motivation:
Currently netty's syncUninterruptibly() and
awaitRequestNUninterruptibly() do not
propogate `InterruptedException`, meaning that jUnit5 is not
able to stop timeouted tests.
Modifications:
- change the uses of `syncUninterruptibly()` to `sync()`
- on `safeSync()` use `Callable` instead of `Runnable`, because
`Runnable` is unable to throw exception;
- Change all usages of `awaitRequestNUninterruptibly()`
to `awaitRequestN()`;
- add `@Deprecated` to `awaitRequestNUninterruptibly()`;
Result:
`InterruptedException` is no longer silently discarded,
meaning jUnit5 will be able to abort the timeouted test.
Related to #1684.
Questions from my side:
1. Why the N in awaitRequestN()?
2. Doesn’t safeClose() in HttpsProxyTest also not 
Propagate the InterruptedException, which might 
result …

Deprecate syncUninterruptibly() and awaitRequestNUninterruptibly() in tests

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FullDuplexAndSequentialModeTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/EnforceSequentialModeRequesterFilter.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/EnforceSequentialModeRequesterFilterTest.java

Motivation:
ServiceTalk transport is full-duplex, meaning that a
`StreamingHttpRequester` or `BlockingStreamingHttpRequester`  can read
the response before or while it still sends a request payload body.
In some scenarios and for backward compatibility with legacy HTTP
clients, users may have expectations of sequential execution of the
request and response. This filter helps to enforce that behavior.
Modifications:
- Add `EnforceSequentialModeRequesterFilter` that makes sure the
response is not returned to the caller until after the request is
complete;
Result:
Users can enforce request-response processing.

Add `EnforceSequentialModeRequesterFilter` for `http-utils` module

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeaders.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeadersFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiMap.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpHeadersTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyH2HeadersToHttpHeaders.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/IllegalHeaderValueTest.java

Motivation:
RFC7230, section 3.2 defines format for header-field / field-value, but
we currently do not validate field-value. It may impact HTTP/1.1 decoder
if the field-value contains illegal control characters, like CRLF.
Because field-value may be relatively long, validation may cause perf
issues. Therefore, this is an opt-in feature for now.
Modifications:
- Enhance `DefaultHttpHeadersFactory` and `H2HeadersFactory` to take
a `validateValues` argument;
- Deprecate ctors that do not take `validateValues`;
- Test how connection behaves with and without validation;
Result:
Ability to validate header values before encoding/decoding HTTP
messages.

Allow users enable validation for header values

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/http/opentracing/build.gradle
servicetalk-examples/http/opentracing/src/main/java/io/servicetalk/examples/http/opentracing/BraveTracingServer.java
servicetalk-examples/http/opentracing/src/main/java/io/servicetalk/examples/http/opentracing/OpenTracingClient.java
servicetalk-examples/http/opentracing/src/main/java/io/servicetalk/examples/http/opentracing/OpenTracingServer.java
servicetalk-examples/http/opentracing/src/main/java/io/servicetalk/examples/http/opentracing/ZipkinServerSimulator.java
servicetalk-examples/http/opentracing/src/main/java/io/servicetalk/examples/http/opentracing/package-info.java
servicetalk-examples/http/opentracing/src/main/resources/log4j2.xml
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/AbstractTracingHttpFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpServiceFilter.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContextExtractor.java
servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContextInjector.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemoryTracer.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/TextMapFormatter.java
settings.gradle

Motivation:
3rd party Tracer implementations use `Format<TextMap>` to inject/extract
spans. TracingHttpRequesterFilter and TracingHttpServiceFilter currently
don't support `Format<TextMap>` and don't easily interoperate with 3rd
party Tracer implementations.
Modifications:
- TracingHttpRequesterFilter and TracingHttpServiceFilter allow the user
to pass in a custom `Format<TextMap>` which is passed directly to the
Tracer to inject/extract spans.
- Add examples for tracing with ServiceTalk and Brave Tracer
implementations that also publish to Zipkin.
Result:
TracingHttpRequesterFilter and TracingHttpServiceFilter more easily
interoperate with 3rd party Tracers.

HTTP OpenTracing filters Format<TextMap> support

---

servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpanBuilder.java
servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTracer.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java

Motivation:
We currently publish a time stamp for begin, a duration, and a timestamp
for end. We can remove the end timestamp which can be derived by doing
begin+end. We also publish a tag for the type of span, but there is also
an explicit field for the type.
Modifications:
- Remove the tag from the span before publishing, remove end timestamp
in ZipkinPublisher.
Result:
Less unnecessary data published from ZipkinPublisher.

ZipkinPublisher remove unnecessary data

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/AbstractCompletableOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CaptureReferences.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublisherOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/AbstractSingleOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java

Motivation:
There have been occasional failures with the offloading test but the
test failure reports lack a critical piece of information; the stack
dump for the failure.
Modifications:
Add stack capturing to `AbstractOffloadingTest`
Result:
Hopefully more information for debugging flaky tests.

Adds stack capture to OffloadingTest

---

servicetalk-gradle-plugin-internal/src/main/resources/io/servicetalk/gradle/plugin/internal/pmd/basic.xml

Motivation:
The recent PMD upgrade now warns that the `BooleanInstantiation` rule
is deprecated. `PrimitiveWrapperInstantiation` is the replacement.
Modifications:
Replace use of the `BooleanInstantiation` rule with
`PrimitiveWrapperInstantiation`
Result:
Reduced warnings

Update to use PMD PrimitiveWrapperInstantiation rule

---

servicetalk-gradle-plugin-internal/gradle/spotbugs/main-exclusions.xml

Motivation:
The recent spotbugs upgrade triggers warnings on the ServiceTalk Gradle
plugin. These issues can be safely ignored.
Modifications:
Exclusions added for encapsulation issues with Gradle plugin.
Result:
No spotbug warnings reported.

Ignore spotbugs encapsulation warnings for gradle

---

servicetalk-grpc-protoc/build.gradle

Motivation:
e844dcdb82922f8e6efec448c193879190f9dc0a updated shadowJar plugin which
changed behavior of how artifacts are published. The build is broken due
to duplicate artifacts being published.
Modifications:
- Let the shadowJar configure the artifacts automatically, as manually
adding the shaded artifacts to publications is no longer required
Result:
grpc-protoc build works and artifacts are published.

Fix grpc-protoc maven publications

---

gradle.properties

Motivation:
checkstyle 9 on JDK 8 has been observed to exhaust memory and fail
builds. We don't tune the default JVM arguments and should increase
memory to give quality build tasks more memory headroom.

Increase memory for quality build tasks

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml

Motivation:
Github action/cache docs updated on recommended usage for gradle [1]. We
should update our yml to be consistent.
[1] https://github.com/actions/cache/blob/main/examples.md#java---gradle

Github Actions: update actions/cache for gradle

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoExecutor.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutor.java

Motivation:
The `isIoThreadSupported` method was recently added to the
`NettyIoExecutor` as a mechanism for determining if the threads of the
`IoExecutor` were marked using the `IoThreadfactory.IoThread`
interface. It is useful to know this for all `IoExecutors`.
Modifications:
Move `isIoThreadSupported` from `NettyIoExecutor` the parent interface
`IoExecutor`
Result:
More situations can use conditional offloading by querying
`IoExecutor`s whether their threads support IoThread identification.

Move isIoThreadSupported to IoExecutor

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcBindableService.java
servicetalk-grpc-netty/build.gradle
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/AsyncUserService.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/BlockingUserService.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/ClientTransport.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/ClientTransportGrpcCallFactory.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/CustomTransportTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/InMemoryServerTransport.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/ServerTransport.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java
servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java

Motivation:
It is currently not possible for a user to get a Collection of
MethodDescriptors corresponding to a service. The collection of
MethodDescriptors is necessary to build dynamic routing in the event of
a custom transport.
Modifications:
- Add `Collection<MethodDescriptor<?, ?>>` method to
`GrpcBindableService` API.
- Add a unit test which introduces a custom in memory transport and
dynamic routing for a service, and also a client that routes to that
transport in memory.
Result:
It is now possible to get a Collection of MethodDescriptor from a
service, and dynamically build routing for a custom transport.

gRPC add MethodDescriptor Collection to services

---

servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/TypeHolder.java

Motivation:
The deprecated serialization.api.TypeHolder class has a direct
replacement for jackson which is the most common use. We should
explicitly mention the replacement to help people migration from
deprecated APIs.

Improve deprecation docs on TypeHolder

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java

Motivation:
removed methods should be deprecated before they are removed.
Modifications:
Marks methods to be removed in #1695 as deprecated and, where possible,
suggests alternatives.
Result:
Warnings for future method removals are provided.

`ExecutionStrategy` simplification deprecations

---

servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java

Motivation
These methods are rarely used and will be removed in future releases.
Modification
The `offloadSend` and `offloadReceive` methods of `ExecutionStrategy`
are deprecated.
Results:
Warning of future method removal is provided.

Deprecate `ExecutionStrategy` `offload*()`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseHttpBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java

Motivation:
removed methods should be deprecated before they are removed.
Modifications:
Marks methods to be removed in #1695 as deprecated and, where possible,
provides and suggests alternatives.
Result:
Warnings for future method removals are provided.

`ExecutionStrategy` simplification deprecations (#1781)

---

servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java

Motivation
These methods are rarely used and will be removed in future releases.
Modification
The `offloadSend` and `offloadReceive` methods of `ExecutionStrategy`
are deprecated.
Results:
Warning of future method removal is provided.

Deprecate `ExecutionStrategy` `offload*()` (#1791)

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContext.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextProvider.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultAsyncContextProvider.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/NoopAsyncContextProvider.java

Motivation:
It is currently not possible for a user to wrap Callable to ensure it is able to track AsyncContext correctly.
Modifications:
- Add wrapCallable method to AsyncContext
- Add wrapCallable method to AsyncContextProvider interface
- Implement wrapCallable method in NoopAsyncContextProvider
- Implement wrapCallable method in DefaultAsyncContextProvider using existing ContextPreservingCallable class
Result:
It is now possible for a user to wrap Callable to ensure it is able to track AsyncContext correctly.

Enable wrapping Callable with AsyncContext via public API

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpMessageBodyUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java

Motivation:
`BlockingStreamingHttpRequest` and `BlockingStreamingHttpResponse`
already have a `payloadBody(Iterable<Buffer>)` overload that can be
used instead. There is no need for more specialized overload for
`CloseableIterable`.
Modifications:
- Mark `payloadBody(CloseableIterable<Buffer>)` methods as `@Deprecated`;
- Add `default` implementations for `payloadBody(CloseableIterable<Buffer>)`
and `payloadBody(CloseableIterable<Buffer>, HttpSerializer<T>)`;
Result:
Less public API on `BlockingStreamingHttpRequest` and
`BlockingStreamingHttpResponse`.

Deprecate `payloadBody(CloseableIterable<Buffer>)` methods

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ChannelOutboundListener.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java

Motivation:
In the event that gRPC client deadine expires it should send a
RST_STREAM to the peer service. There is a scenario where this may not
happen due to common transport code cleaning up internal state before
propagating the error.
Modifications:
- gRPC utiles to propage the TimeoutException so users can see the
timeout duration.
- DefaultNettyConnection should still propagate channel close events in
the event that a write is cancelled.
- WriteStreamSubscriber should still let the close handler know that the
channel outbound close event occurred even if nothing is pending to
write when a ChannelOutboundListener#channelClosed event happens. This
method may not always be the result of a transport error and may be a
local timeout, in which case we should close the outbound side. …

gRPC send RST_STREAM on client deadline expire

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BaseGrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java

Motivation:
9a605c294fe9092d602084313c1efd64bf31ef93 introduced methods on the Http
Client/Server builders to set the executor in preparation for removal of
the Executor from the ExecutionStrategy. These same changes need to be
made for the gRPC builders.
Modifications:
- Add the `executor(Executor)` setters to the gRPC client/serveer
builders.
Result:
Methods exist to set the Executor on the gRPC builders.

ExecutionStrategy simplification deprecations for gRPC builders

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java

Motivation:
0.42 release will break some APIs, and the builder methods that throw
UnsupportedOperationException can be made abstract to force
implementing.
Modifications:
- Remove UnsupportedOperationException and make methods abstract
Result:
Http builder executor methods are now abstract.

Http executor builder methods abstract

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerMultipleRequestsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkToNettyContentCodingCompatibilityTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslProvidersTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractJerseyStreamingHttpServiceTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoThreadFactory.java
servicetalk-transport-netty-internal/gradle/spotbugs/main-exclusions.xml
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IoThreadFactory.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoThreadFactory.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextExtension.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextRule.java
servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java

Motivation:
For greatest potential compatibility the Netty `IoThreadFactory` should
implement the `ThreadFactory` interface explicitly even though this is
redundant.
Modifications:
Reverts the revert PR #1807 and Netty `IoThreadFactory` implements
the `ThreadFactory` interface explicitly which it did not in the original (#1738) PR.
Result:
Greatest backwards compatibility with existing apps compiled against
earlier versions of ServiceTalk 0.41

Add `ThreadFactory` interface to `IoThreadFactory`

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml

Motivation:
Github Actions announced a new "cache" feature for setup-java:
https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/
Modifications:
- Replace actions/cache with new setup-java cache feature;
Result:
No custom `actions/cache` step, less yaml code for GitHub Actions
configuration.

Replace actions/cache with new setup-java cache feature of GitHub Actions

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java

Motivation:
Review of #1814 suggested some improvements to expose less
implementation in the public `NettyIoExecutors` utility class by better
isolating the implementation in the internal `NettyIoExecutors`.
Modifications:
Public API in `NettyIoExecutors` now relies entirely on immplementation
from internal `NettyIoExecutors`.
Result:
Cleaner and simpler public API.

Use internal NettyIoExecutors for public NettyIoExecutors

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpResponse.java

Motivation:
`payloadBody(CloseableIterable<Buffer>)`
and `payloadBody(CloseableIterable<Buffer>, HttpSerializer<T>)` methods
on `BlockingStreamingHttpRequest` and `BlockingStreamingHttpResponse`
were deprecated in 0.41 branch [1], we can safely remove them from the
`main` branch.
1. https://github.com/apple/servicetalk/commit/42688df6c00f229292ba48b30b41a83aa96a1415
Modifications:
- Remove `payloadBody(CloseableIterable<Buffer>)`
and `payloadBody(CloseableIterable<Buffer>, HttpSerializer<T>)` methods
from `BlockingStreamingHttpRequest` and `BlockingStreamingHttpResponse`;
Result:
Less deprecated API.
Follow up for #1797.

Remove `payloadBody(CloseableIterable<Buffer>)` methods

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java

Motivation:
Some javadoc was missed when bringing #1811 in to 0.41 branch.
Modifications:
Add missing javadoc
Result:
More complete javadoc.

Use internal NettyIoExecutors for public NettyIoExecutors (#1815)

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
servicetalk-http-router-jersey-internal/src/main/java/io/servicetalk/http/router/jersey/internal/BufferPublisherInputStream.java
servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultContainerResponseWriter.java
servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/EndpointEnhancingRequestFilter.java
servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategy.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/OffloadFromIOExecutionStrategy.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NoopExecutionStrategy.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/OffloadAllExecutionStrategy.java

Motivation:
These methods are so sparsely used that including them in the interface
serves no useful purpose.
Modifications:
"Inline" the implementation to the current call sites and remove the
`offloadSend` and `offloadReceive` methods.
Result:
Reduced public interface for `ExecutionStrategy`.

Remove `ExecutionStrategy` `offload*` methods

---

scripts/japicmp.sh

Motivation:
It is useful to be able to compare the Java API compatibility of a
local build against a prior release.
Modifications:
Extend `japicmp.sh` to provide capability to compare an old version
of ServiceTalk against a local build.
Result:
Additional API compatibility comparison capability.

Extend `japicmp.sh` to compare versus local build

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java

Motivation:
ConnectionCloseHeaderHandlingTest$NonPipelinedRequestsTest with
noResponseContent=true has been observed to fail [1]. This is because
the test assumes there will be no payload content however the serializer
always appends a fixed 4 byte length onto every write (even if the
payload is empty). This may result in the payload not being empty.
[1]
```
java.lang.AssertionError:
Expected: "0"
but: was "15"
```
Motiviations:
- ConnectionCloseHeaderHandlingTest server will not write empty content
to the PayloadWriter for serialization.
Result:
Less test failures in ConnectionCloseHeaderHandlingTest.

ConnectionCloseHeaderHandlingTest don't write empty payload

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java

Motivation:
`GrpcClientBuilder#MultiClientBuilder` is no longer necessary, as the
`GrpcClientFactory` contains methods that allow providing a custom
`GrpcClientCallFactory` to build multiple clients.
Modifications:
- Deprecated `GrpcClientBuilder#MultiClientBuilder`,
- Deprecated `GrpcClientBuilder#buildMulti` method,
- Enriched Javadoc to provide alternatives
(`GrpcClientFactory#newClient(GrpcClientCallFactory)` and
`GrpcClientFactory#newBlockingClient(GrpcClientCallFactory)`).
Result:
Unnecessary means to create multiple `GrpcClient`s has been removed and
there is one way to build `GrpcClient`s.

Deprecated GrpcClientBuilder#MultiClientBuilder

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java

Motivation:
`GrpcClientBuilder#MultiClientBuilder` was previously deprecated and is no longer necessary.
Modifications:
- Removed `GrpcClientBuilder#MultiClientBuilder`,
- Removed `GrpcClientBuilder#buildMulti` method.
Result:
Unnecessary means to create multiple `GrpcClient`s has been removed and
there is one way to build `GrpcClient`s.

Removed GrpcClientBuilder#MultiClientBuilder

---

scripts/japicmp.sh

Motivation:
The japicmp script used the local directory to determine the modules to
compare, even if that local directory had nothing to do with the
versions being compared.
Modifications:
Use the bom files from the versions being compared to determine which
modules to compare. The local directory will be used rather than bom
file if doing a local compare. The modules compared is the intersection
of the modules present in both versions.
Result:
Smarter comparison

Use bom to determine modules to compare

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthAndTrailersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyTunnel.java

Motivation:
Some tests use appSerializerUtf8FixLen but also rely upon content-length
header being the same quantity as the number of bytes to terminate
gracefully. In these cases we may get spurious errors due to
content-length being larger than the actual payload length because the
http protocol doesn't think we are done, but the socket closes anyways.
Motivation:
- Restore ProxyTunnel behavior which was intended to simulate proxies
that don't support half closure.
- ConnectionCloseHeaderHandlingTest and
GracefulConnectionClosureHandlingTest just count total bytes, and
don't need to restore the exact String contents. In this case we can
just use a raw string serializer and count bytes manually.
Result:
ConnectionCloseHeaderHandlingTest and
GracefulConnectionClosureHandlingTest should …

Avoid appSerializerUtf8FixLen in tests if content-length is byte length

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultAutoRetryStrategyProvider.java
servicetalk-client-api/src/test/java/io/servicetalk/client/api/DefaultAutoRetryStrategyProviderTest.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcClients.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java

Motivation:
To keep the API consistent across the codebase, builder API
methods changing a boolean value should take a boolean
as a parameter.
Modifications:
- Deprecated `DefaultAutoRetryStrategyProvider#disableWaitForLoadBalancer`
in favor of `DefaultAutoRetryStrategyProvider#waitForLoadBalancer(boolean)`,
- Deprecated
`DefaultAutoRetryStrategyProvider#disableRetryAllRetryableExceptions`
in favor of
`DefaultAutoRetryStrategyProvider#retryAllRetryableExceptions(boolean)`,
- Changed references to previously deprecated methods in javadocs to new
methods that accept boolean.
Result:
More consistent builders' APIs.

Deprecate remaining disable* methods in builder APIs

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java

Motivation:
Upcoming refactoring of `HttpServerBuilder` to become an interface will
remove some methods from public API. Therefore, those methods should be
deprecated.
Modifications:
- Deprecated `HttpServerBuilder#doListen` - both variants,
- Deprecated `HttpServerBuilder#buildExecutionContext`.
Result:
Preparing potential users to the removal of these methods in upcoming
release.

Deprecating `HttpServerBuilder` protected methods

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpRequesterFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentCodingHttpServiceFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContentEncodingHttpServiceFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilter.java
servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpServiceFilter.java

Motivation:
The subscribeShareContext was added in a few cases when defer was used
but not added to all return paths. It should also be added to static
sources like succeed and failed for consistency.
Modifications:
- Update deprecated ContentCoding filters to use subscribeShareContext
on static succeeded operators.
- Move subscribeShareContext in tracing filters to the usage of defer,
to make the need for subscribeShareContext more clear.
Result:
More consistent usage of subscribeShareContext on static sources when
control flow otherwise expects sharing context.

Add missing subscribeShareContext to missing static sources

---

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/TerminalNotification.java
servicetalk-http-utils/build.gradle
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java

Motivation:
After `cancel`, async sources can stop propagating more signals. Therefore,
"beforeFinally" operators consider cancellation as a terminal event. However,
cancellation is the best effort and more signals can be delivered later or it may
race with other signals. In some scenarios, like observability, it may be confusing
to receive more signals after a terminal event. For those use-cases, a new option
is added for `BeforeFinallyHttpOperator` to discard further signals after cancel.
Modifications:
- Add a new ctor for `BeforeFinallyHttpOperator` that takes `discardEventsAfterCancel`;
- Enhance internal state machine to accommodate the new features;
- Add tests to verify new behavior;
Result:
Users can configure `BeforeFinallyHttpOperator` to discard further signals after …

`BeforeFinallyHttpOperator`: add option to discard signals after cancelation

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriberTest.java

If netty `Channel` closes after writing the last item of the outbound
publisher (like HTTP/2 stream closes after sending `endStream=true` flag),
`channelInactive` event may race with `onComplete`. If it comes first,
`WriteStreamSubscriber#channelClosed(Throwable)` will be invoked,
triggering cancellation on the subscription that is already effectively
terminated (because we saw `OutboundDataEndEvent` ->
`WriteStreamSubscriber#channelOutboundClosed` -> `SOURCE_TERMINATED`
flag is already set).
This may result in observing response cancellation from filters instead
of successful completion.
Modifications:
- Swap current `subscription` with `CANCELLED` after
`SOURCE_TERMINATED` flag is set in `WriteStreamSubscriber#AllPromise`;
Result:
Cancel is not propagated and filters see the successful …

Prevent response publisher from being cancelled before `onComplete`

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java

Motivation:
These tests are known to be flaky [1]. The cause is identified and the
work is in progress. To improve productivity for other work, let's
disable these tests temporarily until the fix is available.
1. https://github.com/apple/servicetalk/issues/1507
Modifications:
- Disable frequently failing use-case number 5;
Result:
No need to re-run PRB for other PRs multiple times.

Disable frequently flaky `GracefulConnectionClosureHandlingTest`(s)

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCompletable.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestPublisher.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSingle.java
servicetalk-concurrent-test-internal/build.gradle
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java

Motivation:
The current usage of `awaitUtils` catches
`InterruptedException` and silently discards it. jUnit5 uses
thread interrupt to stop tests after the timeout expires. As a
result, these tests may hang forever as the `InterruptedException`
is not propagated.
Modifications:
- Rewrite `awaitUninterruptibly` to await in `awaitUtils`
Result:
Deprecated awaitUninterruptibly. await now throws unchecked
Exception with the help of PlatformDependent.throwException.
It has been verified that a test that takes more than 10 seconds
and uses `awaitUtils.await` will fail with `java.util.concurrent.TimeoutException.`

Deprecate `AwaitUtils#awaitUninterruptibly`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilterTest.java
servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java

Motivation:
Previously deprecated methods in various builders have now been removed
making the API cleaner.
Modifications:
- Removed deprecated one-way builder methods from `GrpcClientBuilder`,
`GrpcServerBuilder`, `HttpServerBuilder`,
`SingleAddressHttpClientBuilder`, and `HttpReporter`,
- Removed the usage of these methods from code and javadocs.
Result:
Cleaner API without deprecations in the main branch.

Removal of deprecated one-way builder methods

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java

Motivation:
NettyHttpServerTest.testErrorBeforeRead has the server intentionally
write an error without first consuming the request content. The server
may close the connection before the client is done writting and if that
is the case a ClosedChannelException may be observed and fail the test.
Modifications:
- Allow ClosedChannelException when making a request
Result:
Fixes https://github.com/apple/servicetalk/issues/245

NettyHttpServerTest.testErrorBeforeRead handle exception

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/SpliceFlatStreamToMetaSingle.java

Motivation:
SpliceFlatStreamToMetaSingle has a race condition which may result in
concurrency invocation of a Subscriber which is prohibited by the
Reactive Streams specification [1].
[1] https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#1.3
Modifications:
- Use a DelayedSubscription so onSubscribe is invoked before the
Subscriber reference is made visible to other threads which may
invoke terminal methods on the Subscriber.
Result:
SpliceFlatStreamToMetaSingle is more compliant with RS spec and provides
more predictable behavior.

Fix race condition in SpliceFlatStreamToMetaSingle

---

servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/OverlappingCapacityAwareEstimatorTest.java

Motivation:
OverlappingCapacityAwareEstimatorTest leverages a Mockito feature which
instantiates an abstract class as a mock object. This has been observed
to interact poorly with Mockito's `mock-maker-inline` feature and
results in false positive test failures.
Modifications:
- Use traditional mock objects injected into a concrete class that
extends OverlappingCapacityAwareEstimator for test purposes.
Result:
OverlappingCapacityAwareEstimatorTest runs successfully regardless of
Mockito's `mock-maker-inline` feature being enabled.

Avoid mock abstract class creation in test

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java

Motivation:
`ServiceDiscoverer#discover` method returns a `Publisher<Collection<E>>`
while `LoadBalancerFactory#newLoadBalancer` takes `Publisher<E>` as an
argument. Those interfaces should be aligned.
Modifications:
Recently introduced `LoadBalancerFactory#newLoadBalancer` default method
now takes a `Publisher<Collection<E>>` as an argument. Implementations
in `DefaultHttpLoadBalancerFactory` and `RoundRobinLoadBalancerFactory`
implement that properly and `RoundRobinLoadBalancer` iterates over the
events.
Result:
A more aligned API that can allow acting upon a fixed collection
returned from the `ServiceDiscoverer` allowing more sophisticated usages
of the fact that these items come as one update.

Unifying `ServiceDiscoverer` and `LoadBalancerFactory` APIs

---

.github/workflows/codeql-analysis.yml
gradle.properties

I did an evaluation of the service talk build using gradle enterprise, and found a few improvements that could be made.
There are three main changes:
* Enable local build caching.  Doesn't do much for CI builds unless you set up a remote build cache, but will make repeated local builds significantly faster.
* Enable configure-on-demand.  This means gradle will only configure the projects participating in the build, rather than all of them.  With the amount of projects you have, this is a noticeable speedup, especially for short, single project tasks.  **Note that this is an incubating feature**, if you don't want that in your builds I can remove it from the PR.
* Update the specified junit platform version to 1.8.0.  This is what was being used anyways, due to transitive dependencies, but …

Build improvements from Gradle Enterprise testing

---

servicetalk-concurrent-test-internal/build.gradle
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java

Motivation:
The current usage of AwaitUtils catches
InterruptedException and silently discards it. jUnit5 uses
thread interrupt to stop tests after the timeout expires. As a
result, these tests may hang forever as the InterruptedException
is not propagated.
Modifications:
- Rewrite `takeUninterruptibly` to `take` in `AwaitUtils`
Result:
Deprecated `takeUninterruptibly`. `take` now throws unchecked
exception in the case when `queue.take()` throws `InterruptedException`.
The only problem here is that  I use `return null` to compile
successfully. `spotBugs` does not like that because 
I return null for a method that has `@NonNullByDefault`.
I don't understand where it is coming from since there is no
`@NonNullByDefault` for the method, could someone explain?
I tried putting `@Nullable`, but …

Deprecate `AwaitUtils#takeUninterruptibly`

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseHttpBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionHttpClientBuilderConfigurator.java

Motivation:
JDK17 warning: empty <p> tag.
Modifications:
- Remove empty `<p>` tags.
Result:
Successful JDK17 build.

Fix javadoc warnings for JDK17

---

servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java

Motivation:
The current usage of AwaitUtils catches
InterruptedException and silently discards it. jUnit5 uses
thread interrupt to stop tests after the timeout expires. As a
result, these tests may hang forever as the InterruptedException
is not propagated.
Modifications:
- introduce `AwaitUtils#poll`
Result:
`AwaitUtils#poll` now throws unchecked exception
in the case that the thread is interrupted. Meaning that
JUnit5 will be able to stop the tests by interrupting
when it timeouts.

Deprecate `AwaitUtils#pollUninterruptibly`

---

.github/workflows/codeql-analysis.yml

Motivation:
`with` is an incorrect property, `env` should be used instead.
Modifications:
- `with` -> `env`;
Result:
CodeQL workflow starts working.
---
Example: https://github.com/github/codeql-action/blob/ef3290ce11a0bf44196019ab9c650d50b69232da/.github/workflows/codeql.yml#L41-L44
Failed workflow: https://github.com/apple/servicetalk/actions/runs/1287548318

Fix how `CI` env variable is set for CodeQL workflow

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverTest.java

Motivation:
`GrpcLifecycleObserverTest` doesn't close its resources after each
test completes.
Modifications:
- Add `@AfterEach` method for tear down in `GrpcLifecycleObserverTest`;
Result:
Each `GrpcLifecycleObserverTest` cleans up its resources.

`GrpcLifecycleObserverTest`: close client and server after each test

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ConditionalHttpClientFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ConditionalHttpConnectionFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StrategyInfluencerAwareConversions.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractConditionalHttpFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConditionalHttpClientFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConditionalHttpConnectionFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConditionalHttpServiceFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RedirectingClientAndConnectionFilterTest.java
servicetalk-http-netty/src/testFixtures/java/io/servicetalk/http/netty/ConditionalFilterFactory.java

Motivation:
In order to unify the way methods in `HttpClientBuilder`
and `HttpServerBuilder` are implemented, the default methods from
`HttpClientBuilder` have been removed and implemented in
`SingleAddressHttpClientBuilder`.
Modifications:
- Removed default methods from `HttpClientBuilder`,
- Added implementations to `SingleAddressHttpClientBuilder`,
- Moved utilities to servicetalk-http-netty package,
- Moved tests around,
- Copied methods from `FilterFactoryUtils` to `ConditionalFilterFactory`
as they are inaccessible from the netty module's testFixtures
directory.
Result:
The API is consistent with the `HttpServerBuilder`.

Removing default implementations from `HttpClientBuilder`

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
servicetalk-test-resources/src/main/resources/log4j2.xml

Motivation:
We recently added a new logger name in `servicetalk-test-resources`
for debugging LifecycleObserver tests, but it has inconsistent system
property name and mentions HTTP protocol in the name, while it is used
for gRPC as well.
Modifications:
- Rename system property `servicetalk.logger.httpLifecycleLogger` ->
`servicetalk.logger.lifecycleObserverLogLevel`;
- Rename logger `servicetalk-tests-http-lifecycle-logger` ->
`servicetalk-tests-lifecycle-observer-logger`;
Result:
Consistency with other test loggers.

Rename default logger name for LifecycleObserver(s)

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilter.java

Motivation:
#1792 introduced new API for configuring redirects and deprecated old
`RedirectingHttpRequesterFilter` ctors and
`MultiAddressHttpClientBuilder#maxRedirects`. We can remove all
deprecated API for 0.42.
Modifications:
- Remove deprecated ctors for `RedirectingHttpRequesterFilter`;
- Remove `BackwardCompatibleRedirectConfig`;
- Remove `MultiAddressHttpClientBuilder#maxRedirects` method;
- Remove default impl of `MultiAddressHttpClientBuilder#followRedirects`;
- Make redirects opt-in for multi-address client;
Result:
No deprecated API for redirects.

Clean up deprecated API after changes for redirects in #1792

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
Publisher [repeat | retry] operators may cause StackOverflowError if too
many recovery operations are done consecutively on the same thread. This
condition can be difficult to detect as the onError recovery path is
unlikely to be called. We should highlight this possibility in the
javadocs for these methods.
Modifications:
- Publisher, Single, Completable repeat* and retry* operators have
javadoc that clarifies the risk of StackOverflowError and mitigation
technique.
Result:
Javadocs highlight risks of StackOverflowError and how it can be
avoided.

Enhance javadoc to clarify StackOverflowError possibility

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatus.java
servicetalk-grpc-api/test/java/io/servicetalk/grpc/api/GrpcStatusTest.java

Motivation:
Preserving the original code value in the description when the code is not recognized. This is also consistent with grpc-java.
Modifications:
Pass in the original error code to `GrpcStatus` in the static factories.
Result:
GrpcStatus with UNKNOWN status code preserves the ogirinal code value.

Enhance GrpcStatus.fromCodeValue static factories to include actual status code when it maps to UNKNOWN

---

servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java

Remove  methods deprecate in (#1834)
Motivation: code cleanup.
Modifications: removed unused deprecated methods.
Result: AwaitUtils.java 225 lines -> 107 lines.

Remove deprecated methods from AwaitUtils

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java

Motivation:
afterResponseNextClientRequestSucceeds attempts to validate that
NettyChannelPublisher preemptively closes the channel after request
processing concluded if there is an error pending to prevent subsequent
requests from using this connection. This condition may not be hit in
all scenarios due to sequencing of offloading as well as when bytes are
read from the network and the error condition is observed. This results
in the test being flaky and failing.
Modifications:
- Make afterResponseNextClientRequestSucceeds more robust by inserting a
RetryingHttpRequesterFilter and adjusting the assertions to expect
retry may happen.
Result:
Fixes https://github.com/apple/servicetalk/issues/1889.

MalformedDataAfterHttpMessageTest.afterResponseNextClientRequestSucceeds fix

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectEncoder.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java

Motivation:
`HttpObjectEncoder` writes static final ByteBufs to encode HTTP chunks.
Some handlers (e.g. SslHandler) may attempt to aggregate data into
existing buffers if they can be expanded. If static buffers are not
marked as ReadOnly then data maybe appended to these static buffers over
time which may lead to data corruption.
Modification:
- Make static ByteBuf/Buffer objects ReadOnly in `HttpObjectEncoder` and
elsewhere.
Result:
Static buffers will not be used to aggregate data.

Make static final buffers unreleasable and read-only

---

servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/MaxRequestLimitExceededRejectedSubscribeException.java
servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionClosedException.java
servicetalk-client-api/src/main/java/io/servicetalk/client/api/MaxRequestLimitExceededException.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionAcceptorTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/InvalidRedirectException.java

Motivation:
There are a few custom exception types that were used in the past, but
became unusable after some refactoring. It's safe to deprecate them and
remove in future releases.
Modifications:
- Deprecate `ConnectionClosedException`, `InvalidRedirectException`
`MaxRequestLimitExceededException`,
`MaxRequestLimitExceededRejectedSubscribeException`;
Result:
All unused exception types are deprecated now.

Deprecate unused exception types

---

servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/AbstractBuffer.java
servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/EmptyBuffer.java

Motivation:
`EmptyBuffer` has a few minor issues.
Modifications:
- Return a read-only view of `ByteBuffer` from `toNioBuffer()`;
- Implement `toString()`, `equals(Object)`, and `hashCode()`;
Result:
`EmptyBuffer` correctly implements methods from `Object` and is
consistent with netty's `EmptyByteBuf` implementation.

Fixes for `EmptyBuffer` implementation

---

servicetalk-bom/build.gradle

Motivation:
The ServiceTalk BOM file currently contains references to two modules,
`grpc` and `http` which do not exist. These modules are generated from
the examples parent directories but have no artifacts.
Modifications:
Exclude the `grpc` and `http` examples parent modules when building
BOM.
Result:
Non-existant modules no longer included in BOM.

Remove `grpc` and `http` modules from BOM

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java

Motivation:
The default `Executor` used by `RoundRobinLoadBalancer` for health
checking uses a single `Thread` combined with a `SynchronousQueue`.
If multiple health checks are executed simultaneously, that can lead to
task rejections and health checks failing. The proper implementation can
still use a single thread, but should queue scheduled tasks.
Modification:
Default `RoundRobinLoadBalancerFactory.SharedExecutor` uses
a single-threaded, unbounded `ThreadPoolExecutor` to schedule health checks.
Result:
Health checks can be safely rescheduled using the default executor used
by `RoundRobinLoadBalancer`.

`RoundRobinLoadBalancer` default `Executor` with unbounded queue

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java

Motivation:
`RoundRobinLoadBalancer` can maintain connections to hosts which
`ServiceDiscoverer` marks as `UNAVAILABLE` via a boolean flag. This
improves overall performance by reusing existing connections if the
backend is still available. We should make it the default behaviour.
Modifications:
- `RoundRobinLoadBalancerFactory#EAGER_CONNECTION_SHUTDOWN_ENABLED` is
`false` by default.
Result:
The default behaviour of `RoundRobinLoadBalancer` will provide better
connection reuse for most cases.

`RoundRobinLoadBalancerFactory#EAGER_CONNECTION_SHUTDOWN_ENABLED` false by default

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

Motivation:
`Completable.retryWhen` actually does
`toSingle().retryWhen(...).ignoreElement()`. We can avoid it by retrying
the `Single` directly.
We can also skip `onErrorMap` and log inside a retry predicate.
Modifications:
- Avoid premature conversion of a `Single` to `Completable`;
- Use retry predicate instead of `onErrorMap` to log an attempt failure;
- Use the original cause instead of `RESCHEDULE_SIGNAL`;
Result:
Less operators in the health check execution chain.

RoundRobinLoadBalancer: reduce number of operators in health check chain

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultExecutor.java

Motivation:
When the `Executor` provided by the user fails to accept the task
executed by the `SingleThreadedScheduler`, the exception is ignored and
the scheduler is no longer usable. The exceptions from the user land
should not surface to the global scheduler and the implementation should
do its' best to run the task even at the cost of skipping offloading.
Modification:
`DefaultExecutor.SingleThreadedScheduler#schedule` is guarded against
rejections from the user's `offloadExecutor` and triest to fallback
and execute the task on its' own thread.
Result:
User error does not prevent the `SingleThreadedScheduler` from executing
future tasks.

`SingleThreadedScheduler` should fallback execution upon offloading failure

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultThreadFactory.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoThreadFactory.java

Motivation:
Users can see what thread name prefix a `ThreadFactory` uses and other
info.
Modifications:
- Add `DefaultThreadFactory#toString()`;
- Add `NettyIoThreadFactory#toString()`;
Result:
Users can get visibility into `DefaultThreadFactory` and
`NettyIoThreadFactory` internal state.

Implement `toString()` for our `ThreadFactory` variants

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableConcatWithCompletables.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/CompletableConcatWithCompletablesTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletableConcatWithCompletablesTckTest.java

Motivation:
There are some use cases (DefaultCompositeCloseable) that dynamically
build a large chain of Completable#concat(Completable) operations. These
large chains may result in a StackOverflowException.
Modifications:
- Introduce a `Completable#concat(Completable...)` operator that has stack
overflow protection.
Result:
Completable concat operator exists with stack overflow protection.

Completable#concat(Completable...)

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultCompositeCloseable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeClosableTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ClosureTest.java

Motivation:
DefaultCompositeCloseable uses operator composition when merging or
appending AsyncClosables. When a close operation is invoked on the
closable that means the stack must have enough depth in order to
cascade invocations of subscribe and signal notification. There are
scenarios where the number of operations is proportional to the number
of channels (ChannelSet, RRLB) which are more likely to result in
StackOverflowException as the number of channels grow.
Modifications:
- Update DefaultCompositeCloseable to avoid composing individual
operators and instead use bulk array based operators.
Result:
Less likely to get SOOE from DefaultCompositeCloseable during
client/server shutdown.

DefaultCompositeCloseable StackOverflowException

---

servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProviderBuilder.java

Motivation:
`MessageEncodingException` expects an encoding name only, not a cause.
It already has a prepared cause inside a ctor.
Modifications:
- Pass encoding to the `MessageEncodingException` ctor instead of a
cause;
Result:
Users see a correct cause message for `MessageEncodingException`.

`MessageEncodingException` should take an encoding name only

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingHttpService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyInfluencer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/FilterableStreamingHttpClient.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClient.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceFilterFactory.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilter.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptorFactory.java

Motivation:
1. There is no much value in making `HttpFilterFactory` public,
hard to think of a use-case for users.
2. Inconsistencies in default `requiredOffloads()` implementations.
3. Incorrect `requiredOffloads()` impl for some service API.
4. No need to implement `ExecutionStrategyInfluencer` for `HttpClient`,
it already has a strategy in `HttpExecutionContext` associated with the
client. No other client API implement `ExecutionStrategyInfluencer`.
Modifications:
- Rename `HttpFilterFactory` to `DefaultHttpExecutionStrategyInfluencer`
and make it pkg-private;
- Make all default `requiredOffloads()` implementations consistent;
- Use `HttpExecutionStrategies.offloadAll()` instead of a pkg-private
`OFFLOAD_ALL_STRATEGY` constant because users will read the default
impl, better to have …

Adjust changes to http-api related to `ExecutionStrategyInfluencer`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java

Motivation:
PR #1832 improved the `HttpExecutionContextBuilder` by sharing code
with `ExecutionContextBuilder` but this resulted in a change to the
return type of some setter methods. The problem was not noticed
because the current source base does not use chaining of builder
methods.
Modifications:
Add overrides for builder methods which specialize the return type to
the expected "`self`" type.
Result:
Chainable use of `HttpExecutionContextBuilder`

Restore `HttpExecutionContextBuilder` returns

---

gradle.properties
servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy

Motivation:
PITest plugin version 1.7.0 fixes deprecations for Gradle 8.0
Modifications:
Update PITest and associated plugin versions
Result:
Improved compatibility with upcoming Gradle by removing deprecations

Update to PITest 1.7.3 and matching plugins

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java

Motivation:
`MalformedURLException` is more suitable for a use-case when an URL is
not in absolute-form.
Modifications:
- Throw  `MalformedURLException` instead of `IllegalArgumentException`;
- Try-catch `selectClient` operation and return failed `Single` in case
of an error;
Result:
`StreamingUrlHttpClient` try-catches all exception during client
selection and throws `MalformedURLException` when a non-absolute form
URL is provided.

Multi-address client: throw  `MalformedURLException` instead of `IllegalArgumentException`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java

Motivation:
#1831 added a new
`LoadBalancerFactory#newLoadBalancer(String, Publisher, ConnectionFactory)`
overload, but didn't override it in `HttpLoadBalancerFactory`.
Modifications:
- Add `HttpLoadBalancerFactory.newLoadBalancer(...)` overload with 3
arguments;
Result:
`HttpLoadBalancerFactory` follows `LoadBalancerFactory` contract with
http-specific types.

`HttpLoadBalancerFactory` should override `newLoadBalancer` with 3 args

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java

Motivation:
Currently default execution strategy is always used for the connect
request but the connection/client may be using a different strategy.
Modifications:
Use the connection execution strategy so as not to introduce unexpected
offloading.
Result:
Proxy connect uses same strategy as the rest of the client operations.

Use connection execution context in proxy connect

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMetaData.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseMetaData.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java

#1904 added two `context` methods on `HttpMetaData`, but had to use
`default` implementations to make it backward compatible with 0.41. We
can remove those `default` implementations now.
Modifications:
- Remove default impl for `HttpMetaData#context()` and
`HttpMetaData#context(ContextMap)`;
- Adjust all interfaces that extend `HttpMetaData`;
Result:
0.42 won't have `default` implementations for `context` methods.

Cleanup default methods from `HttpMetaData`

---

servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ServiceDiscovererUtils.java

Motivation:
`japicmp.sh` highlights `ServiceDiscovererUtils#calculateDifference` as
removed method. For 0.41 branch we should be backward compatible even
for internal classes.
Modifications:
- Restore `ServiceDiscovererUtils#calculateDifference(List, List, Comparator, TwoIntsConsumer)`
overload;
- Mark the whole utility class, `calculateDifference`, and
`TwoIntsConsumer` interface as `@Deprecated`;
Result:
`ServiceDiscovererUtils` is backward compatible with 0.41.11.

Restore `ServiceDiscovererUtils` methods and mark them as deprecated

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java

Motivation:
`japicmp.sh` highlights this method as removed. For 0.41 branch we
should be extra cautious for any changes, even for internal or
pkg-private changes. For extra safety, let's recover this method.
Modifications:
- Restore `BaseSingleAddressHttpClientBuilder#retryServiceDiscoveryErrors(ServiceDiscoveryRetryStrategy)`;
- Add default impl;
Result:
Less changes for `BaseSingleAddressHttpClientBuilder` in 0.41.

Restore `BaseSingleAddressHttpClientBuilder#retryServiceDiscoveryErrors`

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcSslAndNonSslConnectionsTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpServerConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpClientConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingClientSslConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingServerSslConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java

Motivation:
The key for SSLSession is `peerHost+peerPort`. Our builders current
set the peerHost before resolution is complete. This may result in
cache misses if the hostname resolves to multiple IPs.
Modifications:
- The peerHost should be set after resolution, when the IP address
is known. The cache key will then be specific to a host and more
likely to have a cache hit. The peerHost is not authoritative so
overriding should be safe.
Result:
SSLSession cache hits are more likely to happen in practice.

Reduce SSLSession cache misses

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscovererEvent.java

Motivation:
Add a note that clarifies how subsequent events are treated by SD
contract.

Clarify `ServiceDiscovererEvent` contract related to address and status

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcSslAndNonSslConnectionsTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpServerConfig.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractReadOnlyTcpConfig.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpClientConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingClientSslConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingServerSslConfig.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DelegatingSslConfig.java

Motivation:
The key for SSLSession is `peerHost+peerPort`. Our builders current
set the peerHost before resolution is complete. This may result in
cache misses if the hostname resolves to multiple IPs.
Modifications:
- The peerHost should be set after resolution, when the IP address
is known. The cache key will then be specific to a host and more
likely to have a cache hit. The peerHost is not authoritative so
overriding should be safe.
Result:
SSLSession cache hits are more likely to happen in practice.

Reduce SSLSession cache misses (#1958)

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactoryFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionAcceptorOffloadingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionFactoryOffloadingTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpServerBinderConnectionAcceptorTest.java
servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java
servicetalk-transport-api/build.gradle
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectExecutionStrategy.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptorFactory.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultConnectExecutionStrategy.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategyInfluencer.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/InfluencerConnectionAcceptor.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/InfluencerConnectionAcceptorTest.java

Motivation:
Currently `ConnectionAcceptor::accept` and
`ConnectionFactory::newConnection` are always offloaded. This may
be unnecessary.
Modifications:
By implementing `ExecutionStrategyInfluencer` and conditionally
offloading only when the required strategy of the acceptor or factory
is not `anyStrategy()` unnecessary offloading is avoided.
Result:
Potentially less offloading for connection acceptors and factories.

`ConnectionAcceptor` `ConnectionFactory` offloading control

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractH2DuplexHandlerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java

Motivation:
`HttpServerContext` always has an HTTP/2 stream id as part of the
`ctx.toString()`. On the client-side, the identifier is assigned only
after the first write of `HEADERS` frame is made. We can give visibility
into the assigned stream id through the `StreamObserver`.
Modifications:
- Add `StreamObserver#streamIdAssigned(long)` callback;
- Invoke the new callback when the steam id is known;
- Test new behavior;
Result:
Users have visibility into the assigned HTTP/2 stream id and when it's
assigned.

Give visibility to the assigned HTTP/2 Stream ID

---

servicetalk-http-api/gradle/spotbugs/test-exclusions.xml
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/AbstractHttpRequesterFilterTest.java

Motivation:
#1956 introduced `NEW_TO_DEPRECATED_FILTER` which helps to glue a
new filter API to deprecated filter API. This glue was missed in
`AbstractHttpRequesterFilterTest`.
Modifications:
- Add `NEW_TO_DEPRECATED_FILTER` in
`AbstractHttpRequesterFilterTest#newClient`;
Result:
Implementations of `AbstractHttpRequesterFilterTest` work correctly.

Add missed transition between new and deprecated filters

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executors.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/GlobalExecutor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java

Motivation:
`Executors.immediate()` was used in time sensitive operators, which
don't accept an `Executor` instance. When the `ImmediateExecutor` was
used to offload a scheduled task, such as a timeout, it would have been
executed on the global
`io.servicetalk.concurrent.api.DefaultExecutor.SingleThreadedScheduler`
which is used for all future executions internally. When the actual
termination happened, if it blocked, it would have stalled all following
scheduled delayed tasks.
Modifications:
- Moved `GlobalExecutor` from `transport-netty-internal` module to
`concurrent-api`,
- Introduced `Executors.global()` `Executor`, which uses a singleton of
`GlobalExecutor`,
- Using `Executors.global()` in all `timeout(...)` operators that do not
accept `Executor` as an argument.
Result:
The …

Make `GlobalExecutor` part of `concurrent-api` module

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpClientChannelInitializer.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerChannelInitializer.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java

Motivation:
When TCP Fast Open socket option is enabled and available by the OS,
client sends `ClientHello` message with the initial TCP handshake. We
should trigger `onSecurityHandshake()` earlier in this case and give
users another callback to see when the TCP handshake completes.
Modifications:
- Add `ConnectionObserver#onTransportHandshakeComplete()`;
- Improve tests to verity new callback;
- Adjust `ConnectionObserverInitializer` to trigger
`onSecurityHandshake()` earlier when TCP Fast Open is enabled and
available;
Result:
Users can observe TCP and TLS handshake behavior correctly when
Fast Open is used.

Correctly report TLS handshake when TCP Fast Open is enabled

---

servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Processors.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingStrategyInfluencer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToOffloadedStreamingHttpService.java
servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategy.java

Motivation:
Current offloading for transport is inconsistent, some events are offloaded, others are
not. To make it easier to support additional transport event receivers the offloading
should be configurable.
Modifications:
Apply consistent signal delivery with either no offloading or offloading to the context
executor for transport events. Extend `HttpExecutionStrategy` to provide configuration of
transport event offloading.
Result:
More flexible transport event offloading. By default, transport events will be offloaded.

Transportevents offloading

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AutoRetryTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
servicetalk-loadbalancer/build.gradle
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/EagerRoundRobinLoadBalancerTest.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java

Motivation:
We deprecated some APIs in the load balancing area: `LoadBalancerFactory`,
`RoundRobinLoadBalancer`, and `RoundRobinLoadBalancerFactory`.
Modifications:
- `LoadBalancerFactory` default methods swapped,
- `RoundRobinLoadBalancer` is no longer public and the constructors have
been cleaned up,
- `RoundRobinLoadBalancerFactory` removed configuration for
`RoundRobinLoadBalancer` eagerness configuration,
- Adjusted tests.
Result:
Old APIs have been removed and it's more obvious how to use
`RoundRobinLoadBalancerFactory` to obtain a `LoadBalancer` that performs
round-robin strategy.

Cleanup LoadBalancer APIs

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java

Motivation:
Recently, `subscribeShareContext` method from `Completable`, `Single`,
and `Publisher` were renamed to `shareContextOnSubscribe` and the
previous variant was deprecated.
Modification:
`subscribeShareContext` removed from the API.
Result:
Only recent variant - `shareContextOnSubscribe` to achieve the
functionality exists.

Remove `subscribeShareContext` method

---

servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java

Motivation:
#1969 and #1970 introduced two new callbacks for `ConnectionObserver`
and added default impl for backward compatibility. We can clean up API
in 0.42.
Modifications:
- Remove default impl for `onTransportHandshakeComplete()` and
`streamIdAssigned`;
Result:
No default callback impls.

Remove default impl from `ConnectionObserver`

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java

Motivation:
Some `AbstractRetryingFilterBuilder.build*` methods were deprecated in
#1692 and deprecations were announced in one of 0.41.x releases.
It’s safe to remove these methods from the main branch now.
Modifications:
- Remove `buildWithImmediateRetries` and `buildWithConstantBackoff`;
Result:
No deprecated API in `AbstractRetryingFilterBuilder`.

Remove deprecated `AbstractRetryingFilterBuilder` build methods

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java

Motivation:
`HttpClients` factories that are related to proxy were deprecated in
#1751 and deprecations were announced in one of 0.41.x releases.
It’s safe to remove these methods from the main branch now.
Modifications:
- Remove `forSingleAddressViaProxy` and `forResolvedAddressViaProxy`;
Result:
No deprecated API in `HttpClients`.

Remove deprecated `HttpClients` factories for proxy

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java

Motivation:
`publishOn/subscribeOn` does not need any API that
`io.servicetalk.concurrent.api.Executor` define and can work with
`io.servicetalk.concurrent.Executor`.
Modifications:
- Change argument to `io.servicetalk.concurrent.Executor` for
`publishOn/subscribeOn` in `Completable/Single/Publisher`;
- Update javadoc for modified methods;
Result:
`publishOn/subscribeOn` API is less restrictive for the passed executor.

`publishOn/subscribeOn` take `io.servicetalk.concurrent.Executor`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingToStreamingService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingStrategyInfluencer.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/ServiceToStreamingService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingHttpClient.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingStreamingHttpClient.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToHttpClient.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingHttpConnection.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingStreamingHttpConnection.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/FilterableClientToClient.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java

Motivation:
The computed execution strategy used by the client was different in
some cases than 0.41
Modifications:
Improve `ClientEffectiveStrategyTest` to cover more cases and ensure
that the strategy used matches, where reasonable, the behaviour from
0.41. Some cases, where the strategy from filters or connection factory
was `defaultStrategy()` or `noOffloadsStrategy()` are now ignored with
a warning. Influencers must use a computed strategy rather one of the
special strategies.
Result:
More compatible and consistent client behavior with computed execution
strategy.

Fix client expected strategies regression

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StatelessTrailersTransformer.java

Motivation:
`StatelessTrailersTransformer` does not have a state. `Void` type is
more appropriate.
Modifications:
- Change the state type from `Object` to `Void`;
Result:
Correct contract for `StatelessTrailersTransformer`.

`StatelessTrailersTransformer`: Object -> Void state

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy

Motivation:
A newer release of PMD, 6.41.0, is available
Modifications:
Upgrade version of PMD, used to 6.41.0
Result:
Newer version of PMD used for builds

Upgrade build PMD 6.38.0 → 6.41.0

---

servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy

Motivation:
A newer release of Checkstyle, 9.2, is available
Modifications:
Upgrade version of Checkstyle used to 9.2
Result:
Newer version of Checkstyle used for builds

Upgrade build Checkstyle 9.0 → 9.2

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancedAddress.java

Motivation:
Support weight factors for various load-balanced-addresses, for uses in selection and/or subsetting.
Modifications:
A new API to set a weight factor to a `LoadBalancedAddress`.
Results:
Support weights.

Add weight factor to the load balanced addresses

---

servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/loadbalancer/RoundRobinLoadBalancerSDEventsBenchmark.java
servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java

Motivation:
Remove javadoc that is not relevant after #1976, don't use deprecated
`newLoadBalancer` method.

`LoadBalancerFactory`: clean up javadoc

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerContext.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFactory.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java

Motivation:
Existing server builders always return general `ServerContext` object.
Returning a protocol specific context will give us a way to add more
information about the server later, like: protocols its supports,
default grpc deadline, etc. It also gives a correctly typed
`ExecutionContext`.
Modifications:
- Add `HttpServerContext`, change return parameter of "listen" methods
of `HttpServerBuilder` to `HttpServerContext`;
- Add `GrpcServerContext`, change return parameter of "listen" methods
of `GrpcServerBuilder` to `GrpcServerContext`;
- Adjust tests and related API;
Result:
Returned `ServerContext` is aware of the protocol, which opens a way
to add more protocol-specific information in the context, when necessary.

Introduce `HttpServerContext` and `GrpcServerContext`

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java

Motivation:
Users who fail to load native transport may experience hard to debug
issues because Java NIO is less reactive to the network events and
does not proactively notify pipeline when the channel becomes inactive.
Modifications:
- Provide more context in the warn message and notify ST will fail to
start in future releases unless native transport was explicitly disabled;
Result:
More clear warning when native transport can not be loaded.

Provide more context when native transport is unavailable

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java

Motivation:
Users who fail to load native transport may experience hard to debug
issues because Java NIO is less reactive to the network events and
does not proactively notify pipeline when the channel becomes inactive.
In most cases, it's unexpected to run without native transport and
represents a bug with packaging or deployment.
Modifications:
- Throw an exception if the native transport can not be loaded without
being explicitly disabled;
Result:
ST does not start without native transport unless it's explicitly
disabled.
Depends on #1978.

Fail to start without native transport

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java

Motivation:
Leftover javadoc section that is relevant only for 0.41 branch.
Modifications:
- Remove non-relevant javadoc;
Result:
`MultiAddressHttpClientBuilder#followRedirects` javadoc does not mention
pre-existing behavior.

Remove non-relevant javadoc from `MultiAddressHttpClientBuilder#followRedirects`

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java

Motivation:
`unresolvedAddressToHostFunction` should be configured using
`SingleAddressInitializer`, there is no more method on the
`MultiAddressUrlHttpClientBuilder` API.
Modifications:
- Remove internal variable `unresolvedAddressToHostFunction` from
`DefaultMultiAddressUrlHttpClientBuilder`;
Result:
No unused variables in `DefaultMultiAddressUrlHttpClientBuilder`.

`DefaultMultiAddressUrlHttpClientBuilder`: remove unused `unresolvedAddressToHostFunction`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpServerResponse.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpService.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpServerResponse.java

Motivation:
`BlockingStreamingHttpServerResponse` is the only response type that is
an abstract class, not an interface. It limits users ability to wrap it
to intercept the methods because its ctor is pkg-private.
Modifications:
- Convert `BlockingStreamingHttpServerResponse` to an interface;
- Update `DefaultBlockingStreamingHttpServerResponse` to take full
implementation responsibility;
Result:
`BlockingStreamingHttpServerResponse` is consistent with other response
types and users can wrap it now.

Convert `BlockingStreamingHttpServerResponse` to an interface

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ToStH1UtilsTest.java

Motivation:
Some `DefaultHttpHeadersFactory` and `H2HeadersFactory` constructors
were deprecated in #1757, cherry-picked into 0.41, and can be removed
from the main branch now.
Modifications:
- Remove deprecated constructors from `DefaultHttpHeadersFactory` and
`H2HeadersFactory`;
Result:
Less deprecated API.

Remove deprecated constructors from HttpHeadersFactories

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java

Motivation:
#1979 fails app initialization if native transport libs can not be
loaded. This is too aggressive. Instead, keep warning users and let
them opt-in for the enforced behavior.
Modifications:
- Fail initialization only if users explicitly opt-it for this using
`-Dio.servicetalk.transport.netty.requireNativeLibs=true`;
- Improve exception and log messages;
Result:
Users can enforce requirement for native libs if they need.

Let users opt-in for app initialization failures without native libs

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java

Motivation:
Occasional test failures have occurred for
`HttpOffloadingTest::serverOnCloseIsOffloaded()`
where the reported thread is the JUnit executor
thread. This is because the server has already
completed close and the Future.get()/subscribe
happens entirely on the Junit thread.
Modifications:
Allow for either ioThread or Junit thread to
execute the onComplete()
Result:
No spurious test failures.

Close can be observed on test executor thread

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java

Motivation:
Existing `TransportObserver#onNewConnection()` callback does not
provide visibility into an address. In case a connect attempt fails,
users don't know which remote was involved.
Modifications:
- Add a new callback `onNewConnection(Object, Object)` that gives
visibility to local/remote address;
- Deprecate `TransportObserver#onNewConnection()`;
- Update tests and implementation classes;
Result:
`TransportObserver` users have visibility into local/remote address
for each `onNewConnection` attempt.

`TransportObserver#onNewConnection` give visibility into addresses

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/Flush.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java

Motivation:
Existing `ReadObserver` and `WriteObserver` API sends signals without
letting users know what exactly was read or written.
Modifications:
- Add `ReadObserver#itemRead(Object)`, deprecate `ReadObserver#itemRead()`;
- Add `WriteObserver#itemReceived(Object)`, deprecate `WriteObserver#itemReceived()`;
- Add `WriteObserver#itemWritten(Object)`, deprecate `WriteObserver#itemWritten()`;
- Add `WriteObserver#itemFlushed(Object)`;
- Update tests and implementations;
Result:
Users can see what items have been read or written at L4 level.

`Read/WriteObserver`: give users visibility into items

---

servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/BlockingIterable.java
servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/BlockingIterator.java

Motivation:
`BlockingIterable` and `BlockingIterator` methods can throw
`InterruptedException` using the sneaky-throw mechanism. The reason for
it is that implementations rely on `BlockingQueue` which may be
interrupted. However, as `BlockingIterator` extends `Iterator` from the
JDK, its' method signatures don't list any checked exception. Therefore
it would be inconsistent to have some methods declare checked
exceptions, while the overridden ones not.
Modification:
Add javadoc notes to all methods that can throw `InterruptedException`
to `BlockingIterable` and `BlockingIterator`.
Result:
The runtime behavior is better described via javadoc.

Improve BlockingIterable javadoc

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/AutoRetryStrategyProvider.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java

Motivation:
New retrying http request filter has bug when the factory is shared across client builders.
Modifications:
Internalized the state to the filter, where the lazy injection now happens rather than the factory as it was before.
Result:
Safer implementation

Fix sharing issue with Retrying requests filter factory

---

servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
servicetalk-client-api/src/main/java/io/servicetalk/client/api/AutoRetryStrategyProvider.java
servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultAutoRetryStrategyProvider.java
servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverRequesterFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
servicetalk-http-netty/gradle/spotbugs/main-exclusions.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverRequesterFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancerReadySubscriber.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RetryingHttpRequesterFilter.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionContext.java

Motivation:
Use of `AutoRetry` alongside a `RetryingHttpRequesterFilter` creates issues with the retrying logic exponentially increasing to the product of the two max-retry settings. The conflict arises when both solutions are configured to retry `RetryableException`s which is the case by default.
Modifications:
- `AutoRetry` logic is deprecated, to be removed in the future.
- The logic of the `AutoRetry` is merged with the `RetryingHttpRequesterFilter` which now allows retryable flows. Different exceptions can have different retry, as well as support for retries of responses.
Results:
Unified API for retries.
Note:
This is a cherry-picked combination of 3 PRs to the `main` branch, see  #1905, #2004, #2018.

[Backport] Unified retry / auto-retry filter support

---

gradle.properties

Motivation:
Log4J upgrade provides additional mitigations for message lookup CVE
Modifications:
Upgrade from 2.15.0 to 2.16.0
Result:
Using safer Log4J version

Upgrade Log4J 2.15.0 → 2.16.0

---

gradle.properties

Motivation:
Log4J upgrade to address a security risk CVE-2021-45105
Modifications:
Upgrade from 2.16.0 to 2.17.0
Result:
Using a safer Log4J version

Upgrade Log4J 2.16.0 to 2.17.0

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java

Motivation:
The final retry predicate depends on class variables of the builder in
`RetryingHttpRequesterFilter`. User can keep a reference to the builder
and modify functions to change the retry behavior in runtime.
Modifications:
- Capture the context of the builder state in `final` variables to
eliminate any runtime behavior change in `RetryingHttpRequesterFilter`;
Result:
`RetryingHttpRequesterFilter` behavior can not be altered through the
builder at runtime.

Prevent retry logic modifications through the builder

---

docs/modules/ROOT/pages/async-context.adoc
docs/modules/ROOT/pages/performance.adoc
servicetalk-concurrent-api/docs/modules/ROOT/pages/async-context.adoc

Motivation:
Some links in docs reference `http` instead of `https` which
is failing CI builds during doc validation with status code
302.
Modifications:
- Update doc links from `http` to `https`
Result:
Links reference secure content, CI doesn't fail to follow
redirects.

Update doc links to https

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializers.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java

Motivation:
HttpSerializers currently set the Content-Type header
but not the Accept header. The Accept header provides
the server a hint as to what type of contnet should
be returned.
Modifications:
- Modify implementations in HttpSerializers to set the
Accept header
Result:
Clients provide info to servers about what type of
content is accepted in a response.

HttpSerializers client set Accept header

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherCastTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherOfTypeTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleCastTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherCastTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherOfTypeTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleCastTckTest.java

Motivation:
Filtering and casting based upon types maybe a common
use case but it currently requires knowledge of Class
methods and potentially multiple operators.
Modifications:
- Add Publisher#cast, Single#cast, and Publisher#ofType
operators and associated tests.
Result:
Operators exist which make casting and filtering between
types easier.

Add Publisher#cast, Single#cast, and Publisher#ofType

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StrategyInfluencerAwareConversions.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java

Motivation:
When the new retrying http filter is applied under some particular conditions, the retry logic yields infinite attempts.
Modifications:
- When the filter is appended conditionally, capture the instance to lazy inject LB/SD state.
- Change the default max-total-retries to guard better LB/SD error flow.
- Additional input validation for durations.
Result:
Safe retry behaviour.

Fix infinite retries under particular conditions

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java

Motivation:
Before 0.41.12 it was possible to use a custom
`AutoRetryStrategyProvider` with
`io.servicetalk.http.utils.RetryingHttpRequesterFilter`. We should
preserve this behavior.
Also, it was possible to use multiple
`io.servicetalk.http.utils.RetryingHttpRequesterFilter`(s). While users
migrate to the new `io.servicetalk.http.netty.RetryingHttpRequesterFilter`,
we should let them use multiple instances of
`io.servicetalk.http.utils.RetryingHttpRequesterFilter`.
Modifications:
- Adjust validation in `DefaultSingleAddressHttpClientBuilder` to
preserve old behavior;
Result:
Users can have multiple
`io.servicetalk.http.utils.RetryingHttpRequesterFilter` instances and
mix them with custom `AutoRetryStrategyProvider`.

Allow using pre-existing `AutoRetryStrategyProvider` and `RetryingHttpRequesterFilter`

---

servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
servicetalk-examples/grpc/debugging/README.adoc
servicetalk-examples/grpc/debugging/build.gradle
servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingClient.java
servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingServer.java
servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/package-info.java
servicetalk-examples/grpc/debugging/src/main/proto/helloworld.proto
servicetalk-examples/grpc/debugging/src/main/resources/log4j2.xml
servicetalk-examples/grpc/helloworld/pom.xml
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
servicetalk-examples/http/debugging/src/main/resources/log4j2.xml
settings.gradle

Motivation:
Enabling wire logging for gRPC is sufficiently different from the HTTP
example that a separate example would be useful.
Modifications:
Adds example for enabling wire logging for gRPC client and server. Also
demonstrates HTTP initializer.
Result:
Additional example available to reference for support requests.

Add gRPC Debugging Example

---

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java

Motivation:
Current version of `RoundRobinLoadBalancerFactory` adds `#incr_number`
to the `targetResource` as a way to distinguish two different RRLB
instances for the same `targetResource`. It results in something like
`localhost:8080#1` in logs, which is confusing for users because they
can think there is a typo in the address name.
Modifications:
- Remove `RoundRobinLoadBalancerFactory#FACTORY_COUNT`;
- Append `RoundRobinLoadBalancer#hashCode()` value to the passed
`targetResource`;
Result:
Less confusing address in logs:
`localhost:8080#1` -> `localhost:8080 (instance @cafebabe)`.

`RoundRobinLoadBalancer`: make `targetResource` logging less confusing

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContextAwareStreamingHttpClientFilterFactory.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerAwareConversions.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java

Motivation:
When the new retrying http filter is applied under some particular conditions, the retry logic yields infinite attempts.
Modifications:
- When the filter is appended conditionally, capture the instance to lazy inject LB/SD state.
- Change the default max-total-retries to guard better LB/SD error flow.
- Additional input validation for durations.
Result:
Safe retry behavior.

[BACKPORT] Fix infinite retries under particular conditions (#2041)

---

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java

Motivation:
Better visibility of the request-response processing.
Modifications:
- Add debug level logging when route fails with an error in `GrpcRouter`;
- Add debug level logging when `GrpcStatusUpdater` converts an exception
into a `grpc-status` code;
- Add more debug logging in `NettyChannelPublisher` and
`WriteStreamSubscriber`;
Result:
Easier debugging.

Add more logging for `GrpcRouter` and other transport classes

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-snapshot.yml
.github/workflows/codeql-analysis.yml

`0.42` branch will be used for a while until we have API changes that
justify going 0.43.
Modifications:
- Add `0.42` to the list of branches for all CI configurations;
Result:
CI will publish snapshots for `0.42` branch and validate all PRs.

Enable CI for 0.42 branch

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategyTest.java

Motivation:
The current default implementation of `requiredOffloads` does not
consider the case where `influenceStrategy` is implemented.
Modifications:
Call `influenceStrategy` within default `requiredOffloads` to determine
needed offloads. Default `influenceStrategy` may not call default
`requiredOffloads` to avoid infinite recursion.
Result:
Legacy influencers which do not yet implement `requiredOffloads` will
still be able to influence execution strategy.

Default `requiredOffloads` use `influenceStrategy`

---

servicetalk-http-router-jersey/docs/modules/ROOT/pages/index.adoc

Motivation:
The documentation for the Jersey Router needs updates to match the
current ServiceTalk API.
Modifications:
Documentation examples are updated and minor improvements to text.
Result:
Accurate documentation reflecting current usage.

Update Jersey Router documentation

---

servicetalk-data-jackson-jersey/src/main/java/io/servicetalk/data/jackson/jersey/JacksonSerializerMessageBodyReaderWriter.java
servicetalk-data-jackson-jersey/src/test/java/io/servicetalk/data/jackson/jersey/CustomJacksonSerializationFactoryTest.java

Upon deprecation of `JacksonSerializationProvider` our `servicetalk-data-jackson-jersey` stopped evaluating custom object-mappers offered through the `ServiceTalkJacksonSerializerFeature#contextResolverFor(ObjectMapper)`.
Restore old execution path if `JacksonSerializationProvider` is found as a resolver during runtime, otherwise fallback to the new flow.
Order is "old custom Jackson (if found)" -> "new custom Jackson (if found)" -> "new Jackson (fallback)"
**Result**:
Offer solid migration path while the deprecated `JacksonSerializationProvider` is still around.

Fix jersey-jackson not considering deprecated JacksonSerializationProvider

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java

Motivation:
During the retrying http rework, the filter changed from having by default infinite max-retries to have 4. Some places that were modified during the refectory with the first assumption, weren't reverted. This can result in rare test failures.
Modifications:
Restore max-retries on the retrying http builder for retryable and other exceptions.
Result:
Restore old behavior.
(cherry picked from commit 5e8d4828a64594cb69409f82d67fad1cfe98d398)

Fix ClientClosureRaceTest bring back max-retries

---

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java

Motivation:
During the retrying http rework, the filter changed from having by default infinite max-retries to have 4. Some places that were modified during the refectory with the first assumption, weren't reverted. This can result in rare test failures.
Modifications:
Restore max-retries on the retrying http builder.
Result:
Restore old behavior.

[Backport] Fix ClientClosureRaceTest bring back max-retries

---

servicetalk-data-jackson-jersey/docs/modules/ROOT/pages/index.adoc

Motivation:
Docs are still referring to the old `JacksonSerializationProvider`
Modifications:
Replaced old references with the replacements.
Result:
Up-to-date documentation

Fix jackson-jersey references to deprecated classes

---

servicetalk-data-jackson-jersey/src/main/java/io/servicetalk/data/jackson/jersey/JacksonSerializerMessageBodyReaderWriter.java
servicetalk-data-jackson-jersey/src/test/java/io/servicetalk/data/jackson/jersey/CustomJacksonSerializationFactoryTest.java

Motivation:
Upon deprecation of JacksonSerializationProvider our servicetalk-data-jackson-jersey stopped evaluating custom object-mappers offered through the ServiceTalkJacksonSerializerFeature#contextResolverFor(ObjectMapper).
Modifications:
Restore old execution path if JacksonSerializationProvider is found as a resolver during runtime, otherwise fallback to the new flow.
Order is "old custom Jackson (if found)" -> "new custom Jackson (if found)" -> "new Jackson (fallback)"
Result:
Offer solid migration path while the deprecated JacksonSerializationProvider is still around.
(cherry picked from commit 0f0998b9725d738f7b3c506baeb8ea68e2f73a29)

[Backport] Fix jersey-jackson not considering deprecated JacksonSerializationProvider

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherMulticastCancelUpstreamTckTest.java

Motivation:
Some multicast use cases do not want cancellation
from downstream Subscribers to generate a cancel
to the upstream source. For example if the
upstream source doesn't support re-subscribes
or if there are expected Subscribers after
cancellation.
Modifications:
- Add a `boolean cancelUpstream` parameter to the
Publisher#multicast operator. This makes it so
no cancel is propagated upstream and internal
state of the operator is preserved.

Publisher#multicast option to not cancel upstream

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Executor.java
servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoExecutor.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/AbstractNettyIoExecutor.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutor.java
servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/GlobalExecutionContextTest.java

Motivation:
Implementing `Executor` allows `IoExecutor` to used in existing
interfaces. Usage of `IoExecutor`s for `Executor` will still be very
limited for specialized cases.
Modifications:
`IoExecutor` extends `io.servicetalk.concurrent.Executor`. No user
implementations of `IoExecutor` likely exist and `NettyIoExecutor`
already implements the interface.
Result:
`IoExecutor` instances can now be passed in interfaces which currently
only accept `io.servicetalk.concurrent.Executor`.

`IoExecutor` implements `concurrent.Executor`

---

servicetalk-data-jackson-jersey/docs/modules/ROOT/pages/index.adoc

Motivation:
The JAX-RS project has moved their site from
`eclipse-ee4j.github.io/jaxrs-api` to `jakartaee.github.io/rest`
without redirection. Our documentation now contains several 404 links
to the former site.
Modifications:
Adjust JAX-RS javadoc links to point to the new site.
Result:
Documentation `validateLocalHtmlLinks` task suceeeds and links work.

Fix broken JAX-RS javadoc links

---

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverTest.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractConditionalHttpFilterTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpAuthConnectionFactoryClientTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerGracefulConnectionClosureHandlingTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/Tls13Test.java
servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpServerOverrideOffloadingTest.java
servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextExtension.java

Motivation:
The `ExecutionContextExtension` testing extension initializes the
contained execution context once per test unless `setClassLevel(true)`
is called. Some of our tests use a static class-instance of
`ExecutionContextExtension` but fail to call `setClassLevel(true)`
which results in many hundreds of extra invocations of an expensive
operation.
Modifications:
Apply `setClassLevel(true)` to all static instances of
`ExecutionContextExtension`.
Result:
Faster test execution. Saves about 40 seconds for `./gradlew --no-build-cache clean build`
for me.

Use `setClassLevel(true)` on static instances

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/GlobalExecutor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ImmediateExecutor.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutCompletable.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutSingle.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
servicetalk-http-utils/build.gradle
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpServiceFilterTest.java

Motivation:
Currently the timeout filter executes timeout events on the execution
context executor even if the execution strategy requires no offloading.
The IoExecutor should instead be use for these situations to reduce
offloads.
Modifications:
Request `ExecutionContext.ioExecutor()` as the `contextExecutor` if no
offloads are configured.
Result:
Less offloading for some timeout events.

Schedule/execute no offload timeouts on IoExecutor

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerAwareConversions.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MixedFiltersTest.java

Motivation:
Recently the API of filters changed to align better with the way
`ExecutionStrategy` should be set. A temporary additional filter
bridging calls via new API to old API was created to assure compatibility.
Unfortunately, the `MultiAddressUrlHttpClientBuilder` was not updated
and legacy filters may not be exercised.
Modifications:
- Properly appending the `NewToDeprecatedFilter` to filters added via
`MultiAddressUrlHttpClientBuilder`,
- Legacy `StrategyInfluencerAwareConversions#toMultiAddressClientFactory`
was also updated to include the bridge,
- `MixedFiltersTest` include a case validating the
`MultiAddressUrlHttpClientBuilder` behavior.
Result:
Deprecated methods on filters are properly executed when using
`MultiAddressUrlHttpClientBuilder`.

Fix filters for MultiAddressUrlHttpClientBuilder

---

servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCompletable.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestPublisher.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSingle.java
servicetalk-concurrent-test-internal/build.gradle
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java

Motivation:
This is a combination of #1687, #1834, #1851, #1856, #1927 PRs in order
to make backport of #1661 compatible with the `main` branch.

Backport all changes for `AwaitUtils`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java

Motivation:
Users of 0.41.x branch expect to see backward compatible behavior when
they upgrade to the latest bug fix release.
Starting from 0.41.7 (see #1792), default redirect behavior of
`MultiAddressHttpClient` has changed, the following request types are
not redirected by default anymore: POST, PUT, PATCH, DELETE.
Users of deprecated `MultiAddressHttpClientBuilder#maxRedirects(int)`
method also see this behavior change.
Expectation: all the following request methods should follow redirects
as it worked in 0.41.6 and before: GET, HEAD, POST, PUT, DELETE, PATCH.
Modifications:
- List of methods that were redirected in 0.41.6 and before for
`MultiAddressHttpClientBuilder#maxRedirects(int)` and
`DefaultMultiAddressUrlHttpClientBuilder#DEFAULT_REDIRECT_CONFIG`;
- Test that …

MultiAddressUrlHttpClient should redirect POST/PUT/PATCH/DELETE by default

---

servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/AbstractCompletableOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublisherOffloadingTest.java
servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/AbstractSingleOffloadingTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/CompletableStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/PublisherStepVerifierTest.java
servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/SingleStepVerifierTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AbstractCompositeCancellableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableConcurrentStackTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableProcessorTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleProcessorTest.java
servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ExecutorExtension.java
servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyConfigurationFailuresTest.java
servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextExtension.java

Motivation:
The `ExecutorExtension` is often used as a class static with the
assumption that the instance will only be created once per test class
and reused (shared) for all tests. This was not the case and the
contained Executor instance was being created for each test case.
Modifications:
Provide `setClassLevel()` method similar to `ExecutionContextExtension`
and call it with `true` for shared instances.
Result:
Reduced test overhead.

Implement `setClassLevel()` for `ExecutorExtension`

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IoThreadFactory.java

Motivation:
#1910 could not change
`io.servicetalk.transport.api.IoThreadFactory.IoThread` to extend
`ContextMapHolder` to keep it backward compatible. But the internal
`NettyIoThread` must implement `ContextMapHolder`. Otherwise, all
netty threads go through slow path of managing `AsyncContext`.
Modifications:
- `NettyIoThread` implements `ContextMapHolder`;
Result:
All instances of `NettyIoThread`s go through the fast path of operating
with `ContextMap`.

`NettyIoThread` should implement `ContextMapHolder`

---

servicetalk-http-api/docs/modules/ROOT/pages/index.adoc

Motivation:
Docs section about `Expect: 100-continue` points to grpc example instead
of http example.
Modifications:
- Change reference from grpc `DebuggingClient` to http
`DebuggingExampleClient`;
Result:
Correct link, 0.42 branch doesn't fail during link validation step.

Fix incorrect link in `Expect: 100-continue` docs

---

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java

Motivation:
#2037 added a new argument for 2 public methods of
`io.servicetalk.transport.netty.internal.DefaultNettyConnection`.
While this is an internal class, we should maintain backward
compatibility in 0.42 branch.
Modifications:
- Add 2 more overloads for pre-existing methods and mark them as
`@Deprecated`;
Result:
`servicetalk-transport-netty-internal` module is backward compatible
with 0.42.0.

Make `DefaultNettyConnection` backward compatible

---

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java

Motivation:
A source compatible API change was made in #2070 that replaced
`io.servicetalk.concurrent.api.Executor` with
`io.servicetalk.concurrentExecutor`. This change, while source
compatible as `io.servicetalk.concurrentExecutor` is the super-type of
`io.servicetalk.concurrent.api.Executor`, is not binary compatible.
Modifications:
Revert change to use same `Executor` class as prior releases on these
branches.
Result:
Binary compatibility is retained.

Revert API change involving `Executor`

---

servicetalk-concurrent-api/gradle/spotbugs/main-exclusions.xml
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatWhenSingle.java
servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/RepeatWhenSingleTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleRepeatBiPredicateTckTest.java
servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleRepeatWhenTckTest.java

Motivation:
The criteria to repeat a Single may depend upon the
termination value. Existing repeat operators in
Single do not expose the value.
Modifications:
- Add Single.repeatWhen(BiIntFunction<T, Completable>)
operator.
- Change existing Single.repeat* operators to use this
new implementation instead of converting to Publisher.

Add Single.repeatWhen(BiIntFunction<T, Completable>)

---

servicetalk-grpc-netty/build.gradle

Motivation:
The gRPC Java project provides a BOM file for managing versions of
modules and dependencies. Using the BOM results in more consistent
component resolution.
Modifications:
Use BOM in `build.graddle` as an enforcedPlatform. Remove version
references from most other components to use BOM version.
Result:
Cleaner use of gRPC-Java dependencies.

Use gRPC-Java BOM

---

gradle.properties

Motivation:
Until we have any breaking changes in the `main` branch, it will be
easier to continue 0.42.x development from the `main` to avoid a need
for cherry-picking all commits into `0.42`.
At this point of git history, the `main` and `0.42` branches are
identical except antora-related files which have to be like in the
`main` branch.
I won't rename `0.42` branch for now. We can just leave it as-is until we
need it again.

Preparing for 0.42.3-SNAPSHOT development

---

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AbstractToFutureTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/BufferStrategiesTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableMergeWithPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherBufferConcurrencyTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleAmbWithAsyncTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/CompletableToPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/CompletableToSingleTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/PubFirstOrErrorTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/PubToCompletableIgnoreTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/PubToSingleFirstOrElseTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/CompletionStageAsyncContextTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/ConcatWithCompletableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/ReduceSingleTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleFlatMapPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletableTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletionStageTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToFutureTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToPublisherTest.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/internal/ConcurrentTerminalSubscriberTest.java

Motivation:
To potentially reduce the overhead of instantiating the ExecutorExtension class repeatedly between test cases.
Modifications:
Changed instances of ExecutorExtension to static
Result:
All instances of the ExecutorExtension are now static inside servicetalk-concurrent-api module test classes.

Changing instances of ExecutorExtension to static

---

servicetalk-examples/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
servicetalk-examples/http/retry/build.gradle
servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryClient.java
servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryServer.java
servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryUrlClient.java
servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/package-info.java
servicetalk-examples/http/retry/src/main/resources/log4j2.xml
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
settings.gradle

Motivation:
Users have requested a usage sample for client retry filter
Modifications:
Adds an HTTP example for the client `RetryingHttpRequesterFilter` retry
filter.
Result:
Additional usage example available for users.

Add client `RetryingHttpRequesterFilter` example

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverServiceFilter.java

Motivation:
#2051 made `HttpLifecycleObserverServiceFilter` class public, but forgot
to make its constructor public too.
Modifications:
- Make `HttpLifecycleObserverServiceFilter` constructor public;
Result:
Users can create an instance of `HttpLifecycleObserverServiceFilter`
to use it with `appendServiceFilter(...)`.

Make `HttpLifecycleObserverServiceFilter` constructor public

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/NewToDeprecatedFilter.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NewToDeprecatedFilter.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MixedFiltersTest.java

Motivation:
In #1956 `StreamingHttpRequester` defines a new method
`request(StreamingHttpRequest)`. `AbstractStreamingHttpConnection` only
implements the deprecated method that also takes an
`HttpExecutionStrategy`. Users who apply a filter through
`ConnectionFactory` see `UnsupportedOperationException`. Also, if they
have 2+ filters applied through `ConnectionFactory`, they can not mix
deprecated and new API.
Modifications:
- Implement
`AbstractStreamingHttpConnection#request(StreamingHttpRequest)`;
- Enhance `NewToDeprecatedFilter` to be `ConnectionFactoryFilter` too;
- Apply `NewToDeprecatedFilter` when users invoke
`appendConnectionFactoryFilter`;
- Test `appendConnectionFactoryFilter` in `MixedFiltersTest`;
Result:
Users who apply request/response filters through `ConnectionFactory` …

ConnectionFactory-level filters can not migrate to new API of #1956

---

servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java
servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporterTest.java

Motivation:
Zipkin Collector interface accepts spans always as a list using HTTP or
sequence for gRPC:
- https://zipkin.io/zipkin-api/#/default/post_spans
- https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto#L232
`HttpReporter` reports batched spans as a JSON list or a sequence with
gRPC. Unfortunately, `HttpReporter` behaves differently when batching is
not enabled and submits the encoded span without the enclosing
collection.
Modifications:
- Always encode a `List<Span>` in the `HttpReporter`,
- Removed test alternatives for single value reports and always
validating a collection is reported.
Result:
The OpenTracing Zipkin Publisher is conformant to the Collector API.

Always encode spans as list in `HttpReporter`

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExceptionMapperServiceFilter.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/PayloadTooLargeException.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/MutableInt.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/PayloadSizeLimitingHttpRequesterFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/PayloadSizeLimitingHttpServiceFilter.java
servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/PayloadTooLargeException.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/PayloadSizeLimitingHttpRequesterFilterTest.java
servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/PayloadSizeLimitingHttpServiceFilterTest.java

Motivation:
In some cases it is useful to be able to limit the
response payload size. For example when using aggregated
APIs the user may not want to allow larger response
payloads.
Modifications:
- Add PayloadSizeLimitingHttpRequesterFilter which applies
a limit to the response payload size.

Add PayloadSizeLimitingHttpRequesterFilter

---

.github/workflows/ci-prb.yml
.github/workflows/ci-prq.yml
.github/workflows/ci-release.yml
.github/workflows/ci-snapshot.yml
servicetalk-http-netty/build.gradle
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/IoUringTest.java

Motivation:
io_uring is a new asynchronous I/O API for Linux that provides
significant performance improvements for I/O operations. Netty
implements it through netty-incubator-transport-io_uring module.
servicetalk's CI build runs the IOUring test, but it has not been validating io_uring properly.
Modifications:
- add `ulimit -l 65536` to GitHub Actions workflows
- use junit `EnabledOnOs` annotation to designate OS specific tests
- update assertions to ensure IOUring behavior
Result:
- IOUringTest passes in GitHub Actions CI
Reference:
- https://github.com/actions/virtual-environments/issues/4683

refactor io_uring unit test

---

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeaders.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMethod.java
servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpRequestMethodTest.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpRequestDecoder.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestDecoderTest.java

Motivation:
RFC7230, section 3.1.1 defines `method = token`. Currently, there is
no validation for the name format in `HttpRequestMethod`. HTTP/1.1
validation currently requires all uppercase letters. While the standard
HTTP methods are all uppercase, there are other standardized method that
contain tchar:
https://www.iana.org/assignments/http-methods/http-methods.xhtml
Modifications:
- Move validation of the method name from `HttpRequestDecoder` to
`HttpRequestMethod` ctor;
- Update tests to match new behavior;
Result:
HTTP/1.1 supports all method names from IANA registry.
All other protocols and use-cases get consistent method name validation.

Validate HTTP method name matches the token format

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultCompositeCloseable.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeClosableTest.java

Motivation:
`DefaultCompositeCloseable` does not respect ordering if `prepend`
operation is invoked after `append`. It causes issues when the ordering
matters for closeable resources that depend upon each other.
Modifications:
- Change `Operand.closables` to `ArrayDeque`;
- Use `addFirst` for `prepend` operation;
- Test ordiring for "prepend after append" and "prepend after merge";
Result:
Correct ordering of invoking `AsyncCloseable`s if `prepend` is used
after `append`.

CompositeCloseable: prepend doesn't respect ordering

---

servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java

Motivation:
Zipkin receiver expects Content-Type of application/x-protobuf.
Why is this change being made?
Correct Content-Type is needed for receivers to correctly identity the payload format.
Modifications:
- HttpReporter's PROTO_CONTENT_TYPE is updated.
Result:
When using Codec.PROTO3, the outbound request to the trace collector will have the correct Content-Type.

Content-Type for Zipkin Protobuf should be application/x-protobuf.

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/GlobalExecutor.java
servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java

Motivation:
Closing global resources (`IoExecutor` and `Executor`) is unexpected.
Users should have visibility when it happens.
Modifications:
- Change log level from `debug` to `info`;
- Add stack-trace to see where subscribe comes from;
Result:
Users can notice if they unexpectedly closed any of the global
resources.

Increase log level when global resources are closed

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java

Motivation:
Publisher.multicast fails to request more from upstream
if the Subscription with the minimum demand cancels.
This may result in a live lock because the remaining
Subscribers have requested data but that request hasn't
been communicated upstream.
Modifications:
- Publisher.multicast checks when a Subscription is
cancelled if it is has the minimum demand more
must be requested from upstream.
Result:
No more live lock if the minimum demand Subscription cancels.

Publisher.multicast lack of demand on cancel

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableConcurrentStack.java
servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableConcurrentStackTest.java

Motivation:
`Processors.new[Single|Completable]Processor` create a `Processor`s
that permit multiple subscribers. The underlying datastructure is
`ClosableConcurrentStack` that makes a best effort to remove items
on cancellation by setting the `Subscriber` reference to `null`.
However it doesn't attempt to remove the `Node` which can lead
to a memory leak until `close(..)` is called. This may not happen
in scenarios that perpetually retry operations that are failing
continuously for prolonged periods of time.
Modifications:
- `ClosableConcurrentStack` makes a best effort to remove the
`Node` object from the stack in `relaxedRemove`.
Result:
Memory leak fixed.

Fix memory leak in Completable/Single Processors

---

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableConcurrentStack.java

Motivation:
Completable/Single Processors make a best effort to remove
nodes from the underlying data structure upon cancellation.
However if the node is the last added and there is concurrent
cancellation we may may fail to remove the node and give up
leading to increased memory consumption.
Modifications:
- `ClosableConcurrentStack` should iterate the stack to remove
the root node if the first removal attempt fails.
Result:
More robust cleanup of memory on removal.

Completable/Single Processors more robust top of stack removal

---

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancerReadySubscriber.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadySubscriberTest.java
servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java

Modifications:
- DefaultSingleAddressHttpClientBuilder$SdStatusCompletable to
avoid creating multiple Processors when an error occurs.
The Processor will ensure the underlying data structure doesn't
leak memory.
- LoadBalancerReadySubscriber to retain the Processor reference
in a terminal state. Subsequent subscribers will therefore see
the correct terminal state.

Minor Processor usage cleanup
