servicetalk-bom/build.gradle, servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
__Motivation__
We need to publish BOM
Duplicate publish settings for BOM which diverges from library tasks.
__Result__
BOM will be published.
=> BOM is not publishing artifacts

servicetalk-grpc-protobuf/src/main/java/io/servicetalk/grpc/protobuf/ProtoBufSerializationProvider.java
Motivation:
ProtoBufSerializationProvider has extra state stateReadHeader to track if the
gRPC header is being read, but this can be inferred based upon existing state.
Modifications:
- remove stateReadHeader from ProtoBufSerializationProvider and use lengthOfData
instead
Result:
Less state required by ProtoBufSerializationProvider.
=> Remove redundant state from ProtoBufSerializationProvider

README.adoc
**Motivation**
Before pushing or creating PR, the contributor should run the test cases and code quality (lint errors) locally. So that contributor doesn't have to wait for CI/CD tool to validate the common issues. 
**Modifications**
README file contribution setup section updated with commands for running the test and checking the quality.
=> README file update 

servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/CopyByteBufHandlerTest.java
Motivation:
The newly allocated `ByteBuf` could be wrapped by netty's leak
detector. Therefore, it may not be an instance of
`UnpooledDirectByteBuf` or `UnpooledHeapByteBuf`. It's enough
to verify the allocator associated with the `ByteBuf` and the
object references.
Modifications:
- Remove `instanceOf` assertions for `unpooledBuf`;
- Verify that `unpooledBuf` is not the same object as `pooledBuf`;
Results:
Correct `CopyByteBufHandlerTest.copiesAndReleasesPooledByteBuf()`.
=> Do not check type of unpooled `ByteBuf` in `CopyByteBufHandlerTest`

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Motivation:
`DefaultSingleAddressHttpClientBuilder.buildStreaming(HttpClientBuildContext)`
takes a `HttpClientBuildContext` that is a copy of the current builder state.
Therefore, it should use information only from the ctx snapshot.
Modifications:
- Make `DefaultSingleAddressHttpClientBuilder.buildStreaming(HttpClientBuildContext)`
static;
- Use only `HttpClientBuildContext` for `#buildStreaming(...)`;
Result:
`DefaultSingleAddressHttpClientBuilder.buildStreaming(HttpClientBuildContext)`
correctly uses info only from the current ctx snapshot.
=> `buildStreaming(HttpClientBuildContext)` should use information only from `HttpClientBuildContext`

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
Motivation:
WriteStreamSubscriber uses a shared Promise instance for all writes via AllWritesPromise. Netty's Promise API has try* methods which require a boolean response to know if they promise state changed as a result, which is difficult to implement with a shared promise. AllWritesPromise currently returns false if the promise has been completed in ways other than Netty's Promise try* APIs which Netty treats as an error an may take an expensive path to raise an issue like logging stack traces.
Modifications:
- Return true instead of false to avoid additional work in Netty due to perceived failure. This isn't strictly correct from the API perspective but in practice the asynchronous contorl flow is still completed and Netty thinks everything is fine.
Result:
Less expensive error …
=> WriteStreamSubscriber aggregate Netty Promise return true

servicetalk-grpc-gradle-plugin/src/main/groovy/io/servicetalk/grpc/gradle/plugin/ServiceTalkGrpcPlugin.groovy
Motivation:
servicetalk-grpc-gradle-plugin was writing the executable script files
to the temp directory and not cleaning them up. There was also a bug in
a variable substitution which lead to compile errors.
Modifications:
- Write to the buildDir instead of temp, and don't rewrite the file on
every build if it already exists since the version information is in the
file name.
- Fix the variable naming bug
Result:
No more temp files for servicetalk-grpc-gradle-plugin and one less
variable naming bug.
=> gRPC gradle plugin write script to buildDir

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
Motivation:
Publisher#flatMapSingle has the Subscription from onSubscribe saved to a
volatile variable. This was due to the Subscription being in the context
of the mapped Single's Subscriber termination callbacks and ambiguity in
the Reactive Streams specification about visibility related to
Publisher#subscribe(..) and Subscriber state. However recent
[discussions](https://github.com/reactive-streams/reactive-streams-jvm/issues/486)
have provided more insight that the Publisher must provide visibility,
and therefore the volatile state is not necessary.
Modifications:
- Publisher#flatMapSingle subscription member variable can be
non-volatile
Result:
Less volatile state and more clear expecations.
=> Publisher#flatMapSingle make subscription non-volatile

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
Motivation:
Publisher#flatMapMergeSingle has the following race condition:
T1 - FlatMapSubscriber#onComplete (the outer Subscriber)
T2 - FlatMapSingleSubscriber#onComplete (the inner Subscriber)
T1 - terminal.cas(onComplete()) -> true, active == 0 -> false
T2 - active.dec() -> 0, terminal == null -> true
There is no guarantee that T2 will see the terminal.cas() from T1
Publisher#flatMapMerge was recently introduced, shares some control flow
logic with Publisher#flatMapMergeSingle that is now inconsistent.
Modifications:
- use atomic operations on the active count to flip to negative when the
outer source completes to ensure visibility on termination between
differen threads.
Result:
More correct termination of Publisher#flatMapMergeSingle
=> Publisher#flatMapMergeSingle terminal condition race

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java, servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ConcurrentUtils.java
Motivation:
Publisher#flatMapMergeSingle uses the
ConcurrentUtils#drainSingleConsumerQueue to drain the pending signal
queue. However this method relies upon the queue's isEmpty() method
providing visibility as to if an item has been inserted into the queue
since the last poll information. We should avoid leveraging the queue's
visibility guarantees (which may not hold) and instead leverage the
concurrency avoidance for single consumer drain to provide visibility.
Modifications:
- Remove ConcurrentUtils#drainSingleConsumerQueue
- Introduce ConcurrentUtils#acquirePendingLock and releasePendingLock
methods that allow for notification if another thread attempted to
acquire the lock while it was being held. If all threads that publish
and event (e.g. insert into a queue) use this lock it can …
=> Publisher#flatMapMergeSingle potential queue drain visibility issue

servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
SRV response returns a list of `DnsRawRecord`s that are
`ByteBufHolder`s and contain reference counted content.
Modifications:
- Release `DnsRawRecord`s after processing content;
Result:
No memory leak in DNS client.
---
Follow-up PR for https://github.com/apple/servicetalk/pull/1018#discussion_r410165996
=> Release `DnsRawRecord`s after SRV response

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
RoundRobinLoadBalancer has volatile boolean flag to indicate if a close
has occurred. The goal is to avoid retaining references to newly created
connections after a close event occurs. The state management can be
consolidated on the activeHosts lists to prevent newly available hosts
and on the Host's connection list to cleanup any live connections.
Consolidating state into the same atomic state used to add new objects
avoids potential of visibility issues.
Modifications:
- remove the closed volatile boolean, add a static empty list which
indicates closure at the activeHosts level Host connections level.
- remove duplicate close logic if selection fails to add the new
connection to the host, and modify the Host closure to atomically swap
in the CLOSED_LIST.
Result: …
=> RoundRobinLoadBalancer close state simplification

servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/DefaultJerseyStreamingHttpRouter.java
Motivation:
DefaultJerseyStreamingHttpRouter#handle(..) terminates the Subscriber
from multiple locations. Jersey's state machine is complex, it isn't
clear we are guaranteed to only terminate a single time, and test
failures suggest duplicate termination maybe occurring [1][2][3].
Duplicate termination may result in undefined behavior (e.g. infinite
loop) in operators that assume well behaved sources. Preventing
duplicate termination and adding logging will provide insight into
scenarios that have been duplicate to reproduce locally.
[1] https://github.com/apple/servicetalk/issues/744
[2] https://github.com/apple/servicetalk/issues/1040
[3] https://github.com/apple/servicetalk/issues/1053
Modifications:
- DefaultJerseyStreamingHttpRouter to use new local
DuplicateTerminateDetectorSingle …
=> DefaultJerseyStreamingHttpRouter protect against duplicate termination

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDataSourceTransformations.java
Motivation:
Aggregation of the payload body may fail due to some reasons.
For example, when data size does not fit into `Integer.MAX_VALUE`
netty throws `IllegalArgumentException` from the `CompositeByteBuf`.
To simplify understanding of the issue we need to wrap the cause
into a more meaningful exception type for this context.
Motivation:
- Throw `BufferOverflowException` with the original cause;
Result:
Better debuggabillity experience for users of aggregated API.
=> Clarify exception when payload body can not be aggregated

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
Motivation:
`SslHandler` extends `ByteToMessageDecoder` that wraps all thrown
exceptions with `DecoderException`. This complicates understanding of
the problem when users expect an instance of `SSLException`.
Modifications:
- Intercept all caught exceptions and unwrap `SSLException` if possible;
Result:
Users directly receive `SSLException`.
=> Unwrap instances of `SSLException`

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
__Motivation__
We convert unexpected gRPC exceptions to gRPC errors in the trailers. For unknown exceptions; the actual exception is lost which reduces visibility on the server side.
Log an unexpected exception before converting it to a successful HTTP response.
__Result__
gRPC errors are not silently converted to HTTP responses.
=> Log error for unexpected error from a gRPC route

.gitignore
I've just added useless files from NetBeans and VS Code.
```
/nbproject/private/
/nbbuild/
/nbdist/
/.nb-gradle/
#VS Code
.vscode/
```
=> Adding other useless folders in .gitignore

servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
Motivation:
Verify that `ConnectionObserver#connectionClosed` event is reported after
idle timeout.
Modifications:
- Add `CLIENT_IDLE_TIMEOUT` and `SERVER_IDLE_TIMEOUT` variants for
`TcpTransportObserverErrorsTest`;
Result:
More connection closed cases covered in `TcpTransportObserverErrorsTest`.
=> Verify connection close event reported when it is closed after idle timeout

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleToCompletableFuture.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletionStageTest.java
Motivation:
Single#toCompletionStage() will cancel unconditionally if the Single
terminates normally or if the CompletableFuture is manually completed.
Cancellation is only necessary in the latter case and can create
additional work and complicates debugging in the former.
Modifications:
- Make a best effort to avoid cancellation if the Single terminates via
onSuccess or onError.
- These changes are also inherited by other sources (Publisher,
Completable) which leverage Single's conversion to CompletionStage.
Result:
Single, Completable, Publisher conversion to CompletionStage (and
CompletableFuture) no longer cancel when terminated normally.
=> Single#toCompletionStage() avoid cancel if normal termination

servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/EmbeddedDuplexChannel.java
Motivation:
All further attempts to write outbound messages to `EmbeddedDuplexChannel`
trigger an exception, but do not release messages.
Also, `EmbeddedDuplexChannel` should not flush before `shutdownOutput()`.
Modifications:
- Remove `flushOutbound()` from `shutdownOutput` processing;
- Release new outbound messages after `shutdownOutput()`;
Result:
No leaks for ref counted object, consistent behavior with real `SocketChannel`.
Follow-up for #1166.
=> `EmbeddedDuplexChannel`: release outbound messages after `shutdownOutput`

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java
Motivation:
`PrematureClosureBeforeResponsePayloadBodyTest` has lots of duplications
that can be moved to ctor.
Modifications:
- Move connection creating and latch registration to ctor;
Result:
Less code.
=> Simplify `PrematureClosureBeforeResponsePayloadBodyTest`

gradle.properties
Reverts apple/servicetalk#1204
=> Downgrade jakarta.activation 1.2.2 -> 1.2.1 

gradle.properties
Reverts https://github.com/apple/servicetalk/commit/4f41fb268dc925d8e1032510957ba8d6f141a017
Reverts https://github.com/apple/servicetalk/commit/6beb058083f4f3f7b16a3cca200fdb219eee7dab
=> Downgrade Jersey 2.32 -> 2.30.1

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
Motivation:
Publisher#flatMapMerge does not attempt to recover from throwing in
onNext from a mapped publisher. In this case we should attempt to
replenish demand incase there is a recoverWith or similar operator
applied to the mapped publisher, or else we may deadlock.
Modifications:
- FlatMapSubscriber should try to replenish demand even if onNext throws
an exception
Result:
Publisher#flatMapMerge is compatible with recoverWith style operators on
the mapped publishers.
=> Publisher#flatMapMerge recover from mapped Publisher exception

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
Motivation:
Include compression support for compatibility tests of grpc-java and ServiceTalk
Modifications:
Modified existing test-suite to use compression logic too.
Result:
Verify compatibility between the two libraries.
=> gRPC compression compatibility tests

servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
Motivation:
Netty used to use the local DNS cache for SRV record resolution, but
this lead to false positive errors in some situations due to partial
caching. However that issue has been fixed [1] and included in the latest
release.
[1] https://github.com/netty/netty/pull/10808
Modifications:
- Remove the DnsNameResolver that was used specifically to disable the
DNS cache.
Result:
Removal of workaround code in DnsClient with no change in behavior.
=> Remove DnsClient workaround for Netty SRV cache issue

docs/generation/gradle/wrapper/gradle-wrapper.properties
Make it consistent with the main project.
=> Update gradle for docs subproject to 6.7.1

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/Tls13Test.java
Motivation:
JDK8 supports TLSv1.3 now, we can enable more tests. Also, improve logging
for debugging.
Modifications:
- Enable TLSv1.3 tests for JDK8;
- Use different executors for client and server;
- Add wire-logging;
Result:
TLSv1.3 tested on JDK8.
=> Improve `Tls13Test`

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ServiceTalkHttp2FrameLogger.java
Motivation:
Some logger implementations consider `Http2Settings` as a `Map` and use
their own logic to serialize `key=value` pairs into strings. As the result,
names of settings are not visible in logs, because its a control character.
Example: `settings={ =0, =0, =8192}`.
Modifications:
- Explicitly invoke `Http2Settings.toString()` to use its logic of mapping
control characters to the meaningful names;
- Align `toString(ByteBuf)` with impl in parent class `Http2FrameLogger`;
Result:
`ServiceTalkHttp2FrameLogger` correctly logs `Http2Settings`.
=> `ServiceTalkHttp2FrameLogger` doesn't log names of `Http2Settings`

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/Http2Exception.java
Motivation:
There is code in `AbstractH2DuplexHandler` that also checks for `REFUSED_STREAM`
and throws a `RetryableException`. Better to consolidate all `Http2Exception`
cases in one place to avoid missing it during future updates.
Modifications:
- Create a static method for handling `Http2ResetFrame`;
Result:
All logic related to HTTP/2 exceptions is consolidated in `Http2Exception` class.
=> Consolidate all HTTP/2 exceptions logic in `Http2Exception` class

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherConcatMapIterable.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherConcatMapIterableTest.java
Motivation:
Publisher#flatMapConcatIterable(..) will throw exceptions when
encountered in the context of onNext(..), but it will first cancel. This
may result in cleanup without knowledge of the root cause and even
result in incorrect status to be propagated (e.g. error is recovered and
translated into a response).
Modifications:
- Publisher#flatMapConcatIterable(..) should not call cancel() in the
event an exception is thrown. It should throw the exception and rely
upon the upstream source to send an error signal via onError(Throwable).
Result:
More informative errors when Publisher#flatMapConcatIterable(..) is
used.
=> Publisher#flatMapConcatIterable(..) to not cancel if onNext throws

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelPublisher.java, servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyChannelPublisherTest.java
Motivation:
NettyChannelPublisher may deliver multiple onError terminal signals to
the same subscriber if the Subscriber#onSubscribe(..) method requests
and there is an error queued up. The reactive streams specification only
allows for a single terminal signal to be delivered.
Modifications:
- NettyChannelPublisher handleSubscribe method should verify the
subscriber has not already been terminated to check if a queued error
should be delivered.
Result:
NettyChannelPublisher handleSubscribe will deliver at most 1 terminal
signal to the Subscriber.
=> NettyChannelPublisher duplicate onError

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpResponseDecoder.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
Motivation:
https://tools.ietf.org/html/rfc7230#section-3.3.3, item 2 says that any
2xx (Successful) response to a CONNECT request implies that the connection
will become a tunnel immediately after the empty line that concludes the header
fields. But non-2xx response codes may carry additional information in payload
body with more details why connect failed.
Modifications:
- Change `HttpResponseDecoder` to allow content for non-2xx responses to
`CONNECT` request;
- Add tests to verify behavior for responses to `CONNECT` request with
and without payload body;
Result:
HTTP client may parse response payload body for non-2xx responses to
`CONNECT` request.
=> Parse payload body for non-2xx response to `CONNECT` request

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpObjectDecoderTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseDecoderTest.java
Motivation:
Existing `variableWithTrailers()` test assumes that the variable response
parsed as chunked, when it actually parses all bytes until connection closes
regardless of the encoding.
Modifications:
- Update `variableWithTrailers()` test to correctly account variable length;
- Add `variableWithContent()` test;
Result:
More robust testing for variable response body parsing.
=> `HttpResponseDecoderTest`: Improve tests for variable response body length

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractH2DuplexHandler.java
Motivation:
We recently started strictly enforcing the content-length requirements
as specified by https://tools.ietf.org/html/rfc7540#section-8.1.2.6.
However not all h2/gRPC implementations have been updated and may
violate this clause which results in rejected requests/responses.
Modifications:
- Add a system property io.servicetalk.http2.allowInvalidContentLength
which allows opting out of enforcement of the content-length
enforcement requirements.
Result:
System property exists to opt-out of content-length enforcement
requirements. This option is temporary and will be removed in a future
release!
=> Provide opt-out mechansim for HTTP/2 content-length enforcement

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
HTTP/1.x doesn't allow trailers with content-length, but it switches to
"chunked" encoding when trailers are present and removes content-length
header. We should make sure it behaves as expected.
Modifications:
- Enhance the test to verify headers in case of http/1.1 and http/2
protocols;
- Do the same verification for received request message on the
server-side;
Result:
More robust test.
=> Improve `H2PriorKnowledgeFeatureParityTest#trailersWithContentLength()`

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
Motivation:
Improve stability of flaky test
Modifications:
Implemented the [proposed solution](https://github.com/apple/servicetalk/issues/920#issuecomment-705907548) 
Result:
We should stop seeing the following failures going forward.
Fixes https://github.com/apple/servicetalk/issues/1327
Fixes https://github.com/apple/servicetalk/issues/1219
Fixes https://github.com/apple/servicetalk/issues/920
=> FlakyTest: Replace EmbeddedChannel with SocketChannel for server flush strategy

gradle.properties
https://github.com/JCTools/JCTools/blob/master/RELEASE-NOTES.md#330
=> Update jcTools 3.2.0 -> 3.3.0

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ScanWithPublisher.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ScanWithPublisherTest.java
Motivation:
Publisher#scanWith(ScanWithMapper) may not deliver a terminal event
after cancel is invoked. The operator may also deliver an internally
generated error due to state management incorrectly indicated a terminal
event has already been seen (e.g. duplicate terminal with violates RS
spec) or invalid requestN demand was previously seen.
Modifications:
- cancel should not update state to TERMINATED
Result:
Publisher#scanWith(ScanWithMapper) will deliver terminal events after
cancel and won't deliver internal errors at incorrect times.
=> Publisher#scanWith(ScanWithMapper) incorrect/missing terminal after cancel

servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpHeadersFormatter.java, servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java, servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java, servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpan.java, servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContext.java, servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceState.java, servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceStateFormat.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpan.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemoryTracer.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemorySpanContext.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTraceState.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/SingleLineFormatter.java, servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/TextMapFormatter.java, servicetalk-opentracing-log4j2/src/main/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMap.java, servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java, servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java
This reverts commit 619c76ae88e3444fe5e61f4af174972bfe2f5a1f.
=> Revert "Respect missing B3 sampled headers (#1512)"

gradle/wrapper/gradle-wrapper.properties, servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ProjectUtils.groovy, servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkCorePlugin.groovy
Motivation:
Upgrade to latest Gradle release
Modifications:
Update Gradle wrapper to 7.0.2 and fix Gradle deprecations
Result:
Build with latest Gradle
=> Upgrade to Gradle 7.0.2

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientMetadata.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
This reverts commit e055ea78545e1e2caf722bb1634790c0964b5604.
Hold until ~0.41.0~ 0.42.0.
=> Revert "Restore public API changes for `grpc-api` (#1548)"

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
This reverts commit 42be7fff9b4b45f4e6761ef7bf5925d5c01789a6.
Hold until ~0.41.0~ 0.42.0.
=> Revert "Restore public API changes for `transport-netty-internal` (#1549)"

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultExecutor.java
Motivation:
`DefaultExecutor.InternalExecutor` currently implements `Runnable`
which is used to close the executor. This is odd.
Modifications:
Instead implement the `AutoCloseable` interface and rename the `apply`
method to `schedule`.
Result:
More conventional interface and method name use.
=> `DefaultExecutor` internally use `AutoCloseable`

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
Motivation:
Because `TransportObserver` events are published from IO-threads, it's
possible that Mokito may verify some callbacks before they actually
triggered.
Modifications:
- Await until the fill request-response completes and the HTTP/2 stream
is closed, then start verifying read and write events;
Result:
Fixes #1701 and #1265.
=> Fix flaky `HttpTransportObserverTest#clientFailsRequestPayloadBody`

servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
Motivation:
Clarify optional offloading boundary for filters execution.
Modifications:
- Define optional offloading boundary between filters added using
`appendNonOffloadingServiceFilter` and `appendServiceFilter`;
- Use correct method name for `appendServiceFilter` javadoc;
Result:
Better docs.
=> Javadoc improvements for `HttpServerBuilder#append*` methods

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionAcceptingNettyHttpServerTest.java
Fixes https://github.com/apple/servicetalk/issues/1759
=> Flaky ConnectionAcceptingNettyHttpServerTest await indefinitely

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyTunnel.java
Motivation:
ProxyTunnel is a test utility written using java.io primitives. It
creates a proxy and copies the corresponding InputStreams to
OutputStreams. However this process may prematurely exit before the
proxy client's InputStream is finished copying to the Server socket's
OutputStream. This may lead to test failures if the output isn't
completely copied and premature termination happens.
Modifications:
- ProxyTunnel#handleRequest should block until the executed task to copy
proxy client's InputStream to the server socket's OutputStream.
Result:
Tests which use ProxyTunnel less likely to fail due to premature
closures.
=> Test utility ProxyTunnel wait for all input to copy

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java, servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java, servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java, servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java, servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionDrainTest.java, servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporter.java, servicetalk-opentracing-zipkin-publisher/src/test/java/io/servicetalk/opentracing/zipkin/publisher/reporter/HttpReporterTest.java
Cherry-picking https://github.com/apple/servicetalk/pull/1750 onto 0.41 branch.
=> Deprecate one-way boolean settings on builders (#1750)

servicetalk-grpc-utils/src/main/java/io/servicetalk/grpc/utils/LoggingGrpcLifecycleObserver.java, servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java
Motivation:
Because the connections are full-duplex and request/response can be
processed independently, a server may respond much earlier than it
finishes processing of the request payload body.
Modifications:
- Rename `duration` to `totalTime`;
- Add `responseTime`;
Result:
`LoggingHttpLifecycleObserver` and `LoggingGrpcLifecycleObserver` log
`responseTime` and `totalTime`.
=> LifecycleObservers: log `responseTime` and `totalTime`

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
Get visibility for reasons that trigger health checking. Useful to
debug unstable hosts.
Modifications:
- Log each failed attempt to open a new connection with the failure
cause;
- Make all debug logs inside `markUnhealthy` consistent;
Result:
Users can debug the cause for failed attempts to open a new connection.
=> Log the cause of failed attempt to open a new connection

scripts/japicmp.sh
Motivation:
`servicetalk-concurrent-jdkflow` requires JDK9+. Validation of the
`local` build fails when JDK8 is used. Also, old artifact name format
is a bit confusing, better to have it as a jar name.
Modifications:
- If JDK8 is detected for the `local` build, skip verifying
`servicetalk-concurrent-jdkflow` module;
- Change artifact name for error messages to match jar file;
Result:
`japicmp.sh` doesn't fail on JDK8.
=> `japicmp.sh`: skip jdkflow on JDK8 and adjust error msg format

gradle.properties
=> Update proto-google-common-protos 2.5.1 -> 2.7.0

gradle.properties
=> Update protobuf-gradle-plugin 0.8.17 -> 0.8.18

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HeaderUtils.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java, servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SplittingFlushStrategy.java
Motivation:
72a0e64e9837d673d78f3bbb71499585d6fb0373 made it such that
flushOnEnd optimizations weren't always applied when using
HTTP/2 and gRPC. This may have around a 20% performance impact.
Modifications:
- NettyHttpServer should use SplittingFLushStrategy in all cases.
This is necessary because the flush strategy needs to be applied
in a lazy fashion after the write starts, which is a capability
provided by SplittingFLushStrategy. The terminal conditions are
also commonly enforced by SplittingFLushStrategy and should be
reused.
- SplittingFLushStrategy should handle exceptions from the flush
boundaries. This may happen if header parsing throws (duplicate
content-length header).
- While aggregating an in memory request track the content-length
to avoid multiple iterations.
Result:
20% …
=> Fix H2 Flush Strategy Aggregated API Optimization

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StrategyInfluencerAwareConversions.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
When the new retrying http filter is applied under some particular conditions, the retry logic yields infinite attempts.
Modifications:
- When the filter is appended conditionally, capture the instance to lazy inject LB/SD state.
- Change the default max-total-retries to guard better LB/SD error flow.
- Additional input validation for durations.
Result:
Safe retry behavior.
(cherry picked from commit e04a01a53e0bb66d0f0ef47c3ca545c5c50bb8cc)
=> [BACKPORT] Fix infinite retries under particular conditions (#2041)

gradle.properties
~Depends on~ Merge after #2047 to avoid git conflicts
=> Update proto-google-common-protos 2.7.0 -> 2.7.1

servicetalk-examples/grpc/helloworld/pom.xml
Motivation:
The pom.xml is not using servicetalk-bom and is
also missing a required dependecy.
=> Update grpc example pom.xml

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutFromRequest.java
Motivation:
In #1972 we deprecated `TimeoutFromRequest` in favor on `BiFunction`.
Because users have to avoid using `TimeoutFromRequest` anyway, there is
no need to require them to deal with breaking changes when they migrate
from 0.41.X to 0.42.X.
Modifications:
- `TimeoutFromRequest` implements `HttpExecutionStrategyInfluencer`
again and provides a default implementation of `influenceStrategy`
identical to 0.41 branch;
Result:
Users who upgrade from 0.41.X to 0.42.X don't have to resolve
incompatible breaking API changes for `TimeoutFromRequest`. Instead,
they can migrate from `TimeoutFromRequest` to `BiFunction` after they
are already on 0.42.X release.
=> Revert breaking changes for `TimeoutFromRequest` introduced in #1832

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
Motivation:
Publisher.multicast had recent changes to request more
if the Subscription with minimum demand has been cancelled.
We currently don't have a test for long overflow protection
and respecing queueLimit for max outstanding demand.
=> Add more tests for Publisher.multicast

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
This reverts commit 380c2ade540a4df8657ec21053ded6ff0afe1e1b.
=> Revert "Deprecated GrpcClientBuilder#MultiClientBuilder"

.github/workflows/ci-prb.yml, .github/workflows/ci-prq.yml, .github/workflows/ci-release.yml, .github/workflows/ci-snapshot.yml
This reverts commit 0172d87707f302284dcfcdd28b88309e8cc513db.
=> Revert "Disabling gradle caching for CI"

gradle.properties
Contains several changes as separate commits which will be merged using rebase-merge
=> Grpc upgrade

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProvidersTest.java
Motivation:
Some features, like `build*`, `listen*`, `append*` have multiple
overloads. Our implementation may invoke one from another. We should
make sure this behavior does not cause confusion for `HttpProviders`.
Modifications:
- Verify that provider intercepts only one invocation of the mentioned
methods even when delegating impl invokes one from another;
Result:
More confidence how providers work.
=> Enhance testing of `HttpProviders`

servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
Motivation:
#1838 marks `WriteStreamSubscriber.this.subscription` as `CANCELLED`
when source terminates. It covered one use-case (cancel after terminal),
but does not cover another use-case (request after terminal) introduced
later in #1850 due to race between a thread that emits a terminal signal
and the event-loop.
Modifications:
- Mark `WriteStreamSubscriber.this.subscription` as `CANCELLED` before
`promise.sourceTerminated` is scheduled on the event-loop;
Result:
No more interactions with the subscription after terminal signal is
received. Technically, race is still possible if a terminal signal is
delayed, but the time window is lower now.
It also resolves a flaky test
`HttpLifecycleObserverTest.testCompleteWithPayloadBodyAndTrailers` that
may observe `onRequestDataRequested` after …
=> `WriteStreamSubscriber`: don't interact with Subscription after terminal

servicetalk-bom/build.gradle, servicetalk-dependencies/build.gradle, servicetalk-http-utils/build.gradle
Both change sets will be merged with rebase-and-merge
=> Dependencies direct & jaxb-impl `api` declaration

servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/BeforeFinallyHttpOperator.java
Motivation:
After terminating the Single subscriber we need to dereference the Single subscriber as otherwise
we may retain a reference to a downstream Subscriber and violate RS 3.13.
https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md#3.13
=> BeforeFinallyHttpOperator dereference subscriber after termination

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BlockingStreamingGrpcServerResponse.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientMetadata.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcMetadata.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExceptionMapperServiceFilter.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcMetadata.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceContext.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java, servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java, servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java, servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java, servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/RequestResponseContextTest.java, servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java, servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java, servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
This reverts commit f0ab4f38dd937b5e1deade63b94e3eb5a3ec06a1, see the original PR #2311.
=> Revert "Revert "gRPC request/response context to pass data between gRPC and HTTP layers (#2311)" (#2336)"

gradle.properties
Intend is to use "Rebase and merge" instead of "Squash and merge"
=> Update Test dependencies

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
From RFC7540: any message containing connection-specific header fields MUST be treated as malformed, see
https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2 Let's validate that we follow this part of the spec and the peer that originates the malformed message receives reset frame with `PROTOCOL_ERROR`.
Modifications:
- Add a test in `H2PriorKnowledgeFeatureParityTest` to verify client receives `Http2ResetFrame` with `PROTOCOL_ERROR`;
Result:
Validate client-server behavior for malformed messages.
=> Validate HTTP/2 messages with malformed headers are rejected

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapMerge.java, servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java
Motivation:
Publisher#flatMapMerge doesn't subscribe to mapped sources if it has been cancelled. This behavior is inconsistent with Publisher#flatMapMergeSingle and also may be surprising to have mapped Publishers be discarded without any subscribe and terminal event. For example there could be control flows that use `multicast` with a minimum amount of subscribers before subscribing upstream, and if flatMap doesn't subscribe the control flow will hang.
Modifications:
- Publisher#flatMapMerge should always subscribe and cancel the mapped Publishers if necessary.
=> Publisher#flatMapMerge subscribe after cancel

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpLifecycleObserverTest.java
Motivation:
If the payload body was empty, transport can deliver `onComplete()` signal for the payload body immediately after subscribe without waiting for `request(N)`.
=> `HttpLifecycleObserverTest`: account for CL for `*DataRequested` checks

servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultPayloadInfo.java
Motivation:
Simplify understanding of the state during debugging.
=> `DefaultPayloadInfo`: enhance `toString()` to print all flags separately

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpProtocol.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerControlFlowTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java
Motivation:
Cover a few more use-cases to increase confidence in server-side control flow behavior.
Modifications:
- Add `ServerPipelineControlFlowTest`;
- Add utilities for easier setup of debugging options for client/server builder;
Result:
More tests for the server-side control flow.
=> Enhance testing of the server-side control flow

servicetalk-http-api/build.gradle, servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java, servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java, servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesRfc6265Test.java, servicetalk-http-netty/build.gradle, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1Utils.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
Motivation:
While splitting cookie crumbs for h2 we may encouter a StringIndexOutOfBoundsException while adding the last cookie crumb.
=> StringIndexOutOfBoundsException while parsing cookies

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
Motivation:
Current `disableAutoRetries()` filter does not wait for the LB to become ready. It's problematic because almost all initial requests on a new client will fail.
Modifications:
- Change `disableAutoRetries()` behavior to allow 1 attempt to wait for the LB to become ready;
- Introduce `disableAllRetries()` that will disable everything if users really need it;
Result:
`disableAutoRetries()` filter will wait for the LB to become ready and won't retry any other errors after that. If users need to disable everything, they can use new `disableAllRetries()` variant.
=> `RetryingHttpRequesterFilter`: change `disableAutoRetries()`, add `disableAllRetries()`

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExpectContinueTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java, servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java, servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java, servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SplittingFlushStrategy.java, servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java, servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
Just to be safe before the upcoming release and avoid any behavior changes for users, we decided to postpone server-side control flow changes for one more release.
=> Revert server-side control flow changes

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java, servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BuilderUtils.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerPipelineControlFlowTest.java, servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/LoggingHttpLifecycleObserver.java, servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandler.java, servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/SplittingFlushStrategy.java, servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java, servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/SslCloseNotifyAlertServerHandlingTest.java
=> Revert back server-side control flow changes

servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Motivation:
Currently, when RRLB resubscribes to SD we can see it only in logs produced by `DefaultDnsClient#cancel()`. It will be useful to see RRLB behavior by tracking only RRLB logs.
Modifications:
- All logs when RRLB cancels SD subscription and when the next resubscribe attempt will be possible;
Result:
More visibility in RRLB behavior.
=> Enhance RRLB logs to let users know when it resubscribed to SD

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Motivation:
In order for payload body to be reused the Buffers need to be duplicated. When SSL is used it will reliably move buffer indexes and if the payload is replayable the retried request may hang because no payload body is actually sent.
=> RetryingHttpRequesterFilter to duplicate payload body

servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java
Motivation:
HelloWorldJaxRsResource doesn't have an endpoint which does serialization and conditionally sets the response code.
=> JAXRS example demonstrating async response code override

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StreamingConnectionFactory.java
Motivation:
#1958 adds IP-address to the peer host to increase probability for SSL cache hit. JDK can fallback to peer host for hostname verification if it can not find SNI hostname in the certs. When this happens with IPv6, users see
`IllegalArgumentException: Contains non-LDH ASCII characters`.
Modifications:
- Replace colons with dots when convert Inet6Address to String;
Result:
Users see expected `CertificateException`: No subject alternative DNS name matching <...> found.
=> Convert IPv6 colons to dots for the new peer host

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutDemandPublisher.java, servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
Motivation:
There is a race condition in TimeoutDemandPublisher which can
result in a erroneous timeout if we have a call to `.request(n)` racing
with a `.onNext(X)` call. The result is an erroneous timer that will
timeout the publisher despite demand being present.
Modifications:
Leverage the invariant of the system that if the demand is 0 there
must be a timer set: if we transition from 0 -> n and find the timer
to be null, we must be experiencing the race. The solution is to
wait for the thread in `.onNext(X)` to finish setting the timer.
Result:
One less bug.
=> Fix race in TimeoutDemandPublisher

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpObjectDecoder.java
Motivation:
https://httpwg.org/specs/rfc9112.html#rfc.section.7.1
> HTTP/1.1 does not define any means to limit the size of a chunked response such that an intermediary can be assured of buffering the entire response. Additionally, very large chunk sizes may cause overflows or loss of precision if their values are not represented accurately in a receiving implementation. Therefore, recipients MUST anticipate potentially large hexadecimal numerals and prevent parsing errors due to integer conversion overflows or precision loss due to integer representation.
=> HttpObjectDecoder chunk size int -> long

servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/EndpointEnhancingRequestFilter.java
Motivation:
1. It uses `Single.defer` without returning an async source, this is equivalent to `Single.fromSupplier`.
2. The way it uses `SubscribableSingle` is identical to implementation of `Single.fromSupplier`.
=> Jersey's `EndpointEnhancingRequestFilter`: use `Single.fromSupplier`

servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/ThreadInterruptingCancellable.java
Motivation:
ThreadInterruptingCancellable has integer internal state that can be removed by just using the Thread and atomically update it.
=> ThreadInterruptingCancellable consolidate state

servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/RetryWhenTest.java
Motivation:
RetryWhenTest uses LegacyTestCompletable, which is deprecated.
=> Remove deprecated classes from RetryWhenTest

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilter.java, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java, servicetalk-http-netty/src/testFixtures/java/io/servicetalk/http/netty/ProxyTunnel.java
Motivation:
According to RFC7230 section 5.4
(https://datatracker.ietf.org/doc/html/rfc7230#section-5.4), all HTTP/1.1 requests must contain the `Host` header. If the target URI includes an authority component, then a client MUST send a field-value for Host that is identical to that authority component. On the other hand, `content-length: 0` header is not required because request payload body is not expected:
https://datatracker.ietf.org/doc/html/rfc9110#section-9.3.6
Modifications:
- Enhance `ProxyTunnel` to parse and validate initial line and the host header before passing data to `handler`, return 400 if it finds an error in request;
- Update `ProxyConnectConnectionFactoryFilter` to remove `content-lenght: 0` and add `host` header;
- Use `BuilderUtils` in `HttpsProxyTest` to allow …
=> `CONNECT` request to a proxy must include `Host` header

servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc, servicetalk-examples/http/compression/src/main/java/io/servicetalk/examples/http/compression/CompressionFilterExampleUrlClient.java, servicetalk-examples/http/observer/src/main/java/io/servicetalk/examples/http/observer/LifecycleObserverUrlClient.java, servicetalk-examples/http/retry/src/main/java/io/servicetalk/examples/http/retry/RetryUrlClient.java, servicetalk-examples/http/timeout/src/main/java/io/servicetalk/examples/http/timeout/TimeoutUrlClient.java
Motivation:
Some HTTP examples only use single-address client. It would be helpful to also provide multi-address client examples.
Modification:
- Create `RetryUrlClient`
- Create `TimeoutUrlClient`
- Create `LifecycleObserverUrlClient `
- Create `CompressionFilterExampleUrlClient `
Result:
Both single-address and multi-address clients are demonstrated in HTTP examples.
=> Demonstrate multi-address client in HTTP examples

servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
Motivation:
The test `expiringAHostDoesntRaceWithConnectionAdding` is flaky but only in CI.
This is because locally we essentially never hit the `else` branch where the
connection was added first but it does happen in CI. The `else` branch of the
test is flawed: the host is marked as `EXPIRED` and thus unhealthy, so we should
always expect a `NoActiveHostException` instead of a `NoAvailableHostException`.
Modifications:
Change the expected exception to NoActiveHostException.
Result:
Less flakiness.
Closes #2677.
The `else` branch can be tested locally by waiting for the future `f` to complete
before sending the service discovery event, eg adding a `f.get()` right after
the assignment of `f`.
=> Fix the flaky LingeringRoundRobinLoadBalancerTest

gradle.properties, servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
This reverts commit db9a0264d084f3c965d7ebea30ff3c98f8a5cced (#2827).
Resolves #2117.
=> Update Netty 4.1.106 -> 4.1.107

servicetalk-capacity-limiter-api/build.gradle, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/AimdCapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/AimdCapacityLimiterBuilder.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/AllowAllCapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/CapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/CapacityLimiters.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/Classification.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/CompositeCapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/FixedCapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/FixedCapacityLimiterBuilder.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/GradientCapacityLimiter.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/GradientCapacityLimiterBuilder.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/GradientCapacityLimiterUtils.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/apple/capacity/limiter/api/LatencyTracker.java, servicetalk-circuit-breaker-api/build.gradle, servicetalk-circuit-breaker-api/src/main/java/io/servicetalk/apple/circuit/breaker/api/package-info.java, servicetalk-circuit-breaker-resilience4j/build.gradle, servicetalk-circuit-breaker-resilience4j/gradle/spotbugs/test-exclusions.xml, servicetalk-circuit-breaker-resilience4j/src/main/java/io/servicetalk/apple/capacity/management/resilience4j/Resilience4jAdapters.java, servicetalk-circuit-breaker-resilience4j/src/main/java/io/servicetalk/apple/capacity/management/resilience4j/package-info.java, servicetalk-traffic-resilience-http/gradle/spotbugs/test-exclusions.xml, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/AbstractTrafficManagementHttpFilter.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/NoOpTrafficResiliencyObserver.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/PeerCapacityRejectionPolicy.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/SafeTrafficResiliencyObserver.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/TrackPendingRequestsHttpFilter.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/TrafficResilienceHttpClientFilter.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/apple/traffic/resilience/http/TrafficResilienceHttpServiceFilter.java, servicetalk-traffic-resilience-http/src/test/java/io/servicetalk/apple/traffic/resilience/http/TrafficResilienceHttpClientFilterTest.java
Motivation:
Minor comments for #2911.
=> Follow-up comments for traffic resilience features

servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/CapacityLimiters.java, servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/GradientCapacityLimiterProfiles.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/AbstractTrafficResilienceHttpFilter.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpClientFilter.java, servicetalk-traffic-resilience-http/src/main/java/io/servicetalk/traffic/resilience/http/TrafficResilienceHttpServiceFilter.java
Follow up on comments from https://github.com/apple/servicetalk/pull/2911
=> Traffic resiliency gradient profiles API improvements (comments follow up)

servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromInputStreamPublisher.java
Motivation:
Wire logging confirmed that existing value of 64Kb is too big for networks protocols. It requires fragmentation on HTTP/2 and TLS layers, and makes the Channel unwritable after each chunk.
Modifications:
- `FromInputStreamPublisher.DEFAULT_READ_CHUNK_SIZE`: 64Kb -> 16Kb-32B;
Result:
Less fragmentation on HTTP/2 and TLS layers, no overhead of tiny TLS records caused by chunked or HTTP/2 encoding.
---
**64Kb**
Causes 2 flushes per 1 chunk for `transfer-encoding: chunked`:
```
wire-before-encryption - [id: 0x318d0293, L:/_:59858 - R:_:8080] WRITE: 7B
wire-before-encryption - [id: 0x318d0293, L:/_:59858 - R:_:8080] WRITE: 65536B
wire-before-encryption - [id: 0x318d0293, L:/_:59858 - R:_:8080] WRITABILITY_CHANGED: true -> false
wire-before-encryption - [id: 0x318d0293, L:/_:59858 - …
```
=> FromInputStreamPublisher: reduce default read chunk size to 16Kb-32B

servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancer.java, servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DefaultLoadBalancerBuilder.java, servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/DelegatingLoadBalancerBuilder.java, servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerBuilder.java, servicetalk-loadbalancer-experimental/src/main/java/io/servicetalk/loadbalancer/LoadBalancerPolicies.java, servicetalk-loadbalancer-experimental/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerBuilderAdapter.java
This reverts commit e44195a1630783f42baedafa98d3e68c20dcf452.
=> Revert "loadbalancer-experimental: remove deprecated API's (#2968)"

servicetalk-capacity-limiter-api/src/main/java/io/servicetalk/capacity/limiter/api/AimdCapacityLimiter.java
Motivation:
Right now AimdCapacityLimiter uses a custom spin-lock whereas most everywhere else we use a ReentrantLock if locking is necessary.
Modifications:
Convert it to a ReentrantLock.
Result:
More uniformity.
=> capacity-limiter-api: make AimdCapacityLimiter use ReentrantLock

servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java
Motivation:
We have a flaky test. It turns out that it should always fail, but we get lucky and short circuit a `Publisher.cancel()` call the vast majority of the time. However, fixing that is going to be relatively hard/ugly.
Modifications:
Because we're guarding against bad gRPC implementations, not app usage, and the server behavior is correct (it doesn't process the message in any case), the best thing to do is relax the test requirements and accept the `CANCEL` result for the cases where it wins the race. This result is slightly less debuggable from the client perspective, but the behavior is acceptable and at this time the juice isn't worth the squeeze for truly fixing it.
Result:
One less flaky test.
Fixes #2399
=> grpc-netty: fix flaky SingleRequestOrResponseApiTest

servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
Motivation:
1. `serverCloseSecondPipelinedRequestWriteAborted` test should write only portion of the `/second` request to simulate incomplete write. Currently, it writes the full content and then concats with `never()`. As a result, internal state machine of the pipelined connection (`RequestResponseCloseHandler`) thinks that we already finished the write.
2. `tearDown()` may throw NPE if we use `assume` to skip some test scenarios.
Modifications:
1. Write only half of the intended content.
2. Add null checks inside `tearDown()` method.
=> Improvements for `ConnectionCloseHeaderHandlingTest`

.github/workflows/ci-prb.yml
Motivation:
Automatically validate we pass all tests on macOS machines.
=> Add a PR Builder job with JDK 11 and macos-latest

servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java, servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
Motivation:
Server-side `GrpcRouter` works as a translation layer from HTTP to gRPC and back. It logs all exceptions at `DEBUG` level, which makes it hard for users to notice when their endpoints throw exceptions.
Modifications:
- Enhance `GrpcRouter` to log unexpected exceptions at `ERROR` level. Expected exceptions (`GrpcStatusException`, `TimeoutException`, and `CancellationException`) will still be logged at `DEBUG` level.
Result:
Easier to spot unexpected server-side exceptions from gRPC endpoints.
=> Make unexpected gRPC exceptions visible on the server-side

servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLifecycleObserverHttpFilter.java
Motivation:
Similar to #3234, we can implement `Supplier` interface for `ExchangeContext` inside `AbstractLifecycleObserverHttpFilter` to avoid allocation of a captured lambda.
=> `ExchangeContext`: implement `Supplier` to avoid lambda allocation
